import fs from"node:fs";
import{after,afterEach,before,beforeEach,test}from"node:test";
import{assertFails,assertSucceeds,initializeTestEnvironment}from"@firebase/rules-unit-testing";
import{doc,getDoc,setDoc}from"firebase/firestore";

let env;
before(async()=>{env=await initializeTestEnvironment({projectId:"demo-irpa-research-security",firestore:{rules:fs.readFileSync("firestore.rules","utf8")}})});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async ctx=>{
 const db=ctx.firestore();
 await setDoc(doc(db,"members","regular-user"),{status:"Active",role:"Livestock Officer"});
 await setDoc(doc(db,"members","research-user"),{status:"Active",role:"Research Officer"});\n await setDoc(doc(db,"members","research-user-2"),{status:"Active",role:"Research Officer"});
 await setDoc(doc(db,"members","finance-user"),{status:"Active",role:"Finance Manager"});
 await setDoc(doc(db,"researchStudies","study-1"),{recordType:"Research Study",title:"Controlled Study",recordOrigin:"PRODUCTION"});
 await setDoc(doc(db,"researchUpdates","published-1"),{recordType:"Research Update",status:"Published",title:"Published finding"});
 await setDoc(doc(db,"researchUpdates","draft-1"),{recordType:"Research Update",status:"Draft",title:"Private draft"});
 await setDoc(doc(db,"researchInformationRequests","req-1"),{targetPortal:"Finance Portfolio",requestedByUid:"research-user",studyReference:"study-1",informationRequired:"Budget data",specificDataElements:"Approved expenditure summary",purpose:"Research",justification:"Study need",status:"Submitted",recordOrigin:"PRODUCTION"});
 await setDoc(doc(db,"researchPortalAlerts","alert-1"),{requestId:"req-1",targetPortal:"Finance Portfolio",status:"Submitted",alertType:"Research Information Request"});
 await setDoc(doc(db,"researchInformationGrants","grant-1"),{requestId:"req-1",targetPortal:"Finance Portfolio",grantedToUid:"research-user",status:"Active",approvedInformation:"Approved expenditure summary"});
 await setDoc(doc(db,"researchSharedInformation","shared-1"),{requestId:"req-1",grantId:"grant-1",sourcePortal:"Finance Portfolio",status:"Available to Research",information:"Approved expenditure summary"});
 await setDoc(doc(db,"researchToolPermissions","research-user_Research Submission_study-1"),{userUid:"research-user",tool:"Research Submission",studyId:"study-1",status:"Active"});await setDoc(doc(db,"researchToolPermissions","regular-user_Research Submission_study-1"),{userUid:"regular-user",tool:"Research Submission",studyId:"study-1",status:"Active"});
});});
after(async()=>{await env.cleanup()});

test("ordinary active member cannot read private research studies",async()=>{const db=env.authenticatedContext("regular-user").firestore();await assertFails(getDoc(doc(db,"researchStudies","study-1")))});
test("explicit research authority can read research studies",async()=>{const db=env.authenticatedContext("research-user").firestore();await assertSucceeds(getDoc(doc(db,"researchStudies","study-1")))});
test("ordinary portal user can read published research updates",async()=>{const db=env.authenticatedContext("regular-user").firestore();await assertSucceeds(getDoc(doc(db,"researchUpdates","published-1")));await assertFails(getDoc(doc(db,"researchUpdates","draft-1")))});
test("ordinary portal user cannot create research information requests",async()=>{const db=env.authenticatedContext("regular-user").firestore();await assertFails(setDoc(doc(db,"researchInformationRequests","bad"),{targetPortal:"Finance Portfolio",requestedByUid:"regular-user",status:"Submitted",recordOrigin:"PRODUCTION"}))});
test("research authority can create a scoped information request",async()=>{const db=env.authenticatedContext("research-user").firestore();await assertSucceeds(setDoc(doc(db,"researchInformationRequests","req-new"),{targetPortal:"Finance Portfolio",requestedByUid:"research-user",studyReference:"study-1",informationRequired:"Finance summary",specificDataElements:"Approved expenditure summary",purpose:"Research",justification:"Study need",status:"Submitted",recordOrigin:"PRODUCTION"}))});
test("researcher can read only their own request",async()=>{const own=env.authenticatedContext("research-user").firestore();const other=env.authenticatedContext("research-user-2").firestore();await assertSucceeds(getDoc(doc(own,"researchInformationRequests","req-1")));await assertFails(getDoc(doc(other,"researchInformationRequests","req-1")))});\ntest("only responsible portal can read its research alert",async()=>{const finance=env.authenticatedContext("finance-user").firestore();const livestock=env.authenticatedContext("regular-user").firestore();await assertSucceeds(getDoc(doc(finance,"researchPortalAlerts","alert-1")));await assertFails(getDoc(doc(livestock,"researchPortalAlerts","alert-1")))});
test("responsible portal can read an active information grant but unrelated portal cannot",async()=>{const finance=env.authenticatedContext("finance-user").firestore();const livestock=env.authenticatedContext("regular-user").firestore();await assertSucceeds(getDoc(doc(finance,"researchInformationGrants","grant-1")));await assertFails(getDoc(doc(livestock,"researchInformationGrants","grant-1")))});
test("research can read granted shared information but ordinary portal cannot",async()=>{const research=env.authenticatedContext("research-user").firestore();const regular=env.authenticatedContext("regular-user").firestore();await assertSucceeds(getDoc(doc(research,"researchSharedInformation","shared-1")));await assertFails(getDoc(doc(regular,"researchSharedInformation","shared-1")))});
test("research tool access requires explicit user tool and study permission",async()=>{const permitted=env.authenticatedContext("research-user").firestore();const unpermitted=env.authenticatedContext("research-user-2").firestore();await assertSucceeds(setDoc(doc(permitted,"researchSubmissions","permitted"),{recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION",studyId:"study-1",submittedByUid:"research-user"}));await assertFails(setDoc(doc(unpermitted,"researchSubmissions","blocked"),{recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION",studyId:"study-1",submittedByUid:"research-user-2"}));await assertFails(setDoc(doc(permitted,"researchSubmissions","wrong-study"),{recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION",studyId:"other-study",submittedByUid:"research-user"}));}\ntest("tool permission is scoped to the exact research user/tool/study",async()=>{const permitted=env.authenticatedContext("research-user").firestore();const other=env.authenticatedContext("regular-user").firestore();await assertSucceeds(getDoc(doc(permitted,"researchToolPermissions","research-user_Research Submission_study-1")));await assertFails(getDoc(doc(other,"researchToolPermissions","research-user_Research Submission_study-1")))});
test("tool permission permits only the explicitly scoped research submission",async()=>{const db=env.authenticatedContext("regular-user").firestore();await assertSucceeds(setDoc(doc(db,"researchSubmissions","submission-1"),{recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION",studyId:"study-1",submittedByUid:"regular-user"}));await assertFails(setDoc(doc(db,"researchSubmissions","submission-2"),{recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION",studyId:"other-study",submittedByUid:"regular-user"}))});
