import test from "node:test";import assert from "node:assert/strict";import{PDFDocument}from"pdf-lib";import{memoryMeta,memoryStorage}from"../src/adapters.mjs";import{makeContext,route}from"../src/router.mjs";import{runCleanup}from"../src/upload.mjs";import{verifyChain}from"../src/signing.mjs";import{MAX_PDF_BYTES}from"../src/pdf.mjs";import{sha256Hex}from"../src/util.mjs";
const quiet={error(){},log(){}};const PNG="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";const U={u1:{uid:"u1"},u2:{uid:"u2"},admin:{uid:"admin",isAdmin:true}};
function setup(){const storage=memoryStorage(),meta=memoryMeta(),invites=[],clock={t:new Date("2026-10-04T10:00:00Z")};const ctx=makeContext({storage,meta,logger:quiet,now:()=>new Date(clock.t),verifyUser:async r=>U[(r.headers.get("authorization")||"").replace("Bearer ","")]||null,sendInvitation:async i=>invites.push(i),config:{appUrl:"https://app.example.test",ttlDays:14}});return{ctx,storage,meta,invites,clock,tokenFor:e=>new URL(invites.find(i=>i.to===e).link).searchParams.get("token")}}
async function pdf(p=1){const d=await PDFDocument.create();for(let i=0;i<p;i++)d.addPage().drawText("Page "+(i+1),{x:50,y:700});return d.save()}
function uploadReq(b,o={}){const f=new FormData();f.set("file",new Blob([b],{type:"application/pdf"}),o.name||"doc.pdf");if(o.documentId)f.set("documentId",o.documentId);f.set("title","Test Doc");f.set("classification",o.classification||"Restricted");f.set("archives",JSON.stringify(o.archives||["administrative-documents","board-governance"]));return new Request("https://gw.test/api/documents",{method:"POST",headers:{authorization:`Bearer ${o.user||"u1"}`},body:f})}
const post=(p,b,u)=>new Request("https://gw.test"+p,{method:"POST",headers:{"content-type":"application/json",...(u?{authorization:`Bearer ${u}`}:{})},body:JSON.stringify(b)});const get=(p,o={})=>new Request("https://gw.test"+p,{headers:{...(o.user?{authorization:`Bearer ${o.user}`}:{}),...(o.token?{"x-signing-token":o.token}:{})}});
async function up(s,id="DOC-001",o={}){const b=await pdf(2),r=await route(uploadReq(b,{documentId:id,...o}),s.ctx);assert.equal(r.status,201);return{b,h:await sha256Hex(b)}}
const ss=[{name:"Amina",email:"a@example.org",order:1},{name:"Juma",email:"j@example.org",order:2}];
async function env(s,signers=ss){await up(s);const r=await route(post("/api/envelopes",{documentId:"DOC-001",signers,archives:["legal-contracts","board-governance"]},"u1"),s.ctx);assert.equal(r.status,201);return(await r.json()).envelopeId}
const sig=(t,v="Amina K")=>post("/api/sign/submit",{token:t,consent:true,signature:{type:"typed",value:v}});
test("1 valid PDF stored in every archive",async()=>{const s=setup(),x=await up(s);assert.equal(s.storage.objs.size,2);assert.equal((await s.meta.get("documents","DOC-001")).hash,x.h)});
test("2 invalid PDF rejected",async()=>{const s=setup();assert.equal((await route(uploadReq(new TextEncoder().encode("hello")),s.ctx)).status,400)});
test("3 truncated PDF rejected",async()=>{const s=setup(),b=await pdf();assert.equal((await route(uploadReq(b.slice(0,-100)),s.ctx)).status,400)});
test("4 empty PDF rejected",async()=>{const s=setup();assert.equal((await route(uploadReq(new Uint8Array()),s.ctx)).status,400)});
test("5 oversize PDF rejected",async()=>{const s=setup(),b=new Uint8Array(MAX_PDF_BYTES+1);b.set(new TextEncoder().encode("%PDF-1.7"));assert.equal((await route(uploadReq(b),s.ctx)).status,413)});
test("6 bad archive/classification rejected",async()=>{const s=setup(),b=await pdf();assert.equal((await route(uploadReq(b,{archives:["bad"]}),s.ctx)).status,400);assert.equal((await route(uploadReq(b,{classification:"Secret"}),s.ctx)).status,400)});
test("7 unauthenticated retrieval denied",async()=>{const s=setup();await up(s);assert.equal((await route(get("/api/documents/DOC-001/pdf"),s.ctx)).status,401)});
test("8 owner retrieval passes hash",async()=>{const s=setup(),x=await up(s),r=await route(get("/api/documents/DOC-001/pdf",{user:"u1"}),s.ctx);assert.equal(r.status,200);assert.equal(await sha256Hex(new Uint8Array(await r.arrayBuffer())),x.h)});
test("9 duplicate ID returns 409",async()=>{const s=setup(),b=await pdf();assert.equal((await route(uploadReq(b,{documentId:"DOC-DUP"}),s.ctx)).status,201);assert.equal((await route(uploadReq(b,{documentId:"DOC-DUP"}),s.ctx)).status,409)});
test("10 rollback releases ID",async()=>{const s=setup();s.storage.failPutWhen=n=>n===2;assert.equal((await route(uploadReq(await pdf()),s.ctx)).status,502);assert.equal(await s.meta.get("documents","DOC-001"),null)});
test("11 cleanup removes failed rollback",async()=>{const s=setup();s.storage.failPutWhen=n=>n===2;s.storage.failDelete=true;await route(uploadReq(await pdf()),s.ctx);assert.equal((await s.meta.list("pendingCleanup")).length,1);s.storage.failDelete=false;assert.deepEqual(await runCleanup(s.ctx),{removed:1})});
test("12 envelope owner authorization",async()=>{const s=setup();await up(s);assert.equal((await route(post("/api/envelopes",{documentId:"DOC-001",signers:ss,archives:["legal-contracts"]},"u2"),s.ctx)).status,403)});
test("13 invitation transport required",async()=>{const s=setup(),c=makeContext({storage:s.storage,meta:s.meta,verifyUser:s.ctx.verifyUser,logger:quiet});await up(s);assert.equal((await route(post("/api/envelopes",{documentId:"DOC-001",signers:ss,archives:["legal-contracts"]},"u1"),c)).status,500)});
test("14 signing order enforced",async()=>{const s=setup();await env(s);assert.equal((await route(sig(s.tokenFor("j@example.org"),"Juma M"),s.ctx)).status,409)});
test("15 sequential signing completes and creates copies",async()=>{const s=setup();const id=await env(s);const a=s.tokenFor("a@example.org"),j=s.tokenFor("j@example.org");assert.equal((await route(sig(a),s.ctx)).status,200);const r=await route(post("/api/sign/submit",{token:j,consent:true,signature:{type:"drawn",value:PNG}},s.ctx),s.ctx);assert.equal(r.status,200);assert.equal((await r.json()).completed,true);const st=await(await route(get("/api/envelopes/"+id,{user:"u1"}),s.ctx)).json();assert.equal(st.status,"Completed");assert.equal(st.auditChainValid,true);assert.equal(st.completion.files.length,5)});
test("16 malformed and tampered token rejected",async()=>{const s=setup();await env(s);const t=s.tokenFor("a@example.org"),p=t.split(".");assert.equal((await route(sig("bad"),s.ctx)).status,401);assert.equal((await route(sig(p[0]+"."+p[1]+"."+"0".repeat(64)),s.ctx)).status,403)});
test("17 invalid signature and wrong linked account rejected",async()=>{const s=setup();await env(s,[{name:"A",email:"a@example.org",order:1},{name:"L",email:"l@example.org",order:2,uid:"u2"}]);assert.equal((await route(sig(s.tokenFor("a@example.org"),"<bad>"),s.ctx)).status,400);await route(sig(s.tokenFor("a@example.org")),s.ctx);const r=await route(post("/api/sign/submit",{token:s.tokenFor("l@example.org"),consent:true,signature:{type:"typed",value:"Linked"}}, "u1"),s.ctx);assert.equal(r.status,403)});
test("18 audit chain detects tampering and completed PDF integrity",async()=>{const s=setup(),id=await env(s,[{name:"Amina",email:"a@example.org",order:1}]);await route(sig(s.tokenFor("a@example.org")),s.ctx);const e=await s.meta.get("envelopes",id);assert.equal(await verifyChain(e.events),true);e.events[1].ip="6.6.6.6";assert.equal(await verifyChain(e.events),false)});
