import { collection, doc, getDoc, getDocs, orderBy, query, runTransaction, serverTimestamp, where } from "firebase/firestore";
import { auth, db } from "./config";

const WORKFLOW="Authorization";const MODULE="Authorization & Approvals";const TERMINAL=["Completed","Rejected"];
const ROLES={reviewer:["Director Internal Oversight","Internal Oversight Officer","Director Human Resources","HR Manager","Director Finance & Administration","Finance Manager","Programme/Technical Officer","Operations Manager"],approver:["Executive Director"],implementer:["Executive Director","Director Finance & Administration","Finance Manager","Operations Manager","Programme/Technical Officer","Director Human Resources","HR Manager"]};
function uid(){return auth.currentUser?.uid||null}function email(){return auth.currentUser?.email||null}function actorData(){return{uid:uid(),email:email()}}function list(v){return Array.from(new Set((Array.isArray(v)?v:String(v||"").split(",")).map(x=>String(x).trim()).filter(Boolean)))}
function audit(action,recordId,details={}){const a=actorData();return{action,collection:"workflowActions",recordId,details,actorUid:a.uid,actorEmail:a.email,createdAt:serverTimestamp()}}
function event(status,from,action,reason=""){return{status,from:from||null,action,reason:reason||null,actorUid:uid(),actorEmail:email(),at:new Date().toISOString()}}
function reference(){return`IRPA-AUTH-${new Date().getFullYear()}-${Date.now().toString().slice(-8)}`}
export async function getAuthorizationWorkflows(){const actor=uid();if(!actor)throw new Error("Authentication is required.");const adminSnap=await getDoc(doc(db,"adminProfiles",actor));const base=[where("workflowType","==",WORKFLOW),where("module","==",MODULE)];const q=adminSnap.exists()&&adminSnap.data().active===true?query(collection(db,"workflowActions"),...base,orderBy("createdAt","desc")):query(collection(db,"workflowActions"),...base,where("involvedUids","array-contains",actor),orderBy("createdAt","desc"));const snap=await getDocs(q);return snap.docs.map(d=>({id:d.id,...d.data()}))}
export async function createAuthorizationWorkflow(input){const actor=uid();if(!actor)throw new Error("Authentication is required.");if(!String(input.title||"").trim()||!String(input.justification||"").trim())throw new Error("Title and justification are required.");if(!input.reviewerUid||!input.approverUid)throw new Error("A named reviewer and approver are required.");if(input.approverUid===actor)throw new Error("Self-approval is prohibited. The requester cannot be the approver.");const involved=list([actor,input.reviewerUid,input.approverUid,input.implementerUid,...list(input.involvedUids)]);const ref=doc(collection(db,"workflowActions"));const auditRef=doc(collection(db,"audit"));const payload={workflowType:WORKFLOW,module:MODULE,status:"Draft",stageIndex:0,workflowVersion:1,reference:input.reference||reference(),title:String(input.title).trim(),requestedByUid:actor,requestedByEmail:email(),requestedByName:input.requestedByName||"",reviewerUid:input.reviewerUid,reviewerName:input.reviewerName||"",approverUid:input.approverUid,approverName:input.approverName||"",implementerUid:input.implementerUid||input.approverUid,implementerName:input.implementerName||input.approverName||"",amount:input.amount||"",budgetLine:input.budgetLine||"",justification:String(input.justification).trim(),involvedUids:involved,history:[event("Draft",null,"Created")],createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await runTransaction(db,async tx=>{tx.set(ref,payload);tx.set(auditRef,audit("AUTHORIZATION_CREATED",ref.id,{reference:payload.reference,status:"Draft",requestedByUid:actor,reviewerUid:payload.reviewerUid,approverUid:payload.approverUid,implementerUid:payload.implementerUid}))});return ref.id}
const TRANSITIONS={Draft:{Submitted:"requester"},Submitted:{"Under Review":"reviewer",Returned:"reviewer"},"Under Review":{Approved:"approver",Rejected:"approver",Returned:"reviewer"},Returned:{Submitted:"requester"},Approved:{Completed:"implementer"}};
export async function transitionAuthorization(id,next,reason=""){const actor=uid();if(!actor)throw new Error("Authentication is required.");if(!id||!next)throw new Error("A workflow record and target stage are required.");if(["Returned","Rejected"].includes(next)&&!String(reason||"").trim())throw new Error(`A reason is required when ${next.toLowerCase()} is selected.`);const ref=doc(db,"workflowActions",id),auditRef=doc(collection(db,"audit"));await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error("Authorization request not found.");const r=snap.data();if(r.workflowType!==WORKFLOW||r.module!==MODULE)throw new Error("This is not an Authorization & Approvals workflow record.");if(TERMINAL.includes(r.status))throw new Error("This authorization workflow is closed and cannot be changed.");const required=TRANSITIONS[r.status]?.[next];if(!required)throw new Error(`The transition ${r.status} → ${next} is not permitted.`);const roleSnap=await tx.get(doc(db,"members",actor));const role=roleSnap.exists()?roleSnap.data().role:null;const allowed=required==="requester"?r.requestedByUid===actor:required==="reviewer"?r.reviewerUid===actor&&ROLES.reviewer.includes(role):required==="approver"?r.approverUid===actor&&ROLES.approver.includes(role):r.implementerUid===actor&&ROLES.implementer.includes(role);if(!allowed)throw new Error("You are not authorised to perform this workflow transition.");if(required==="approver"&&r.requestedByUid===actor)throw new Error("Self-approval is prohibited.");const history=Array.isArray(r.history)?[...r.history]:[];history.push(event(next,r.status,next,reason));const stages=["Draft","Submitted","Under Review","Approved","Rejected","Returned","Completed"];const changes={status:next,stageIndex:stages.indexOf(next),history,workflowVersion:Number(r.workflowVersion||1)+1,lastWorkflowActionAt:serverTimestamp(),updatedAt:serverTimestamp()};if(next==="Under Review")changes.reviewStartedAt=serverTimestamp();if(next==="Approved")changes.approvedAt=serverTimestamp();if(next==="Rejected")changes.rejectedAt=serverTimestamp();if(next==="Returned")changes.returnedAt=serverTimestamp();if(next==="Completed")changes.completedAt=serverTimestamp();if(reason)changes.decisionReason=reason.trim();tx.update(ref,changes);tx.set(auditRef,audit(`AUTHORIZATION_${next.replace(/\s+/g,"_").toUpperCase()}`,id,{reference:r.reference,from:r.status,to:next,reason:reason||null}))});}
export{ROLES};
