import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, runTransaction, serverTimestamp, updateDoc, setDoc, where } from "firebase/firestore";
import { auth, db } from "./config";
export const COLLECTIONS={members:"members",employees:"employees",employeeCounters:"employeeCounters",participants:"participants",meetings:"meetings",meetingSubscriptions:"meetingSubscriptions",meetingRoomEvents:"meetingRoomEvents",transcriptions:"transcriptions",resolutions:"resolutions",votes:"votes",voteLocks:"voteLocks",actions:"actions",documents:"documents",signatures:"signatures",decisions:"decisions",risks:"risks",audit:"audit",reports:"reports",authorizationRequests:"authorizationRequests",workflowActions:"workflowActions",staffPaymentRequests:"staffPaymentRequests",financeBudgets:"financeBudgets",financeTransactions:"financeTransactions",financeFunding:"financeFunding",financeApprovals:"financeApprovals",financeCommitments:"financeCommitments",financeGrants:"financeGrants",financeBankAccounts:"financeBankAccounts",financeReconciliations:"financeReconciliations",financeAssets:"financeAssets",financeRisks:"financeRisks",financeReports:"financeReports",invitations:"invitations",adminProfiles:"adminProfiles",systemSettings:"systemSettings"};
function currentActor(){return{uid:auth.currentUser?.uid||null,email:auth.currentUser?.email||null};}
async function writeAudit(action,collectionName,recordId,details={}){const a=currentActor();await addDoc(collection(db,COLLECTIONS.audit),{action,collection:collectionName,recordId,details,actorUid:a.uid,actorEmail:a.email,createdAt:serverTimestamp()});}
export async function createRecord(collectionName,data){const ref=await addDoc(collection(db,collectionName),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("CREATE",collectionName,ref.id,data);return ref.id;}
export async function createMemberProfile(uid,data){if(!uid)throw new Error("A Firebase Authentication UID is required.");await setDoc(doc(db,COLLECTIONS.members,uid),{...data,uid,memberType:data.memberType||"Governance Member",createdAt:data.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await writeAudit("CREATE_OR_UPDATE_MEMBER_PROFILE",COLLECTIONS.members,uid,{...data,uid});return uid;}
export async function generateEmployeeNumber(){const ref=doc(db,COLLECTIONS.employeeCounters,"employees");return runTransaction(db,async tx=>{const snap=await tx.get(ref);const next=snap.exists()?Number(snap.data().nextNumber||1):1;tx.set(ref,{nextNumber:next+1,updatedAt:serverTimestamp()},{merge:true});return`IRPA-EMP-${String(next).padStart(5,"0")}`;});}
export async function createEmployee(data){const employeeNumber=await generateEmployeeNumber();const ref=await addDoc(collection(db,COLLECTIONS.employees),{...data,uid:data.uid||null,employeeNumber,status:data.employmentStatus||data.status||"Active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("CREATE_EMPLOYEE_PROFILE",COLLECTIONS.employees,ref.id,{employeeNumber,role:data.role||"",department:data.department||""});return employeeNumber;}
export async function createEmployeeProfile(data){const uid=data.uid||auth.currentUser?.uid;if(!uid)throw new Error("A Firebase Authentication UID is required.");const existing=await getRecord(COLLECTIONS.employees,uid);if(existing)return existing;const employeeNumber=data.employeeNumber||await generateEmployeeNumber();await setDoc(doc(db,COLLECTIONS.employees,uid),{...data,uid,employeeNumber,status:data.status||"Active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:false});await writeAudit("CREATE_EMPLOYEE_PROFILE",COLLECTIONS.employees,uid,{employeeNumber,role:data.role||"",department:data.department||""});return getRecord(COLLECTIONS.employees,uid);}
export async function provisionCurrentMemberFromInvitation(invitationId){const uid=auth.currentUser?.uid;const email=auth.currentUser?.email?.trim().toLowerCase();if(!uid||!email||!invitationId)return null;const invitation=await getRecord(COLLECTIONS.invitations,invitationId);if(!invitation)throw new Error("The member invitation could not be found.");if(invitation.email?.trim().toLowerCase()!==email)throw new Error("This invitation is not assigned to the authenticated email address.");if(invitation.status==="Cancelled")throw new Error("This member invitation has been cancelled.");const role=invitation.role||"Board Member";const memberType=invitation.memberType||"Governance Member";const member=await createMemberProfile(uid,{invitationId,email,name:invitation.name||"",role,memberType,status:"Active"});const employeeRoles=["Executive Director","Director Human Resources","HR Manager","Director Finance & Administration","Finance Personnel","Finance Manager","Accountant","Finance Officer","Director Internal Oversight","Internal Oversight Officer","Secretariat","Procurement Officer","Programme/Technical Officer","Management","Operations Manager","Rangeland Officer","Livestock Officer","Outreach Officer","Community Development Officer","Environment Officer","HR Officer","Employee"];if(employeeRoles.includes(role))await createEmployeeProfile({uid,email,name:invitation.name||"",role,department:invitation.department||"",employmentType:invitation.employmentType||"Employee",status:"Active",invitationId});return member;}
export async function getRecord(collectionName,id){const s=await getDoc(doc(db,collectionName,id));return s.exists()?{id:s.id,...s.data()}:null;}
export async function getRecords(collectionName){const s=await getDocs(query(collection(db,collectionName),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function getEmployeePaymentRequests(employeeUid){const s=await getDocs(query(collection(db,COLLECTIONS.staffPaymentRequests),where("employeeUid","==",employeeUid),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function updateRecord(collectionName,id,data){await updateDoc(doc(db,collectionName,id),{...data,updatedAt:serverTimestamp()});await writeAudit("UPDATE",collectionName,id,data);}
export async function processPaymentRequest(id,changes){const actor=currentActor();await updateDoc(doc(db,COLLECTIONS.staffPaymentRequests,id),{...changes,actionByUid:actor.uid,actionByEmail:actor.email,actionAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("PAYMENT_WORKFLOW_ACTION",COLLECTIONS.staffPaymentRequests,id,{...changes,actorUid:actor.uid,actorEmail:actor.email});}
export async function deleteRecord(collectionName,id){await deleteDoc(doc(db,collectionName,id));await writeAudit("DELETE",collectionName,id);}
export async function getAdminProfile(uid){return uid?getRecord(COLLECTIONS.adminProfiles,uid):null;}
export async function getCurrentMemberProfile(){const uid=auth.currentUser?.uid;return uid?getRecord(COLLECTIONS.members,uid):null;}
export async function getCurrentEmployeeProfile(){const uid=auth.currentUser?.uid;return uid?getRecord(COLLECTIONS.employees,uid):null;}
