import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, runTransaction, serverTimestamp, updateDoc, setDoc, where } from "firebase/firestore";
import { auth, db } from "./config";
import { sendEmployeeRegistrationEmail } from "./auth";

export const COLLECTIONS={members:"members",employees:"employees",employeeCounters:"employeeCounters",participants:"participants",meetings:"meetings",meetingSubscriptions:"meetingSubscriptions",meetingRoomEvents:"meetingRoomEvents",transcriptions:"transcriptions",resolutions:"resolutions",votes:"votes",voteLocks:"voteLocks",voteCorrections:"voteCorrections",actions:"actions",documents:"documents",signatures:"signatures",decisions:"decisions",risks:"risks",audit:"audit",reports:"reports",authorizationRequests:"authorizationRequests",workflowActions:"workflowActions",staffPaymentRequests:"staffPaymentRequests",financeBudgets:"financeBudgets",financeTransactions:"financeTransactions",financeFunding:"financeFunding",financeApprovals:"financeApprovals",financeCommitments:"financeCommitments",financeGrants:"financeGrants",financeBankAccounts:"financeBankAccounts",financeReconciliations:"financeReconciliations",financeAssets:"financeAssets",financeRisks:"financeRisks",financeReports:"financeReports",invitations:"invitations",adminProfiles:"adminProfiles",systemSettings:"systemSettings",mail:"mail"};

function currentActor(){return{uid:auth.currentUser?.uid||null,email:auth.currentUser?.email||null};}
async function writeAudit(action,collectionName,recordId,details={}){const a=currentActor();await addDoc(collection(db,COLLECTIONS.audit),{action,collection:collectionName,recordId,details,actorUid:a.uid,actorEmail:a.email,createdAt:serverTimestamp()});}
export async function createRecord(collectionName,data){const ref=await addDoc(collection(db,collectionName),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("CREATE",collectionName,ref.id,data);return ref.id;}
export async function createMemberProfile(uid,data){if(!uid)throw new Error("A Firebase Authentication UID is required.");await setDoc(doc(db,COLLECTIONS.members,uid),{...data,uid,memberType:data.memberType||"Governance Member",createdAt:data.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await writeAudit("CREATE_OR_UPDATE_MEMBER_PROFILE",COLLECTIONS.members,uid,{...data,uid});return uid;}
export async function generateEmployeeNumber(){const ref=doc(db,COLLECTIONS.employeeCounters,"employees");return runTransaction(db,async tx=>{const snap=await tx.get(ref);const next=snap.exists()?Number(snap.data().nextNumber||1):1;tx.set(ref,{nextNumber:next+1,updatedAt:serverTimestamp()},{merge:true});return`IRPA-EMP-${String(next).padStart(5,"0")}`;});}
export async function createEmployee(data){const cleanEmail=(data.email||"").trim().toLowerCase();if(!cleanEmail)throw new Error("Official Email is required.");const duplicateQuery=await getDocs(query(collection(db,COLLECTIONS.employees),where("email","==",cleanEmail)));if(!duplicateQuery.empty){const existing=duplicateQuery.docs[0];const existingData=existing.data();await writeAudit("DUPLICATE_EMPLOYEE_REGISTRATION_BLOCKED",COLLECTIONS.employees,existing.id,{employeeNumber:existingData.employeeNumber||null,email:cleanEmail});throw new Error(`An employee is already registered with ${cleanEmail}. Employee Number: ${existingData.employeeNumber||"not available"}. No new Employee Number was generated.`);}const employeeNumber=await generateEmployeeNumber();const ref=await addDoc(collection(db,COLLECTIONS.employees),{...data,email:cleanEmail,uid:data.uid||null,employeeNumber,status:data.employmentStatus||data.status||"Active",registrationStatus:"Registered",registrationDate:serverTimestamp(),registeredByUid:auth.currentUser?.uid||null,registeredByEmail:auth.currentUser?.email||null,registrationEmailStatus:"Pending",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("EMPLOYEE_REGISTRATION_SUCCESS",COLLECTIONS.employees,ref.id,{employeeNumber,email:cleanEmail,registrationEmailStatus:"Pending"});try{const emailResult=await sendEmployeeRegistrationEmail(cleanEmail,employeeNumber);await updateDoc(ref,{registrationEmailStatus:"Queued",registrationEmailQueuedAt:serverTimestamp(),registrationEmailError:null,registrationEmailProvider:"Firebase Authentication",registrationEmailAccountCreated:emailResult.accountCreated,updatedAt:serverTimestamp()});await writeAudit("EMPLOYEE_REGISTRATION_EMAIL_QUEUED",COLLECTIONS.employees,ref.id,{employeeNumber,email:cleanEmail,provider:"Firebase Authentication",accountCreated:emailResult.accountCreated});return{employeeNumber,id:ref.id,registrationEmailStatus:"Queued",emailResult};}catch(error){await updateDoc(ref,{registrationEmailStatus:"Failed",registrationEmailError:error.message||"Unable to send registration email",updatedAt:serverTimestamp()});await writeAudit("EMPLOYEE_REGISTRATION_EMAIL_FAILED",COLLECTIONS.employees,ref.id,{employeeNumber,email:cleanEmail,error:error.message||"Unable to send registration email"});return{employeeNumber,id:ref.id,registrationEmailStatus:"Failed",registrationEmailError:error.message||"Unable to send registration email"};}}
export async function retryEmployeeRegistrationEmail(employee){if(!employee?.id||!employee.employeeNumber)throw new Error("A valid employee record is required.");if(!employee.email)throw new Error("This employee has no official email address.");const emailResult=await sendEmployeeRegistrationEmail(employee.email,employee.employeeNumber);await updateDoc(doc(db,COLLECTIONS.employees,employee.id),{registrationEmailStatus:"Queued",registrationEmailQueuedAt:serverTimestamp(),registrationEmailError:null,registrationEmailProvider:"Firebase Authentication",registrationEmailAccountCreated:emailResult.accountCreated,updatedAt:serverTimestamp()});await writeAudit("RETRY_EMPLOYEE_REGISTRATION_EMAIL",COLLECTIONS.employees,employee.id,{employeeNumber:employee.employeeNumber,email:employee.email,provider:"Firebase Authentication",accountCreated:emailResult.accountCreated});return emailResult;}
export async function updateEmployee(id,data){if(!id)throw new Error("An employee record ID is required.");const existing=await getRecord(COLLECTIONS.employees,id);if(!existing)throw new Error("The employee record could not be found.");const changes={name:data.name,email:data.email?.trim().toLowerCase(),role:data.role,department:data.department,employmentType:data.employmentType,status:data.status,phone:data.phone,startDate:data.startDate,updatedAt:serverTimestamp()};await updateDoc(doc(db,COLLECTIONS.employees,id),changes);await writeAudit("UPDATE_EMPLOYEE_PROFILE",COLLECTIONS.employees,id,{...changes,employeeNumber:existing.employeeNumber});}
export async function createEmployeeProfile(data){const uid=data.uid||auth.currentUser?.uid;if(!uid)throw new Error("A Firebase Authentication UID is required.");const existing=await getRecord(COLLECTIONS.employees,uid);if(existing)return existing;const employeeNumber=data.employeeNumber||await generateEmployeeNumber();await setDoc(doc(db,COLLECTIONS.employees,uid),{...data,uid,employeeNumber,status:data.status||"Active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:false});await writeAudit("CREATE_EMPLOYEE_PROFILE",COLLECTIONS.employees,uid,{employeeNumber,role:data.role||"",department:data.department||""});return getRecord(COLLECTIONS.employees,uid);}
export async function provisionCurrentMemberFromInvitation(invitationId){const uid=auth.currentUser?.uid;const email=auth.currentUser?.email?.trim().toLowerCase();if(!uid||!email||!invitationId)return null;const invitation=await getRecord(COLLECTIONS.invitations,invitationId);if(!invitation)throw new Error("The member invitation could not be found.");if(invitation.email?.trim().toLowerCase()!==email)throw new Error("This invitation is not assigned to the authenticated email address.");if(invitation.status==="Cancelled")throw new Error("This member invitation has been cancelled.");const role=invitation.role||"Board Member";const memberType=invitation.memberType||"Governance Member";const member=await createMemberProfile(uid,{invitationId,email,name:invitation.name||"",role,memberType,status:"Active"});const employeeRoles=["Executive Director","Director Human Resources","HR Manager","Director Finance & Administration","Finance Personnel","Finance Manager","Accountant","Finance Officer","Director Internal Oversight","Internal Oversight Officer","Secretariat","Procurement Officer","Programme/Technical Officer","Management","Operations Manager","Rangeland Officer","Livestock Officer","Outreach Officer","Community Development Officer","Environment Officer","HR Officer","Employee"];if(employeeRoles.includes(role))await createEmployeeProfile({uid,email,name:invitation.name||"",role,department:invitation.department||"",employmentType:invitation.employmentType||"Employee",status:"Active",invitationId});return member;}
export async function getRecord(collectionName,id){const s=await getDoc(doc(db,collectionName,id));return s.exists()?{id:s.id,...s.data()}:null;}
export async function getRecords(collectionName){const s=await getDocs(query(collection(db,collectionName),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function getEmployeePaymentRequests(employeeUid){const s=await getDocs(query(collection(db,COLLECTIONS.staffPaymentRequests),where("employeeUid","==",employeeUid),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}

// Voting records are created only by the voting process. No voter UID, email or other voter identity is persisted in the ballot record.
export async function castAnonymousVote({meetingId,meetingReference,resolutionId=null,resolutionReference=null,votingReference,outcome,result="Pending",status="Locked",votingMethod="Meeting Vote"}){if(!auth.currentUser)throw new Error("Authentication is required to cast a vote.");if(!meetingId)throw new Error("A meeting is required for every voting process.");if(!votingReference?.trim())throw new Error("The voting origin / issue requiring voting action is required.");if(!["For","Against","Abstain"].includes(outcome))throw new Error("Invalid voting outcome.");const ref=await addDoc(collection(db,COLLECTIONS.votes),{voteReference:`IRPA-VOTE-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`,meetingId,meetingReference:votingReference?meetingReference||meetingId:null,resolutionId,resolutionReference,votingReference:votingReference.trim(),outcome,result,status,votingMethod,anonymous:true,votedAt:serverTimestamp(),createdAt:serverTimestamp()});await writeAudit("ANONYMOUS_VOTE_CAST",COLLECTIONS.votes,ref.id,{meetingId,resolutionId,votingReference:votingReference.trim(),outcome,result,status,votingMethod,anonymous:true});return ref.id;}

// Corrections never modify or delete the original ballot. They create a separate administrative record linked to the immutable vote.
export async function createVoteCorrection({voteId,reason,correctionNote}){if(!voteId||!reason?.trim()||!correctionNote?.trim())throw new Error("Vote, correction reason and correction note are required.");const ref=await addDoc(collection(db,COLLECTIONS.voteCorrections),{voteId,reason:reason.trim(),correctionNote:correctionNote.trim(),originalVotePreserved:true,requestedByUid:auth.currentUser?.uid||null,requestedAt:serverTimestamp(),status:"Administrative Review",createdAt:serverTimestamp()});await writeAudit("VOTE_CORRECTION_REQUEST_CREATED",COLLECTIONS.voteCorrections,ref.id,{voteId,reason:reason.trim(),originalVotePreserved:true});return ref.id;}

export async function updateRecord(collectionName,id,data){await updateDoc(doc(db,collectionName,id),{...data,updatedAt:serverTimestamp()});await writeAudit("UPDATE",collectionName,id,data);}
export async function processPaymentRequest(id,changes){const actor=currentActor();await updateDoc(doc(db,COLLECTIONS.staffPaymentRequests,id),{...changes,actionByUid:actor.uid,actionByEmail:actor.email,actionAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit("PAYMENT_WORKFLOW_ACTION",COLLECTIONS.staffPaymentRequests,id,{...changes,actorUid:actor.uid,actorEmail:actor.email});}
export async function deleteRecord(collectionName,id){await deleteDoc(doc(db,collectionName,id));await writeAudit("DELETE",collectionName,id);}
export async function getAdminProfile(uid){return uid?getRecord(COLLECTIONS.adminProfiles,uid):null;}
export async function getCurrentMemberProfile(){const uid=auth.currentUser?.uid;return uid?getRecord(COLLECTIONS.members,uid):null;}
export async function getCurrentEmployeeProfile(){const uid=auth.currentUser?.uid;return uid?getRecord(COLLECTIONS.employees,uid):null;}
