import{addDoc,collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,setDoc,updateDoc,where}from"firebase/firestore";
import{auth,db}from"./config";
import{COLLECTIONS,getRecord}from"./data";
import{ref,uploadBytes,ensureDocumentArchiveFolder,downloadDriveBytes}from"./signatureStorage";

export const PROCUREMENT_STAGES=["Quotations Required","PR Registration","Procurement Review","Pending Authorization","PO Generation","PO Generated","Delivery Note Required","Invoice Required","Finance Handoff","Sent to Finance","Payment Completed"];
export const PROCUREMENT_GOODS_SERVICES=[
 "Office Supplies & Stationery",
 "ICT Equipment & Services",
 "Furniture & Office Equipment",
 "Vehicles & Transport Services",
 "Vehicle Maintenance & Spare Parts",
 "Fuel & Lubricants",
 "Construction & Civil Works",
 "Building Maintenance & Repairs",
 "Water Infrastructure & Borehole Services",
 "Solar Energy & Electrical Services",
 "Livestock & Veterinary Supplies",
 "Animal Health Services",
 "Livestock Equipment & Infrastructure",
 "Agricultural Inputs & Fodder",
 "Rangeland Restoration & Environmental Services",
 "Tree Seedlings & Nursery Supplies",
 "Research & Consultancy Services",
 "Training & Capacity Development",
 "Travel & Accommodation Services",
 "Communication & Media Services",
 "Printing & Branding Services",
 "Security Services",
 "Cleaning & Sanitation Services",
 "Professional & Legal Services",
 "Insurance Services",
 "Financial & Audit Services",
 "Events & Conference Services",
 "Food & Catering Services",
 "Logistics & Freight Services",
 "Others"
];
export const PROCUREMENT_DEPARTMENTS=[
 "Executive Office",
 "Internal Oversight",
 "Livestock Development",
 "Environment & Sustainable Rangeland Management",
 "Finance & Administration",
 "Human Resources",
 "Outreach",
 "Community Development",
 "Field Department",
 "Operations"
];
export const PROCUREMENT_UNITS_BY_DEPARTMENT={
 "Executive Office":["Executive Director's Office","Management Coordination Unit"],
 "Internal Oversight":["Internal Oversight Unit","Compliance & Assurance Unit"],
 "Livestock Development":["Livestock Production Unit","Veterinary Services Unit","Breeding & Genetics Unit","Livestock Infrastructure Unit"],
 "Environment & Sustainable Rangeland Management":["Rangeland Management Unit","Rangeland Restoration Unit","Invasive Species Control Unit","Climate Change & Resilience Unit","Environmental Conservation & Education Unit"],
 "Finance & Administration":["Finance Unit","Accounting Unit","Administration Unit","Procurement Unit"],
 "Human Resources":["Human Resources & Staff Welfare Unit","Training & Capacity Development Unit","Personnel & Records Unit"],
 "Outreach":["Communications & Outreach Unit","Partnerships & Resource Mobilization Unit","ICT & Digital Engagement Unit"],
 "Community Development":["Community Mobilization Unit","Women & Youth Empowerment Unit","Gender & Social Inclusion Unit"],
 "Field Department":["Field Implementation Unit","Monitoring, Evaluation, Accountability & Learning Unit","Community-Based Monitoring Unit"],
 "Operations":["Logistics & Transport Unit","Infrastructure & Facilities Unit","General Operations Unit"]
};
export const PROCUREMENT_METHODS=[
 {value:"Request for Quotations",label:"Request for Quotations",entryLabel:"Quotations",minEntries:3,maxEntries:3,defaultEntries:3},
 {value:"Competitive Tender",label:"Competitive Tender",entryLabel:"Tender / Bid Documents",minEntries:1,maxEntries:10,defaultEntries:3},
 {value:"Direct Procurement",label:"Direct Procurement",entryLabel:"Supplier Quotation / Justification",minEntries:1,maxEntries:1,defaultEntries:1},
 {value:"Framework Contract",label:"Framework Contract",entryLabel:"Framework Call-off / Quotation",minEntries:1,maxEntries:1,defaultEntries:1}
];
export function procurementMethodConfig(method){return PROCUREMENT_METHODS.find(x=>x.value===method)||PROCUREMENT_METHODS[0]}
const TEAM_ROLES=["Procurement Officer","Procurement Manager","Procurement Team Member"];
const APPROVER_ROLES=["Executive Director","Director Livestock","Livestock Director","Director Internal Oversight","Internal Oversight Director","Director Finance & Administration","Director Human Resources","Director Outreach","Director Community Development","Director Environment","Director Field","Director Operations","Operations Director","Outreach Director","Community Development Director","Environment Director","Field Director"];
export function procurementTeamRole(role){return TEAM_ROLES.includes(role)}
export function procurementApproverRole(role){return APPROVER_ROLES.includes(role)}
export const PROCUREMENT_PERFORMANCE_CRITERIA=[
 {key:"quality",label:"Quality / conformity of goods or services",max:2},
 {key:"delivery",label:"Timeliness of delivery / service completion",max:2},
 {key:"compliance",label:"Compliance with specifications, contract and IRPA requirements",max:2},
 {key:"value",label:"Price competitiveness / value for money",max:2},
 {key:"responsiveness",label:"Responsiveness and communication",max:1},
 {key:"documentation",label:"Documentation, invoicing and professional conduct",max:1}
];
export const PROCUREMENT_BLACKLIST_THRESHOLD=6;
export const PROCUREMENT_BLACKLIST_MONTHS=6;
export const PROCUREMENT_PROBATION_MONTHS=3;
export const PROCUREMENT_PROBATION_MAX_ENGAGEMENTS=2;
function monthsAfter(date,months){const d=new Date(date);d.setMonth(d.getMonth()+months);return d}
function asDate(value){return value?.toDate?value.toDate():value?new Date(value):null}
export async function refreshVendorRestriction(v){if(!v)return v;const now=new Date();const blacklistStart=asDate(v.blacklistStartedAt||v.enteredAt);if((v.status==="Blacklisted"||v.performanceStatus==="Blacklisted")&&blacklistStart){const probationAt=monthsAfter(blacklistStart,PROCUREMENT_BLACKLIST_MONTHS);if(now>=probationAt){const probationStart=v.probationStartedAt||probationAt;await updateDoc(doc(db,COLLECTIONS.procurementVendors,v.id),{status:"Probation",performanceStatus:"Probation",probationStartedAt:probationStart,probationEndsAt:monthsAfter(asDate(probationStart),PROCUREMENT_PROBATION_MONTHS),updatedAt:serverTimestamp()});return{...v,status:"Probation",performanceStatus:"Probation",probationStartedAt:probationStart,probationEndsAt:monthsAfter(asDate(probationStart),PROCUREMENT_PROBATION_MONTHS)}}}if(v.status==="Probation"&&v.probationStartedAt){const probationEnd=asDate(v.probationEndsAt)||monthsAfter(asDate(v.probationStartedAt),PROCUREMENT_PROBATION_MONTHS);if(now>=probationEnd){await updateDoc(doc(db,COLLECTIONS.procurementVendors,v.id),{status:"Approved",performanceStatus:"Eligible",probationCompletedAt:serverTimestamp(),updatedAt:serverTimestamp()});return{...v,status:"Approved",performanceStatus:"Eligible"}}}return v}
export async function submitVendorPerformanceScore(vendorId,year,scores){const a=await team();const v=await getRecord(COLLECTIONS.procurementVendors,vendorId);if(!v)throw new Error("Vendor / service provider not found.");const y=Number(year);if(!Number.isInteger(y)||y<2020||y>2100)throw new Error("Enter a valid scoring year.");const values={};let total=0;for(const c of PROCUREMENT_PERFORMANCE_CRITERIA){const n=Number(scores?.[c.key]);if(!Number.isFinite(n)||n<0||n>c.max)throw new Error(c.label+" must be scored from 0 to "+c.max+".");values[c.key]=n;total+=n;}const scoreId=v.id+"_"+y;const scoreRef=doc(db,COLLECTIONS.procurementVendorScores,scoreId);const existing=await getDoc(scoreRef);if(existing.exists())throw new Error("An annual performance score for this vendor already exists for "+y+".");const blacklisted=total<PROCUREMENT_BLACKLIST_THRESHOLD;await setDoc(scoreRef,{vendorId:v.id,vendorRegistrationNumber:v.vendorRegistrationNumber||"",vendorName:v.name,year:y,scores:values,totalScore:total,maximumScore:10,threshold:PROCUREMENT_BLACKLIST_THRESHOLD,performanceStatus:blacklisted?"Blacklisted":"Eligible",scoredByUid:a.uid,scoredByName:a.name||a.email,scoredAt:serverTimestamp(),createdAt:serverTimestamp()});if(blacklisted){await setDoc(doc(db,COLLECTIONS.procurementVendorBlacklist,v.id),{vendorId:v.id,vendorRegistrationNumber:v.vendorRegistrationNumber||"",vendorName:v.name,reason:"Annual vendor/service provider performance score below 6 points.",score:total,threshold:PROCUREMENT_BLACKLIST_THRESHOLD,scoreYear:y,status:"Active",enteredByUid:a.uid,enteredByName:a.name||a.email,enteredAt:serverTimestamp(),blacklistStartedAt:serverTimestamp(),probationEngagements:0,updatedAt:serverTimestamp()},{merge:true});await updateDoc(doc(db,COLLECTIONS.procurementVendors,v.id),{status:"Blacklisted",blacklistScore:total,blacklistYear:y,updatedAt:serverTimestamp()});}else{await updateDoc(doc(db,COLLECTIONS.procurementVendors,v.id),{performanceScore:total,performanceScoreYear:y,performanceStatus:"Eligible",updatedAt:serverTimestamp()});}await audit("PROCUREMENT_VENDOR_PERFORMANCE_SCORED",COLLECTIONS.procurementVendorScores,scoreId,{vendorId:v.id,year:y,totalScore:total,performanceStatus:blacklisted?"Blacklisted":"Eligible"});return{scoreId,totalScore:total,blacklisted}}
export async function getVendorPerformanceScores(vendorId){await team();const q=await getDocs(query(collection(db,COLLECTIONS.procurementVendorScores),where("vendorId","==",vendorId)));return q.docs.map(x=>({id:x.id,...x.data()}))}

async function actor(){const uid=auth.currentUser?.uid;if(!uid)throw new Error("Authentication is required.");const s=await getDoc(doc(db,COLLECTIONS.members,uid));if(!s.exists()||s.data()?.status!=="Active")throw new Error("An active IRPA member profile is required.");return{uid,...s.data()}}
async function team(){const a=await actor();if(!procurementTeamRole(a.role))throw new Error("Procurement Team authorization is required.");return a}
async function audit(action,c,id,details={}){const a=await actor();await addDoc(collection(db,COLLECTIONS.audit),{action,collection:c,recordId:id,details,actorUid:a.uid,actorEmail:a.email||auth.currentUser?.email||null,createdAt:serverTimestamp()})}
async function nextNumber(counter,prefix){const r=doc(db,"systemSettings","procurementCounters");return runTransaction(db,async tx=>{const s=await tx.get(r);const n=Number(s.data()?.[counter]||0)+1;tx.set(r,{[counter]:n,updatedAt:serverTimestamp()},{merge:true});return prefix+"-"+new Date().getFullYear()+"-"+String(n).padStart(5,"0")})}
async function request(id){const r=await getRecord(COLLECTIONS.procurementRequests,id);if(!r)throw new Error("Procurement request not found.");return r}
export async function getMyProcurementRequests(){const a=await actor();const q=await getDocs(query(collection(db,COLLECTIONS.procurementRequests),where("requestedByUid","==",a.uid)));return q.docs.map(x=>({id:x.id,...x.data()}))}
export async function createProcurementVendor(data){const a=await actor();const name=String(data.name||"").trim();if(!name)throw new Error("Vendor / service provider name is required.");const serviceType=String(data.serviceType||"").trim();const serviceTypeOther=String(data.serviceTypeOther||"").trim();if(!PROCUREMENT_GOODS_SERVICES.includes(serviceType))throw new Error("Select a goods/service from the provided list.");if((serviceType==="Others"||serviceType==="Other")&&!serviceTypeOther)throw new Error("Please provide clarification for the Others selection.");const q=await getDocs(query(collection(db,COLLECTIONS.procurementVendors),where("name","==",name)));if(!q.empty)throw new Error("This vendor / service provider is already registered.");const vendorRegistrationNumber=await nextNumber("vendorRegistrationNumber","IRPA-VSP");const r=await addDoc(collection(db,COLLECTIONS.procurementVendors),{...data,name,serviceType,serviceTypeOther:serviceType==="Others"?serviceTypeOther:"",vendorRegistrationNumber,status:"Pending Review",registeredByUid:a.uid,registeredByEmail:a.email||auth.currentUser?.email,registeredByName:a.name||auth.currentUser?.email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_VENDOR_REGISTERED",COLLECTIONS.procurementVendors,r.id,{name,vendorRegistrationNumber});return r.id}
export async function createProcurementRequest(data){const a=await actor();let v=await getRecord(COLLECTIONS.procurementVendors,data.vendorId);v=await refreshVendorRestriction(v);if(!v)throw new Error("Registered vendor / service provider not found.");if(v.status!=="Approved"&&v.status!=="Probation")throw new Error("Only an approved or probationary registered vendor / service provider can be selected for a procurement request.");if(v.performanceStatus==="Blacklisted"||v.status==="Blacklisted")throw new Error("Procurement is restricted: this vendor / service provider is blacklisted following an annual performance score below 6 points.");if(v.status==="Probation"&&Number(v.probationEngagements||0)>=PROCUREMENT_PROBATION_MAX_ENGAGEMENTS)throw new Error("This vendor / service provider is on probation and has reached the maximum of 2 procurement/service engagements during the 3-month probation period.");const method=procurementMethodConfig(data.procurementMethod);const department=String(data.department||"").trim();const unit=String(data.unit||"").trim();if(!PROCUREMENT_DEPARTMENTS.includes(department))throw new Error("Select a valid IRPA department from the listed choices.");if(!(PROCUREMENT_UNITS_BY_DEPARTMENT[department]||[]).includes(unit))throw new Error("Select a valid unit from the listed choices for the selected department.");const requestedEntries=Math.max(method.minEntries,Math.min(method.maxEntries,Number(data.quotationRequiredCount||method.defaultEntries)));const n=await nextNumber("requestNumber","IRPA-PREQ");const requestRef=doc(collection(db,COLLECTIONS.procurementRequests));const requestData={requestNumber:n,title:String(data.title||"").trim(),description:String(data.description||"").trim(),department,unit,estimatedAmount:Number(data.estimatedAmount||0),procurementMethod:method.value,quotationRequiredCount:requestedEntries,vendorId:v.id,vendorName:v.name,vendorRegistrationNumber:v.vendorRegistrationNumber||v.registrationNumber||"",vendorStatus:v.status,status:"Quotations Required",quotationCount:0,requestedByUid:a.uid,requestedByEmail:a.email||auth.currentUser?.email,requestedByName:a.name||auth.currentUser?.email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};if(v.status==="Probation"){await runTransaction(db,async tx=>{const vendorRef=doc(db,COLLECTIONS.procurementVendors,v.id);const usage=await tx.get(vendorRef);const current=Number(usage.data()?.probationEngagements||0);if(usage.data()?.status!=="Probation"||current>=PROCUREMENT_PROBATION_MAX_ENGAGEMENTS)throw new Error("This vendor / service provider has reached its probation engagement allowance of 2.");tx.set(requestRef,requestData);tx.update(vendorRef,{probationEngagements:current+1,updatedAt:serverTimestamp()});});}else await setDoc(requestRef,requestData);await audit("PROCUREMENT_REQUEST_INITIATED",COLLECTIONS.procurementRequests,requestRef.id,{requestNumber:n,vendorStatus:v.status});return requestRef.id}
export async function uploadProcurementQuotation(id,file,number){const a=await actor();const r=await request(id);if(r.requestedByUid!==a.uid)throw new Error("Only the procurement requester may upload quotations.");if(r.status!=="Quotations Required")throw new Error("Quotation upload is not open at this stage.");const method=procurementMethodConfig(r.procurementMethod);const required=Number(r.quotationRequiredCount||method.defaultEntries);if(number<1||number>required)throw new Error("This procurement method requires "+required+" document entr"+(required===1?"y":"ies")+" at this stage.");if(!file)throw new Error("Select a PDF quotation.");if(file.type&&file.type!=="application/pdf")throw new Error("Only PDF quotation documents are accepted.");const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest("SHA-256",bytes);const fileHash=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");const hashRef=doc(db,"procurementQuotationHashes",fileHash);await runTransaction(db,async tx=>{const existing=await tx.get(hashRef);if(existing.exists()){const d=existing.data();if(d.requestId!==id||Number(d.quotationNumber)!==Number(number))throw new Error("DUPLICATE QUOTATION REJECTED: this document is already registered as quotation "+d.quotationNumber+" for procurement request "+(d.requestNumber||d.requestId)+".");return;}tx.set(hashRef,{requestId:id,requestNumber:r.requestNumber,quotationNumber:number,fileHash,uploadedByUid:a.uid,uploadedAt:serverTimestamp(),status:"Registered"});});const archive=await ensureDocumentArchiveFolder({documentId:r.requestNumber,title:r.title+" - Procurement Evidence",reference:r.requestNumber,archiveCategory:"Procurement Documents",classification:"Confidential"});const target=ref(null,"procurement/"+r.requestNumber+"/quotations/quotation-"+number+".pdf");const uploaded=await uploadBytes(target,file,{contentType:"application/pdf",purpose:"Procurement Quotation",folderId:archive.folderId,ownerUid:a.uid});const quotes=[...(r.quotations||[])];quotes[number-1]={number,fileName:file.name,fileId:target.fileId,fileHash,webViewLink:uploaded.metadata?.webViewLink||null,archiveUidLink:archive.archiveUidLink,uploadedByUid:a.uid,uploadedAt:new Date().toISOString()};const count=quotes.filter(Boolean).length;await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{quotations:quotes,quotationCount:count,procurementArchiveUidLink:archive.archiveUidLink,procurementArchiveFolderId:archive.folderId,status:count>=required?"PR Registration":"Quotations Required",updatedAt:serverTimestamp()});await audit("PROCUREMENT_QUOTATION_UPLOADED",COLLECTIONS.procurementRequests,id,{quotationNumber:number,quotationCount:count,fileHash,duplicateScanner:"SHA-256"});}
export async function registerProcurementPR(id){const a=await team();const r=await request(id);if(r.status!=="PR Registration")throw new Error("PR registration is not open.");const v=await getRecord(COLLECTIONS.procurementVendors,r.vendorId);if(!v||!["Approved","Probation"].includes(v.status))throw new Error("The registered vendor/service provider must be approved or on active probation before PR registration.");const n=await nextNumber("prNumber","IRPA-PR");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{prNumber:n,prRegisteredAt:serverTimestamp(),prRegisteredByUid:a.uid,vendorStatus:v.status,status:"Procurement Review",updatedAt:serverTimestamp()});await audit("PROCUREMENT_PR_REGISTERED",COLLECTIONS.procurementRequests,id,{prNumber:n});return n}
export async function reviewProcurementRequest(id,decision,type="request"){const a=await team();if(type==="vendor"){const v=await getRecord(COLLECTIONS.procurementVendors,id);if(!v)throw new Error("Vendor not found.");await updateDoc(doc(db,COLLECTIONS.procurementVendors,id),{status:decision==="Approved"?"Approved":"Rejected",reviewedByUid:a.uid,reviewedByName:a.name||a.email,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_VENDOR_REVIEWED",COLLECTIONS.procurementVendors,id,{decision});return}const r=await request(id);if(r.status!=="Procurement Review")throw new Error("Procurement Team review is not open.");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:decision==="Approved"?"Pending Authorization":"Rejected",procurementReviewDecision:decision,procurementReviewedByUid:a.uid,procurementReviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_REQUEST_REVIEWED",COLLECTIONS.procurementRequests,id,{decision})}
export async function authorizeProcurementRequest(id,approverUid){const a=await actor();if(a.uid!==approverUid||!procurementApproverRole(a.role))throw new Error("Only the selected authorised officer may approve this procurement.");const r=await request(id);if(r.status!=="Pending Authorization")throw new Error("Authorization is not open.");if(r.requestedByUid===a.uid)throw new Error("The procurement requester cannot authorize the same request.");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:"PO Generation",approverUid:a.uid,authorizedByUid:a.uid,authorizedByName:a.name||a.email,authorizedByRole:a.role,authorizedAt:serverTimestamp(),authorizationStatus:"Approved",updatedAt:serverTimestamp()});await audit("PROCUREMENT_AUTHORIZED",COLLECTIONS.procurementRequests,id,{approverUid:a.uid,approverRole:a.role})}
export async function generateProcurementPO(id){const a=await team();const r=await request(id);if(r.status!=="PO Generation")throw new Error("PO generation is not open.");const n=await nextNumber("poNumber","IRPA-PO");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{poNumber:n,poGeneratedAt:serverTimestamp(),poGeneratedByUid:a.uid,status:"Delivery Note Required",updatedAt:serverTimestamp()});await audit("PROCUREMENT_PO_GENERATED",COLLECTIONS.procurementRequests,id,{poNumber:n,prNumber:r.prNumber})}
export async function uploadProcurementEvidence(id,type,file){const a=await actor();const r=await request(id);if(r.requestedByUid!==a.uid)throw new Error("Only the procurement requester may upload delivery note and invoice.");if(type==="deliveryNote"&&r.status!=="Delivery Note Required")throw new Error("Delivery Note upload is not open.");if(type==="invoice"&&r.status!=="Invoice Required")throw new Error("Invoice upload is not open.");const archive=await ensureDocumentArchiveFolder({documentId:r.requestNumber,title:r.title+" - Procurement Evidence",reference:r.requestNumber,archiveCategory:"Procurement Documents",classification:"Confidential"});const target=ref(null,"procurement/"+r.requestNumber+"/"+type+".pdf");const uploaded=await uploadBytes(target,file,{contentType:"application/pdf",purpose:"Procurement "+type,folderId:archive.folderId,ownerUid:a.uid});const nextStatus=type==="deliveryNote"?"Invoice Required":"Finance Handoff";await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{[type]:{fileName:file.name,fileId:target.fileId,webViewLink:uploaded.metadata?.webViewLink||null,archiveUidLink:archive.archiveUidLink,uploadedByUid:a.uid,uploadedAt:new Date().toISOString()},procurementArchiveUidLink:archive.archiveUidLink,procurementArchiveFolderId:archive.folderId,status:nextStatus,updatedAt:serverTimestamp()});await audit("PROCUREMENT_"+type.toUpperCase()+"_UPLOADED",COLLECTIONS.procurementRequests,id,{fileId:target.fileId})}
export async function sendProcurementToFinance(id){const a=await team();const r=await request(id);if(r.status!=="Finance Handoff")throw new Error("Finance handoff is not open.");const evidence=[...(r.quotations||[]).map((x,i)=>({key:"quotation-"+(i+1),fileId:x?.fileId,fileName:x?.fileName||("quotation-"+(i+1)+".pdf")})),...(r.deliveryNote?.fileId?[{key:"delivery-note",fileId:r.deliveryNote.fileId,fileName:r.deliveryNote.fileName||"delivery-note.pdf"}]:[]),...(r.invoice?.fileId?[{key:"invoice",fileId:r.invoice.fileId,fileName:r.invoice.fileName||"invoice.pdf"}]:[])].filter(x=>x.fileId);if(!evidence.length)throw new Error("No uploaded procurement evidence was found for Finance handoff.");const financeArchive=await ensureDocumentArchiveFolder({documentId:"FIN-"+r.requestNumber,title:r.title+" - Finance Evidence",reference:r.poNumber||r.prNumber||r.requestNumber,archiveCategory:"Finance Documents",classification:"Confidential"});const financeFiles=[];for(const item of evidence){const bytes=await downloadDriveBytes(item.fileId);const target=ref(null,"finance/"+r.requestNumber+"/"+item.key+".pdf");const uploaded=await uploadBytes(target,bytes,{contentType:"application/pdf",purpose:"Controlled Documents",folderId:financeArchive.folderId,ownerUid:a.uid});financeFiles.push({sourceFileId:item.fileId,fileId:target.fileId,fileName:item.fileName,webViewLink:uploaded.metadata?.webViewLink||null});}const tx=await addDoc(collection(db,COLLECTIONS.financeTransactions),{title:"Procurement Payment — "+r.title,reference:r.poNumber||r.prNumber||r.requestNumber,amount:r.estimatedAmount||0,date:new Date().toISOString().slice(0,10),description:"Procurement payment request. Evidence package: "+r.requestNumber+"; PR "+r.prNumber+"; PO "+r.poNumber+".",payee:r.vendorName,transactionType:"Procurement Payment",costCentre:r.department,procurementRequestId:r.id,procurementRequestNumber:r.requestNumber,procurementPrNumber:r.prNumber,procurementPoNumber:r.poNumber,procurementEvidence:{quotations:r.quotations||[],deliveryNote:r.deliveryNote||null,invoice:r.invoice||null},financeArchiveUidLink:financeArchive.archiveUidLink,financeArchiveFolderId:financeArchive.folderId,financeEvidence:financeFiles,sourceModule:"Procurement",status:"Pending Approval",workflowStage:"Payment Processing",createdByUid:a.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:"Sent to Finance",financeTransactionId:tx.id,financeStatus:"Pending Payment",financeArchiveUidLink:financeArchive.archiveUidLink,financeArchiveFolderId:financeArchive.folderId,financeEvidence:financeFiles,sentToFinanceByUid:a.uid,sentToFinanceAt:serverTimestamp()});await audit("PROCUREMENT_SENT_TO_FINANCE",COLLECTIONS.procurementRequests,id,{financeTransactionId:tx.id,financeArchiveUidLink:financeArchive.archiveUidLink,evidenceCopied:financeFiles.length});return tx.id}
