import{addDoc,collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,updateDoc,where}from"firebase/firestore";
import{auth,db}from"./config";
import{COLLECTIONS,getRecord}from"./data";
import{ref,uploadBytes,ensureDocumentArchiveFolder}from"./signatureStorage";

export const PROCUREMENT_STAGES=["Quotations Required","PR Registration","Procurement Review","Pending Authorization","PO Generation","PO Generated","Delivery Note Required","Invoice Required","Finance Handoff","Sent to Finance","Payment Completed"];
const TEAM_ROLES=["Procurement Officer","Procurement Manager","Procurement Team Member"];
const APPROVER_ROLES=["Executive Director","Director Livestock","Livestock Director","Director Internal Oversight","Internal Oversight Director","Director Finance & Administration","Director Human Resources","Director Outreach","Director Community Development","Director Environment","Director Field","Director Operations","Operations Director","Outreach Director","Community Development Director","Environment Director","Field Director"];
export function procurementTeamRole(role){return TEAM_ROLES.includes(role)}
export function procurementApproverRole(role){return APPROVER_ROLES.includes(role)}
async function actor(){const uid=auth.currentUser?.uid;if(!uid)throw new Error("Authentication is required.");const s=await getDoc(doc(db,COLLECTIONS.members,uid));if(!s.exists()||s.data()?.status!=="Active")throw new Error("An active IRPA member profile is required.");return{uid,...s.data()}}
async function team(){const a=await actor();if(!procurementTeamRole(a.role))throw new Error("Procurement Team authorization is required.");return a}
async function audit(action,c,id,details={}){const a=await actor();await addDoc(collection(db,COLLECTIONS.audit),{action,collection:c,recordId:id,details,actorUid:a.uid,actorEmail:a.email||auth.currentUser?.email||null,createdAt:serverTimestamp()})}
async function nextNumber(counter,prefix){const r=doc(db,"systemSettings","procurementCounters");return runTransaction(db,async tx=>{const s=await tx.get(r);const n=Number(s.data()?.[counter]||0)+1;tx.set(r,{[counter]:n,updatedAt:serverTimestamp()},{merge:true});return prefix+"-"+new Date().getFullYear()+"-"+String(n).padStart(5,"0")})}
async function request(id){const r=await getRecord(COLLECTIONS.procurementRequests,id);if(!r)throw new Error("Procurement request not found.");return r}
export async function getMyProcurementRequests(){const a=await actor();const q=await getDocs(query(collection(db,COLLECTIONS.procurementRequests),where("requestedByUid","==",a.uid)));return q.docs.map(x=>({id:x.id,...x.data()}))}
export async function createProcurementVendor(data){const a=await actor();const name=String(data.name||"").trim();if(!name)throw new Error("Vendor / service provider name is required.");const q=await getDocs(query(collection(db,COLLECTIONS.procurementVendors),where("name","==",name)));if(!q.empty)throw new Error("This vendor / service provider is already registered.");const r=await addDoc(collection(db,COLLECTIONS.procurementVendors),{...data,name,status:"Pending Review",registeredByUid:a.uid,registeredByEmail:a.email||auth.currentUser?.email,registeredByName:a.name||auth.currentUser?.email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_VENDOR_REGISTERED",COLLECTIONS.procurementVendors,r.id,{name});return r.id}
export async function createProcurementRequest(data){const a=await actor();const v=await getRecord(COLLECTIONS.procurementVendors,data.vendorId);if(!v)throw new Error("Registered vendor / service provider not found.");const n=await nextNumber("requestNumber","IRPA-PREQ");const r=await addDoc(collection(db,COLLECTIONS.procurementRequests),{requestNumber:n,title:String(data.title||"").trim(),description:String(data.description||"").trim(),department:String(data.department||"").trim(),estimatedAmount:Number(data.estimatedAmount||0),procurementMethod:data.procurementMethod||"Request for Quotations",vendorId:v.id,vendorName:v.name,vendorRegistrationNumber:v.vendorRegistrationNumber||v.registrationNumber||"",vendorStatus:v.status,status:"Quotations Required",quotationCount:0,requestedByUid:a.uid,requestedByEmail:a.email||auth.currentUser?.email,requestedByName:a.name||auth.currentUser?.email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_REQUEST_INITIATED",COLLECTIONS.procurementRequests,r.id,{requestNumber:n});return r.id}
export async function uploadProcurementQuotation(id,file,number){const a=await actor();const r=await request(id);if(r.requestedByUid!==a.uid)throw new Error("Only the procurement requester may upload quotations.");if(r.status!=="Quotations Required")throw new Error("Quotation upload is not open at this stage.");const archive=await ensureDocumentArchiveFolder({documentId:r.requestNumber+"-Q"+number,title:r.title+" - Quotation "+number,reference:r.requestNumber+"-Q"+number,archiveCategory:"Procurement Documents",classification:"Confidential"});const target=ref(null,"procurement/"+r.requestNumber+"/quotations/quotation-"+number+".pdf");const uploaded=await uploadBytes(target,file,{contentType:"application/pdf",purpose:"Procurement Quotation",folderId:archive.folderId,ownerUid:a.uid});const quotes=[...(r.quotations||[])];quotes[number-1]={number,fileName:file.name,fileId:target.fileId,webViewLink:uploaded.metadata?.webViewLink||null,archiveUidLink:archive.archiveUidLink,uploadedByUid:a.uid,uploadedAt:new Date().toISOString()};const count=quotes.filter(Boolean).length;await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{quotations:quotes,quotationCount:count,status:count===3?"PR Registration":"Quotations Required",updatedAt:serverTimestamp()});await audit("PROCUREMENT_QUOTATION_UPLOADED",COLLECTIONS.procurementRequests,id,{quotationNumber:number,quotationCount:count})}
export async function registerProcurementPR(id){const a=await team();const r=await request(id);if(r.status!=="PR Registration")throw new Error("PR registration is not open.");const v=await getRecord(COLLECTIONS.procurementVendors,r.vendorId);if(!v||v.status!=="Approved")throw new Error("The registered vendor/service provider must be approved by the Procurement Team before PR registration.");const n=await nextNumber("prNumber","IRPA-PR");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{prNumber:n,prRegisteredAt:serverTimestamp(),prRegisteredByUid:a.uid,vendorStatus:"Approved",status:"Procurement Review",updatedAt:serverTimestamp()});await audit("PROCUREMENT_PR_REGISTERED",COLLECTIONS.procurementRequests,id,{prNumber:n});return n}
export async function reviewProcurementRequest(id,decision,type="request"){const a=await team();if(type==="vendor"){const v=await getRecord(COLLECTIONS.procurementVendors,id);if(!v)throw new Error("Vendor not found.");await updateDoc(doc(db,COLLECTIONS.procurementVendors,id),{status:decision==="Approved"?"Approved":"Rejected",reviewedByUid:a.uid,reviewedByName:a.name||a.email,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_VENDOR_REVIEWED",COLLECTIONS.procurementVendors,id,{decision});return}const r=await request(id);if(r.status!=="Procurement Review")throw new Error("Procurement Team review is not open.");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:decision==="Approved"?"Pending Authorization":"Rejected",procurementReviewDecision:decision,procurementReviewedByUid:a.uid,procurementReviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_REQUEST_REVIEWED",COLLECTIONS.procurementRequests,id,{decision})}
export async function authorizeProcurementRequest(id,approverUid){const a=await actor();if(a.uid!==approverUid||!procurementApproverRole(a.role))throw new Error("Only the selected authorised officer may approve this procurement.");const r=await request(id);if(r.status!=="Pending Authorization")throw new Error("Authorization is not open.");if(r.requestedByUid===a.uid)throw new Error("The procurement requester cannot authorize the same request.");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:"PO Generation",approverUid:a.uid,authorizedByUid:a.uid,authorizedByName:a.name||a.email,authorizedByRole:a.role,authorizedAt:serverTimestamp(),authorizationStatus:"Approved",updatedAt:serverTimestamp()});await audit("PROCUREMENT_AUTHORIZED",COLLECTIONS.procurementRequests,id,{approverUid:a.uid,approverRole:a.role})}
export async function generateProcurementPO(id){const a=await team();const r=await request(id);if(r.status!=="PO Generation")throw new Error("PO generation is not open.");const n=await nextNumber("poNumber","IRPA-PO");await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{poNumber:n,poGeneratedAt:serverTimestamp(),poGeneratedByUid:a.uid,status:"Delivery Note Required",updatedAt:serverTimestamp()});await audit("PROCUREMENT_PO_GENERATED",COLLECTIONS.procurementRequests,id,{poNumber:n,prNumber:r.prNumber})}
export async function uploadProcurementEvidence(id,type,file){const a=await actor();const r=await request(id);if(r.requestedByUid!==a.uid)throw new Error("Only the procurement requester may upload delivery note and invoice.");if(type==="deliveryNote"&&r.status!=="Delivery Note Required")throw new Error("Delivery Note upload is not open.");if(type==="invoice"&&r.status!=="Invoice Required")throw new Error("Invoice upload is not open.");const archive=await ensureDocumentArchiveFolder({documentId:r.requestNumber+"-"+type,title:r.title+" - "+type,reference:r.requestNumber+"-"+type,archiveCategory:"Procurement Documents",classification:"Confidential"});const target=ref(null,"procurement/"+r.requestNumber+"/"+type+".pdf");const uploaded=await uploadBytes(target,file,{contentType:"application/pdf",purpose:"Procurement "+type,folderId:archive.folderId,ownerUid:a.uid});const nextStatus=type==="deliveryNote"?"Invoice Required":"Finance Handoff";await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{[type]:{fileName:file.name,fileId:target.fileId,webViewLink:uploaded.metadata?.webViewLink||null,archiveUidLink:archive.archiveUidLink,uploadedByUid:a.uid,uploadedAt:new Date().toISOString()},status:nextStatus,updatedAt:serverTimestamp()});await audit("PROCUREMENT_"+type.toUpperCase()+"_UPLOADED",COLLECTIONS.procurementRequests,id,{fileId:target.fileId})}
export async function sendProcurementToFinance(id){const a=await team();const r=await request(id);if(r.status!=="Finance Handoff")throw new Error("Finance handoff is not open.");const tx=await addDoc(collection(db,COLLECTIONS.financeTransactions),{title:"Procurement Payment — "+r.title,reference:r.poNumber||r.prNumber||r.requestNumber,amount:r.estimatedAmount||0,date:new Date().toISOString().slice(0,10),description:"Procurement payment request. Evidence package: "+r.requestNumber+"; PR "+r.prNumber+"; PO "+r.poNumber+".",payee:r.vendorName,transactionType:"Procurement Payment",costCentre:r.department,procurementRequestId:r.id,procurementRequestNumber:r.requestNumber,procurementPrNumber:r.prNumber,procurementPoNumber:r.poNumber,procurementEvidence:{quotations:r.quotations||[],deliveryNote:r.deliveryNote||null,invoice:r.invoice||null},sourceModule:"Procurement",status:"Pending Approval",workflowStage:"Payment Processing",createdByUid:a.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,COLLECTIONS.procurementRequests,id),{status:"Sent to Finance",financeTransactionId:tx.id,financeStatus:"Pending Payment",sentToFinanceByUid:a.uid,sentToFinanceAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit("PROCUREMENT_SENT_TO_FINANCE",COLLECTIONS.procurementRequests,id,{financeTransactionId:tx.id});return tx.id}
