import { collection, doc, getDoc, getDocs, query, serverTimestamp, setDoc, where } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { auth, db, storage } from "./config";
const PROFILE_COLLECTION="signatureProfiles";const ENVELOPE_COLLECTION="signatureEnvelopes";
function user(){if(!auth.currentUser)throw new Error("Authentication is required.");return auth.currentUser;}
async function hash(file){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function uploadAsset(uid,type,file){if(!file)throw new Error(`${type} is required.`);if(!["image/png","image/jpeg","image/jpg","image/webp"].includes(file.type))throw new Error(`${type} must be PNG, JPG or WEBP.`);if(file.size>1024*1024)throw new Error(`${type} must not exceed 1 MB.`);const sha=await hash(file);const path=`signatureProfiles/${uid}/${type.toLowerCase()}-${sha}`;const r=ref(storage,path);await uploadBytes(r,file,{contentType:file.type,customMetadata:{ownerUid:uid,assetType:type,sha256:sha}});return{path,url:await getDownloadURL(r),sha};}
export async function getMySignatureProfile(){const u=user(),s=await getDoc(doc(db,PROFILE_COLLECTION,u.uid));return s.exists()?{id:s.id,...s.data()}:null;}
export async function saveMySignatureProfile({signatureFile,initialsFile,displayName,initials,method="Upload"}){const u=user();if(!String(displayName||u.displayName||"").trim())throw new Error("Display name is required.");const signature=await uploadAsset(u.uid,"Signature",signatureFile);const initialsAsset=initialsFile?await uploadAsset(u.uid,"Initials",initialsFile):null;const p={uid:u.uid,email:u.email||"",displayName:String(displayName).trim(),initials:String(initials||"").trim(),method,signaturePath:signature.path,signatureUrl:signature.url,signatureSha256:signature.sha,initialsPath:initialsAsset?.path||null,initialsUrl:initialsAsset?.url||null,initialsSha256:initialsAsset?.sha||null,status:"Active",updatedAt:serverTimestamp()};await setDoc(doc(db,PROFILE_COLLECTION,u.uid),p,{merge:true});return p;}
export async function getSignatureEnvelopes(){const u=user();const q=query(collection(db,ENVELOPE_COLLECTION),where("participantUids","array-contains",u.uid));const s=await getDocs(q);return s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>String(b.createdAt?.seconds||0).localeCompare(String(a.createdAt?.seconds||0)));}
export async function createSignatureEnvelope({title,documentId,documentReference,signingMode,recipients,fields=[]}){const u=user();if(!title?.trim())throw new Error("Envelope title is required.");if(!documentId)throw new Error("An authorized document must be selected.");if(!recipients?.length)throw new Error("At least one signer is required.");const envelopeId=`IRPA-ENV-${new Date().getFullYear()}-${Date.now().toString().slice(-8)}`;const participantUids=[u.uid,...recipients.map(r=>r.uid).filter(Boolean)];const payload={envelopeReference:envelopeId,title:title.trim(),documentId,documentReference:documentReference||"",senderUid:u.uid,senderEmail:u.email||"",status:"Draft",signingMode:signingMode||"Sequential",recipients,fields,participantUids,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,ENVELOPE_COLLECTION,envelopeId),payload);return{id:envelopeId,...payload};}
export async function recordSignatureAdoption({documentId,documentReference,fieldId,signatureProfile}){const u=user(),r=doc(collection(db,"signatures"));await setDoc(r,{documentId:documentId||null,documentReference:documentReference||"",fieldId:fieldId||"",signerUid:u.uid,signerEmail:u.email||"",signerName:signatureProfile?.displayName||u.displayName||"",signatureMethod:signatureProfile?.method||"Upload",signatureSha256:signatureProfile?.signatureSha256||null,status:"Signed",signedAt:serverTimestamp(),createdAt:serverTimestamp(),immutable:true});return r.id;}
