import { collection, doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { auth, db, storage } from "./config";
const COLLECTION="signatureProfiles";
function user(){if(!auth.currentUser)throw new Error("Authentication is required.");return auth.currentUser;}
async function hash(file){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function uploadAsset(uid,type,file){if(!file)throw new Error(`${type} is required.`);if(!["image/png","image/jpeg","image/jpg","image/webp"].includes(file.type))throw new Error(`${type} must be PNG, JPG or WEBP.`);if(file.size>1024*1024)throw new Error(`${type} must not exceed 1 MB.`);const sha=await hash(file);const path=`signatureProfiles/${uid}/${type.toLowerCase()}-${sha}`;const r=ref(storage,path);await uploadBytes(r,file,{contentType:file.type,customMetadata:{ownerUid:uid,assetType:type,sha256:sha}});return{path,url:await getDownloadURL(r),sha};}
export async function getMySignatureProfile(){const u=user(),s=await getDoc(doc(db,COLLECTION,u.uid));return s.exists()?{id:s.id,...s.data()}:null;}
export async function saveMySignatureProfile({signatureFile,initialsFile,displayName,initials,method="Upload"}){const u=user();if(!String(displayName||u.displayName||"").trim())throw new Error("Display name is required.");const signature=await uploadAsset(u.uid,"Signature",signatureFile);const initialsAsset=initialsFile?await uploadAsset(u.uid,"Initials",initialsFile):null;const p={uid:u.uid,email:u.email||"",displayName:String(displayName).trim(),initials:String(initials||"").trim(),method,signaturePath:signature.path,signatureUrl:signature.url,signatureSha256:signature.sha,initialsPath:initialsAsset?.path||null,initialsUrl:initialsAsset?.url||null,initialsSha256:initialsAsset?.sha||null,status:"Active",updatedAt:serverTimestamp()};await setDoc(doc(db,COLLECTION,u.uid),p,{merge:true});return p;}
export async function recordSignatureAdoption({documentId,documentReference,fieldId,signatureProfile}){const u=user(),r=doc(collection(db,"signatures"));await setDoc(r,{documentId:documentId||null,documentReference:documentReference||"",fieldId:fieldId||"",signerUid:u.uid,signerEmail:u.email||"",signerName:signatureProfile?.displayName||u.displayName||"",signatureMethod:signatureProfile?.method||"Upload",signatureSha256:signatureProfile?.signatureSha256||null,status:"Signed",signedAt:serverTimestamp(),createdAt:serverTimestamp(),immutable:true});return r.id;}
