import React,{useEffect,useMemo,useState}from"react";
import{getCurrentMemberProfile,getRecords,COLLECTIONS}from"../firebase/data";
import{createAuthorizationWorkflow,getAuthorizationWorkflows,transitionAuthorization,ROLES}from"../firebase/authorizationWorkflow";
import"../styles/workflow.css";

const STAGES=["Draft","Submitted","Under Review","Approved","Rejected","Returned","Completed"];
const EMPTY={title:"",requestedByName:"",reviewerUid:"",reviewerName:"",approverUid:"",approverName:"",implementerUid:"",implementerName:"",amount:"",budgetLine:"",justification:"",involvedUids:""};
function Field({label,name,value,onChange,type="text",wide=false,required=false,children}){return <div className={wide?"form-field form-field-wide":"form-field"}><label>{label}</label>{children||<input type={type}name={name}value={value||""}onChange={onChange}required={required}/>}</div>}
function canReview(r,p){return p?.uid===r.reviewerUid&&ROLES.reviewer.includes(p.role)}
function canApprove(r,p){return p?.uid===r.approverUid&&ROLES.approver.includes(p.role)&&r.requestedByUid!==p.uid}
function canImplement(r,p){return p?.uid===r.implementerUid&&ROLES.implementer.includes(p.role)}
export default function AuthorizationWorkflow(){
 const[profile,setProfile]=useState(null),[employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState(EMPTY),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){try{const p=await getCurrentMemberProfile();setProfile(p);const[e,r]=await Promise.all([getRecords(COLLECTIONS.employees),getAuthorizationWorkflows()]);setEmployees(e.filter(x=>x.status==="Active"));setRows(r)}catch(e){setErr(e.message||"Unable to load authorization register.")}}
 useEffect(()=>{load()},[]);
 const people=useMemo(()=>employees.map(x=>({uid:x.uid||x.id,name:x.name||x.email||x.id,email:x.email||"",role:x.role||""})),[employees]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 function personOptions(roles){return people.filter(p=>roles.includes(p.role))}
 function setPerson(field,uid){const p=people.find(x=>x.uid===uid);setForm({...form,[field]:uid,[field.replace("Uid","Name")]:p?.name||p?.email||""})}
 async function submit(e){e.preventDefault();setBusy(true);setErr("");setMsg("");try{if(form.reviewerUid===form.approverUid)throw new Error("Reviewer and approver must be different people.");await createAuthorizationWorkflow(form);setForm(EMPTY);setMsg("Authorization request created in Draft. The requester must submit it before review.");await load()}catch(e){setErr(e.message||"Unable to create authorization request.")}finally{setBusy(false)}}
 async function act(next){if(!selected)return;setBusy(true);setErr("");setMsg("");try{await transitionAuthorization(selected.id,next,reason);setReason("");setMsg(`Authorization moved to ${next}.`);await load();setSelected(null)}catch(e){setErr(e.message||"Workflow transition failed.")}finally{setBusy(false)}}
 function actionButtons(r){const b=[];if(r.status==="Draft"&&r.requestedByUid===profile?.uid)b.push("Submitted");if(r.status==="Submitted"&&canReview(r,profile)){b.push("Under Review","Returned")}if(r.status==="Under Review"&&canReview(r,profile))b.push("Returned");if(r.status==="Under Review"&&canApprove(r,profile))b.push("Approved","Rejected");if(r.status==="Approved"&&canImplement(r,profile))b.push("Completed");if(r.status==="Returned"&&r.requestedByUid===profile?.uid)b.push("Submitted");return b}
 const filtered=rows.filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">CONTROLLED AUTHORIZATION WORKFLOW</span><h1>Authorization & Approvals</h1><p>Role-separated operational authorization: requester → reviewer → Executive Director approver → authorised implementer.</p></div><div className="identity-card"><span>YOUR ROLE</span><strong>{profile?.role||"Loading..."}</strong></div></section>{msg&&<div className="success-message action-feedback">{msg}</div>}{err&&<div className="error-message action-feedback">{err}</div>}
 <section className="panel"><div className="panel-header"><div><h2>New Authorization Request</h2><p className="panel-description">The authenticated user becomes the requester automatically. Approval cannot be performed by the requester.</p></div></div><form onSubmit={submit}><div className="form-grid"><Field label="Title / Subject"name="title"value={form.title}onChange={change}required/><Field label="Requested Amount"name="amount"value={form.amount}onChange={change}/><Field label="Budget Line"name="budgetLine"value={form.budgetLine}onChange={change}/><Field label="Reviewer"name="reviewerUid"value={form.reviewerUid}onChange={e=>setPerson("reviewerUid",e.target.value)}required><select name="reviewerUid"value={form.reviewerUid}onChange={e=>setPerson("reviewerUid",e.target.value)}required><option value="">Select authorised reviewer</option>{personOptions(ROLES.reviewer).map(p=><option key={p.uid}value={p.uid}>{p.name} — {p.role}</option>)}</select></Field><Field label="Approver"name="approverUid"value={form.approverUid}onChange={e=>setPerson("approverUid",e.target.value)}required><select name="approverUid"value={form.approverUid}onChange={e=>setPerson("approverUid",e.target.value)}required><option value="">Select Executive Director</option>{personOptions(ROLES.approver).map(p=><option key={p.uid}value={p.uid}>{p.name} — {p.role}</option>)}</select></Field><Field label="Implementer / Accounting Officer"name="implementerUid"value={form.implementerUid}onChange={e=>setPerson("implementerUid",e.target.value)}><select name="implementerUid"value={form.implementerUid}onChange={e=>setPerson("implementerUid",e.target.value)}><option value="">Use approver after approval</option>{personOptions(ROLES.implementer).map(p=><option key={p.uid}value={p.uid}>{p.name} — {p.role}</option>)}</select></Field><Field label="Additional Involved User UIDs"name="involvedUids"value={form.involvedUids}onChange={change}/><Field label="Justification / Request"name="justification"value={form.justification}onChange={change}wide required/></div><div className="form-actions"><button disabled={busy}>{busy?"Processing...":"Create Authorization Request"}</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><h2>Authorization Register</h2><span>{filtered.length} record(s)</span></div><input className="table-search"placeholder="Search authorization..."value={search}onChange={e=>setSearch(e.target.value)}/></div><div className="workflow-steps">{STAGES.map((s,i)=><span key={s}className="workflow-step">{i+1}. {s}</span>)}</div><div className="table-wrapper"><table><thead><tr><th>Reference / Subject</th><th>Stage</th><th>Requester</th><th>Reviewer</th><th>Approver</th><th>Control</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="6">No authorization records found.</td></tr>:filtered.map(r=><tr key={r.id}><td><strong>{r.reference}</strong><div className="table-subtext">{r.title}</div></td><td><span className="status-badge">{r.status}</span></td><td>{r.requestedByName||r.requestedByEmail||"—"}</td><td>{r.reviewerName||"—"}</td><td>{r.approverName||"—"}</td><td><button type="button"onClick={()=>setSelected(r)}>Open</button></td></tr>)}</tbody></table></div></section>
 {selected&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">AUTHORIZATION RECORD</span><h2>{selected.reference}</h2><p>{selected.title} · {selected.status} · Version {selected.workflowVersion||1}</p></div><button className="secondary-button"onClick={()=>setSelected(null)}>Close</button></div><div className="form-grid"><Field label="Requester"name="x"value={selected.requestedByName||selected.requestedByEmail}onChange={()=>{}}/><Field label="Reviewer"name="x"value={selected.reviewerName}onChange={()=>{}}/><Field label="Approver"name="x"value={selected.approverName}onChange={()=>{}}/><Field label="Implementer"name="x"value={selected.implementerName}onChange={()=>{}}/><Field label="Amount"name="x"value={selected.amount}onChange={()=>{}}/><Field label="Budget Line"name="x"value={selected.budgetLine}onChange={()=>{}}/><Field label="Justification"name="x"value={selected.justification}onChange={()=>{}}wide/></div><div className="workflow-timeline">{(selected.history||[]).map((h,i)=><div className="workflow-event"key={i}><strong>{h.status}</strong><span>{h.action||""}</span><small>{h.reason||""}</small></div>)}</div>{actionButtons(selected).length>0&&<><div className="form-field form-field-wide"><label>Reason (required for Return / Reject)</label><textarea value={reason}onChange={e=>setReason(e.target.value)}placeholder="Enter decision or return reason..."/></div><div className="form-actions">{actionButtons(selected).map(a=><button key={a}disabled={busy}onClick={()=>act(a)}>{a}</button>)}</div></>}</section>}
 </div>;
}
