import React,{useEffect,useState}from"react";
import {createEmployee,getRecords,updateRecord,deleteRecord,COLLECTIONS}from"../firebase/data";

const empty={name:"",email:"",phone:"",gender:"",dateOfBirth:"",nationality:"Tanzanian",address:"",role:"Board Member",department:"Board of Directors",employmentType:"Board Appointment",status:"Active",startDate:"",appointmentDate:"",termStart:"",termEnd:"",biography:""};
const positions=["Board Chairperson","Board Vice Chairperson","Board Secretary","Board Treasurer","Board Member"];

export default function BoardMembers(){
 const[records,setRecords]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[viewing,setViewing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState("");
 async function load(){try{const all=await getRecords(COLLECTIONS.employees);setRecords(all.filter(x=>x.boardMember===true||x.role==="Board Member"||x.boardPosition))}catch(e){setError(e.message||"Unable to load Board Member register.")}}
 useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 function reset(){setEditing(null);setForm(empty)}
 function startEdit(r){setEditing(r);setViewing(null);setError("");setMessage("");setForm({...empty,...Object.fromEntries(Object.keys(empty).map(k=>[k,r[k]??empty[k]]))});window.scrollTo({top:0,behavior:"smooth"})}
 async function submit(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(editing){await updateRecord(COLLECTIONS.employees,editing.id,{...form,role:"Board Member",department:"Board of Directors",employmentType:"Board Appointment",boardMember:true,registrationStatus:"Registered"});setMessage(`✓ ${editing.employeeNumber} Board Member record updated successfully.`)}else{const result=await createEmployee({...form,role:"Board Member",department:"Board of Directors",employmentType:"Board Appointment",boardMember:true,boardPosition:form.boardPosition||"Board Member",registrationStatus:"Registered — Account Pending"});setMessage(`✓ Board Member ${result.employeeNumber} registered successfully. The institutional record is now available for account invitation and activation.`)}reset();await load()}catch(x){setError(x.message||"Unable to save Board Member registration.")}finally{setBusy(false)}}
 async function deactivate(r){if(!window.confirm(`Deactivate ${r.name||r.employeeNumber}?`))return;setBusy(true);setError("");try{await updateRecord(COLLECTIONS.employees,r.id,{status:"Inactive",employmentStatus:"Inactive",boardMember:true});await load();setMessage(`✓ ${r.employeeNumber} is now inactive.`)}catch(e){setError(e.message||"Unable to deactivate Board Member.")}finally{setBusy(false)}}
 async function remove(r){if(!window.confirm(`Permanently delete ${r.employeeNumber} — ${r.name}? This cannot be undone.`))return;setBusy(true);setError("");try{await deleteRecord(COLLECTIONS.employees,r.id);await load();setMessage(`✓ ${r.employeeNumber} was deleted.`)}catch(e){setError(e.message||"Unable to delete Board Member.")}finally{setBusy(false)}}
 const filtered=records.filter(r=>!search.trim()||[r.employeeNumber,r.name,r.email,r.boardPosition,r.status,r.registrationStatus].join(" ").toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="page">
  <div className="page-header"><div><span className="eyebrow">GOVERNANCE MEMBERSHIP REGISTER</span><h1>Board Members Registration</h1><p>Authoritative IRPA Board Member register. Registration creates the institutional record first; account invitation and activation are handled separately.</p></div><button onClick={()=>{reset();setError("");setMessage("");window.scrollTo({top:0,behavior:"smooth"})}}>+ Register Board Member</button></div>
  {message&&<div className="success-message action-feedback"role="status">{message}</div>}{error&&<div className="error-message action-feedback"role="alert">{error}</div>}
  <section className="panel"><div className="panel-header"><div><h2>{editing?`Edit ${editing.employeeNumber}`:"Register Board Member"}</h2><span>Institutional record before system account activation</span></div></div>
   <form onSubmit={submit}><div className="form-grid">
    <div className="form-field"><label>Full Name</label><input name="name"value={form.name}onChange={change}required/></div>
    <div className="form-field"><label>Official Email</label><input type="email"name="email"value={form.email}onChange={change}required/></div>
    <div className="form-field"><label>Board Position</label><select name="boardPosition"value={form.boardPosition||"Board Member"}onChange={change}>{positions.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="form-field"><label>Phone</label><input name="phone"value={form.phone}onChange={change}/></div>
    <div className="form-field"><label>Gender</label><select name="gender"value={form.gender}onChange={change}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></div>
    <div className="form-field"><label>Date of Birth</label><input type="date"name="dateOfBirth"value={form.dateOfBirth}onChange={change}/></div>
    <div className="form-field"><label>Nationality</label><input name="nationality"value={form.nationality}onChange={change}/></div>
    <div className="form-field"><label>Address</label><input name="address"value={form.address}onChange={change}/></div>
    <div className="form-field"><label>Appointment Date</label><input type="date"name="appointmentDate"value={form.appointmentDate}onChange={change}required/></div>
    <div className="form-field"><label>Term Start</label><input type="date"name="termStart"value={form.termStart}onChange={change}required/></div>
    <div className="form-field"><label>Term End</label><input type="date"name="termEnd"value={form.termEnd}onChange={change}/></div>
    <div className="form-field"><label>Governance Status</label><select name="status"value={form.status}onChange={change}><option>Active</option><option>Inactive</option><option>Suspended</option><option>Term Ended</option></select></div>
    <div className="form-field form-field-wide"><label>Professional Biography / Board Profile</label><textarea name="biography"value={form.biography}onChange={change}rows="4"placeholder="Qualifications, professional background and relevant Board profile information"/></div>
   </div><div className="form-actions"><button disabled={busy}>{busy?(editing?"Saving...":"Registering..."):(editing?"Save Board Member":"Register Board Member")}</button>{editing&&<button type="button"className="secondary-button"onClick={reset}disabled={busy}>Cancel</button>}</div></form>
  </section>
  <section className="panel"><div className="panel-header"><div><h2>Official Board Member Register</h2><span>{filtered.length} of {records.length} registered Board Member(s)</span></div><input className="table-search"placeholder="Search Board Members..."value={search}onChange={e=>setSearch(e.target.value)}/></div>
   <div className="table-wrapper"><table><thead><tr><th>IRPA ID</th><th>Name</th><th>Position</th><th>Email</th><th>Term</th><th>Status</th><th>Account</th><th>Actions</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="8">No Board Members registered.</td></tr>:filtered.map(r=><tr key={r.id}><td><strong>{r.employeeNumber}</strong></td><td>{r.name||"—"}</td><td>{r.boardPosition||"Board Member"}</td><td>{r.email||"—"}</td><td>{r.termStart||"—"}{r.termEnd?` → ${r.termEnd}`:""}</td><td><span className="status-badge">{r.status||r.employmentStatus||"—"}</span></td><td><span className="status-badge">{r.uid?"Activated":"Account Pending"}</span></td><td><div className="member-actions"><button type="button"onClick={()=>setViewing(r)}disabled={busy}>View</button><button type="button"onClick={()=>startEdit(r)}disabled={busy}>Edit</button>{(r.status||r.employmentStatus)==="Active"&&<button type="button"onClick={()=>deactivate(r)}disabled={busy}>Deactivate</button>}<button type="button"className="danger-button"onClick={()=>remove(r)}disabled={busy}>Delete</button></div></td></tr>)}</tbody></table></div>
  </section>
  {viewing&&<section className="panel"><div className="panel-header"><div><h2>Board Member Profile</h2><span>{viewing.employeeNumber}</span></div><button className="secondary-button"onClick={()=>setViewing(null)}>Close</button></div><div className="detail-grid">{[["IRPA ID",viewing.employeeNumber],["Full Name",viewing.name],["Official Email",viewing.email],["Board Position",viewing.boardPosition||"Board Member"],["Phone",viewing.phone],["Gender",viewing.gender],["Date of Birth",viewing.dateOfBirth],["Nationality",viewing.nationality],["Address",viewing.address],["Appointment Date",viewing.appointmentDate],["Term Start",viewing.termStart],["Term End",viewing.termEnd],["Governance Status",viewing.status||viewing.employmentStatus],["Registration Status",viewing.registrationStatus],["Account UID",viewing.uid||"Not activated"],["Biography",viewing.biography],["Registered By",viewing.registeredByEmail]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b||"—"}</strong></div>)}</div></section>}
 </div>;
}
