import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,updateRecord}from"../firebase/data";
import{uploadCommunicationMediaAsset}from"../firebase/signatureStorage";

const ROLES=["Communications Officer","Director Outreach","Outreach Director","Director Community Development","Community Development Director","Executive Director"];
const box={background:"rgba(255,255,255,.045)",border:"1px solid rgba(255,255,255,.12)",borderRadius:16,padding:18};
const CONTENT_STAGES=["Draft","Under Review","Approved","Published","Archived"];
const REQUEST_STAGES=["New","Assigned","In Production","For Approval","Completed","Cancelled"];
const EVENT_STAGES=["Planned","Confirmed","In Progress","Completed","Cancelled"];
const ASSET_TYPES=["Photo","Video","Audio","Graphic","Publication PDF","Press Material","Brand Asset","Other"];
const CONTENT_TYPES=["News","Press Release","Field Story","Publication","Event Notice","Campaign","Internal Notice","Social Media","Photo Caption","Statement"];
const AUDIENCES=["Internal","Public","Partners","Media"];
const PRIORITIES=["Normal","High","Urgent"];

const actor=(profile,employee,role)=>({createdByUid:profile?.uid||employee?.uid||null,createdByRole:role,recordOrigin:"PRODUCTION"});
const fmtDate=value=>{if(!value)return"—";const d=value?.toDate?.()||new Date(value);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});};

export default function CommunicationMediaPortal({profile,employee,selectedAuthority,admin=false,onNavigate}){
 const role=String(selectedAuthority||profile?.role||"").trim(),ok=admin||ROLES.includes(role);
 const[content,setContent]=useState([]),[requests,setRequests]=useState([]),[assets,setAssets]=useState([]),[events,setEvents]=useState([]);
 const[tab,setTab]=useState("Command"),[msg,setMsg]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[uploadBusy,setUploadBusy]=useState(false);
 const[assetType,setAssetType]=useState("Photo"),[contentFilter,setContentFilter]=useState("All"),[requestFilter,setRequestFilter]=useState("All"),[assetFilter,setAssetFilter]=useState("All");
 const[form,setForm]=useState({title:"",type:"News",summary:"",body:"",audience:"Internal",priority:"Normal"});
 const[requestForm,setRequestForm]=useState({title:"",description:"",priority:"Normal",requestedFor:"",dueDate:""});
 const[eventForm,setEventForm]=useState({title:"",eventDate:"",location:"",purpose:"",audience:"Public",lead:""});
 const actorData=actor(profile,employee,role);
 async function refresh(){const r=await Promise.all(["communicationContent","mediaRequests","mediaAssets","communicationEvents"].map(k=>getRecords(k).catch(()=>[])));setContent(r[0]);setRequests(r[1]);setAssets(r[2]);setEvents(r[3]);}
 useEffect(()=>{let live=true;(async()=>{const r=await Promise.all(["communicationContent","mediaRequests","mediaAssets","communicationEvents"].map(k=>getRecords(k).catch(()=>[])));if(live){setContent(r[0]);setRequests(r[1]);setAssets(r[2]);setEvents(r[3])}})();return()=>{live=false}},[]);
 if(!ok)return <div className="page"><section className="panel"><h1>Communication & Media</h1><p>Access is restricted to authorized communication and management capacities.</p></section></div>;

 async function saveContent(e){e.preventDefault();setBusy(true);setMsg("");setError("");try{await createRecord("communicationContent",{...form,title:form.title.trim(),summary:form.summary.trim(),body:form.body.trim(),status:"Draft",...actorData});setForm({title:"",type:"News",summary:"",body:"",audience:"Internal",priority:"Normal"});await refresh();setMsg("Editorial draft registered in the controlled pipeline.");setTab("Editorial");}catch(x){setError(x.message||"Unable to save content.")}finally{setBusy(false)}}
 async function transitionContent(row,next){setBusy(true);try{await updateRecord("communicationContent",row.id,{status:next,statusChangedAt:new Date().toISOString(),statusChangedByUid:profile?.uid||employee?.uid||null});await refresh();setMsg(`${row.title||"Content"} moved to ${next}.`)}catch(x){setError(x.message||"Unable to change content status.")}finally{setBusy(false)}}
 async function mediaRequest(e){e.preventDefault();setBusy(true);try{if(!requestForm.title.trim())throw new Error("Request title is required.");await createRecord("mediaRequests",{...requestForm,title:requestForm.title.trim(),status:"New",...actorData});setRequestForm({title:"",description:"",priority:"Normal",requestedFor:"",dueDate:""});await refresh();setMsg("Media production request registered.");setTab("Requests")}catch(x){setError(x.message||"Unable to register request.")}finally{setBusy(false)}}
 async function transitionRequest(row,next){setBusy(true);try{await updateRecord("mediaRequests",row.id,{status:next,statusChangedAt:new Date().toISOString(),statusChangedByUid:profile?.uid||employee?.uid||null});await refresh();setMsg(`${row.title||"Request"} moved to ${next}.`)}catch(x){setError(x.message||"Unable to change request status.")}finally{setBusy(false)}}
 async function createEvent(e){e.preventDefault();setBusy(true);try{if(!eventForm.title.trim()||!eventForm.eventDate)throw new Error("Event title and date are required.");await createRecord("communicationEvents",{...eventForm,title:eventForm.title.trim(),status:"Planned",...actorData});setEventForm({title:"",eventDate:"",location:"",purpose:"",audience:"Public",lead:""});await refresh();setMsg("Communication event registered.");setTab("Events")}catch(x){setError(x.message||"Unable to register event.")}finally{setBusy(false)}}
 async function transitionEvent(row,next){setBusy(true);try{await updateRecord("communicationEvents",row.id,{status:next,statusChangedAt:new Date().toISOString(),statusChangedByUid:profile?.uid||employee?.uid||null});await refresh();setMsg(`${row.title||"Event"} moved to ${next}.`)}catch(x){setError(x.message||"Unable to change event status.")}finally{setBusy(false)}}
 async function uploadMedia(e){const file=e.target.files?.[0];e.target.value="";if(!file)return;setUploadBusy(true);setMsg("");setError("");try{if(file.size>10*1024*1024)throw new Error("Media files must not exceed 10 MB.");const title=window.prompt("Media asset title",file.name)||file.name;const assetId=await createRecord("mediaAssets",{title:String(title).trim(),fileName:file.name,assetType,mimeType:file.type,fileSize:file.size,status:"Uploading",...actorData});try{const uploaded=await uploadCommunicationMediaAsset({assetId,title,assetType,file});await updateRecord("mediaAssets",assetId,{status:"Available",fileId:uploaded.fileId,storageProvider:uploaded.storageProvider||"Google Drive",fileSize:uploaded.fileSize||file.size,webViewLink:uploaded.webViewLink||"",storagePath:`communication-media/${assetId}/${file.name}`,uploadedAt:new Date().toISOString()});setMsg("Media asset uploaded to the controlled Communication & Media archive.");}catch(uploadError){await updateRecord("mediaAssets",assetId,{status:"Upload Failed",uploadError:String(uploadError?.message||"Media upload failed.")});throw uploadError}await refresh();setTab("Library")}catch(x){setError(x.message||"Unable to upload media asset.")}finally{setUploadBusy(false)}}

 const contentVisible=useMemo(()=>contentFilter==="All"?content:[...content].filter(x=>(x.status||"Draft")===contentFilter),[content,contentFilter]);
 const requestVisible=useMemo(()=>requestFilter==="All"?requests:[...requests].filter(x=>(x.status||"New")===requestFilter),[requests,requestFilter]);
 const assetVisible=useMemo(()=>assetFilter==="All"?assets:[...assets].filter(x=>(x.assetType||"Other")===assetFilter),[assets,assetFilter]);
 const counts={draft:content.filter(x=>x.status==="Draft").length,review:content.filter(x=>x.status==="Under Review").length,published:content.filter(x=>x.status==="Published").length,requests:requests.filter(x=>!["Completed","Cancelled"].includes(x.status)).length,assets:assets.filter(x=>x.status==="Available").length,events:events.filter(x=>x.status!=="Completed"&&x.status!=="Cancelled").length};
 const stageButtons=(row,stages,fn)=>{const i=stages.indexOf(row.status);const next=i>=0&&i<stages.length-1?stages[i+1]:null;return <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{next&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>fn(row,next)}>Move to {next}</button>}</div>};

 return <div className="page" style={{maxWidth:1500,margin:"0 auto"}}>
  <section className="welcome-panel"><div><span className="eyebrow">COMMUNICATION & MEDIA COMMAND CENTRE</span><h1>Communication & Media</h1><p>Editorial command, media production, asset control, press activity, events and communication intelligence.</p></div><div className="identity-card"><span>ACTIVE AUTHORITY</span><strong>{admin?"Administrator":role}</strong></div></section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginTop:14}}>{[["Drafts",counts.draft],["Under Review",counts.review],["Published",counts.published],["Open Requests",counts.requests],["Media Assets",counts.assets],["Active Events",counts.events]].map(x=><div key={x[0]} style={box}><strong style={{fontSize:24,display:"block"}}>{x[1]}</strong><small>{x[0]}</small></div>)}</section>
  {msg&&<div className="success-message action-feedback" style={{marginTop:14}}>{msg}</div>}{error&&<div className="error-message action-feedback" style={{marginTop:14}}>{error}</div>}
  <nav className="member-actions" style={{marginTop:14,display:"flex",gap:8,flexWrap:"wrap"}} aria-label="Media command sections">{["Command","Editorial","Library","Requests","Events"].map(x=><button type="button" key={x} className={tab===x?"":"secondary-button"} onClick={()=>setTab(x)}>{x}</button>)}</nav>

  {tab==="Command"&&<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14,marginTop:14}}>
    <section style={box}><b>CONTENT STUDIO</b><form onSubmit={saveContent} style={{display:"grid",gap:10,marginTop:12}}><input required placeholder="Content title" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/><select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>{CONTENT_TYPES.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Summary / standfirst" value={form.summary} onChange={e=>setForm(f=>({...f,summary:e.target.value}))}/><textarea required rows="7" placeholder="Draft content" value={form.body} onChange={e=>setForm(f=>({...f,body:e.target.value}))}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><select value={form.audience} onChange={e=>setForm(f=>({...f,audience:e.target.value}))}>{AUDIENCES.map(x=><option key={x}>{x}</option>)}</select><select value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></div><button type="submit" disabled={busy}>{busy?"Saving…":"Save Draft"}</button></form></section>
    <section style={box}><b>MEDIA PRODUCTION REQUEST</b><form onSubmit={mediaRequest} style={{display:"grid",gap:10,marginTop:12}}><input required placeholder="Request title" value={requestForm.title} onChange={e=>setRequestForm(f=>({...f,title:e.target.value}))}/><textarea rows="4" placeholder="Production brief / deliverable" value={requestForm.description} onChange={e=>setRequestForm(f=>({...f,description:e.target.value}))}/><input placeholder="Requested for / programme" value={requestForm.requestedFor} onChange={e=>setRequestForm(f=>({...f,requestedFor:e.target.value}))}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><select value={requestForm.priority} onChange={e=>setRequestForm(f=>({...f,priority:e.target.value}))}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={requestForm.dueDate} onChange={e=>setRequestForm(f=>({...f,dueDate:e.target.value}))}/></div><button type="submit" disabled={busy}>{busy?"Registering…":"Create Production Request"}</button></form></section>
    <section style={box}><b>MEDIA LIBRARY INTAKE</b><div style={{display:"grid",gap:10,marginTop:12}}><select value={assetType} onChange={e=>setAssetType(e.target.value)}>{ASSET_TYPES.map(x=><option key={x}>{x}</option>)}</select><label className="secondary-button" style={{display:"flex",alignItems:"center",justifyContent:"center",cursor:uploadBusy?"wait":"pointer",opacity:uploadBusy?.6:1}}>{uploadBusy?"Uploading…":"Upload Media Asset"}<input type="file" accept=".pdf,image/png,image/jpeg,image/webp" onChange={uploadMedia} disabled={uploadBusy} style={{display:"none"}}/></label><small style={{opacity:.7}}>Controlled Drive archive · PDF/PNG/JPEG/WEBP · maximum 10 MB.</small></div></section>
    <section style={box}><b>FIELD & PRESS COMMAND</b><div style={{display:"grid",gap:8,marginTop:12}}><button className="secondary-button" onClick={()=>setTab("Events")}>Plan Communication Event</button><button className="secondary-button" onClick={()=>setTab("Requests")}>Manage Media Requests</button><button className="secondary-button" onClick={()=>setTab("Library")}>Open Media Library</button><button className="secondary-button" onClick={()=>onNavigate?.("Documents")}>Documents & Records ›</button><button className="secondary-button" onClick={()=>onNavigate?.("Reports")}>Reports ›</button><button className="secondary-button" onClick={()=>onNavigate?.("Actions")}>Actions ›</button></div></section>
  </section>}

  {tab==="Editorial"&&<section style={{...box,marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"}}><b>EDITORIAL CONTROL ROOM</b><select value={contentFilter} onChange={e=>setContentFilter(e.target.value)}>{["All",...CONTENT_STAGES].map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrapper" style={{marginTop:12}}><table><thead><tr><th>Content</th><th>Audience</th><th>Priority</th><th>Status</th><th>Command</th></tr></thead><tbody>{contentVisible.length?contentVisible.map(x=><tr key={x.id}><td><strong>{x.title}</strong><div className="table-subtext">{x.type} · {x.summary||"No summary"}</div></td><td>{x.audience||"—"}</td><td>{x.priority||"Normal"}</td><td><span className="status-badge">{x.status||"Draft"}</span></td><td>{stageButtons(x,CONTENT_STAGES,transitionContent)}</td></tr>):<tr><td colSpan="5">No editorial records in this stage.</td></tr>}</tbody></table></div></section>}

  {tab==="Library"&&<section style={{...box,marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"}}><b>MEDIA ASSET COMMAND LIBRARY</b><select value={assetFilter} onChange={e=>setAssetFilter(e.target.value)}>{["All",...ASSET_TYPES].map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrapper" style={{marginTop:12}}><table><thead><tr><th>Asset</th><th>Type</th><th>Status</th><th>Archive</th><th>Command</th></tr></thead><tbody>{assetVisible.length?assetVisible.map(x=><tr key={x.id}><td><strong>{x.title||x.fileName}</strong><div className="table-subtext">{x.fileName||"—"} · {fmtDate(x.uploadedAt)}</div></td><td>{x.assetType||"Other"}</td><td><span className="status-badge">{x.status||"Recorded"}</span></td><td>{x.webViewLink?<a href={x.webViewLink} target="_blank" rel="noreferrer">Open Drive</a>:"Not available"}</td><td>{x.status==="Available"&&x.webViewLink?<a className="secondary-button" href={x.webViewLink} target="_blank" rel="noreferrer">Open Asset</a>:x.status==="Upload Failed"?<small>{x.uploadError||"Upload failed"}</small>:<span>—</span>}</td></tr>):<tr><td colSpan="5">No media assets in this register.</td></tr>}</tbody></table></div></section>}

  {tab==="Requests"&&<section style={{...box,marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"}}><b>MEDIA PRODUCTION QUEUE</b><select value={requestFilter} onChange={e=>setRequestFilter(e.target.value)}>{["All",...REQUEST_STAGES].map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrapper" style={{marginTop:12}}><table><thead><tr><th>Request</th><th>Programme</th><th>Due</th><th>Priority</th><th>Status</th><th>Command</th></tr></thead><tbody>{requestVisible.length?requestVisible.map(x=><tr key={x.id}><td><strong>{x.title}</strong><div className="table-subtext">{x.description||"No brief"}</div></td><td>{x.requestedFor||"—"}</td><td>{x.dueDate||"—"}</td><td>{x.priority||"Normal"}</td><td><span className="status-badge">{x.status||"New"}</span></td><td>{stageButtons(x,REQUEST_STAGES,transitionRequest)}</td></tr>):<tr><td colSpan="6">No production requests in this stage.</td></tr>}</tbody></table></div></section>}

  {tab==="Events"&&<section style={{display:"grid",gridTemplateColumns:"minmax(300px,.75fr) minmax(420px,1.25fr)",gap:14,marginTop:14}}><section style={box}><b>COMMUNICATION EVENT PLANNER</b><form onSubmit={createEvent} style={{display:"grid",gap:10,marginTop:12}}><input required placeholder="Event / media activity title" value={eventForm.title} onChange={e=>setEventForm(f=>({...f,title:e.target.value}))}/><input required type="date" value={eventForm.eventDate} onChange={e=>setEventForm(f=>({...f,eventDate:e.target.value}))}/><input placeholder="Location / platform" value={eventForm.location} onChange={e=>setEventForm(f=>({...f,location:e.target.value}))}/><input placeholder="Purpose / campaign" value={eventForm.purpose} onChange={e=>setEventForm(f=>({...f,purpose:e.target.value}))}/><input placeholder="Lead / contact" value={eventForm.lead} onChange={e=>setEventForm(f=>({...f,lead:e.target.value}))}/><select value={eventForm.audience} onChange={e=>setEventForm(f=>({...f,audience:e.target.value}))}>{AUDIENCES.map(x=><option key={x}>{x}</option>)}</select><button disabled={busy}>{busy?"Registering…":"Register Communication Event"}</button></form></section><section style={box}><b>EVENT COMMAND BOARD</b><div className="table-wrapper" style={{marginTop:12}}><table><thead><tr><th>Activity</th><th>Date</th><th>Location</th><th>Status</th><th>Command</th></tr></thead><tbody>{events.length?events.slice().sort((a,b)=>String(a.eventDate||"").localeCompare(String(b.eventDate||""))).map(x=><tr key={x.id}><td><strong>{x.title}</strong><div className="table-subtext">{x.purpose||"—"} · {x.audience||"—"}</div></td><td>{x.eventDate||"—"}</td><td>{x.location||"—"}</td><td><span className="status-badge">{x.status||"Planned"}</span></td><td>{stageButtons(x,EVENT_STAGES,transitionEvent)}</td></tr>):<tr><td colSpan="5">No communication events registered.</td></tr>}</tbody></table></div></section></section>}
 </section>
 </section>}
 </section>
 </section>}
 </section>
 </section>}
 </div>;
}
