import React,{useEffect,useState} from "react";
import {createRecord,getRecords,COLLECTIONS} from "../firebase/data";

const TYPES=["Salary","Allowance","Reimbursement","Other Employee Payment"];
const ALLOWANCES=["Housing Allowance","Transport Allowance","Per Diem","Communication Allowance","Field Allowance","Other"];
export default function EmployeePayments({profile}){
 const [requests,setRequests]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({type:"Salary",allowanceType:"",amount:"",currency:"TZS",period:"",justification:"",supportingReference:""});
 async function load(){try{const all=await getRecords(COLLECTIONS.staffPaymentRequests);setRequests(all.filter(x=>x.employeeUid===profile?.uid||x.employeeEmail===profile?.email))}catch(e){setError(e.message||"Unable to load payment requests.")}}
 useEffect(()=>{if(profile)load()},[profile?.uid]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function submit(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{await createRecord(COLLECTIONS.staffPaymentRequests,{employeeUid:profile.uid,employeeNumber:profile.employeeNumber||"",employeeName:profile.name||profile.email,employeeEmail:profile.email||"",type:form.type,allowanceType:form.type==="Allowance"?form.allowanceType:"",amount:Number(form.amount),currency:form.currency,period:form.period,justification:form.justification,supportingReference:form.supportingReference,status:"Submitted",workflowStage:"HR/Administrative Verification",involvedUids:[profile.uid]});setMessage("Payment application submitted for verification.");setForm({type:"Salary",allowanceType:"",amount:"",currency:"TZS",period:"",justification:"",supportingReference:""});await load()}catch(x){setError(x.message||"Unable to submit payment application.")}finally{setBusy(false)}}
 return <div className="page"><div className="page-header"><div><h1>Employee Payments</h1><p>All employee salary, allowance and reimbursement applications are submitted through this controlled IRPA workflow.</p></div></div><div className="module-status"><strong>Employee identification</strong><span>{profile?.employeeNumber||"Employee Number not yet assigned"} — {profile?.name||profile?.email}</span></div>{message&&<div className="success-message">{message}</div>}{error&&<div className="error-message">{error}</div>}
 <div className="panel"><h2>New Payment Application</h2><p className="panel-description">Submitting an application does not constitute authorization or payment. The request must pass the applicable verification and authorization protocol.</p><form onSubmit={submit}><div className="form-grid"><div className="form-field"><label>Payment Type</label><select name="type" value={form.type} onChange={change}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div>{form.type==="Allowance"&&<div className="form-field"><label>Allowance Type</label><select name="allowanceType" value={form.allowanceType} onChange={change} required><option value="">Select allowance</option>{ALLOWANCES.map(x=><option key={x}>{x}</option>)}</select></div>}<div className="form-field"><label>Amount</label><input type="number" min="0" step="0.01" name="amount" value={form.amount} onChange={change} required/></div><div className="form-field"><label>Currency</label><select name="currency" value={form.currency} onChange={change}><option>TZS</option><option>USD</option><option>EUR</option></select></div><div className="form-field"><label>Period / Claim Date</label><input name="period" value={form.period} onChange={change} placeholder="e.g. September 2026" required/></div><div className="form-field"><label>Supporting Reference</label><input name="supportingReference" value={form.supportingReference} onChange={change} placeholder="Optional document/reference number"/></div><div className="form-field" style={{gridColumn:"1/-1"}}><label>Justification / Description</label><textarea name="justification" value={form.justification} onChange={change} rows="4" required/></div></div><button type="submit" disabled={busy}>{busy?"Submitting...":"Submit Payment Application"}</button></form></div>
 <div className="panel"><div className="panel-header"><h2>My Payment Applications</h2><span>{requests.length} request(s)</span></div><div className="table-wrapper"><table><thead><tr><th>Employee No.</th><th>Type</th><th>Amount</th><th>Period</th><th>Status</th><th>Workflow Stage</th></tr></thead><tbody>{requests.length===0?<tr><td colSpan="6">No payment applications submitted.</td></tr>:requests.map(r=><tr key={r.id}><td><strong>{r.employeeNumber||"—"}</strong></td><td>{r.type}{r.allowanceType?` — ${r.allowanceType}`:""}</td><td>{r.currency} {Number(r.amount||0).toLocaleString()}</td><td>{r.period||"—"}</td><td><span className="status-badge">{r.status}</span></td><td>{r.workflowStage||"—"}</td></tr>)}</tbody></table></div></div></div>
}
