import React,{useEffect,useState}from"react";
import {createRecord,getRecords,getEmployeePaymentRequests,processPaymentRequest,COLLECTIONS}from"../firebase/data";
const TYPES=["Salary","Allowance","Reimbursement","Other Employee Payment"];
const ALLOWANCES=["Housing Allowance","Transport Allowance","Per Diem","Communication Allowance","Field Allowance","Other"];
const HR=["Executive Director","Director Human Resources","HR Manager"];const FIN=["Finance Personnel","Finance Manager","Accountant","Finance Officer","Executive Director"];const MGMT=["Executive Director","Management","Finance Manager","Director Internal Oversight"];
const empty={type:"Salary",allowanceType:"",amount:"",currency:"TZS",period:"",justification:"",supportingReference:""};
export default function EmployeePayments({profile}){
 const role=profile?.role||"",admin=profile?.authorizationType==="administrator",isHR=admin||HR.includes(role),isFinance=admin||FIN.includes(role),isED=admin||role==="Executive Director",canQueue=isHR||isFinance||MGMT.includes(role);
 const[requests,setRequests]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const[form,setForm]=useState(empty);
 async function load(){try{setError("");setRequests(canQueue?await getRecords(COLLECTIONS.staffPaymentRequests):await getEmployeePaymentRequests(profile.uid))}catch(e){setError(e.message||"Unable to load payment applications.")}}
 useEffect(()=>{if(profile?.uid)load()},[profile?.uid,canQueue]);function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function submit(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{await createRecord(COLLECTIONS.staffPaymentRequests,{employeeUid:profile.uid,employeeNumber:profile.employeeNumber||"",employeeName:profile.name||profile.email,employeeEmail:profile.email||"",type:form.type,allowanceType:form.type==="Allowance"?form.allowanceType:"",amount:Number(form.amount),currency:form.currency,period:form.period,justification:form.justification,supportingReference:form.supportingReference,status:"Submitted",workflowStage:"HR/Administrative Verification",responsibleRole:"HR/Administrative Verifier",reviewerRoles:["Finance"],approverRoles:["Executive Director / Accounting Officer"],copiedUids:[],involvedUids:[profile.uid],workflowHistory:[{stage:"Submitted",action:"Employee submitted payment application"}]});setMessage("Payment application submitted for HR/Administrative Verification.");setForm(empty);await load()}catch(x){setError(x.message||"Unable to submit payment application.")}finally{setBusy(false)}}
 async function act(r,nextStage,status,noteLabel){if(r.employeeUid===profile.uid&&(nextStage==="Payment Processing"||status==="Completed"||status==="Authorized")){setError("The requester cannot authorize or process their own payment.");return}let note=window.prompt(noteLabel+" (optional):","");if(note===null)return;setBusy(true);setError("");try{const changes={workflowStage:nextStage,status,note:note||"",lastAction:noteLabel,historyEntry:{stage:r.workflowStage,action:noteLabel,note:note||""}};if(status==="Rejected")changes.rejectionReason=note||"Rejected by authorized officer.";if(status==="Returned")changes.returnReason=note||"Returned for correction.";if(status==="Completed"){changes.paymentReference=window.prompt("Enter payment reference / transaction number:","")||"";changes.processedAt=new Date().toISOString()}await processPaymentRequest(r.id,changes);setMessage(`Request ${r.employeeNumber||r.employeeName} moved to ${nextStage}.`);await load()}catch(x){setError(x.message||"Workflow action failed.")}finally{setBusy(false)}}
 function actions(r){const a=[];if(admin||isHR){if(r.workflowStage==="HR/Administrative Verification"){a.push(["Verify & Send to Finance","Finance Verification","Under Finance Verification","Verify payment application"]);a.push(["Return","HR/Administrative Verification","Returned","Return payment application"]);a.push(["Reject","HR/Administrative Verification","Rejected","Reject payment application"])} }if(admin||isFinance){if(r.workflowStage==="Finance Verification"){a.push(["Verify & Send to ED","Executive Authorization","Awaiting Executive Authorization","Verify financial documentation"]);a.push(["Return","Finance Verification","Returned","Return to Finance correction"]);a.push(["Reject","Finance Verification","Rejected","Reject payment application"])}if(r.workflowStage==="Payment Processing"){a.push(["Mark Paid / Complete","Completed","Completed","Confirm payment processing"]);a.push(["Return","Payment Processing","Returned","Return payment for correction"])} }if(admin||isED){if(r.workflowStage==="Executive Authorization"&&r.employeeUid!==profile.uid){a.push(["Authorize & Send to Finance","Payment Processing","Authorized","Authorize payment for processing"]);a.push(["Return","Executive Authorization","Returned","Return payment for correction"]);a.push(["Reject","Executive Authorization","Rejected","Reject payment application"])} }return a}
 return <div className="page"><div className="page-header"><div><h1>Employee Payments</h1><p>Controlled application, verification, authorization and payment-processing workflow for salaries, allowances and employee claims.</p></div></div><div className="module-status"><strong>Employee identification</strong><span>{profile?.employeeNumber||"Employee Number not yet assigned"} — {profile?.name||profile?.email}</span></div>{message&&<div className="success-message">{message}</div>}{error&&<div className="error-message">{error}</div>}
 <div className="panel"><h2>Workflow Protocol</h2><div className="module-status"><strong>1. Employee</strong><span>Submit application and supporting reference.</span></div><div className="module-status"><strong>2. HR / Administration</strong><span>Verify employment, entitlement and administrative completeness.</span></div><div className="module-status"><strong>3. Finance</strong><span>Verify budget, calculation and financial documentation.</span></div><div className="module-status"><strong>4. Executive Director / Accounting Officer</strong><span>Authorize implementation within delegated authority. The requester cannot authorize their own payment.</span></div><div className="module-status"><strong>5. Finance</strong><span>Process payment, record transaction reference and close the request.</span></div></div>
 <div className="panel"><h2>New Payment Application</h2><p className="panel-description">Submission is not authorization or payment. Ordinary salary and allowance processing remains operational; reserved or threshold matters can be escalated through the Authorization & Approvals framework.</p><form onSubmit={submit}><div className="form-grid"><div className="form-field"><label>Payment Type</label><select name="type" value={form.type} onChange={change}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div>{form.type==="Allowance"&&<div className="form-field"><label>Allowance Type</label><select name="allowanceType" value={form.allowanceType} onChange={change} required><option value="">Select allowance</option>{ALLOWANCES.map(x=><option key={x}>{x}</option>)}</select></div>}<div className="form-field"><label>Amount</label><input type="number" min="0" step="0.01" name="amount" value={form.amount} onChange={change} required/></div><div className="form-field"><label>Currency</label><select name="currency" value={form.currency} onChange={change}><option>TZS</option><option>USD</option><option>EUR</option></select></div><div className="form-field"><label>Period / Claim Date</label><input name="period" value={form.period} onChange={change} placeholder="e.g. September 2026" required/></div><div className="form-field"><label>Supporting Reference</label><input name="supportingReference" value={form.supportingReference} onChange={change} placeholder="Document / claim reference"/></div><div className="form-field" style={{gridColumn:"1/-1"}}><label>Justification / Description</label><textarea name="justification" value={form.justification} onChange={change} rows="4" required/></div></div><button type="submit" disabled={busy}>{busy?"Submitting...":"Submit Payment Application"}</button></form></div>
 <div className="panel"><div className="panel-header"><h2>{canQueue?"Payment Processing Queue":"My Payment Applications"}</h2><span>{requests.length} request(s)</span></div><div className="table-wrapper"><table><thead><tr><th>Employee</th><th>Type</th><th>Amount</th><th>Period</th><th>Status</th><th>Workflow Stage</th><th>Action</th></tr></thead><tbody>{requests.length===0?<tr><td colSpan="7">No payment applications.</td></tr>:requests.map(r=><tr key={r.id}><td><strong>{r.employeeNumber||"—"}</strong><br/>{r.employeeName||"—"}</td><td>{r.type}{r.allowanceType?` — ${r.allowanceType}`:""}</td><td>{r.currency} {Number(r.amount||0).toLocaleString()}</td><td>{r.period||"—"}</td><td><span className="status-badge">{r.status}</span></td><td>{r.workflowStage||"—"}</td><td>{actions(r).map(([label,stage,status,note],i)=><button key={i} type="button" disabled={busy} onClick={()=>act(r,stage,status,note)} style={{margin:"3px"}}>{label}</button>)}</td></tr>)}</tbody></table></div></div></div>
}
