import React,{useEffect,useState}from"react";
import {createEmployee,getRecords,updateEmployee,updateRecord,deleteRecord,retryEmployeeRegistrationEmail,COLLECTIONS}from"../firebase/data";
const ROLES=["Executive Director","Director Human Resources","HR Manager","Director Finance & Administration","Finance Manager","Accountant","Finance Officer","Director Internal Oversight","Internal Oversight Officer","Programme/Technical Officer","Procurement Officer","Management","Employee"];
const DEPARTMENTS=["Executive Office","Human Resources","Finance & Administration","Internal Oversight","Programmes","Procurement","Operations","Community Development","Livestock","Environment","Outreach","Field Operations"];
const empty={name:"",email:"",role:"Employee",department:"",employmentType:"Full-time",status:"Active",phone:"",startDate:""};
export default function Employees(){
 const[employees,setEmployees]=useState([]),[busy,setBusy]=useState(false),[emailBusy,setEmailBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[feedback,setFeedback]=useState(null),[editing,setEditing]=useState(null),[viewing,setViewing]=useState(null),[search,setSearch]=useState("");const[form,setForm]=useState(empty);
 async function load(){try{setEmployees(await getRecords(COLLECTIONS.employees))}catch(e){setError(e.message||"Unable to load employee register.")}}
 useEffect(()=>{load()},[]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 function editEmployee(employee){setError("");setMessage("");setFeedback(null);setViewing(null);setEditing(employee);setForm({name:employee.name||"",email:employee.email||"",role:employee.role||"Employee",department:employee.department||"",employmentType:employee.employmentType||"Full-time",status:employee.status||employee.employmentStatus||"Active",phone:employee.phone||"",startDate:employee.startDate||""});window.scrollTo({top:0,behavior:"smooth"})}
 function cancelEdit(){setEditing(null);setForm(empty);setError("")}
 async function submit(e){e.preventDefault();setBusy(true);setError("");setMessage("");setFeedback(null);try{if(editing){await updateEmployee(editing.id,form);setMessage(`✓ Employee ${editing.employeeNumber} saved successfully.`);cancelEdit();await load()}else{const result=await createEmployee(form);setFeedback({type:"success",employeeNumber:result.employeeNumber,email:form.email,status:result.registrationEmailStatus,message:"Employee registration completed. The employee record has been created and the registration email has been queued for delivery."});setMessage(`✓ Employee ${result.employeeNumber} registered successfully.`);setForm(empty);await load()}}catch(x){setError(x.message||`Unable to ${editing?"update":"register"} employee.`);setFeedback({type:"error",message:x.message||"Registration could not be completed."})}finally{setBusy(false)}}
 async function retryEmail(employee){setEmailBusy(employee.id);setError("");setMessage("");try{await retryEmployeeRegistrationEmail(employee);setMessage(`✓ Registration email for ${employee.employeeNumber} has been queued again.`);setFeedback({type:"email",employeeNumber:employee.employeeNumber,email:employee.email,status:"Queued",message:"The registration email has been queued again. Delivery is handled by the configured Firebase email service."});await load()}catch(x){setError(x.message||"Unable to queue registration email.");setFeedback({type:"error",employeeNumber:employee.employeeNumber,message:x.message||"Unable to queue registration email."})}finally{setEmailBusy("")}}
 async function deactivate(employee){if(!window.confirm(`Deactivate ${employee.name||employee.employeeNumber}?`))return;setBusy(true);setError("");try{await updateRecord(COLLECTIONS.employees,employee.id,{employmentStatus:"Inactive",status:"Inactive"});await load();setMessage(`✓ Employee ${employee.employeeNumber} has been deactivated.`)}catch(x){setError(x.message||"Unable to update employee.")}finally{setBusy(false)}}
 async function remove(employee){if(!window.confirm(`Permanently delete employee ${employee.employeeNumber} — ${employee.name}? This cannot be undone.`))return;setBusy(true);setError("");try{await deleteRecord(COLLECTIONS.employees,employee.id);await load();setMessage(`✓ Employee ${employee.employeeNumber} was deleted.`)}catch(x){setError(x.message||"Unable to delete employee.")}finally{setBusy(false)}}
 const filtered=employees.filter(e=>!search.trim()||[e.employeeNumber,e.name,e.email,e.role,e.department,e.status,e.employmentStatus].join(" ").toLowerCase().includes(search.trim().toLowerCase()));
 const emailLabel=e=>e.registrationEmailStatus==="Queued"?"Queued":e.registrationEmailStatus||"Not queued";
 return <div className="page"><div className="page-header"><div><h1>Employees & Personnel</h1><p>Official IRPA employee register. Employee Number is system-generated and is the formal system identification number.</p></div><button onClick={()=>{setEditing(null);setViewing(null);setFeedback(null);setError("");setForm(empty);window.scrollTo({top:0,behavior:"smooth"})}}>+ Register Employee</button></div>{message&&<div className="success-message action-feedback"role="status">{message}</div>}{error&&<div className="error-message action-feedback"role="alert">{error}</div>}
 {feedback&&<div className={`panel registration-feedback ${feedback.type===`error`?`feedback-error`:``}`}><div className="panel-header"><div><h2>{feedback.type===`error`?"Registration Feedback":"Registration Result"}</h2><span>{feedback.type===`email`?"Email delivery queue update":"Persistent registration status"}</span></div><button type="button"className="secondary-button"onClick={()=>setFeedback(null)}>Close</button></div><div className="detail-grid">{feedback.employeeNumber&&<div><span>Employee Number</span><strong>{feedback.employeeNumber}</strong></div>}{feedback.email&&<div><span>Official Email</span><strong>{feedback.email}</strong></div>}{feedback.status&&<div><span>Registration Email Status</span><strong>{feedback.status}</strong></div>}<div><span>Registration Status</span><strong>{feedback.type===`error`?"Action requires attention":"Registered"}</strong></div><div><span>System Feedback</span><strong>{feedback.message}</strong></div></div></div>}
 <div className="panel"><h2>{editing?`Edit Employee — ${editing.employeeNumber}`:"Register Employee"}</h2><p className="panel-description"><strong>Employee Number is system-generated.</strong>{editing&&<> Current Employee Number: <strong>{editing.employeeNumber}</strong></>}</p><form onSubmit={submit}><div className="form-grid"><div className="form-field"><label>Full Name</label><input name="name"value={form.name}onChange={change}required/></div><div className="form-field"><label>Official Email</label><input type="email"name="email"value={form.email}onChange={change}required/></div><div className="form-field"><label>Position / Title</label><select name="role"value={form.role}onChange={change}>{ROLES.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Department</label><select name="department"value={form.department}onChange={change}required><option value="">Select department</option>{DEPARTMENTS.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Employment Type</label><select name="employmentType"value={form.employmentType}onChange={change}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Consultancy</option><option>Internship</option></select></div><div className="form-field"><label>Employment Status</label><select name="status"value={form.status}onChange={change}><option>Active</option><option>On Leave</option><option>Suspended</option><option>Inactive</option></select></div><div className="form-field"><label>Phone</label><input name="phone"value={form.phone}onChange={change}/></div><div className="form-field"><label>Employment Start Date</label><input type="date"name="startDate"value={form.startDate}onChange={change}required/></div></div><div className="form-actions"><button type="submit"disabled={busy}>{busy?(editing?"Saving Changes...":"Registering & Recording Feedback..."):(editing?"Save Changes":"Register Employee & Generate Number")}</button>{editing&&<button type="button"className="secondary-button"onClick={cancelEdit}disabled={busy}>Cancel Edit</button>}</div></form></div>
 <div className="panel"><div className="panel-header"><div><h2>Official Employee Register</h2><span>{filtered.length} of {employees.length} employee(s)</span></div><input className="table-search"placeholder="Search employees..."value={search}onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrapper"><table><thead><tr><th>Employee Number</th><th>Name</th><th>Position / Title</th><th>Department</th><th>Email</th><th>Status</th><th>Email Queue</th><th>Actions</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="8">No employees registered.</td></tr>:filtered.map(e=><tr key={e.id}><td><strong>{e.employeeNumber}</strong></td><td>{e.name||"—"}</td><td>{e.role||"—"}</td><td>{e.department||"—"}</td><td>{e.email||"—"}</td><td><span className="status-badge">{e.status||e.employmentStatus||"—"}</span></td><td><span className="status-badge">{emailLabel(e)}</span>{e.registrationEmailError&&<small className="field-help">{e.registrationEmailError}</small>}</td><td><div className="member-actions"><button type="button"disabled={busy||!!emailBusy}onClick={()=>setViewing(e)}>View</button><button type="button"disabled={busy||!!emailBusy}onClick={()=>editEmployee(e)}>Edit</button><button type="button"disabled={busy||!!emailBusy}onClick={()=>retryEmail(e)}>{emailBusy===e.id?"Queueing...":"Retry Email"}</button>{(e.status||e.employmentStatus)==="Active"&&<button type="button"disabled={busy||!!emailBusy}onClick={()=>deactivate(e)}>Deactivate</button>}<button type="button"className="danger-button"disabled={busy||!!emailBusy}onClick={()=>remove(e)}>Delete</button></div></td></tr>)}</tbody></table></div></div>
 {viewing&&<div className="panel"><div className="panel-header"><h2>Employee Details</h2><button type="button"className="secondary-button"onClick={()=>setViewing(null)}>Close</button></div><div className="detail-grid">{[["Employee Number",viewing.employeeNumber],["Full Name",viewing.name],["Official Email",viewing.email],["Position / Title",viewing.role],["Department",viewing.department],["Employment Type",viewing.employmentType],["Status",viewing.status||viewing.employmentStatus],["Phone",viewing.phone],["Start Date",viewing.startDate],["Registration Status",viewing.registrationStatus||"Registered"],["Registration Email",emailLabel(viewing)],["Email Error",viewing.registrationEmailError],["Registered By",viewing.registeredByEmail]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b||"—"}</strong></div>)}</div></div>}
 </div>}
