import React,{useEffect,useMemo,useState}from"react";
import{collection,getDocs}from"firebase/firestore";
import{db,auth}from"../firebase/config";

const LABELS={members:"Members & Personnel",employees:"Members & Personnel",participants:"Participants",meetings:"Meetings",meetingRoomEvents:"Meeting Room",transcriptions:"Meeting Room",resolutions:"Resolutions",votes:"Voting",actions:"Actions",documents:"Documents",signatures:"Signature Platform",decisions:"Decisions",risks:"Risk Register",authorizationRequests:"Authorization & Approvals",workflowActions:"Governance Workflows",staffPaymentRequests:"Employee Payments",financeBudgets:"Finance Portfolio",financeTransactions:"Finance Portfolio",financeFunding:"Finance Portfolio",financeApprovals:"Finance Portfolio",financeCommitments:"Finance Portfolio",financeGrants:"Finance Portfolio",financeBankAccounts:"Finance Portfolio",financeReconciliations:"Finance Portfolio",financeAssets:"Finance Portfolio",financeRisks:"Finance Portfolio",financeReports:"Finance Portfolio",financePaymentTrace:"Finance Portfolio",procurementVendors:"Procurement",procurementRequests:"Procurement",procurementVendorScores:"Procurement",procurementVendorBlacklist:"Procurement",procurementVendorProbation:"Procurement",invitations:"Invitations",registrationRequests:"Board Members Registration",inductionRecords:"Induction & Orientation",audit:"Audit Trail",reports:"Reports"};
const SEGMENTS=[["Q1","Quarter 1","01 January – 31 March"],["Q2","Quarter 2","01 April – 30 June"],["Q3","Quarter 3","01 July – 30 September"],["Q4","Quarter 4","01 October – 31 December"],["ANNUAL","Annual Report","01 January – 31 December"]];
function range(year,key){const y=Number(year);if(key==="ANNUAL")return[new Date(y,0,1),new Date(y+1,0,1)];const q={Q1:[0,3],Q2:[3,6],Q3:[6,9],Q4:[9,12]}[key];return[new Date(y,q[0],1),new Date(y,q[1],1)]}
function dateValue(v){if(!v)return null;if(v?.toDate)return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function currentSegment(){const m=new Date().getMonth();return m<3?"Q1":m<6?"Q2":m<9?"Q3":"Q4"}
function ExternalAuditorPortal(){
 const[year,setYear]=useState(String(new Date().getFullYear())),[segment,setSegment]=useState(currentSegment()),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const snap=await getDocs(collection(db,"audit"));setRows(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){setError(e?.message||"Unable to load external audit evidence.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const[r1,r2]=range(year,segment);return rows.filter(r=>{const d=dateValue(r.createdAt);return d&&d>=r1&&d<r2}).sort((a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0))},[rows,year,segment]);
 const workflows=useMemo(()=>{const map=new Map();for(const r of filtered){const key=String(r.recordId||r.id);const x=map.get(key)||{recordId:key,module:LABELS[r.collection]||r.collection||"Governance Workflow",events:0,actions:[],first:null,last:null};x.events++;x.actions.push(String(r.action||"EVENT"));const d=dateValue(r.createdAt);if(!x.first||d<x.first)x.first=d;if(!x.last||d>x.last)x.last=d;map.set(key,x)}return[...map.values()].sort((a,b)=>(b.last?.getTime()||0)-(a.last?.getTime()||0))},[filtered]);
 function generate(){setMessage(`Generated ${segment==="ANNUAL"?"Annual":segment+" quarterly"} external audit report for ${year}: ${workflows.length} workflow records and ${filtered.length} evidence events.`)}
 function print(){const title=`IRPA External Audit Report — ${segment==="ANNUAL"?"Annual":segment+" Quarterly"} — ${year}`;const body=document.getElementById("external-auditor-report")?.innerHTML||"";const w=window.open("","_blank","noopener,noreferrer");if(!w){setError("The browser blocked the report window. Allow pop-ups for the IRPA governance site.");return}w.document.write(`<!doctype html><html><head><title>${title}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#17212b}h1{margin-bottom:4px}h2{margin-top:28px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #bbb;padding:8px;text-align:left;vertical-align:top}th{background:#eee}.meta{color:#555}.no-print{display:none}</style></head><body><h1>${title}</h1><p class="meta">Improvement of Rangeland in Pastoral Areas (IRPA) · External Auditor Portal</p>${body}</body></html>`);w.document.close();w.focus();w.print()}
 const now=new Date(),selectedRange=range(year,segment),isCurrentYear=Number(year)===now.getFullYear(),isOpen=isCurrentYear&&now>=selectedRange[0]&&now<selectedRange[1];
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">INDEPENDENT ASSURANCE</span><h1>External Auditor Portal</h1><p>Read-only evidence of governance workflows across IRPA governance portals. This portal records the workflow trail without providing operational editing or approval rights.</p></div></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">REPORTING CYCLE</span><h2>Generate Reports</h2><p className="panel-description">Each reporting year opens on 01 January and closes on 31 December. The five reporting segments are Q1, Q2, Q3, Q4 and the Annual Report.</p></div></div>
 <div className="form-grid"><label className="form-field">Reporting Year<input type="number" min="2024" max={new Date().getFullYear()} value={year} onChange={e=>setYear(e.target.value)}/></label><label className="form-field">Reporting Segment<select value={segment} onChange={e=>setSegment(e.target.value)}>{SEGMENTS.map(([k,n,d])=><option key={k} value={k}>{n} — {d}</option>)}</select></label></div>
 <div className="stat-grid" style={{marginTop:16}}>{SEGMENTS.map(([k,n,d])=><button type="button" key={k} className={segment===k?"stat-card active":"stat-card"} onClick={()=>setSegment(k)}><span>{n}</span><strong>{d}</strong><small>{Number(year)===new Date().getFullYear()&&((k==="ANNUAL")||k===currentSegment())?"Current reporting cycle":"Historical / scheduled segment"}</small></button>)}</div>
 <div className="form-actions" style={{marginTop:18}}><button type="button" onClick={generate} disabled={busy}>{busy?"Collecting Evidence…":"Generate Report"}</button><button type="button" className="secondary-button" onClick={print} disabled={busy||!filtered.length}>Print Report</button><button type="button" className="secondary-button" onClick={load} disabled={busy}>Refresh Evidence</button></div>
 {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="auth-message">{error}</div>}<div className="auth-message" style={{marginTop:14}}><strong>{isOpen?"Reporting segment open":"Reporting segment closed or not yet open"}</strong> · {selectedRange[0].toLocaleDateString()} – {new Date(selectedRange[1].getTime()-86400000).toLocaleDateString()}</div></section>
 <section id="external-auditor-report" className="panel"><div className="panel-header"><div><span className="eyebrow">AUDIT EVIDENCE REGISTER</span><h2>{segment==="ANNUAL"?"Annual Report":segment+" Quarterly Report"} — {year}</h2><p className="panel-description">Evidence is grouped into complete workflow records using the immutable governance audit trail.</p></div></div><div className="stat-grid"><div className="stat-card"><span>Workflow records</span><strong>{workflows.length}</strong></div><div className="stat-card"><span>Evidence events</span><strong>{filtered.length}</strong></div><div className="stat-card"><span>Governance portals represented</span><strong>{new Set(workflows.map(x=>x.module)).size}</strong></div></div><div style={{overflowX:"auto",marginTop:18}}><table className="data-table"><thead><tr><th>Workflow / Record</th><th>Governance Portal</th><th>Evidence Events</th><th>Workflow Actions</th><th>First Evidence</th><th>Latest Evidence</th></tr></thead><tbody>{workflows.map(x=><tr key={x.recordId}><td>{x.recordId}</td><td>{x.module}</td><td>{x.events}</td><td>{[...new Set(x.actions)].join(" → ")}</td><td>{x.first?.toLocaleString()||"—"}</td><td>{x.last?.toLocaleString()||"—"}</td></tr>)}{!workflows.length&&<tr><td colSpan="6">No audit evidence exists for the selected reporting segment.</td></tr>}</tbody></table></div><h3 style={{marginTop:28}}>Complete Workflow Evidence</h3><div style={{overflowX:"auto",marginTop:12}}><table className="data-table"><thead><tr><th>Date / Time</th><th>Portal</th><th>Record</th><th>Action</th><th>Evidence Detail</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{dateValue(r.createdAt)?.toLocaleString()||"—"}</td><td>{LABELS[r.collection]||r.collection||"Governance"}</td><td>{r.recordId||r.id}</td><td>{r.action||"EVENT"}</td><td>{typeof r.details==="string"?r.details:JSON.stringify(r.details||{})}</td></tr>)}{!filtered.length&&<tr><td colSpan="5">No workflow evidence exists for the selected reporting segment.</td></tr>}</tbody></table></div></section></div>
}
export default ExternalAuditorPortal;
