import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";
const REGISTERS=[
{id:"budgets",label:"Budgets",collection:COLLECTIONS.financeBudgets,stages:["Draft","Submitted for Board Approval","Board Approved","Active","Closed"]},
{id:"transactions",label:"Transactions",collection:COLLECTIONS.financeTransactions,stages:["Draft","Pending Approval","Approved","Posted","Reconciled"]},
{id:"funding",label:"Funding",collection:COLLECTIONS.financeFunding,stages:["Prospect","Committed","Received","Restricted","Closed"]},
{id:"approvals",label:"Approvals",collection:COLLECTIONS.financeApprovals,stages:["Pending","Under Review","Approved","Rejected","Implemented"]},
{id:"grants",label:"Grants",collection:COLLECTIONS.financeGrants,stages:["Prospect","Application","Awarded","Active","Reporting","Closed"]},
{id:"bank",label:"Bank & Reconciliation",collection:COLLECTIONS.financeReconciliations,stages:["Open","In Reconciliation","Reviewed","Reconciled","Exception"]},
{id:"assets",label:"Assets",collection:COLLECTIONS.financeAssets,stages:["Register","In Use","Transferred","Disposed"]},
{id:"reports",label:"Financial Reports",collection:COLLECTIONS.financeReports,stages:["Draft","Under Review","Approved","Issued","Archived"]}
];
const base={title:"",reference:"",amount:"",date:"",description:"",owner:"",budgetYear:String(new Date().getFullYear()),fundingSource:"",costCentre:"",transactionType:"",payee:"",approvalReference:"",donor:"",grantPeriod:"",bankAccount:"",statementBalance:"",bookBalance:"",reconciliationDifference:"",assetNumber:"",assetCategory:"",location:"",reportingPeriod:"",preparedBy:"",reviewedBy:"",approvedBy:""};
function money(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"—"}
function Field({label,name,form,setForm,type="text",wide=false}){return <label className={wide?"form-field form-field-wide":"form-field"}>{label}<input name={name} type={type} value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>}
export default function FinancePortfolio(){
 const[register,setRegister]=useState("budgets"),[rows,setRows]=useState([]),[portfolio,setPortfolio]=useState({}),[form,setForm]=useState({...base,status:REGISTERS[0].stages[0]}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const cfg=REGISTERS.find(x=>x.id===register)||REGISTERS[0];
 async function load(){const result={};for(const r of REGISTERS){try{result[r.id]=await getRecords(r.collection)}catch(e){result[r.id]=[]}}setPortfolio(result);setRows(result[cfg.id]||[])}
 useEffect(()=>{setForm({...base,status:cfg.stages[0]});setMessage("");setError("");load().catch(e=>setError(e.message||"Unable to load finance registers."))},[register]);
 const totals=useMemo(()=>({budget:(portfolio.budgets||[]).reduce((s,x)=>s+Number(x.amount||x.budgetAmount||0),0),transactions:(portfolio.transactions||[]).reduce((s,x)=>s+Number(x.amount||0),0),funding:(portfolio.funding||[]).reduce((s,x)=>s+Number(x.amount||0),0),grants:(portfolio.grants||[]).reduce((s,x)=>s+Number(x.amount||0),0)}),[portfolio]);
 const stageCounts=useMemo(()=>cfg.stages.map(s=>[s,rows.filter(r=>r.status===s).length]),[rows,cfg]);
 async function save(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(!form.title.trim())throw new Error("Finance record title / subject is required.");const payload={...form,register:cfg.id,registerLabel:cfg.label,workflowStage:cfg.stages[0],status:cfg.stages[0],financialControl:true};await createRecord(cfg.collection,payload);setMessage(`${cfg.label}: record created at ${cfg.stages[0]}.`);setForm({...base,status:cfg.stages[0]});await load()}catch(e){setError(e.message||"Unable to save finance record.")}finally{setBusy(false)}}
 async function advance(r){const i=cfg.stages.indexOf(r.status);if(i<0||i>=cfg.stages.length-1)return;setBusy(true);setError("");try{const next=cfg.stages[i+1];await updateRecord(cfg.collection,r.id,{status:next,workflowStage:next,lastWorkflowAction:`${r.status} → ${next}`});setMessage(`${r.reference||r.title}: ${r.status} → ${next}.`);await load()}catch(e){setError(e.message||"Unable to advance financial workflow.")}finally{setBusy(false)}}
 return <div className="page">
 <section className="welcome-panel"><div><span className="eyebrow">FINANCIAL CONTROL CENTRE</span><h1>Finance Portfolio</h1><p>Integrated financial control for Board-approved budgets, execution, funding, approvals, grants, reconciliation, assets and financial reporting.</p></div></section>
 {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
 <section className="dashboard-grid"><div className="stat-card"><span>Budget Portfolio</span><strong>{money(totals.budget)}</strong><small>Registered budget value</small></div><div className="stat-card"><span>Transactions</span><strong>{money(totals.transactions)}</strong><small>Recorded transaction value</small></div><div className="stat-card"><span>Funding</span><strong>{money(totals.funding)}</strong><small>Funding register value</small></div><div className="stat-card"><span>Grants</span><strong>{money(totals.grants)}</strong><small>Grant portfolio value</small></div></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">SEPARATION OF DUTIES</span><h2>Financial Governance Architecture</h2><p className="panel-description">Board approval is separated from accounting execution. The Executive Director as Accounting Officer authorizes implementation within approved budgets; routine procurement and financial execution do not automatically become Board approvals.</p></div></div><div className="dashboard-grid"><div className="stat-card"><span>Governance</span><strong>Board</strong><small>Annual budgets and reserved matters</small></div><div className="stat-card"><span>Accounting Officer</span><strong>Execute</strong><small>Authorized implementation and budget execution</small></div><div className="stat-card"><span>Finance Control</span><strong>Reconcile</strong><small>Transactions, bank and evidence</small></div><div className="stat-card"><span>Accountability</span><strong>Report</strong><small>Management, Board and donor reporting</small></div></div></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">FINANCIAL REGISTERS</span><h2>Control Registers</h2><p className="panel-description">Each financial process has its own authoritative register and lifecycle.</p></div></div><div className="member-actions">{REGISTERS.map(r=><button key={r.id} type="button" className={register===r.id?"":"secondary-button"} onClick={()=>setRegister(r.id)}>{r.label}</button>)}</div></section>
 <section className="dashboard-grid workflow-stage-grid">{stageCounts.map(([s,c])=><div key={s} className="stat-card workflow-stage"><span>{s}</span><strong>{c}</strong><small>{s==="Board Approved"?"Formal governing approval stage":"Controlled lifecycle stage"}</small></div>)}</section>
 <section className="panel" id="finance-entry"><div className="panel-header"><div><span className="eyebrow">CONTROLLED FINANCIAL ENTRY</span><h2>{cfg.label} Entry</h2><p className="panel-description">Every new record starts automatically at <strong>{cfg.stages[0]}</strong>. Users cannot choose a later stage to bypass controls.</p></div></div><form onSubmit={save}><div className="form-grid">
 <Field label="Subject / Title" name="title" form={form} setForm={setForm}/><Field label="Reference" name="reference" form={form} setForm={setForm}/>
 {cfg.id==="budgets"&&<><Field label="Budget Year" name="budgetYear" form={form} setForm={setForm}/><Field label="Funding Source" name="fundingSource" form={form} setForm={setForm}/><Field label="Cost Centre / Budget Line" name="costCentre" form={form} setForm={setForm}/><Field label="Budget Amount" name="amount" type="number" form={form} setForm={setForm}/></>}
 {cfg.id==="transactions"&&<><Field label="Transaction Date" name="date" type="date" form={form} setForm={setForm}/><Field label="Transaction Type" name="transactionType" form={form} setForm={setForm}/><Field label="Payee / Recipient" name="payee" form={form} setForm={setForm}/><Field label="Amount" name="amount" type="number" form={form} setForm={setForm}/><Field label="Cost Centre" name="costCentre" form={form} setForm={setForm}/></>}
 {cfg.id==="funding"&&<><Field label="Funding Source" name="fundingSource" form={form} setForm={setForm}/><Field label="Funding Date" name="date" type="date" form={form} setForm={setForm}/><Field label="Amount" name="amount" type="number" form={form} setForm={setForm}/></>}
 {cfg.id==="approvals"&&<><Field label="Approval Reference" name="approvalReference" form={form} setForm={setForm}/><Field label="Amount" name="amount" type="number" form={form} setForm={setForm}/><Field label="Responsible Owner" name="owner" form={form} setForm={setForm}/></>}
 {cfg.id==="grants"&&<><Field label="Donor / Grantor" name="donor" form={form} setForm={setForm}/><Field label="Grant Period" name="grantPeriod" form={form} setForm={setForm}/><Field label="Award Amount" name="amount" type="number" form={form} setForm={setForm}/><Field label="Responsible Owner" name="owner" form={form} setForm={setForm}/></>}
 {cfg.id==="bank"&&<><Field label="Bank Account" name="bankAccount" form={form} setForm={setForm}/><Field label="Statement Balance" name="statementBalance" type="number" form={form} setForm={setForm}/><Field label="Book Balance" name="bookBalance" type="number" form={form} setForm={setForm}/><Field label="Difference" name="reconciliationDifference" type="number" form={form} setForm={setForm}/></>}
 {cfg.id==="assets"&&<><Field label="Asset Number" name="assetNumber" form={form} setForm={setForm}/><Field label="Asset Category" name="assetCategory" form={form} setForm={setForm}/><Field label="Location" name="location" form={form} setForm={setForm}/></>}
 {cfg.id==="reports"&&<><Field label="Reporting Period" name="reportingPeriod" form={form} setForm={setForm}/><Field label="Prepared By" name="preparedBy" form={form} setForm={setForm}/><Field label="Reviewed By" name="reviewedBy" form={form} setForm={setForm}/><Field label="Approved By" name="approvedBy" form={form} setForm={setForm}/></>}
 <Field label="Responsible Owner" name="owner" form={form} setForm={setForm}/><Field label="Description / Purpose" name="description" form={form} setForm={setForm} wide/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving…":`Create ${cfg.label} Record`}</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">LIVE FINANCIAL REGISTER</span><h2>{cfg.label}</h2><p className="panel-description">Records move sequentially through the defined control lifecycle. The register retains the audit trail generated by the data layer.</p></div></div><div className="table-wrapper"><table><thead><tr><th>Reference / Subject</th><th>Stage</th><th>Amount</th><th>Owner / Source</th><th>Control</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan="5">No records in this register.</td></tr>:rows.slice(0,100).map(r=><tr key={r.id}><td><strong>{r.reference||r.title||r.id}</strong><div className="table-subtext">{r.description||r.payee||r.reportingPeriod||r.costCentre||""}</div></td><td><span className="status-badge">{r.status||"Recorded"}</span></td><td>{r.amount!==undefined?money(r.amount):r.budgetAmount!==undefined?money(r.budgetAmount):r.statementBalance!==undefined?money(r.statementBalance):"—"}</td><td>{r.owner||r.fundingSource||r.donor||r.payee||"—"}</td><td>{cfg.stages.indexOf(r.status)<cfg.stages.length-1?<button type="button" className="secondary-button" disabled={busy} onClick={()=>advance(r)}>Advance</button>:<span className="muted">Terminal stage</span>}</td></tr>)}</tbody></table></div></section>
 </div>;
}
