import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";

const WORKFLOWS={
 Actions:{collection:"actions",eyebrow:"ACTION MANAGEMENT",title:"Action & Implementation Control",intro:"Convert decisions and meeting outcomes into accountable, time-bound implementation actions.",stages:["Open","In Progress","Blocked","Completed","Cancelled"],primary:"New Action",fields:["owner","dueDate","priority","meetingReference"]},
 Documents:{collection:"documents",eyebrow:"DOCUMENT CONTROL",title:"Controlled Document Workspace",intro:"Register, review, authorize, supersede and archive institutional documents.",stages:["Draft","Under Review","Authorized","Superseded","Archived"],primary:"Register Document",fields:["documentType","version","classification","expiryDate"]},
 Decisions:{collection:"decisions",eyebrow:"DECISION MANAGEMENT",title:"Decision & Implementation Workspace",intro:"Track approved decisions from adoption through accountable implementation and closure.",stages:["Draft","Approved","In Implementation","Implemented","Closed"],primary:"Record Decision",fields:["owner","dueDate","meetingReference"]},
 "Risk Register":{collection:"risks",eyebrow:"RISK MANAGEMENT",title:"Institutional Risk Workspace",intro:"Assess institutional risks, assign ownership, monitor treatment and evidence closure.",stages:["Open","Monitoring","Mitigated","Accepted","Closed"],primary:"Register Risk",fields:["riskOwner","likelihood","impact","mitigation"]},
 "Finance Portfolio":{collection:"financeBudgets",eyebrow:"FINANCIAL OVERSIGHT",title:"Budget & Financial Control",intro:"Track Board-approved budgets, funding sources, allocations and financial status without mixing approval with execution.",stages:["Draft","Board Approved","Active","Closed"],primary:"Add Budget Line",fields:["budgetYear","budgetAmount","fundingSource","costCentre"]},
 Procurement:{collection:"financeCommitments",eyebrow:"PROCUREMENT CONTROL",title:"Procurement Workflow",intro:"Move procurement from request through evaluation, authorization, ordering and completion.",stages:["Draft","Submitted","Evaluation","Approved","Ordered","Completed","Cancelled"],primary:"Start Procurement",fields:["procurementMethod","supplier","estimatedAmount","purchaseOrder"]},
 Reports:{collection:"reports",eyebrow:"MANAGEMENT INFORMATION",title:"Reports & Evidence Workspace",intro:"Track preparation, review, approval, publication and archival of institutional reports.",stages:["Draft","Under Review","Approved","Published","Archived"],primary:"Register Report",fields:["reportType","reportingPeriod","preparedBy","approvedBy"]},
 "Audit Trail":{collection:"audit",eyebrow:"IMMUTABLE EVIDENCE",title:"Institutional Audit Trail",intro:"Review system-generated evidence of governance and administrative actions. Records are read-only.",stages:[],primary:null,fields:[]},
 Settings:{collection:"systemSettings",eyebrow:"SYSTEM ADMINISTRATION",title:"Controlled System Configuration",intro:"Review configuration values used by the IRPA Digital Governance System.",stages:["Active","Inactive"],primary:"Add Configuration",fields:[]}
};
const defaults={title:"",reference:"",description:"",status:"Draft",owner:"",dueDate:"",priority:"Medium",meetingReference:"",documentType:"Governance Document",version:"1.0",classification:"Internal",expiryDate:"",riskOwner:"",likelihood:"3",impact:"3",mitigation:"",budgetYear:String(new Date().getFullYear()),budgetAmount:"",fundingSource:"",costCentre:"",procurementMethod:"Request for Quotations",supplier:"",estimatedAmount:"",purchaseOrder:"",reportType:"Management Report",reportingPeriod:"",preparedBy:"",approvedBy:""};
function empty(cfg){return{...defaults,status:cfg.stages[0]||""}}
function Field({label,name,value,onChange,type="text",children,wide}){return <label className={wide?"form-field form-field-wide":"form-field"}>{label}{children||<input name={name} value={value??""} type={type} onChange={onChange}/>}</label>}
export default function GovernanceWorkspaces({module}){
 const cfg=WORKFLOWS[module]||WORKFLOWS.Settings;const readOnly=module==="Audit Trail";const[rows,setRows]=useState([]),[form,setForm]=useState(empty(cfg)),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState("All");
 async function load(){try{setRows(await getRecords(COLLECTIONS[cfg.collection]))}catch(e){setError(e.message||"Unable to load workspace records.")}}
 useEffect(()=>{setForm(empty(cfg));setSelected(null);setMessage("");setError("");setFilter("All");load()},[module]);
 const counts=useMemo(()=>cfg.stages.map(s=>[s,rows.filter(r=>(r.status||"")==s).length]),[rows,cfg]);
 const visible=useMemo(()=>filter==="All"?rows:rows.filter(r=>(r.status||"")==filter),[rows,filter]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function save(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{await createRecord(cfg.collection,form);setMessage(`${cfg.title}: workflow item created.`);setForm(empty(cfg));await load()}catch(e){setError(e.message||"Unable to create workflow item.")}finally{setBusy(false)}}
 async function advance(r){const i=cfg.stages.indexOf(r.status);if(i<0||i===cfg.stages.length-1)return;setBusy(true);try{await updateRecord(cfg.collection,r.id,{...r,status:cfg.stages[i+1]});setMessage(`${r.reference||r.title||"Item"} moved to ${cfg.stages[i+1]}.`);await load()}catch(e){setError(e.message||"Unable to advance workflow.")}finally{setBusy(false)}}
 async function sendBack(r){const i=cfg.stages.indexOf(r.status);if(i<=0)return;setBusy(true);try{await updateRecord(cfg.collection,r.id,{...r,status:cfg.stages[i-1]});setMessage(`${r.reference||r.title||"Item"} returned to ${cfg.stages[i-1]}.`);await load()}catch(e){setError(e.message||"Unable to change workflow stage.")}finally{setBusy(false)}}
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">{cfg.eyebrow}</span><h1>{cfg.title}</h1><p>{cfg.intro}</p></div>{cfg.primary&&<button onClick={()=>document.getElementById("workflow-form")?.scrollIntoView({behavior:"smooth"})}>+ {cfg.primary}</button>}</section>
 {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
 {cfg.stages.length>0&&<section className="dashboard-grid workflow-stage-grid">{counts.map(([stage,count])=><button key={stage} className={filter===stage?"stat-card workflow-stage active-stage":"stat-card workflow-stage"} onClick={()=>setFilter(filter===stage?"All":stage)}><span>{stage}</span><strong>{count}</strong><small>workflow items</small></button>)}</section>}
 {!readOnly&&<section id="workflow-form" className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROLLED ENTRY</span><h2>Start New Workflow Item</h2><p className="panel-description">This creates the record at the first controlled stage. Progression is performed through workflow controls below.</p></div></div><form onSubmit={save}><div className="form-grid"><Field label="Subject / Title" name="title" value={form.title} onChange={change}/><Field label="Reference" name="reference" value={form.reference} onChange={change}/>{cfg.stages.length>0&&<Field label="Initial Stage" name="status" value={form.status} onChange={change}><select name="status" value={form.status} onChange={change}>{cfg.stages.map(s=><option key={s}>{s}</option>)}</select></Field>}
 {cfg.fields.includes("owner")&&<Field label="Responsible Owner" name="owner" value={form.owner} onChange={change}/>} {cfg.fields.includes("dueDate")&&<Field label="Due Date" name="dueDate" value={form.dueDate} onChange={change} type="date"/>} {cfg.fields.includes("priority")&&<Field label="Priority" name="priority" value={form.priority} onChange={change}><select name="priority" value={form.priority} onChange={change}><option>High</option><option>Medium</option><option>Low</option></select></Field>} {cfg.fields.includes("meetingReference")&&<Field label="Meeting / Decision Reference" name="meetingReference" value={form.meetingReference} onChange={change}/>} 
 {cfg.fields.includes("documentType")&&<Field label="Document Type" name="documentType" value={form.documentType} onChange={change}/>} {cfg.fields.includes("version")&&<Field label="Version" name="version" value={form.version} onChange={change}/>} {cfg.fields.includes("classification")&&<Field label="Classification" name="classification" value={form.classification} onChange={change}><select name="classification" value={form.classification} onChange={change}><option>Public</option><option>Internal</option><option>Confidential</option><option>Restricted</option></select></Field>} {cfg.fields.includes("expiryDate")&&<Field label="Expiry Date" name="expiryDate" value={form.expiryDate} onChange={change} type="date"/>}
 {cfg.fields.includes("riskOwner")&&<Field label="Risk Owner" name="riskOwner" value={form.riskOwner} onChange={change}/>} {cfg.fields.includes("likelihood")&&<Field label="Likelihood (1–5)" name="likelihood" value={form.likelihood} onChange={change} type="number"/>} {cfg.fields.includes("impact")&&<Field label="Impact (1–5)" name="impact" value={form.impact} onChange={change} type="number"/>} {cfg.fields.includes("mitigation")&&<Field label="Treatment / Mitigation" name="mitigation" value={form.mitigation} onChange={change}/>} 
 {cfg.fields.includes("budgetYear")&&<Field label="Budget Year" name="budgetYear" value={form.budgetYear} onChange={change}/>} {cfg.fields.includes("budgetAmount")&&<Field label="Approved / Proposed Amount" name="budgetAmount" value={form.budgetAmount} onChange={change} type="number"/>} {cfg.fields.includes("fundingSource")&&<Field label="Funding Source" name="fundingSource" value={form.fundingSource} onChange={change}/>} {cfg.fields.includes("costCentre")&&<Field label="Cost Centre / Budget Line" name="costCentre" value={form.costCentre} onChange={change}/>} 
 {cfg.fields.includes("procurementMethod")&&<Field label="Procurement Method" name="procurementMethod" value={form.procurementMethod} onChange={change}><select name="procurementMethod" value={form.procurementMethod} onChange={change}><option>Request for Quotations</option><option>Competitive Tender</option><option>Direct Procurement</option><option>Framework Contract</option></select></Field>} {cfg.fields.includes("supplier")&&<Field label="Supplier" name="supplier" value={form.supplier} onChange={change}/>} {cfg.fields.includes("estimatedAmount")&&<Field label="Estimated Amount" name="estimatedAmount" value={form.estimatedAmount} onChange={change} type="number"/>} {cfg.fields.includes("purchaseOrder")&&<Field label="Purchase Order" name="purchaseOrder" value={form.purchaseOrder} onChange={change}/>} 
 {cfg.fields.includes("reportType")&&<Field label="Report Type" name="reportType" value={form.reportType} onChange={change}/>} {cfg.fields.includes("reportingPeriod")&&<Field label="Reporting Period" name="reportingPeriod" value={form.reportingPeriod} onChange={change}/>} {cfg.fields.includes("preparedBy")&&<Field label="Prepared By" name="preparedBy" value={form.preparedBy} onChange={change}/>} {cfg.fields.includes("approvedBy")&&<Field label="Approved By" name="approvedBy" value={form.approvedBy} onChange={change}/>} 
 <Field label="Description / Scope" name="description" value={form.description} onChange={change} wide/><Field label="Evidence / Notes" name="notes" value={form.notes} onChange={change} wide/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving...":"Start Workflow"}</button></div></form></section>}
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">WORKFLOW REGISTER</span><h2>{filter==="All"?"All Workflow Items":filter}</h2><p className="panel-description">Use the stage controls to move work through the institutional process.</p></div></div><div className="table-wrapper"><table><thead><tr><th>Reference / Subject</th><th>Stage</th><th>Owner</th><th>Key Information</th><th>Workflow</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan="5">No workflow items in this stage.</td></tr>:visible.map(r=>{const i=cfg.stages.indexOf(r.status);return <tr key={r.id}><td><strong>{r.reference||r.title||r.id}</strong><div className="table-subtext">{r.title||""}</div></td><td><span className="status-badge">{r.status||"—"}</span></td><td>{r.owner||r.riskOwner||r.preparedBy||"—"}</td><td>{r.dueDate||r.meetingReference||r.supplier||r.budgetAmount||r.reportingPeriod||r.mitigation||r.description||"—"}</td><td><div className="member-actions"><button type="button" onClick={()=>setSelected(r)}>Open</button>{!readOnly&&i>0&&<button type="button" className="secondary-button" onClick={()=>sendBack(r)} disabled={busy}>Back</button>}{!readOnly&&i>=0&&i<cfg.stages.length-1&&<button type="button" onClick={()=>advance(r)} disabled={busy}>Advance</button>}</div></td></tr>})}</tbody></table></div></section>
 {selected&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">WORKFLOW ITEM</span><h2>{selected.reference||selected.title||"Record"}</h2><p className="panel-description">Current stage: {selected.status||"—"}</p></div><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></div><div className="detail-grid"><div><span>Subject</span><strong>{selected.title||"—"}</strong></div><div><span>Status</span><strong>{selected.status||"—"}</strong></div><div><span>Owner</span><strong>{selected.owner||selected.riskOwner||selected.preparedBy||"—"}</strong></div><div><span>Reference</span><strong>{selected.reference||"—"}</strong></div></div><div className="record-details">{selected.description||selected.notes||selected.mitigation||"No additional narrative recorded."}</div></section>}
 </div>
}
