import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";

const PACKS={
 Actions:{collection:"actions",eyebrow:"IMPLEMENTATION CONTROL",title:"Action & Implementation Control",intro:"Turn approved decisions and meeting outcomes into accountable implementation work.",stages:["Open","In Progress","Blocked","Completed","Cancelled"],primary:"Create Action",fields:["owner","dueDate","priority","meetingReference"],next:{Open:"Assign owner and start work", "In Progress":"Record progress or escalate a blocker",Blocked:"Resolve blocker and resume",Completed:"Retain completion evidence",Cancelled:"Retain cancellation reason"}},
 Documents:{collection:"documents",eyebrow:"DOCUMENT CONTROL",title:"Controlled Document Workspace",intro:"Manage institutional documents through drafting, review, authorization, supersession and archival.",stages:["Draft","Under Review","Authorized","Superseded","Archived"],primary:"Register Document",fields:["documentType","version","classification","expiryDate"],next:{Draft:"Complete controlled draft", "Under Review":"Complete review and authorize",Authorized:"Use current authorized version",Superseded:"Identify replacement version",Archived:"Retain as institutional evidence"}},
 Decisions:{collection:"decisions",eyebrow:"DECISION IMPLEMENTATION",title:"Decision & Implementation Workspace",intro:"Connect governance decisions to owners, implementation and closure evidence.",stages:["Draft","Approved","In Implementation","Implemented","Closed"],primary:"Record Decision",fields:["owner","dueDate","meetingReference"],next:{Draft:"Link originating resolution or meeting",Approved:"Assign implementation owner", "In Implementation":"Track delivery",Implemented:"Verify evidence",Closed:"Retain closure record"}},
 "Risk Register":{collection:"risks",eyebrow:"RISK MANAGEMENT",title:"Institutional Risk Register",intro:"Identify, assess, treat and close organizational risks with accountable ownership.",stages:["Open","Monitoring","Mitigated","Accepted","Closed"],primary:"Register Risk",fields:["riskOwner","likelihood","impact","mitigation"],next:{Open:"Assign risk owner and treatment",Monitoring:"Review residual risk",Mitigated:"Verify treatment evidence",Accepted:"Record acceptance authority",Closed:"Retain closure evidence"}},
 "Finance Portfolio":{collection:"financeBudgets",eyebrow:"FINANCIAL CONTROL",title:"Finance Portfolio Control Centre",intro:"Separate Board-approved budgeting from financial execution, funding, commitments, reconciliation and reporting.",stages:["Draft","Board Approved","Active","Closed"],primary:"Create Budget",fields:["budgetYear","budgetAmount","fundingSource","costCentre"],next:{Draft:"Prepare budget for approval", "Board Approved":"Release approved budget for execution",Active:"Monitor commitments and expenditure",Closed:"Complete financial close"},tabs:[
  ["Budgets","financeBudgets"],["Transactions","financeTransactions"],["Funding","financeFunding"],["Approvals","financeApprovals"],["Grants","financeGrants"],["Bank & Reconciliation","financeReconciliations"],["Assets","financeAssets"],["Financial Reports","financeReports"]]},
 Procurement:{collection:"financeCommitments",eyebrow:"PROCUREMENT CONTROL",title:"Procurement Workflow",intro:"Control the procurement lifecycle from justified request through evaluation, authorization, ordering and completion.",stages:["Draft","Submitted","Evaluation","Approved","Ordered","Completed","Cancelled"],primary:"Start Procurement",fields:["procurementMethod","supplier","estimatedAmount","purchaseOrder"],next:{Draft:"Submit justified procurement request",Submitted:"Complete compliance review",Evaluation:"Document evaluation",Approved:"Issue authorization/order",Ordered:"Receive and verify goods/services",Completed:"Close commitment and retain evidence",Cancelled:"Record cancellation reason"}},
 Reports:{collection:"reports",eyebrow:"MANAGEMENT INFORMATION",title:"Reports & Evidence Workspace",intro:"Move reports through preparation, review, approval, publication and archival with accountable ownership.",stages:["Draft","Under Review","Approved","Published","Archived"],primary:"Register Report",fields:["reportType","reportingPeriod","preparedBy","approvedBy"],next:{Draft:"Complete report and evidence", "Under Review":"Resolve review comments",Approved:"Authorize publication",Published:"Maintain published evidence",Archived:"Retain final institutional record"}},
 "Audit Trail":{collection:"audit",eyebrow:"IMMUTABLE EVIDENCE",title:"Institutional Audit Trail",intro:"Read-only evidence of system actions, governance events and administrative changes.",stages:[],primary:null,fields:[]},
 Settings:{collection:"systemSettings",eyebrow:"SYSTEM ADMINISTRATION",title:"Controlled System Configuration",intro:"Maintain approved configuration values. Changes must be deliberate and traceable.",stages:["Active","Inactive"],primary:"Add Configuration",fields:[]}
};
const defaults={title:"",reference:"",description:"",notes:"",status:"Draft",owner:"",dueDate:"",priority:"Medium",meetingReference:"",documentType:"Governance Document",version:"1.0",classification:"Internal",expiryDate:"",riskOwner:"",likelihood:"3",impact:"3",mitigation:"",budgetYear:String(new Date().getFullYear()),budgetAmount:"",fundingSource:"",costCentre:"",procurementMethod:"Request for Quotations",supplier:"",estimatedAmount:"",purchaseOrder:"",reportType:"Management Report",reportingPeriod:"",preparedBy:"",approvedBy:""};
function empty(cfg){return{...defaults,status:cfg.stages[0]||""}}
function Field({label,name,value,onChange,type="text",children,wide}){return <label className={wide?"form-field form-field-wide":"form-field"}>{label}{children||<input name={name} value={value??""} type={type} onChange={onChange}/>}</label>}

export default function GovernanceWorkspaces({module}){
 const cfg=PACKS[module]||PACKS.Settings;const readOnly=module==="Audit Trail";const[rows,setRows]=useState([]),[form,setForm]=useState(empty(cfg)),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState("All"),[tab,setTab]=useState(cfg.tabs?.[0]?.[1]||cfg.collection),[tabRows,setTabRows]=useState([]);
 async function load(){try{setRows(await getRecords(cfg.collection));if(cfg.tabs){const r=await getRecords(tab);setTabRows(r)}}catch(e){setError(e.message||"Unable to load workspace records.")}}
 async function loadTab(name){setTab(name);try{setTabRows(await getRecords(name))}catch(e){setError(e.message||"Unable to load financial register.")}}
 useEffect(()=>{setForm(empty(cfg));setSelected(null);setMessage("");setError("");setFilter("All");setTab(cfg.tabs?.[0]?.[1]||cfg.collection);load()},[module]);
 const counts=useMemo(()=>cfg.stages.map(s=>[s,rows.filter(r=>(r.status||"")==s).length]),[rows,cfg]);
 const visible=useMemo(()=>filter==="All"?rows:rows.filter(r=>(r.status||"")==filter),[rows,filter]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function save(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(!form.title.trim())throw new Error("Subject / Title is required.");if(cfg.stages.length&&cfg.stages.indexOf(form.status)<0)throw new Error("Invalid workflow stage.");await createRecord(cfg.collection,{...form,workflowModule:module,workflowStage:form.status});setMessage(`${cfg.title}: item entered at ${form.status||"controlled register"}.`);setForm(empty(cfg));await load()}catch(e){setError(e.message||"Unable to create workflow item.")}finally{setBusy(false)}}
 async function move(r,direction){const i=cfg.stages.indexOf(r.status);const ni=i+direction;if(i<0||ni<0||ni>=cfg.stages.length)return;setBusy(true);setError("");try{await updateRecord(cfg.collection,r.id,{status:cfg.stages[ni],workflowStage:cfg.stages[ni],lastWorkflowAction:direction>0?"Advanced":"Returned"});setMessage(`${r.reference||r.title||"Item"}: ${r.status} → ${cfg.stages[ni]}.`);await load()}catch(e){setError(e.message||"Workflow transition failed.")}finally{setBusy(false)}}
 async function executeGate(r){const action=cfg.next?.[r.status]||"Complete the next required workflow action";if(r.status===cfg.stages[cfg.stages.length-1])return;setSelected({...r,nextAction:action});}
 const displayRows=cfg.tabs?tabRows:visible;
 return <div className="page">
  <section className="welcome-panel"><div><span className="eyebrow">{cfg.eyebrow}</span><h1>{cfg.title}</h1><p>{cfg.intro}</p></div>{cfg.primary&&<button onClick={()=>document.getElementById("workflow-form")?.scrollIntoView({behavior:"smooth"})}>+ {cfg.primary}</button>}</section>
  {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
  {cfg.stages.length>0&&<section className="dashboard-grid workflow-stage-grid">{counts.map(([stage,count])=><button key={stage} className={filter===stage?"stat-card workflow-stage active-stage":"stat-card workflow-stage"} onClick={()=>setFilter(filter===stage?"All":stage)}><span>{stage}</span><strong>{count}</strong><small>{cfg.next?.[stage]||"controlled stage"}</small></button>)}</section>}
  {cfg.tabs&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">FINANCIAL REGISTERS</span><h2>Control Registers</h2><p className="panel-description">Select the financial process you are controlling. Each register is separate so approvals, execution and evidence are not mixed.</p></div></div><div className="member-actions">{cfg.tabs.map(([label,name])=><button key={name} type="button" className={tab===name?"":"secondary-button"} onClick={()=>loadTab(name)}>{label}</button>)}</div><div className="table-wrapper"><table><thead><tr><th>Record</th><th>Status</th><th>Owner / Source</th><th>Amount / Period</th><th>Reference</th></tr></thead><tbody>{displayRows.length===0?<tr><td colSpan="5">No records in this register.</td></tr>:displayRows.slice(0,100).map(r=><tr key={r.id}><td><strong>{r.reference||r.title||r.name||r.id}</strong><div className="table-subtext">{r.description||r.notes||""}</div></td><td><span className="status-badge">{r.status||"Recorded"}</span></td><td>{r.owner||r.fundingSource||r.supplier||r.preparedBy||"—"}</td><td>{r.amount??r.budgetAmount??r.estimatedAmount??r.reportingPeriod??"—"}</td><td>{r.reference||r.purchaseOrder||r.costCentre||"—"}</td></tr>)}</tbody></table></div></section>}
  {!readOnly&&<section id="workflow-form" className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROLLED ENTRY</span><h2>{cfg.primary||"Workflow Entry"}</h2><p className="panel-description">A record is created at a controlled stage and must move through the defined institutional sequence. It is not a free-form status field.</p></div></div><form onSubmit={save}><div className="form-grid"><Field label="Subject / Title" name="title" value={form.title} onChange={change}/><Field label="Reference" name="reference" value={form.reference} onChange={change}/>{cfg.stages.length>0&&<Field label="Entry Stage" name="status" value={form.status} onChange={change}><select name="status" value={form.status} onChange={change}>{cfg.stages.map(s=><option key={s}>{s}</option>)}</select></Field>}
  {cfg.fields.includes("owner")&&<Field label="Responsible Owner" name="owner" value={form.owner} onChange={change}/>} {cfg.fields.includes("dueDate")&&<Field label="Due Date" name="dueDate" value={form.dueDate} onChange={change} type="date"/>} {cfg.fields.includes("priority")&&<Field label="Priority" name="priority" value={form.priority} onChange={change}><select name="priority" value={form.priority} onChange={change}><option>High</option><option>Medium</option><option>Low</option></select></Field>} {cfg.fields.includes("meetingReference")&&<Field label="Meeting / Decision Reference" name="meetingReference" value={form.meetingReference} onChange={change}/>} 
  {cfg.fields.includes("documentType")&&<Field label="Document Type" name="documentType" value={form.documentType} onChange={change}/>} {cfg.fields.includes("version")&&<Field label="Version" name="version" value={form.version} onChange={change}/>} {cfg.fields.includes("classification")&&<Field label="Classification" name="classification" value={form.classification} onChange={change}><select name="classification" value={form.classification} onChange={change}><option>Public</option><option>Internal</option><option>Confidential</option><option>Restricted</option></select></Field>} {cfg.fields.includes("expiryDate")&&<Field label="Expiry Date" name="expiryDate" value={form.expiryDate} onChange={change} type="date"/>}
  {cfg.fields.includes("riskOwner")&&<Field label="Risk Owner" name="riskOwner" value={form.riskOwner} onChange={change}/>} {cfg.fields.includes("likelihood")&&<Field label="Likelihood (1–5)" name="likelihood" value={form.likelihood} onChange={change} type="number" min="1" max="5"/>} {cfg.fields.includes("impact")&&<Field label="Impact (1–5)" name="impact" value={form.impact} onChange={change} type="number" min="1" max="5"/>} {cfg.fields.includes("mitigation")&&<Field label="Treatment / Mitigation" name="mitigation" value={form.mitigation} onChange={change}/>} 
  {cfg.fields.includes("budgetYear")&&<Field label="Budget Year" name="budgetYear" value={form.budgetYear} onChange={change}/>} {cfg.fields.includes("budgetAmount")&&<Field label="Proposed / Approved Amount" name="budgetAmount" value={form.budgetAmount} onChange={change} type="number" min="0"/>} {cfg.fields.includes("fundingSource")&&<Field label="Funding Source" name="fundingSource" value={form.fundingSource} onChange={change}/>} {cfg.fields.includes("costCentre")&&<Field label="Cost Centre / Budget Line" name="costCentre" value={form.costCentre} onChange={change}/>} 
  {cfg.fields.includes("procurementMethod")&&<Field label="Procurement Method" name="procurementMethod" value={form.procurementMethod} onChange={change}><select name="procurementMethod" value={form.procurementMethod} onChange={change}><option>Request for Quotations</option><option>Competitive Tender</option><option>Direct Procurement</option><option>Framework Contract</option></select></Field>} {cfg.fields.includes("supplier")&&<Field label="Supplier" name="supplier" value={form.supplier} onChange={change}/>} {cfg.fields.includes("estimatedAmount")&&<Field label="Estimated Amount" name="estimatedAmount" value={form.estimatedAmount} onChange={change} type="number" min="0"/>} {cfg.fields.includes("purchaseOrder")&&<Field label="Purchase Order" name="purchaseOrder" value={form.purchaseOrder} onChange={change}/>} 
  {cfg.fields.includes("reportType")&&<Field label="Report Type" name="reportType" value={form.reportType} onChange={change}/>} {cfg.fields.includes("reportingPeriod")&&<Field label="Reporting Period" name="reportingPeriod" value={form.reportingPeriod} onChange={change}/>} {cfg.fields.includes("preparedBy")&&<Field label="Prepared By" name="preparedBy" value={form.preparedBy} onChange={change}/>} {cfg.fields.includes("approvedBy")&&<Field label="Approved By" name="approvedBy" value={form.approvedBy} onChange={change}/>} 
  <Field label="Description / Scope" name="description" value={form.description} onChange={change} wide/><Field label="Evidence / Notes" name="notes" value={form.notes} onChange={change} wide/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving...":"Enter Controlled Workflow"}</button></div></form></section>}
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">{readOnly?"READ-ONLY EVIDENCE":"WORKFLOW REGISTER"}</span><h2>{filter==="All"?"Current Work":filter}</h2><p className="panel-description">Every stage exposes the next institutional action instead of presenting the register as simple CRUD.</p></div></div><div className="table-wrapper"><table><thead><tr><th>Reference / Subject</th><th>Stage</th><th>Owner</th><th>Next Required Action</th><th>Control</th></tr></thead><tbody>{displayRows.length===0?<tr><td colSpan="5">No workflow records.</td></tr>:displayRows.map(r=>{const i=cfg.stages.indexOf(r.status);return <tr key={r.id}><td><strong>{r.reference||r.title||r.id}</strong><div className="table-subtext">{r.title||r.description||""}</div></td><td><span className="status-badge">{r.status||"Recorded"}</span></td><td>{r.owner||r.riskOwner||r.preparedBy||r.fundingSource||"—"}</td><td>{cfg.next?.[r.status]||"Review record evidence"}</td><td><div className="member-actions"><button type="button" onClick={()=>executeGate(r)}>Open Control</button>{!readOnly&&i>0&&<button type="button" className="secondary-button" onClick={()=>move(r,-1)} disabled={busy}>Return</button>}{!readOnly&&i>=0&&i<cfg.stages.length-1&&<button type="button" onClick={()=>move(r,1)} disabled={busy}>Advance</button>}</div></td></tr>})}</tbody></table></div></section>
  {selected&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROL GATE</span><h2>{selected.reference||selected.title||"Record"}</h2><p className="panel-description">Current stage: {selected.status||"Recorded"}</p></div><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></div><div className="detail-grid"><div><span>Subject</span><strong>{selected.title||"—"}</strong></div><div><span>Stage</span><strong>{selected.status||"—"}</strong></div><div><span>Owner</span><strong>{selected.owner||selected.riskOwner||selected.preparedBy||"—"}</strong></div><div><span>Reference</span><strong>{selected.reference||"—"}</strong></div></div><div className="record-details"><strong>Next required action</strong><p>{selected.nextAction||cfg.next?.[selected.status]||"Review evidence and record the required institutional action."}</p><p>{selected.description||selected.notes||selected.mitigation||"No narrative evidence recorded."}</p></div></section>}
 </div>
}
