import React,{useEffect,useState}from"react";
import{getInductionRegistrationRequests,linkInductionRegistration}from"../firebase/data";
export default function InductionAdmin(){
 const[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[action,setAction]=useState(""),[message,setMessage]=useState("");
 async function load(){setBusy(true);setMessage("");try{const r=await getInductionRegistrationRequests();setRows(r)}catch(e){setMessage(e.message||"Unable to load induction applications.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function link(row){setAction(row.id);setMessage("");try{const result=await linkInductionRegistration(row.id);setMessage("LINK completed. "+(row.fullName||row.email)+" is now approved and linked to "+(result.boardMember?"Board Member":(result.department||"the registered department"))+(result.unit?" — "+result.unit:"")+" .");await load()}catch(e){setMessage(e.message||"The application could not be linked.")}finally{setAction("")}}

 const pending=rows.filter(x=>x.status!=="Linked"&&x.roleAssignmentStatus!=="Linked");
 return <div className="page">
  <section className="welcome-panel"><div><span className="eyebrow">ADMINISTRATOR INDUCTION CONTROL</span><h1>Induction and Orientation — Administrator Applications</h1><p>This is the administrator review register, not the applicant filling form. Registered Members and Employees open “Induction and Orientation” from the parallel login-assistance pathway after authentication. Their administrator-registered Member/Employee capacity, roles, department and unit are retrieved by the system. This portal reviews the induction record; it does not create new accounts or registrations.</p></div><div className="identity-card"><span>Pending LINK</span><strong>{pending.length}</strong><small>Applications awaiting administrator approval</small></div></section>
  {message&&<div className="auth-message" role="status" aria-live="polite" style={{marginBottom:18}}>{message}</div>}
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">APPLICANT WORKFLOW</span><h2>Where registered members complete induction</h2><p className="panel-description">From the sign-in gateway, a registered Member/Employee selects <strong>Induction & Orientation — Login Assistance</strong>, uses the credential-assistance pathway if required, then receives the registration-linked form. The form then exposes the applicant’s registered capacity as <strong>Employee</strong> or <strong>Member</strong> (or both where both records exist), followed by role, department and unit choices retrieved from IRPA records.</p></div></div><div className="form-actions" style={{marginBottom:20}}><button type="button" onClick={()=>{window.location.href=window.location.origin+window.location.pathname+"?induction=1"}}>Open Induction and Orientation</button></div></section>
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">APPLICATION REGISTER</span><h2>Completed Induction Applications</h2><p className="panel-description">Use <strong>LINK</strong> to approve the induction and immediately bind the applicant to the department/unit or Board Member identity already held in the system.</p></div><button type="button" className="secondary-button" onClick={load} disabled={busy}>{busy?"Refreshing…":"Refresh Applications"}</button></div>
   {busy?<p className="muted">Loading applications…</p>:rows.length===0?<p className="muted">No induction applications have been submitted.</p>:
   <div style={{display:"grid",gap:14,marginTop:18}}>{rows.map(row=><article key={row.id} className="stat-card">
    <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span>APPLICANT</span><strong>{row.fullName||"Unnamed applicant"}</strong><small>{row.email||"No email"} · {row.registrationNumber?row.registrationNumber:"Registration number issued after LINK"}</small></div><div><span>STATUS</span><strong>{row.status||"Pending"}</strong><small>{row.roleAssignmentStatus||"Pending Assignment"}</small></div></div>
    <div className="dashboard-grid" style={{marginTop:14}}><div><span>ROLE</span><strong>{row.systemRole||row.requestedRole||"—"}</strong></div><div><span>DEPARTMENT</span><strong>{row.systemDepartment||row.routingDepartment||"—"}</strong></div><div><span>UNIT</span><strong>{row.systemUnit||row.routingUnit||"—"}</strong></div><div><span>BOARD MEMBER</span><strong>{row.boardMember?"Yes":"No"}</strong></div></div>
    <section className="panel" style={{marginTop:14}}><div className="panel-header"><div><span className="eyebrow">SUBMITTED INDUCTION QUESTIONS</span><h3>Applicant Responses</h3></div></div><div className="detail-grid"><div><span>INVITATION EMAIL</span><strong>{row.answers?.verifiedEmail||row.email||"—"}</strong></div><div><span>REGISTERED FULL NAME</span><strong>{row.answers?.verifiedFullName||row.fullName||"—"}</strong></div><div><span>INVITATION REFERENCE</span><strong>{row.answers?.credentialInvitationReference||row.invitationReference||"—"}</strong></div><div><span>CAPACITY</span><strong>{row.answers?.credentialCapacity||row.answers?.accountType||row.accountType||"—"}</strong></div><div><span>ROLE / POSITION</span><strong>{row.answers?.credentialRole||row.requestedRole||"—"}</strong></div><div><span>Q1</span><strong>{row.answers?.q1||"—"}</strong></div><div><span>Q2</span><strong>{row.answers?.q2||"—"}</strong></div><div><span>Q3</span><strong>{row.answers?.q3||"—"}</strong></div><div><span>Q4</span><strong>{row.answers?.q4||"—"}</strong></div><div><span>Q5</span><strong>{row.answers?.q5||"—"}</strong></div><div><span>Q6</span><strong>{row.answers?.q6||"—"}</strong></div><div><span>COMMENTS</span><strong>{row.answers?.comments||"—"}</strong></div></div></section>
    <div className="form-actions" style={{marginTop:16}}><button type="button" onClick={()=>link(row)} disabled={action===row.id||row.status==="Linked"||row.roleAssignmentStatus==="Linked"}>{action===row.id?"LINKING…":row.status==="Linked"||row.roleAssignmentStatus==="Linked"?"LINKED":"LINK"}</button></div>
   </article>)}</div>}
  </section>
 </div>
}