import React, { useEffect, useState } from "react";
import { createRecord, deleteRecord, getRecords, updateRecord, COLLECTIONS } from "../firebase/data";
import { sendMemberInvitationEmail } from "../firebase/auth";

const ROLES=["Board Member","Board Chairperson","Board Secretary","Executive Director","Finance Personnel","Finance Manager","Secretariat","Procurement Officer","Programme/Technical Officer","Management","Technical Advisor","Observer"];
const TYPES=["Governance Member","Management","Finance Personnel","Secretariat","Technical/Operational Personnel","Technical Advisor","Observer"];

export default function Invitations(){
 const [invitations,setInvitations]=useState([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState("Board Member"),[memberType,setMemberType]=useState("Governance Member"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){try{setInvitations(await getRecords(COLLECTIONS.invitations))}catch(e){setError(e.message||"Unable to load invitations.")}}
 useEffect(()=>{load()},[]);
 async function createInvitation(e){e.preventDefault();const cleanEmail=email.trim().toLowerCase(),cleanName=name.trim();setBusy(true);setError("");setMessage("");try{const id=await createRecord(COLLECTIONS.invitations,{email:cleanEmail,name:cleanName,role,memberType,status:"Pending",deliveryStatus:"Preparing"});try{await sendMemberInvitationEmail(cleanEmail,id);await updateRecord(COLLECTIONS.invitations,id,{status:"Sent",deliveryStatus:"Accepted by Firebase email service",sentAt:new Date().toISOString()});setMessage(`Invitation created successfully. A password setup email has been sent to ${cleanEmail}.`)}catch(x){await updateRecord(COLLECTIONS.invitations,id,{deliveryStatus:"Failed",deliveryError:x.message||"Email delivery failed."});throw new Error(`Invitation record was created, but the email could not be sent: ${x.message||"Email delivery failed."}`)}setEmail("");setName("");setRole("Board Member");setMemberType("Governance Member");await load()}catch(x){setError(x.message||"Unable to create invitation.");await load()}finally{setBusy(false)}}
 async function resend(i){setBusy(true);setError("");setMessage("");try{await sendMemberInvitationEmail(i.email,i.id);await updateRecord(COLLECTIONS.invitations,i.id,{status:"Sent",deliveryStatus:"Accepted by Firebase email service",sentAt:new Date().toISOString(),deliveryError:""});await load();setMessage(`Invitation email resent to ${i.email}.`)}catch(x){await updateRecord(COLLECTIONS.invitations,i.id,{deliveryStatus:"Failed",deliveryError:x.message||"Email delivery failed."});await load();setError(x.message||"Unable to resend invitation.")}finally{setBusy(false)}}
 async function cancel(i){setBusy(true);setError("");setMessage("");try{await updateRecord(COLLECTIONS.invitations,i.id,{status:"Cancelled",deliveryStatus:"—"});await load();setMessage("Invitation cancelled.")}catch(x){setError(x.message||"Unable to cancel invitation.")}finally{setBusy(false)}}
 async function remove(i){if(!window.confirm(`Permanently delete the cancelled invitation for ${i.email}? This action cannot be undone.`))return;setBusy(true);try{await deleteRecord(COLLECTIONS.invitations,i.id);await load();setMessage("Cancelled invitation permanently deleted.")}catch(x){setError(x.message||"Unable to delete invitation.")}finally{setBusy(false)}}
 return <div className="page"><div className="page-header"><div><h1>Member & Personnel Invitations</h1><p>Create controlled invitations for IRPA governance, finance, secretariat and operational personnel.</p></div></div>{message&&<div className="success-message">{message}</div>}{error&&<div className="error-message">{error}</div>}<div className="panel"><h2>Create Invitation</h2><p className="panel-description">The selected role becomes the person's initial IRPA authorization role after activation.</p><form onSubmit={createInvitation}><div className="form-grid"><div className="form-field"><label>Full Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/></div><div className="form-field"><label>Email Address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="member@example.org" required/></div><div className="form-field"><label>IRPA Role</label><select value={role} onChange={e=>setRole(e.target.value)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></div><div className="form-field"><label>Member Type</label><select value={memberType} onChange={e=>setMemberType(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></div></div><button type="submit" disabled={busy}>{busy?"Sending Invitation...":"Create & Send Invitation"}</button></form></div><div className="panel"><div className="panel-header"><h2>Invitation Register</h2><span>{invitations.length} invitation(s)</span></div><div className="table-wrapper"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Type</th><th>Status</th><th>Delivery</th><th>Action</th></tr></thead><tbody>{invitations.length===0?<tr><td colSpan="7">No invitations found.</td></tr>:invitations.map(i=><tr key={i.id}><td>{i.name||"—"}</td><td>{i.email}</td><td>{i.role}</td><td>{i.memberType}</td><td><span className="status-badge">{i.status}</span></td><td>{i.deliveryStatus||"—"}</td><td>{i.status!=="Cancelled"&&<><button type="button" onClick={()=>resend(i)} disabled={busy}>Resend</button><button type="button" onClick={()=>cancel(i)} disabled={busy}>Cancel</button></>}{i.status==="Cancelled"&&<button type="button" onClick={()=>remove(i)} disabled={busy}>Delete Permanently</button>}</td></tr>)}</tbody></table></div></div></div>
}
