import React,{useEffect,useMemo,useRef,useState}from"react";
import {createRecord,deleteRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";
import {sendMemberInvitationEmail}from"../firebase/auth";
const ROLES=["Board Member","Board Chairperson","Board Secretary","Executive Director","Finance Personnel","Finance Manager","Secretariat","Procurement Officer","Programme/Technical Officer","Management","Technical Advisor","Observer"];
const TYPES=["Governance Member","Management","Finance Personnel","Secretariat","Technical/Operational Personnel","Technical Advisor","Observer"];
const EMPTY={name:"",email:"",role:"Board Member",roles:["Board Member"],memberType:"Governance Member",employeeId:""};
export default function Invitations(){
 const[invitations,setInvitations]=useState([]),[employees,setEmployees]=useState([]),[boardMembers,setBoardMembers]=useState([]),[form,setForm]=useState(EMPTY),[editId,setEditId]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[feedback,setFeedback]=useState(null),[linkExisting,setLinkExisting]=useState(true),[busyId,setBusyId]=useState(null);
 async function load(){setError("");const results=await Promise.allSettled([getRecords(COLLECTIONS.invitations),getRecords(COLLECTIONS.employees),getRecords(COLLECTIONS.members)]);const inv=results[0],emp=results[1],mem=results[2];if(inv.status==="fulfilled")setInvitations(inv.value);else setError(inv.reason?.message||"Unable to load the Invitation Register.");if(emp.status==="fulfilled")setEmployees(emp.value);if(mem.status==="fulfilled")setBoardMembers(mem.value.filter(x=>x.boardMember===true||x.boardPosition||x.department==="Board of Directors"));const failures=[inv,emp,mem].filter(x=>x.status==="rejected");if(failures.length>0&&!error)setError(failures[0].reason?.message||"Some institutional records could not be loaded.")}
 useEffect(()=>{load()},[]);
 const pendingRecords=useMemo(()=>employees.filter(x=>!x.uid&&x.email&&(x.status||x.employmentStatus||"Active")==="Active"),[employees]); const pendingBoardMembers=useMemo(()=>boardMembers.filter(x=>!x.uid&&x.email&&(x.status||x.employmentStatus||"Active")==="Active"),[boardMembers]);
 function chooseEmployee(id){const r=employees.find(x=>x.id===id);if(!r){setForm(EMPTY);return}const email=(r.email||"").trim().toLowerCase();const counterpart=boardMembers.find(x=>(x.email||"").trim().toLowerCase()===email);const roles=[r.role,...(r.roles||[]),counterpart?.boardPosition,counterpart?.role,...(counterpart?.roles||[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);setForm({name:r.name||"",email,role:r.role||"Employee",roles,memberType:r.memberType||"Management",employeeId:r.id,boardMemberId:counterpart?.id||"",institutionalRecordType:"Employee"})} function chooseBoardMember(id){const r=boardMembers.find(x=>x.id===id);if(!r){setForm(EMPTY);return}const email=(r.email||"").trim().toLowerCase();const counterpart=employees.find(x=>(x.email||"").trim().toLowerCase()===email);const roles=[r.boardPosition,r.role,...(r.roles||[]),counterpart?.role,...(counterpart?.roles||[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);setForm({name:r.name||"",email,role:r.boardPosition||r.role||"Board Member",roles,memberType:r.memberType||"Governance Member",employeeId:counterpart?.id||"",boardMemberId:r.id,institutionalRecordType:"Board Member"})}
 async function createInvitation(e){e.preventDefault();const cleanEmail=form.email.trim().toLowerCase(),cleanName=form.name.trim();if(!cleanEmail||!cleanName)return;setBusy(true);setError("");setMessage("");setFeedback(null);try{
   const id=await createRecord(COLLECTIONS.invitations,{email:cleanEmail,name:cleanName,role:form.role,memberType:form.memberType,roles:Array.isArray(form.roles)&&form.roles.length?form.roles:[form.role].filter(Boolean),status:"Pending",deliveryStatus:"Preparing",employeeId:form.employeeId||null,boardMemberId:form.boardMemberId||null,institutionalRecordId:form.employeeId||form.boardMemberId||null,institutionalRecordType:form.institutionalRecordType||null,source:form.employeeId||form.boardMemberId?"Institutional Register":"Invitation Register",deliveryProvider:"IRPA Mail Server",inductionOrientationProtocol:"Complete the Induction & Orientation pathway or use normal sign-in; the Administrator finalises registration by linking the submitted information to the system record."});await updateRecord(COLLECTIONS.invitations,id,{subscriptionLink:window.location.origin+"/?induction=1&applicant=1&route=subscription&memberInvite="+encodeURIComponent(id),loginAssistanceLink:window.location.origin+"/?induction=1&applicant=1&route=assistance&memberInvite="+encodeURIComponent(id)});
   try{const result=await sendMemberInvitationEmail(cleanEmail,id,form.role,form.memberType);await updateRecord(COLLECTIONS.invitations,id,{status:"Invitation Requested",deliveryStatus:result.deliveryStatus||"Accepted by Firebase Authentication; SMTP delivery not yet confirmed",sentAt:new Date().toISOString(),deliveryError:""});setFeedback({type:"success",email:cleanEmail,status:result.deliveryStatus||"Accepted by Firebase Authentication; SMTP delivery not yet confirmed",message:"Firebase Authentication accepted the invitation email request. SMTP delivery and mailbox receipt are not yet confirmed. The invitee will use the secure account-setup link and the invitation record will provide the assigned role and Induction & Orientation pathway."});setMessage("Invitation created. Firebase Authentication accepted the email request. SMTP delivery and mailbox receipt are not yet confirmed.")}catch(x){await updateRecord(COLLECTIONS.invitations,id,{deliveryStatus:"Failed",deliveryError:x.message||"IRPA mail server rejected the invitation request."});setFeedback({type:"error",email:cleanEmail,status:"Failed",message:x.message||"IRPA Mail Server rejected the invitation request."});setError("Invitation record was created, but the IRPA mail server request failed.")}
   setForm(EMPTY);await load();
 }catch(x){setError(x.message||"Unable to create invitation.");await load()}finally{setBusy(false);setBusyId(null)}}
 async function editInvitation(i){setEditId(i.id);setLinkExisting(Boolean(i.institutionalRecordId||i.employeeId||i.boardMemberId));setForm({name:i.name||"",email:i.email||"",role:i.role||"Board Member",roles:Array.isArray(i.roles)&&i.roles.length?i.roles:[i.role||"Board Member"],memberType:i.memberType||"Governance Member",employeeId:i.employeeId||"",boardMemberId:i.boardMemberId||"",institutionalRecordType:i.institutionalRecordType||""});setError("");setMessage("");setFeedback(null);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"smooth"}))}
 async function saveInvitationEdit(e){e.preventDefault();const cleanEmail=form.email.trim().toLowerCase(),cleanName=form.name.trim();if(!editId||!cleanEmail||!cleanName)return;setBusy(true);setBusyId(editId);setError("");setMessage("");try{await updateRecord(COLLECTIONS.invitations,editId,{name:cleanName,email:cleanEmail,role:form.role,roles:Array.isArray(form.roles)&&form.roles.length?form.roles:[form.role].filter(Boolean),memberType:form.memberType,employeeId:form.employeeId||null,boardMemberId:form.boardMemberId||null,institutionalRecordId:form.employeeId||form.boardMemberId||null,institutionalRecordType:form.institutionalRecordType||null,lastEditedAt:new Date().toISOString()});setEditId(null);setForm(EMPTY);await load();setMessage("Invitation record updated.");}catch(x){setError(x.message||"Unable to update invitation record.")}finally{setBusy(false);setBusyId(null)}}
 function cancelEdit(){setEditId(null);setForm(EMPTY);setMessage("")}
 async function resend(i){setBusy(true);setBusyId(i.id);setError("");setMessage("");setFeedback(null);try{const result=await sendMemberInvitationEmail(i.email,i.id,i.role,i.memberType);await updateRecord(COLLECTIONS.invitations,i.id,{status:"Invitation Requested",deliveryStatus:result.deliveryStatus||"Accepted by Firebase Authentication; SMTP delivery not yet confirmed",sentAt:new Date().toISOString(),deliveryError:""});await load();setFeedback({type:"success",email:i.email,status:result.deliveryStatus||"Accepted by Firebase Authentication; SMTP delivery not yet confirmed",message:"Invitation email request was accepted by Firebase Authentication. SMTP delivery and mailbox receipt are not yet confirmed."});setMessage("Invitation email request accepted again by Firebase Authentication. SMTP delivery and mailbox receipt are not yet confirmed.")}catch(x){await updateRecord(COLLECTIONS.invitations,i.id,{deliveryStatus:"Failed",deliveryError:x.message||"Email request failed."});await load();setFeedback({type:"error",email:i.email,status:"Failed",message:x.message||"Firebase Authentication rejected the email request."});setError(x.message||"Unable to request invitation email.")}finally{setBusy(false);setBusyId(null)}}
 async function cancel(i){setBusy(true);setBusyId(i.id);setError("");setMessage("");try{await updateRecord(COLLECTIONS.invitations,i.id,{status:"Cancelled",deliveryStatus:"—"});await load();setMessage("Invitation cancelled.")}catch(x){setError(x.message||"Unable to cancel invitation.")}finally{setBusy(false);setBusyId(null)}}
 async function remove(i){if(!window.confirm(`Remove the invitation record for ${i.email}? This permanently removes the invitee from the Invitation Register and cannot be undone.`))return;setBusy(true);setBusyId(i.id);try{await deleteRecord(COLLECTIONS.invitations,i.id);await load();setMessage("Invitee removed from the Invitation Register.")}catch(x){setError(x.message||"Unable to delete invitation.")}finally{setBusy(false);setBusyId(null)}}
 return <div className="page"><div className="page-header"><div><h1>Member & Personnel Invitations</h1><p>Create controlled invitations and connect them to the authoritative IRPA membership/personnel register.</p></div></div>
 {message&&<div className="success-message">{message}</div>}{error&&<div className="error-message">{error}</div>}{feedback&&<div className={`panel registration-feedback ${feedback.type==="error"?"feedback-error":""}`}><div className="panel-header"><div><h2>{feedback.type==="error"?"Invitation Email Failure":"Invitation Email Request"}</h2><span>Delivery request status</span></div><button type="button"className="secondary-button"onClick={()=>setFeedback(null)}>Close</button></div><div className="detail-grid"><div><span>Email Address</span><strong>{feedback.email}</strong></div><div><span>Mail Server Request</span><strong>{feedback.status}</strong></div><div><span>System Feedback</span><strong>{feedback.message}</strong></div></div></div>}
 <div className={`panel invitation-editor-panel${editId?" is-editing":""}`}><h2>{editId?"Edit Invitation Record":"Create Invitation"}</h2>{editId&&<div className="success-message invitation-edit-notice">Editing the selected invitation record. Review the fields below and select <strong>Save Invitation Record</strong> to commit the changes.</div><p className="panel-description">For a person already registered in the institutional register, link the invitation to that record. This prevents a second personnel record from being created during activation.</p>
 <div className="form-actions"><label><input type="checkbox"checked={linkExisting}onChange={e=>{setLinkExisting(e.target.checked);setForm(EMPTY)}}/> Link to existing institutional record</label></div>
 <form onSubmit={editId?saveInvitationEdit:createInvitation}><div className="form-grid">
 {linkExisting&&<div className="form-field form-field-wide" style={{display:"grid",gap:14}}><div><label style={{display:"block",fontWeight:800,marginBottom:6}}>Employees&apos; Register</label><select value={form.institutionalRecordType==="Employee"?form.employeeId:""} onChange={e=>chooseEmployee(e.target.value)}><option value="">Select an employee</option>{pendingRecords.map(r=><option key={r.id}value={r.id}>{r.employeeNumber||r.id} — {r.name} — {r.email} — {r.role||"Employee"}</option>)}</select>{pendingRecords.length===0&&<small className="field-help">No active employees are waiting for account activation.</small>}</div><div><label style={{display:"block",fontWeight:800,marginBottom:6}}>Board Members&apos; Register</label><select value={form.institutionalRecordType==="Board Member"?form.boardMemberId:""} onChange={e=>chooseBoardMember(e.target.value)}><option value="">Select a Board Member</option>{pendingBoardMembers.map(r=><option key={r.id}value={r.id}>{r.memberNumber||r.id} — {r.name} — {r.email} — {r.boardPosition||"Board Member"}</option>)}</select>{pendingBoardMembers.length===0&&<small className="field-help">No active Board Members are waiting for account activation.</small>}</div></div>}
 <div className="form-field"><label>Full Name</label><input value={form.name}onChange={e=>setForm({...form,name:e.target.value})}placeholder="Full name"required/></div>
 <div className="form-field"><label>Email Address</label><input type="email"value={form.email}onChange={e=>setForm({...form,email:e.target.value})}placeholder="member@example.org"required/></div>
 <div className="form-field"><label>IRPA Role</label><select value={form.role}disabled={Boolean(form.institutionalRecordType)}onChange={e=>setForm({...form,role:e.target.value})}>{ROLES.map(r=><option key={r}>{r}</option>)}</select>{form.institutionalRecordType&&<small className="field-help">Captured automatically from the selected {form.institutionalRecordType} Register.</small>}</div>
 <div className="form-field"><label>Member Type</label><select value={form.memberType}onChange={e=>setForm({...form,memberType:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></div>
 </div><div className="form-actions"><button type="submit"disabled={busy|| (linkExisting&&!form.employeeId&&!form.boardMemberId)}>{busy?(editId?"Saving...":"Sending Invitation..."):(editId?"Save Invitation Record":"Create & Send Invitation")}</button>{editId&&<button type="button"className="secondary-button"onClick={cancelEdit}disabled={busy}>Cancel Edit</button>}</div></form></div>
 <div className="panel"><div className="panel-header"><h2>Invitation Register</h2><span>{invitations.length} invitation(s)</span></div><div className="table-wrapper"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Type</th><th>Linked Record</th><th>Status</th><th>Delivery</th><th>Action</th></tr></thead><tbody>{invitations.length===0?<tr><td colSpan="8">No invitations found.</td></tr>:invitations.map(i=><tr key={i.id}><td>{i.name||"—"}</td><td>{i.email}</td><td>{i.role}</td><td>{i.memberType}</td><td>{i.employeeId?"Linked":"New account"}</td><td><span className="status-badge">{i.status}</span></td><td>{i.deliveryStatus||"—"}{i.deliveryError&&<small className="field-help">{i.deliveryError}</small>}</td><td><div className="invitation-action-buttons">{i.status!=="Cancelled"&&i.status!=="Activated"&&<><button type="button"onClick={()=>resend(i)}disabled={busyId===i.id}><span>{busyId===i.id?"Resending…":"Resend"}</span></button><button type="button"onClick={()=>cancel(i)}disabled={busyId===i.id}>Cancel</button></>}{i.status==="Activated"&&<span className="status-badge">Activated</span>}<button type="button"onClick={()=>editInvitation(i)}disabled={busyId===i.id}>Edit Record</button><button type="button"className="danger-button"onClick={()=>remove(i)}disabled={busyId===i.id}>{busyId===i.id?"Removing…":"Remove Invitee"}</button></div></td></tr>)}</tbody></table></div></div>
 </div>
}
