import React from"react";
const UNIT_INFO={
"Service Desk & User Support":"User accounts, support requests, devices, troubleshooting and user training.",
"Infrastructure, Network & Cloud":"Hosting, DNS, network services, cloud infrastructure and availability.",
"Cybersecurity & Access Management":"Identity, permissions, security incidents, access reviews and protection controls.",
"Applications & Digital Systems":"DBGS applications, integrations, testing, release support and application lifecycle.",
"Website, Communications & Digital Content":"IRPA website updates, repairs, maintenance and controlled public communications.",
"Data, Backup & Recovery":"Data quality, backup operations, restoration, continuity and recovery evidence.",
"IT Asset & Vendor Management":"IT assets, software licences, subscriptions, warranties and vendor lifecycle.",
"IT Governance, QA & Change Control":"IT policies, standards, QA, change approvals, release evidence and audit readiness."
};
export default function ITUnitPortal({unit,onNavigate}){const description=UNIT_INFO[unit]||"Information Technology operational unit.";return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">INFORMATION TECHNOLOGY DEPARTMENT</span><h1>{unit}</h1><p>{description}</p></div><div className="identity-card"><span>PORTAL STATUS</span><strong>Operational</strong><small>Ready for records and departmental configuration.</small></div></section><section className="panel" style={{marginTop:18}}><div className="panel-heading"><div><span className="eyebrow">OPERATIONAL WORKSPACE</span><h2>{unit} Portal</h2><p className="muted">This portal is available even when its operational register is empty. Records can be added as the unit begins its work.</p></div></div><div className="dashboard-grid" style={{marginTop:16}}><div className="stat-card"><span>RECORDS</span><strong>0</strong><small>No records have been entered for this unit yet.</small></div><div className="stat-card"><span>STATUS</span><strong>Ready</strong><small>The portal is connected and ready for operational records.</small></div><div className="stat-card"><span>ACCESS</span><strong>Controlled</strong><small>Access remains subject to IRPA role and departmental authorization.</small></div></div><div className="auth-message" style={{marginTop:18}}><strong>Empty portal is intentional</strong><br/>An empty register does not disable this portal. The unit remains navigable and operationally available for future records, requests, approvals and evidence.</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:18}}><button type="button" onClick={()=>onNavigate?.("IT Operations")}>← IT Operations Portal</button><button type="button" className="secondary-button" onClick={()=>onNavigate?.("Documents")}>Documents Portal</button><button type="button" className="secondary-button" onClick={()=>onNavigate?.("Reports")}>Reports Portal</button></div></section></div>}
