import React,{useEffect,useMemo,useRef,useState}from"react";
import{auth}from"../firebase/config";
import{COLLECTIONS,createRecord,getAdminProfile,getCurrentMemberProfile,getRecords,openVotingIssue,updateRecord}from"../firebase/data";
const PROCEEDINGS=["Not Started","In Progress","Transcript Saved","Draft Minutes","Reviewed","Approved","Final"],ATTENDANCE=["Present","Absent","Excused"],ITEM_STATUS=["Pending","In Discussion","Motion Recorded","Voting","Decision Recorded","Deferred","Completed"];
const emptyMotion={text:"",movedBy:"",secondedBy:""},emptyAction={description:"",responsiblePerson:"",deadline:""};
function fmt(v){if(!v)return"—";const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
function lines(v){return String(v||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function votingRole(p){return!/non.?voting|guest|observer|external/i.test(`${p.role||p.participantRole||""} ${p.participantType||""}`)}
function roleControl(member,meeting){if(!member||!meeting)return false;const r=String(member.role||"");return member.uid===meeting.chairpersonUid||member.uid===meeting.secretaryUid||(r==="Executive Director"&&meeting.accountingOfficerUid===member.uid)}
export default function MeetingRoom({onNavigate}){
 const[meetings,setMeetings]=useState([]),[participants,setParticipants]=useState([]),[member,setMember]=useState(null),[admin,setAdmin]=useState(null),[selectedId,setSelectedId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[transcript,setTranscript]=useState(""),[listening,setListening]=useState(false),[currentIndex,setCurrentIndex]=useState(-1),[itemStatus,setItemStatus]=useState("Pending"),[motion,setMotion]=useState(emptyMotion),[decision,setDecision]=useState(""),[action,setAction]=useState(emptyAction),[quorumOverride,setQuorumOverride]=useState(""),[events,setEvents]=useState([]),[meetingVotes,setMeetingVotes]=useState([]);
 const recognition=useRef(null),selected=useMemo(()=>meetings.find(m=>m.id===selectedId)||null,[meetings,selectedId]);
 const attending=useMemo(()=>participants.filter(p=>p.meetingId===selected?.id||p.meetingReference===selected?.title),[participants,selected]),agenda=useMemo(()=>lines(selected?.agenda),[selected]);
 const eligible=useMemo(()=>attending.filter(votingRole),[attending]),present=useMemo(()=>attending.filter(p=>(p.attendanceStatus||p.status)==="Present"),[attending]),eligiblePresent=useMemo(()=>present.filter(votingRole),[present]);
 const quorumRequired=Number(selected?.quorumRequired||quorumOverride||Math.max(1,Math.ceil(eligible.length/2))),quorumMet=eligiblePresent.length>=quorumRequired,controller=!!admin?.active||roleControl(member,selected),currentItem=currentIndex>=0?agenda[currentIndex]:selected?.currentAgendaItem||"";
 async function load(){try{const[m,p]=await Promise.all([getRecords(COLLECTIONS.meetings),getRecords(COLLECTIONS.participants)]);setMeetings(m);setParticipants(p);if(!selectedId&&m[0])setSelectedId(m[0].id);if(auth.currentUser){setMember(await getCurrentMemberProfile().catch(()=>null));setAdmin(await getAdminProfile(auth.currentUser.uid).catch(()=>null))}}catch(e){setError(e.message||"Unable to load meeting room.")}}
 async function refresh(id){try{const all=await getRecords(COLLECTIONS.meetingRoomEvents);setEvents(all.filter(e=>e.meetingId===id).slice(0,30))}catch{setEvents([])}try{const all=await getRecords(COLLECTIONS.votes);setMeetingVotes(all.filter(v=>v.meetingId===id))}catch{setMeetingVotes([])}}
 useEffect(()=>{load();return()=>recognition.current?.stop()},[]);useEffect(()=>{if(selected){setTranscript(selected.transcript||"");setCurrentIndex(agenda.indexOf(selected.currentAgendaItem||""));setItemStatus(selected.currentAgendaItemStatus||"Pending");setQuorumOverride(selected.quorumRequired||"");setMotion(emptyMotion);setDecision("");setAction(emptyAction);refresh(selected.id)}},[selectedId]);
 async function patch(data,text,event){if(!selected)return;setBusy(true);setError("");try{await updateRecord(COLLECTIONS.meetings,selected.id,data);const next={...selected,...data};setMeetings(v=>v.map(m=>m.id===selected.id?next:m));if(event)await createRecord(COLLECTIONS.meetingRoomEvents,{meetingId:selected.id,meetingReference:selected.reference||selected.title,...event,actorUid:auth.currentUser?.uid||null,createdAt:new Date().toISOString()});setMessage(text);await refresh(selected.id);return next}catch(e){setError(e.code==="permission-denied"?"Security policy blocked this meeting change. The current Firebase rules permit meeting updates only to an administrator; the interface will not pretend that a non-administrator has control.":(e.message||"Unable to save meeting room update."));throw e}finally{setBusy(false)}}
 function deny(){setError("Read-only access. You are not an authorised meeting controller for this meeting.")}
 async function openLive(){if(!controller)return deny();if(!quorumMet)return setError(`Quorum is not met: ${eligiblePresent.length} of ${quorumRequired} eligible voting participants are present.`);await patch({status:"In Progress",proceedingsStatus:selected.proceedingsStatus==="Not Started"?"In Progress":selected.proceedingsStatus,quorumVerified:true,quorumVerifiedAt:new Date().toISOString()},"Meeting is LIVE and quorum has been verified.",{eventType:"LIVE_SESSION_STARTED",status:"Live"})}
 async function pauseLive(){if(!controller)return deny();await patch({status:"Scheduled"},"Meeting paused.",{eventType:"LIVE_SESSION_PAUSED",status:"Paused"})}
 async function closeLive(){if(!controller)return deny();if(selected.votingRequired&&selected.votingStatus!=="Completed")return setError("Required voting is unresolved; the meeting cannot be closed.");if(currentIndex>=0&&!['Completed','Deferred'].includes(itemStatus))return setError("Complete or defer the current agenda item before closing the meeting.");await patch({status:"Completed",closedAt:new Date().toISOString()},"Meeting closed. Minutes remain in the Meetings workflow for review and approval.",{eventType:"LIVE_SESSION_ENDED",status:"Closed"})}
 async function attendance(p,state){if(!controller)return deny();try{await updateRecord(COLLECTIONS.participants,p.id,{attendanceStatus:state,attendanceRecordedAt:new Date().toISOString(),attendanceRecordedByUid:auth.currentUser?.uid||null});setParticipants(v=>v.map(x=>x.id===p.id?{...x,attendanceStatus:state}:x));setMessage(`${p.name||p.participantName||"Participant"}: ${state}.`)}catch(e){setError(e.code==="permission-denied"?"Attendance is protected by the current security rules; only an administrator can modify the participant record.":(e.message||"Unable to update attendance."))}}
 async function selectAgenda(i){if(!controller)return deny();const item=agenda[i];setCurrentIndex(i);setItemStatus("In Discussion");await patch({currentAgendaItem:item,currentAgendaItemIndex:i,currentAgendaItemStatus:"In Discussion",proceedingsStatus:"In Progress"},`Agenda item ${i+1} is now before the meeting.`,{eventType:"AGENDA_ITEM_OPENED",agendaItem:item,agendaItemIndex:i,status:"In Discussion"})}
 async function changeItemStatus(v){if(!controller)return deny();setItemStatus(v);await patch({currentAgendaItemStatus:v},`Current agenda item marked ${v}.`,{eventType:"AGENDA_ITEM_STATUS_CHANGED",agendaItem:currentItem,status:v})}
 async function saveQuorum(){if(!controller)return deny();const n=Math.max(1,Number(quorumOverride||Math.ceil(eligible.length/2)));await patch({quorumRequired:n},`Quorum requirement set to ${n}.`)}
 async function saveMotion(){if(!controller)return deny();if(!currentItem)return setError("Select the current agenda item first.");if(!motion.text.trim())return setError("Motion text is required.");await patch({currentMotion:{...motion,text:motion.text.trim()},currentAgendaItemStatus:"Motion Recorded"},"Motion recorded against the current agenda item.",{eventType:"MOTION_RECORDED",agendaItem:currentItem,motion:motion.text.trim(),movedBy:motion.movedBy,secondedBy:motion.secondedBy,status:"Recorded"});setItemStatus("Motion Recorded")}
 async function openVote(){if(!controller)return deny();if(!currentItem)return setError("Select the agenda item before opening a vote.");if(!quorumMet)return setError(`Voting is blocked until quorum is met: ${eligiblePresent.length}/${quorumRequired}.`);const ref=selected.votingReference||`IRPA-VOTE-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`;try{const issue=await openVotingIssue({meetingId:selected.id,meetingReference:selected.reference||selected.title,resolutionId:null,resolutionReference:"",votingReference:ref});await patch({votingRequired:true,votingReference:ref,votingIssueId:issue.id,votingStatus:"Open",votingResult:"Pending",currentAgendaItemStatus:"Voting"},"Anonymous voting is open for this meeting.",{eventType:"VOTE_OPENED",agendaItem:currentItem,votingReference:ref,votingIssueId:issue.id,status:"Open"})}catch(e){setError(e.message||"Unable to open voting.")}}
 async function recordDecision(){if(!controller)return deny();if(!currentItem)return setError("Select the current agenda item first.");if(!decision.trim())return setError("Decision text is required.");await patch({currentDecision:decision.trim(),currentAgendaItemStatus:"Decision Recorded"},"Decision recorded against the current agenda item.",{eventType:"DECISION_RECORDED",agendaItem:currentItem,decision:decision.trim(),status:"Recorded"});setItemStatus("Decision Recorded")}
 async function recordAction(){if(!controller)return deny();if(!currentItem||!action.description.trim())return setError("Select an agenda item and enter an action.");const line=`${action.description.trim()} | Responsible: ${action.responsiblePerson||"Unassigned"} | Deadline: ${action.deadline||"Not set"}`;await patch({actionItems:[...lines(selected.actionItems),line].join("\n")},"Action item recorded in the meeting record.",{eventType:"ACTION_RECORDED",agendaItem:currentItem,action:line,status:"Recorded"});setAction(emptyAction)}
 function startTranscript(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return setError("Live browser transcription is not supported. Type or paste proceedings below.");if(listening){recognition.current?.stop();setListening(false);return}const r=new SR();r.continuous=true;r.interimResults=true;r.lang="en-TZ";r.onresult=e=>{let out="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)out+=`${e.results[i][0].transcript.trim()}\n`;if(out)setTranscript(v=>`${v}${v&&!v.endsWith("\n")?"\n":""}${out}`)};r.onerror=e=>{setListening(false);setError(`Transcription stopped: ${e.error||"browser error"}`)};r.onend=()=>setListening(false);recognition.current=r;r.start();setListening(true);setError("")}
 async function saveTranscript(){if(!controller)return deny();await patch({transcript,proceedingsStatus:transcript.trim()?"Transcript Saved":"Not Started"},"Transcript saved to the authoritative meeting record.",{eventType:"TRANSCRIPT_SAVED",status:"Saved"})}
 function nav(m){if(onNavigate)onNavigate(m);else window.dispatchEvent(new CustomEvent("irpa:navigate",{detail:m}))}
 const tally={For:meetingVotes.filter(v=>v.outcome==="For").length,Against:meetingVotes.filter(v=>v.outcome==="Against").length,Abstain:meetingVotes.filter(v=>v.outcome==="Abstain").length};
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">IRPA LIVE GOVERNANCE</span><h1>Meeting Room</h1><p>Authoritative live-session control for quorum, attendance, agenda, motions, voting, decisions, actions, transcript and closure.</p></div><span className="status-badge">{selected?.status==="In Progress"?"● LIVE":"READY"}</span></section>
 {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">AUTHORITATIVE MEETING</span><h2>Select Meeting</h2></div><span className="status-badge">{controller?"CONTROL ENABLED":"READ ONLY"}</span></div><div className="form-grid"><div className="form-field form-field-wide"><label>Meeting</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select meeting</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.reference||m.title} — {fmt(m.date)} {m.startTime||""}</option>)}</select></div></div>{selected&&<div className="dashboard-grid" style={{marginTop:16}}><div className="stat-card"><span>Meeting</span><strong style={{fontSize:16}}>{selected.reference||selected.title}</strong><small>{selected.title}</small></div><div className="stat-card"><span>Date / Time</span><strong style={{fontSize:16}}>{fmt(selected.date)}</strong><small>{selected.startTime||"—"} – {selected.endTime||"—"}</small></div><div className="stat-card"><span>Chair / Secretary</span><strong style={{fontSize:15}}>{selected.chairperson||"—"}</strong><small>{selected.secretary||"Secretary not recorded"}</small></div><div className="stat-card"><span>Quorum</span><strong>{eligiblePresent.length}/{quorumRequired}</strong><small>{quorumMet?"QUORUM MET":"QUORUM NOT MET"}</small></div></div>}</section>
 {selected&&<><section className="dashboard-grid"><div className="stat-card"><span>Attendance</span><strong>{present.length}/{attending.length}</strong><small>Present</small></div><div className="stat-card"><span>Voting Eligible Present</span><strong>{eligiblePresent.length}</strong><small>of {eligible.length} eligible</small></div><div className="stat-card"><span>Current Item</span><strong style={{fontSize:14}}>{currentItem||"None"}</strong><small>{itemStatus}</small></div><div className="stat-card"><span>Voting</span><strong style={{fontSize:16}}>{selected.votingStatus||"Not Open"}</strong><small>{tally.For} For · {tally.Against} Against · {tally.Abstain} Abstain</small></div></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">SESSION CONTROL</span><h2>Chair / Secretary Control</h2><p className="panel-description">Controls are role-gated and the client now follows the current Firebase server policy. No non-administrator is shown as authorised unless the meeting explicitly assigns their UID.</p></div></div><div className="form-actions"><button onClick={openLive} disabled={busy||!controller||selected.status==="In Progress"}>▶ Start / Resume</button><button className="secondary-button" onClick={pauseLive} disabled={busy||!controller||selected.status!=="In Progress"}>Pause</button><button className="danger-button" onClick={closeLive} disabled={busy||!controller||selected.status!=="In Progress"}>Close Meeting</button><button className="secondary-button" onClick={()=>nav("Meetings")}>Meeting Register</button></div><div className="form-grid" style={{marginTop:18}}><div className="form-field"><label>Quorum Required</label><input type="number" min="1" value={quorumOverride||Math.max(1,Math.ceil(eligible.length/2))} onChange={e=>setQuorumOverride(e.target.value)} disabled={!controller}/></div><div className="form-field"><label>Quorum Status</label><input value={quorumMet?"MET":"NOT MET"} readOnly/></div><div className="form-field"><label>Proceedings Status</label><select value={selected.proceedingsStatus||"Not Started"} onChange={e=>patch({proceedingsStatus:e.target.value},`Proceedings status changed to ${e.target.value}.`)} disabled={!controller}>{PROCEEDINGS.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Meeting Status</label><input value={selected.status||"Scheduled"} readOnly/></div></div><div className="form-actions"><button className="secondary-button" onClick={saveQuorum} disabled={!controller||busy}>Save Quorum</button></div></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">ATTENDANCE & QUORUM</span><h2>Live Attendance Register</h2></div><strong>{present.length}/{attending.length} Present</strong></div>{attending.length?<div className="table-wrapper"><table><thead><tr><th>Participant</th><th>Role</th><th>Voting</th><th>Attendance</th><th>Control</th></tr></thead><tbody>{attending.map(p=>{const nv=!votingRole(p);return <tr key={p.id}><td>{p.name||p.participantName||"—"}</td><td>{p.role||p.participantRole||p.participantType||"—"}</td><td>{nv?"Non-voting":"Eligible"}</td><td>{p.attendanceStatus||p.status||"—"}</td><td>{controller?<select value={p.attendanceStatus||"Present"} onChange={e=>attendance(p,e.target.value)}>{ATTENDANCE.map(x=><option key={x}>{x}</option>)}</select>:<span>Read only</span>}</td></tr>})}</tbody></table></div>:<p>No participants registered for this meeting.</p>}</section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">AGENDA</span><h2>Current Agenda Item</h2></div><span className="status-badge">{itemStatus}</span></div>{agenda.length?<div className="agenda-list">{agenda.map((item,i)=><button key={`${item}-${i}`} className={`agenda-item ${i===currentIndex?"active":""}`} onClick={()=>selectAgenda(i)} disabled={!controller}><strong>{i+1}. {item}</strong><span>{i===currentIndex?itemStatus:"Pending"}</span></button>)}</div>:<p>No agenda items recorded for this meeting.</p>} {currentItem&&<div className="form-grid" style={{marginTop:18}}><div className="form-field form-field-wide"><label>Motion</label><textarea value={motion.text} onChange={e=>setMotion(v=>({...v,text:e.target.value}))} disabled={!controller}/></div><div className="form-field"><label>Moved By</label><input value={motion.movedBy} onChange={e=>setMotion(v=>({...v,movedBy:e.target.value}))} disabled={!controller}/></div><div className="form-field"><label>Seconded By</label><input value={motion.secondedBy} onChange={e=>setMotion(v=>({...v,secondedBy:e.target.value}))} disabled={!controller}/></div><div className="form-actions"><button onClick={saveMotion} disabled={!controller||busy}>Record Motion</button><button className="secondary-button" onClick={openVote} disabled={!controller||busy||selected.votingStatus==="Open"}>Open Anonymous Vote</button></div><div className="form-field form-field-wide"><label>Decision</label><textarea value={decision} onChange={e=>setDecision(e.target.value)} disabled={!controller}/></div><div className="form-actions"><button onClick={recordDecision} disabled={!controller||busy}>Record Decision</button></div><div className="form-field"><label>Action</label><input value={action.description} onChange={e=>setAction(v=>({...v,description:e.target.value}))} disabled={!controller}/></div><div className="form-field"><label>Responsible</label><input value={action.responsiblePerson} onChange={e=>setAction(v=>({...v,responsiblePerson:e.target.value}))} disabled={!controller}/></div><div className="form-field"><label>Deadline</label><input type="date" value={action.deadline} onChange={e=>setAction(v=>({...v,deadline:e.target.value}))} disabled={!controller}/></div><div className="form-actions"><button onClick={recordAction} disabled={!controller||busy}>Record Action</button></div><div className="form-field"><label>Agenda Item Status</label><select value={itemStatus} onChange={e=>changeItemStatus(e.target.value)} disabled={!controller}>{ITEM_STATUS.map(x=><option key={x}>{x}</option>)}</select></div></div>}</section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">PROCEEDINGS</span><h2>Transcript</h2></div><span className="status-badge">{listening?"LISTENING":"READY"}</span></div><div className="form-actions"><button className="secondary-button" onClick={startTranscript} disabled={!controller}>{listening?"Stop Transcription":"Start Live Transcription"}</button><button onClick={saveTranscript} disabled={!controller||busy}>Save Transcript</button></div><textarea className="large-textarea" value={transcript} onChange={e=>setTranscript(e.target.value)} disabled={!controller} placeholder="Type or paste proceedings here..."/><div className="outputs-grid" style={{marginTop:18}}><div><strong>Session Events</strong><small>{events.length} recorded events</small></div><div><strong>Vote Tally</strong><small>{tally.For} For · {tally.Against} Against · {tally.Abstain} Abstain</small></div><div><strong>Downstream Outputs</strong><small>Meetings · Resolutions · Voting · Decisions · Actions</small></div></div></section>
 </>}
 </div>}
