import React,{useEffect,useMemo,useRef,useState}from"react";
import{auth}from"../firebase/config";
import{COLLECTIONS,createRecord,getRecord,getRecords,openVotingIssue,updateRecord}from"../firebase/data";

const PROCEEDINGS=["Not Started","In Progress","Transcript Saved","Draft Minutes","Reviewed","Approved","Final"];
const ATTENDANCE=["Present","Absent","Excused"];
const ITEM_STATUS=["Pending","In Discussion","Motion Recorded","Voting","Decision Recorded","Deferred","Completed"];
const emptyMotion={text:"",movedBy:"",secondedBy:""};
const emptyAction={description:"",responsiblePerson:"",deadline:""};
function fmt(v){if(!v)return"—";const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
function lines(v){return String(v||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function votingRole(p){return!/non.?voting|guest|observer|external/i.test(`${p.role||p.participantRole||""} ${p.participantType||""}`)}
function memberCanControl(member,meeting){if(!member)return false;const role=String(member.role||"");return["Board Chairperson","Board Secretary","Executive Director","Secretariat","Administrator"].includes(role)||member.uid===meeting?.chairpersonUid||member.uid===meeting?.secretaryUid}
export default function MeetingRoom({onNavigate}){
 const[meetings,setMeetings]=useState([]),[participants,setParticipants]=useState([]),[member,setMember]=useState(null),[selectedId,setSelectedId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[transcript,setTranscript]=useState(""),[listening,setListening]=useState(false),[currentIndex,setCurrentIndex]=useState(-1),[itemStatus,setItemStatus]=useState("Pending"),[motion,setMotion]=useState(emptyMotion),[decision,setDecision]=useState(""),[action,setAction]=useState(emptyAction),[quorumOverride,setQuorumOverride]=useState(""),[events,setEvents]=useState([]),[meetingVotes,setMeetingVotes]=useState([]),[hasVoted,setHasVoted]=useState(false);
 const recognition=useRef(null);
 const selected=useMemo(()=>meetings.find(m=>m.id===selectedId)||null,[meetings,selectedId]);
 const attending=useMemo(()=>participants.filter(p=>p.meetingId===selected?.id||p.meetingReference===selected?.title),[participants,selected]);
 const agenda=useMemo(()=>lines(selected?.agenda),[selected]);
 const eligible=useMemo(()=>attending.filter(votingRole),[attending]);
 const present=useMemo(()=>attending.filter(p=>(p.attendanceStatus||p.status)==="Present"),[attending]);
 const eligiblePresent=useMemo(()=>present.filter(votingRole),[present]);
 const quorumRequired=Number(selected?.quorumRequired||quorumOverride||Math.max(1,Math.ceil(eligible.length/2)));
 const quorumMet=eligiblePresent.length>=quorumRequired;
 const controller=memberCanControl(member,selected);
 const currentItem=currentIndex>=0?agenda[currentIndex]:selected?.currentAgendaItem||"";
 async function load(){try{const[m,p]=await Promise.all([getRecords(COLLECTIONS.meetings),getRecords(COLLECTIONS.participants)]);setMeetings(m);setParticipants(p);if(!selectedId&&m[0])setSelectedId(m[0].id);if(auth.currentUser)setMember(await getRecord(COLLECTIONS.members,auth.currentUser.uid))}catch(e){setError(e.message||"Unable to load meeting room.")}}
 async function loadEvents(id){if(!id){setEvents([]);return}try{const all=await getRecords(COLLECTIONS.meetingRoomEvents);setEvents(all.filter(e=>e.meetingId===id).slice(0,30))}catch{setEvents([])}}
 async function loadVotes(id){if(!id){setMeetingVotes([]);return}try{const all=await getRecords(COLLECTIONS.votes);setMeetingVotes(all.filter(v=>v.meetingId===id))}catch{setMeetingVotes([])}}
 useEffect(()=>{load();return()=>recognition.current?.stop()},[]);
 useEffect(()=>{if(selected){setTranscript(selected.transcript||"");setCurrentIndex(agenda.indexOf(selected.currentAgendaItem||""));setItemStatus(selected.currentAgendaItemStatus||"Pending");setQuorumOverride(selected.quorumRequired||"");setMotion(emptyMotion);setDecision("");setAction(emptyAction);loadEvents(selected.id);loadVotes(selected.id)}},[selectedId]);
 useEffect(()=>{(async()=>{if(selected?.votingIssueId){try{const{hasVotedOnIssue}=await import("../firebase/data");setHasVoted(await hasVotedOnIssue(selected.votingIssueId))}catch{setHasVoted(false)}}else setHasVoted(false)})()},[selected?.votingIssueId]);
 async function patch(data,text,opts={}){if(!selected)return;setBusy(true);setError("");try{await updateRecord(COLLECTIONS.meetings,selected.id,data);const next={...selected,...data};setMeetings(v=>v.map(m=>m.id===selected.id?next:m));setMessage(text);if(opts.event)await createRecord(COLLECTIONS.meetingRoomEvents,{meetingId:selected.id,meetingReference:selected.reference||selected.title,...opts.event,actorUid:auth.currentUser?.uid||null,createdAt:new Date().toISOString()});return next}catch(e){setError(e.message||"Unable to save meeting room update.");throw e}finally{setBusy(false)}}
 async function openLive(){if(!controller){setError("Only the authorised meeting chair, secretary, Executive Director or administrator can control the live session.");return}if(!quorumMet){setError(`Quorum is not met. ${eligiblePresent.length} of ${quorumRequired} eligible voting participants are present.`);return}await patch({status:"In Progress",proceedingsStatus:selected.proceedingsStatus==="Not Started"?"In Progress":selected.proceedingsStatus,quorumVerified:true,quorumVerifiedAt:new Date().toISOString() },"Meeting is now LIVE and quorum has been verified.",{event:{eventType:"LIVE_SESSION_STARTED",status:"Live"}});}
 async function pauseLive(){if(!controller)return setError("You are not authorised to pause this meeting.");await patch({status:"Scheduled"},"Meeting paused.",{event:{eventType:"LIVE_SESSION_PAUSED",status:"Paused"}})}
 async function closeLive(){if(!controller){setError("Only the authorised meeting controller can close the session.");return}if(selected.votingRequired&&selected.votingStatus!=="Completed"){setError("This meeting cannot be closed while required voting is unresolved.");return}if(currentIndex>=0&&itemStatus!=="Completed"&&itemStatus!=="Deferred"){setError("Complete or defer the current agenda item before closing the meeting.");return}await patch({status:"Completed",closedAt:new Date().toISOString()},"Meeting closed. Proceedings remain available for minutes approval.",{event:{eventType:"LIVE_SESSION_ENDED",status:"Closed"}})}
 async function attendance(p,state){if(!controller){setError("Only the authorised meeting chair, secretary, Executive Director or administrator can record attendance.");return}try{await updateRecord(COLLECTIONS.participants,p.id,{attendanceStatus:state,attendanceRecordedAt:new Date().toISOString(),attendanceRecordedByUid:auth.currentUser?.uid||null});setParticipants(v=>v.map(x=>x.id===p.id?{...x,attendanceStatus:state}:x));setMessage(`${p.name||p.participantName||"Participant"}: ${state}.`)}catch(e){setError(e.message||"Unable to update attendance.")}}
 async function selectAgenda(i){if(!controller){setError("Only the authorised meeting controller can change the current agenda item.");return}const item=agenda[i];setCurrentIndex(i);setItemStatus("In Discussion");await patch({currentAgendaItem:item,currentAgendaItemIndex:i,currentAgendaItemStatus:"In Discussion",proceedingsStatus:"In Progress"},`Agenda item ${i+1} is now before the meeting.`,{event:{eventType:"AGENDA_ITEM_OPENED",agendaItem:item,agendaItemIndex:i,status:"In Discussion"}})}
 async function changeItemStatus(v){if(!controller)return setError("You are not authorised to change agenda item status.");setItemStatus(v);await patch({currentAgendaItemStatus:v},`Current agenda item marked ${v}.`,{event:{eventType:"AGENDA_ITEM_STATUS_CHANGED",agendaItem:currentItem,status:v}})}
 async function saveQuorum(){if(!controller)return setError("You are not authorised to set quorum.");const n=Math.max(1,Number(quorumOverride||Math.ceil(eligible.length/2)));await patch({quorumRequired:n},`Quorum requirement set to ${n}.`)}
 async function saveMotion(){if(!controller)return setError("Only the meeting controller can record a motion.");if(!currentItem)return setError("Select the current agenda item first.");if(!motion.text.trim())return setError("Motion text is required.");await patch({currentMotion:{...motion,text:motion.text.trim()},currentAgendaItemStatus:"Motion Recorded"},"Motion recorded against the current agenda item.",{event:{eventType:"MOTION_RECORDED",agendaItem:currentItem,motion:motion.text.trim(),movedBy:motion.movedBy,secondedBy:motion.secondedBy,status:"Recorded"}});setItemStatus("Motion Recorded")}
 async function openVote(){if(!controller)return setError("Only the meeting controller can open a vote.");if(!currentItem)return setError("Select the agenda item before opening a vote.");if(!quorumMet)return setError(`Voting is blocked until quorum is met: ${eligiblePresent.length}/${quorumRequired}.`);const ref=selected.votingReference||`IRPA-VOTE-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`;try{const issue=await openVotingIssue({meetingId:selected.id,meetingReference:selected.reference||selected.title,resolutionId:null,resolutionReference:"",votingReference:ref});await patch({votingRequired:true,votingReference:ref,votingIssueId:issue.id,votingStatus:"Open",votingResult:"Pending",currentAgendaItemStatus:"Voting"},"Anonymous voting is open for this meeting item.",{event:{eventType:"VOTE_OPENED",agendaItem:currentItem,votingReference:ref,votingIssueId:issue.id,status:"Open"}});await loadVotes(selected.id)}catch(e){setError(e.message||"Unable to open voting.")}}
 async function recordDecision(){if(!controller)return setError("Only the meeting controller can record a decision.");if(!currentItem)return setError("Select the current agenda item first.");if(!decision.trim())return setError("Decision text is required.");await patch({currentDecision:decision.trim(),currentAgendaItemStatus:"Decision Recorded"},"Decision recorded against the current agenda item.",{event:{eventType:"DECISION_RECORDED",agendaItem:currentItem,decision:decision.trim(),status:"Recorded"}});setItemStatus("Decision Recorded")}
 async function recordAction(){if(!controller)return setError("Only the meeting controller can record an action.");if(!currentItem||!action.description.trim())return setError("Select an agenda item and enter an action.");const existing=lines(selected.actionItems);const line=`${action.description.trim()} | Responsible: ${action.responsiblePerson||"Unassigned"} | Deadline: ${action.deadline||"Not set"}`;await patch({actionItems:[...existing,line].join("\n")},"Action item recorded in the meeting record.",{event:{eventType:"ACTION_RECORDED",agendaItem:currentItem,action:line,status:"Recorded"}});setAction(emptyAction)}
 function startTranscript(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError("Live browser transcription is not supported. Type or paste proceedings below.");return}if(listening){recognition.current?.stop();setListening(false);return}const r=new SR();r.continuous=true;r.interimResults=true;r.lang="en-TZ";r.onresult=e=>{let out="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)out+=`${e.results[i][0].transcript.trim()}\n`;if(out)setTranscript(v=>`${v}${v&&!v.endsWith("\n")?"\n":""}${out}`)};r.onerror=e=>{setListening(false);setError(`Transcription stopped: ${e.error||"browser error"}`)};r.onend=()=>setListening(false);recognition.current=r;r.start();setListening(true);setError("")}
 async function saveTranscript(){await patch({transcript,proceedingsStatus:transcript.trim()?"Transcript Saved":"Not Started"},"Transcript saved to the authoritative meeting record.",{event:{eventType:"TRANSCRIPT_SAVED",status:"Saved"}})}
 function nav(module){if(onNavigate)onNavigate(module);else window.dispatchEvent(new CustomEvent("irpa:navigate",{detail:module}))}
 const tally={For:meetingVotes.filter(v=>v.outcome==="For").length,Against:meetingVotes.filter(v=>v.outcome==="Against").length,Abstain:meetingVotes.filter(v=>v.outcome==="Abstain").length};
 return <div className="page">
  <section className="welcome-panel"><div><span className="eyebrow">IRPA LIVE GOVERNANCE</span><h1>Meeting Room</h1><p>Authoritative live-session control: quorum, attendance, agenda, motions, voting, decisions, actions, transcript and closure.</p></div><span className="status-badge">{selected?.status==="In Progress"?"● LIVE":"READY"}</span></section>
  {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">AUTHORITATIVE MEETING</span><h2>Select Meeting</h2></div><span className="status-badge">{controller?"CONTROL ENABLED":"READ ONLY"}</span></div><div className="form-grid"><div className="form-field form-field-wide"><label>Meeting</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select meeting</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.reference||m.title} — {fmt(m.date)} {m.startTime||""}</option>)}</select></div></div>{selected&&<div className="dashboard-grid" style={{marginTop:16}}><div className="stat-card"><span>Meeting</span><strong style={{fontSize:16}}>{selected.reference||selected.title}</strong><small>{selected.title}</small></div><div className="stat-card"><span>Date / Time</span><strong style={{fontSize:16}}>{fmt(selected.date)}</strong><small>{selected.startTime||"—"} – {selected.endTime||"—"}</small></div><div className="stat-card"><span>Chair / Secretary</span><strong style={{fontSize:15}}>{selected.chairperson||"—"}</strong><small>{selected.secretary||"Secretary not recorded"}</small></div><div className="stat-card"><span>Quorum</span><strong>{eligiblePresent.length}/{quorumRequired}</strong><small>{quorumMet?"QUORUM MET":"QUORUM NOT MET"}</small></div></div>}</section>
  {selected&&<>
   <section className="dashboard-grid"><div className="stat-card"><span>Attendance</span><strong>{present.length}/{attending.length}</strong><small>Present</small></div><div className="stat-card"><span>Voting Eligible Present</span><strong>{eligiblePresent.length}</strong><small>of {eligible.length} eligible</small></div><div className="stat-card"><span>Current Item</span><strong style={{fontSize:14}}>{currentItem||"None"}</strong><small>{itemStatus}</small></div><div className="stat-card"><span>Voting</span><strong style={{fontSize:16}}>{selected.votingStatus||"Not Open"}</strong><small>{tally.For} For · {tally.Against} Against · {tally.Abstain} Abstain</small></div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">SESSION CONTROL</span><h2>Chair / Secretary Control</h2><p className="panel-description">Controls are role-gated. Attendance and proceedings changes are recorded against the meeting and audited.</p></div></div><div className="form-actions"><button onClick={openLive} disabled={busy||selected.status==="In Progress"}>▶ Start / Resume</button><button className="secondary-button" onClick={pauseLive} disabled={busy||selected.status!=="In Progress"}>Pause</button><button className="danger-button" onClick={closeLive} disabled={busy||selected.status!=="In Progress"}>Close Meeting</button><button className="secondary-button" onClick={()=>nav("Meetings")}>Meeting Register</button></div><div className="form-grid" style={{marginTop:18}}><div className="form-field"><label>Quorum Required</label><input type="number" min="1" value={quorumOverride||Math.max(1,Math.ceil(eligible.length/2))} onChange={e=>setQuorumOverride(e.target.value)} disabled={!controller}/></div><div className="form-field"><label>Quorum Status</label><input value={quorumMet?"MET":"NOT MET"} readOnly/></div><div className="form-field"><label>Proceedings Status</label><select value={selected.proceedingsStatus||"Not Started"} onChange={e=>patch({proceedingsStatus:e.target.value},`Proceedings status changed to ${e.target.value}.`)} disabled={!controller}>{PROCEEDINGS.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Meeting Status</label><input value={selected.status||"Scheduled"} readOnly/></div></div><div className="form-actions"><button className="secondary-button" onClick={saveQuorum} disabled={!controller||busy}>Save Quorum</button></div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">ATTENDANCE & QUORUM</span><h2>Live Attendance Register</h2></div><strong>{present.length}/{attending.length} Present</strong></div>{attending.length?<div className="table-wrapper"><table><thead><tr><th>Participant</th><th>Role</th><th>Voting</th><th>Attendance</th><th>Control</th></tr></thead><tbody>{attending.map(p=>{const nv=!votingRole(p);return <tr key={p.id}><td><strong>{p.name||p.participantName||p.email||"Participant"}</strong><br/><small>{p.email||""}</small></td><td>{p.role||p.participantRole||"—"}</td><td>{nv?"Non-Voting":"Eligible"}</td><td>{p.attendanceStatus||p.status||"Invited"}</td><td><div className="form-actions">{ATTENDANCE.map(s=><button key={s} className="secondary-button" onClick={()=>attendance(p,s)} disabled={!controller}>{s}</button>)}</div></td></tr>})}</tbody></table></div>:<p className="muted">No participants are linked to this meeting. Add participants before opening the session.</p>}<div className="action-feedback" style={{marginTop:16}}><strong>Quorum:</strong> {eligiblePresent.length} eligible voting participants present of {quorumRequired} required. {quorumMet?"The meeting may proceed.":"The meeting must not proceed to formal business or voting."}</div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">AGENDA CONTROL</span><h2>Current Agenda Item</h2><p className="panel-description">Select one item as the authoritative matter currently before the meeting.</p></div></div>{agenda.length?<div className="form-grid">{agenda.map((item,i)=><button key={`${item}-${i}`} type="button" className={currentIndex===i?"":"secondary-button"} onClick={()=>selectAgenda(i)} disabled={!controller} style={{textAlign:"left",padding:14}}><strong>{String(i+1).padStart(2,"0")}</strong> — {item}{currentIndex===i&&<small style={{display:"block",marginTop:4}}>CURRENT · {itemStatus}</small>}</button>)}</div>:<p className="muted">No agenda is recorded. Update the meeting record first.</p>}<div className="form-grid" style={{marginTop:18}}><div className="form-field"><label>Item Status</label><select value={itemStatus} onChange={e=>changeItemStatus(e.target.value)} disabled={!controller}>{ITEM_STATUS.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Current Item</label><input value={currentItem||""} readOnly/></div></div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">MOTION & DECISION</span><h2>Governance Action Desk</h2><p className="panel-description">Record the formal motion, open the linked vote, capture the resulting decision and assign follow-up action without losing the meeting context.</p></div></div><div className="form-grid"><div className="form-field form-field-wide"><label>Motion Text</label><textarea rows="3" value={motion.text} onChange={e=>setMotion({...motion,text:e.target.value})} disabled={!controller} placeholder="The motion placed before the meeting..."/></div><div className="form-field"><label>Moved By</label><input value={motion.movedBy} onChange={e=>setMotion({...motion,movedBy:e.target.value})} disabled={!controller}/></div><div className="form-field"><label>Seconded By</label><input value={motion.secondedBy} onChange={e=>setMotion({...motion,secondedBy:e.target.value})} disabled={!controller}/></div><div className="form-field form-field-wide"><label>Decision</label><textarea rows="3" value={decision} onChange={e=>setDecision(e.target.value)} disabled={!controller} placeholder="Decision adopted by the meeting..."/></div></div><div className="form-actions"><button onClick={saveMotion} disabled={!controller||busy}>Record Motion</button><button className="secondary-button" onClick={openVote} disabled={!controller||busy||!quorumMet||!currentItem}>Open Anonymous Vote</button><button className="secondary-button" onClick={recordDecision} disabled={!controller||busy}>Record Decision</button></div><div className="form-grid" style={{marginTop:18}}><div className="form-field form-field-wide"><label>Action Description</label><input value={action.description} onChange={e=>setAction({...action,description:e.target.value})} disabled={!controller}/></div><div className="form-field"><label>Responsible Person</label><input value={action.responsiblePerson} onChange={e=>setAction({...action,responsiblePerson:e.target.value})} disabled={!controller}/></div><div className="form-field"><label>Deadline</label><input type="date" value={action.deadline} onChange={e=>setAction({...action,deadline:e.target.value})} disabled={!controller}/></div></div><div className="form-actions"><button className="secondary-button" onClick={recordAction} disabled={!controller||busy}>Record Action</button><button className="secondary-button" onClick={()=>nav("Resolutions")}>Create Resolution</button></div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">LIVE TRANSCRIPTION</span><h2>Proceedings Capture</h2></div><span className="status-badge">{listening?"● RECORDING":"READY"}</span></div><textarea value={transcript} onChange={e=>setTranscript(e.target.value)} rows="10" placeholder="Live proceedings / transcript..."/><div className="form-actions"><button onClick={startTranscript}>{listening?"Stop Transcription":"Start Live Transcription"}</button><button className="secondary-button" onClick={saveTranscript} disabled={busy||!controller}>Save Proceedings</button><button className="secondary-button" onClick={()=>nav("Meetings")}>Open Minutes Workspace</button></div></section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">AUDITABLE SESSION LOG</span><h2>Meeting Room Events</h2><p className="panel-description">Chronological control events provide a trace of session start, agenda, motion, voting, decisions, actions and closure.</p></div></div>{events.length?<div className="table-wrapper"><table><thead><tr><th>Event</th><th>Agenda Item</th><th>Status</th><th>Time</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td><strong>{String(e.eventType||"EVENT").replaceAll("_"," ")}</strong></td><td>{e.agendaItem||"—"}</td><td>{e.status||"—"}</td><td>{e.createdAt?.toDate?e.createdAt.toDate().toLocaleString():e.createdAt?new Date(e.createdAt).toLocaleString():"—"}</td></tr>)}</tbody></table></div>:<p className="muted">No session events have been recorded yet.</p>}</section>
   <section className="panel"><div className="panel-header"><div><span className="eyebrow">GOVERNANCE OUTPUTS</span><h2>Post-Meeting Workflows</h2></div></div><div className="form-actions"><button onClick={()=>nav("Resolutions")}>Resolutions</button><button className="secondary-button" onClick={()=>nav("Voting")}>Voting</button><button className="secondary-button" onClick={()=>nav("Decisions")}>Decisions</button><button className="secondary-button" onClick={()=>nav("Actions")}>Actions</button><button className="secondary-button" onClick={()=>nav("Documents")}>Documents</button><button className="secondary-button" onClick={()=>nav("Signature Platform")}>Sign Minutes</button><button className="secondary-button" onClick={()=>nav("Meetings")}>Minutes Approval</button></div></section>
  </>}
 </div>
}
