import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRecord,deleteRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";

const TYPES=["Board Meeting","Board Committee Meeting","Management Meeting","Special Meeting","Annual General Meeting","Other"];
const STATUSES=["Scheduled","In Progress","Completed","Cancelled"];
const FILTERS=["All","Scheduled","In Progress","Completed","Cancelled"];
const empty={title:"",meetingType:"Board Meeting",date:"",startTime:"",endTime:"",venue:"",chairperson:"",agenda:"",status:"Scheduled",transcript:"",summary:"",keyDiscussionPoints:"",decisions:"",actionItems:"",minutes:"",proceedingsStatus:"Not Started"};
function dateTime(m){return`${m.date||""}T${m.startTime||"00:00"}`}
function formatDate(v){if(!v)return"—";const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
function splitLines(v){return String(v||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function generateDraft(transcript,meeting){const lines=splitLines(transcript);const clean=lines.filter(x=>x.length>12);const decisions=clean.filter(x=>/\b(decision|decided|resolution|resolved|approved|agreed)\b/i.test(x));const actions=clean.filter(x=>/\b(action|assigned|responsible|deadline|follow.?up|will)\b/i.test(x));const points=clean.filter(x=>!decisions.includes(x)&&!actions.includes(x)).slice(0,8);const summary=(clean.slice(0,4).join(" ")||"No transcript content was available for summarisation.").slice(0,1400);const minutes=[`MINUTES OF ${String(meeting.title||"IRPA MEETING").toUpperCase()}`,`Date: ${formatDate(meeting.date)} | Time: ${meeting.startTime||"—"}${meeting.endTime?` – ${meeting.endTime}`:""}`,`Venue / Link: ${meeting.venue||"—"}`,`Chairperson: ${meeting.chairperson||"—"}`,"","1. OPENING AND PURPOSE",meeting.agenda||"The meeting considered the matters recorded in the agenda.","","2. KEY DISCUSSION POINTS",...(points.length?points.map((x,i)=>`${i+1}. ${x}`):["No distinct discussion points were detected from the transcript."]),"","3. DECISIONS / RESOLUTIONS",...(decisions.length?decisions.map((x,i)=>`${i+1}. ${x}`):["No explicit decisions or resolutions were detected in the transcript."]),"","4. ACTION ITEMS",...(actions.length?actions.map((x,i)=>`${i+1}. ${x}`):["No explicit action items were detected in the transcript."]),"","5. CLOSING","Draft generated from the meeting transcript and must be reviewed by the authorised meeting secretary before approval.",].join("\n");return{summary,keyDiscussionPoints:points.join("\n"),decisions:decisions.join("\n"),actionItems:actions.join("\n"),minutes}}

export default function Meetings({onNavigate}){
 const[meetings,setMeetings]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[showForm,setShowForm]=useState(false),[assistantOpen,setAssistantOpen]=useState(false),[listening,setListening]=useState(false),[assistantTranscript,setAssistantTranscript]=useState("");
 const recognitionRef=useRef(null);
 async function load(){try{setMeetings(await getRecords(COLLECTIONS.meetings))}catch(e){setError(e.message||"Unable to load meeting register.")}}
 useEffect(()=>{load();return()=>{if(recognitionRef.current)recognitionRef.current.stop()}},[]);
 const today=new Date().toISOString().slice(0,10);
 const metrics=useMemo(()=>({total:meetings.length,upcoming:meetings.filter(m=>m.status==="Scheduled"&&m.date>=today).length,active:meetings.filter(m=>m.status==="In Progress").length,completed:meetings.filter(m=>m.status==="Completed").length}),[meetings,today]);
 const visible=useMemo(()=>meetings.filter(m=>{const q=search.trim().toLowerCase();const ok=!q||[m.title,m.meetingType,m.venue,m.chairperson,m.agenda].some(v=>String(v||"").toLowerCase().includes(q));return(filter==="All"||m.status===filter)&&ok}).sort((a,b)=>dateTime(a).localeCompare(dateTime(b))),[meetings,search,filter]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 function startCreate(){setEditing(null);setSelected(null);setForm(empty);setError("");setMessage("");setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})}
 function edit(m){setEditing(m);setSelected(m);setForm({...empty,...m});setError("");setMessage("");setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})}
 function openWorkspace(m){setSelected(m);setForm({...empty,...m});setShowForm(false);setAssistantTranscript(m.transcript||"");setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 function cancel(){setEditing(null);setForm(empty);setShowForm(false)}
 async function submit(e){e.preventDefault();setBusy(true);setError("");setMessage("");const title=form.title;try{if(editing){await updateRecord(COLLECTIONS.meetings,editing.id,form);setMessage(`Meeting "${title}" updated successfully.`)}else{await createRecord(COLLECTIONS.meetings,form);setMessage(`Meeting "${title}" has been scheduled successfully.`)}cancel();await load()}catch(x){setError(x.message||"Unable to save meeting.")}finally{setBusy(false)}}
 async function remove(m){if(!window.confirm(`Delete the meeting "${m.title}"? This action cannot be undone.`))return;setBusy(true);setError("");try{await deleteRecord(COLLECTIONS.meetings,m.id);if(selected?.id===m.id)setSelected(null);await load();setMessage("Meeting deleted successfully.")}catch(x){setError(x.message||"Unable to delete meeting.")}finally{setBusy(false)}}
 async function saveProceedings(patch,messageText="Proceedings saved successfully."){if(!selected)return;setBusy(true);setError("");try{const next={...selected,...patch,proceedingsStatus:patch.minutes?"Draft Minutes":"In Progress"};await updateRecord(COLLECTIONS.meetings,selected.id,next);setSelected(next);setForm(next);await load();setMessage(messageText)}catch(x){setError(x.message||"Unable to save proceedings.")}finally{setBusy(false)}}
 function startLiveTranscription(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){setError("Live browser transcription is not supported in this browser. You can paste or type the transcript below.");return}if(listening){recognitionRef.current?.stop();setListening(false);return}const r=new SpeechRecognition();r.continuous=true;r.interimResults=true;r.lang="en-TZ";r.onresult=e=>{let finalText="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)finalText+=`${e.results[i][0].transcript.trim()}\n`;if(finalText)setAssistantTranscript(v=>`${v}${v&&!v.endsWith("\n")?"\n":""}${finalText}`)};r.onerror=e=>{setListening(false);setError(`Live transcription stopped: ${e.error||"browser recognition error"}.`)};r.onend=()=>setListening(false);recognitionRef.current=r;r.start();setListening(true);setError("")}
 function openAssistant(){if(!selected){setError("Open a meeting workspace first.");return}setAssistantTranscript(selected.transcript||"");setAssistantOpen(true)}
 async function generateAI(){if(!selected)return;const transcript=assistantTranscript.trim();if(!transcript){setError("Enter or record a transcript before generating minutes.");return}const draft=generateDraft(transcript,selected);await saveProceedings({...draft,transcript,proceedingsStatus:"Draft Minutes"},"AI Minutes Assistant generated a draft. Review it before approval.");setAssistantOpen(false)}
 async function saveTranscript(){await saveProceedings({transcript:assistantTranscript,proceedingsStatus:assistantTranscript.trim()?"Transcript Saved":"Not Started"},"Transcript saved to the meeting record.")}
 function go(module){if(onNavigate)onNavigate(module)}
 return <div className="page">
  <section className="welcome-panel"><div><span className="eyebrow">IRPA GOVERNANCE GATEWAY</span><h1>Meetings Gateway</h1><p>One authoritative workspace for scheduling, participants, agenda, meeting room, live proceedings, AI-assisted minutes, resolutions, voting, decisions and actions.</p></div><button onClick={startCreate}>+ Schedule Meeting</button></section>
  {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
  <section className="dashboard-grid"><div className="stat-card"><span>Total Meetings</span><strong>{metrics.total}</strong><small>Institutional register</small></div><div className="stat-card"><span>Upcoming</span><strong>{metrics.upcoming}</strong><small>Scheduled from today</small></div><div className="stat-card"><span>In Progress</span><strong>{metrics.active}</strong><small>Live governance sessions</small></div><div className="stat-card"><span>Completed</span><strong>{metrics.completed}</strong><small>Closed meeting records</small></div></section>
  <section className="panel"><div className="panel-header"><div><h2>Meeting Lifecycle</h2><p className="panel-description">The meeting record is the parent record. Proceedings, transcript, AI draft minutes and governance outputs stay attached to it.</p></div></div><div className="form-actions"><button onClick={()=>go("Meeting Room")}>Meeting Room</button><button className="secondary-button" onClick={()=>go("Participants")}>Participants</button><button className="secondary-button" onClick={()=>go("Resolutions")}>Resolutions</button><button className="secondary-button" onClick={()=>go("Voting")}>Voting</button><button className="secondary-button" onClick={()=>go("Actions")}>Actions</button></div></section>
  {showForm&&<section className="panel"><div className="panel-header"><div><h2>{editing?`Edit Meeting — ${editing.title}`:"Schedule Meeting"}</h2><p className="panel-description">Create or update the authoritative meeting record.</p></div><button className="secondary-button" type="button" onClick={cancel}>Close</button></div><form onSubmit={submit}><div className="form-grid"><div className="form-field"><label>Meeting Title</label><input name="title" value={form.title} onChange={change} required/></div><div className="form-field"><label>Meeting Type</label><select name="meetingType" value={form.meetingType} onChange={change}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Date</label><input type="date" name="date" value={form.date} onChange={change} required/></div><div className="form-field"><label>Start Time</label><input type="time" name="startTime" value={form.startTime} onChange={change} required/></div><div className="form-field"><label>End Time</label><input type="time" name="endTime" value={form.endTime} onChange={change}/></div><div className="form-field"><label>Venue / Meeting Link</label><input name="venue" value={form.venue} onChange={change} required/></div><div className="form-field"><label>Chairperson</label><input name="chairperson" value={form.chairperson} onChange={change} required/></div><div className="form-field"><label>Status</label><select name="status" value={form.status} onChange={change}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field form-field-wide"><label>Agenda / Purpose</label><textarea name="agenda" value={form.agenda} onChange={change} rows="5"/></div></div><div className="form-actions"><button type="submit" disabled={busy}>{busy?(editing?"Saving Changes...":"Scheduling..."):(editing?"Save Meeting":"Schedule Meeting")}</button><button type="button" className="secondary-button" onClick={cancel} disabled={busy}>Cancel</button></div></form></section>}
  {selected&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">MEETING WORKSPACE</span><h2>{selected.title}</h2><p className="panel-description">{formatDate(selected.date)} · {selected.startTime||"—"}{selected.endTime?` – ${selected.endTime}`:""} · {selected.venue||"No venue"}</p></div><div className="member-actions"><button className="secondary-button" onClick={()=>edit(selected)}>Edit Meeting</button><button onClick={openAssistant}>✦ AI Minutes Assistant</button></div></div>
   <div className="form-actions"><button onClick={startLiveTranscription}>{listening?"Stop Live Transcription":"Start Live Transcription"}</button><button className="secondary-button" onClick={()=>go("Meeting Room")}>Open Meeting Room</button><button className="secondary-button" onClick={()=>go("Participants")}>Manage Participants</button><button className="secondary-button" onClick={()=>go("Resolutions")}>Resolutions</button><button className="secondary-button" onClick={()=>go("Voting")}>Voting</button><button className="secondary-button" onClick={()=>go("Actions")}>Actions</button></div>
   <div className="form-grid"><div className="form-field form-field-wide"><label>Meeting Transcript / Proceedings Record</label><textarea rows="12" value={assistantTranscript} onChange={e=>setAssistantTranscript(e.target.value)} placeholder="Type, paste, or capture the meeting proceedings here..."/></div><div className="form-field"><label>Proceedings Status</label><select value={selected.proceedingsStatus||"Not Started"} onChange={e=>saveProceedings({proceedingsStatus:e.target.value},"Proceedings status updated.")}><option>Not Started</option><option>In Progress</option><option>Transcript Saved</option><option>Draft Minutes</option><option>Reviewed</option><option>Approved</option><option>Final</option></select></div><div className="form-field"><label>Actions</label><div className="form-actions"><button type="button" disabled={busy} onClick={saveTranscript}>Save Transcript</button><button type="button" disabled={busy} onClick={openAssistant}>Generate / Review Minutes</button></div></div></div>
   <div className="form-grid"><div className="form-field form-field-wide"><label>Meeting Summary</label><textarea rows="6" value={selected.summary||""} readOnly placeholder="AI-generated or manually entered summary will appear here."/></div><div className="form-field"><label>Key Discussion Points</label><textarea rows="8" value={selected.keyDiscussionPoints||""} readOnly/></div><div className="form-field"><label>Decisions / Resolutions</label><textarea rows="8" value={selected.decisions||""} readOnly/></div><div className="form-field"><label>Action Items</label><textarea rows="8" value={selected.actionItems||""} readOnly/></div><div className="form-field form-field-wide"><label>Draft / Final Minutes</label><textarea rows="16" value={selected.minutes||""} readOnly/></div></div>
  </section>}
  <section className="panel"><div className="panel-header"><div><h2>Meeting Register</h2><span>{visible.length} of {meetings.length} meeting(s)</span></div><button className="secondary-button" onClick={startCreate}>+ New Meeting</button></div><div className="form-grid"><div className="form-field"><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, chairperson, venue or agenda..."/></div><div className="form-field"><label>Status Filter</label><select value={filter} onChange={e=>setFilter(e.target.value)}>{FILTERS.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="table-wrapper"><table><thead><tr><th>Meeting</th><th>Schedule</th><th>Chairperson</th><th>Status</th><th>Proceedings</th><th>Record</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan="6">No meetings match the current search/filter.</td></tr>:visible.map(m=><tr key={m.id}><td><strong>{m.title}</strong><div className="table-subtext">{m.meetingType||"Other"}</div></td><td>{formatDate(m.date)}<div className="table-subtext">{m.startTime||"—"}{m.endTime?` – ${m.endTime}`:""} · {m.venue||"No venue"}</div></td><td>{m.chairperson||"—"}</td><td><span className="status-badge">{m.status||"—"}</span></td><td><span className="status-badge">{m.proceedingsStatus||"Not Started"}</span></td><td><div className="member-actions"><button type="button" disabled={busy} onClick={()=>openWorkspace(m)}>Open Workspace</button><button type="button" disabled={busy} onClick={()=>edit(m)}>Edit</button><button type="button" disabled={busy} onClick={()=>remove(m)}>Delete</button></div></td></tr>)}</tbody></table></div></section>
  {assistantOpen&&<div style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.72)",display:"flex",alignItems:"center",justifyContent:"center",padding:"24px"}}><div style={{width:"min(980px,100%)",maxHeight:"90vh",overflow:"auto",background:"var(--panel-bg,#151515)",border:"1px solid rgba(255,255,255,.14)",borderRadius:"16px",padding:"24px",boxShadow:"0 24px 80px rgba(0,0,0,.45)"}}><div className="panel-header"><div><span className="eyebrow">AI-ASSISTED DRAFTING</span><h2>Minutes Assistant</h2><p className="panel-description">Generate a structured draft from the transcript. The draft remains subject to human review and approval.</p></div><button className="secondary-button" onClick={()=>setAssistantOpen(false)}>Close</button></div><div className="form-field"><label>Transcript Source</label><textarea rows="14" value={assistantTranscript} onChange={e=>setAssistantTranscript(e.target.value)} placeholder="Paste or type the proceedings transcript..."/></div><div className="form-actions"><button onClick={startLiveTranscription}>{listening?"Stop Live Transcription":"Start Live Transcription"}</button><button className="secondary-button" onClick={saveTranscript} disabled={busy}>Save Transcript</button><button onClick={generateAI} disabled={busy}>{busy?"Generating Draft...":"✦ Generate AI Draft Minutes"}</button></div><p className="muted">The current drafting engine produces a structured governance draft from the supplied transcript. It does not claim that the draft is an approved or legally final minute.</p></div></div>}
 </div>
}
