import React,{useEffect,useMemo,useState}from"react";
import MeetingRoom from"./MeetingRoom";
import{createRecord,deleteRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";

const CONFIG={
 "Meeting Room":{collection:"meetingRoomEvents",title:"Meeting Room",eyebrow:"LIVE GOVERNANCE SESSION",intro:"Control the live meeting environment, attendance events and session record."},
 Actions:{collection:"actions",title:"Actions Management",eyebrow:"ACTION MANAGEMENT",intro:"Assign, track and close institutional action items arising from meetings, decisions and authorizations."},
 Documents:{collection:"documents",title:"Document Control",eyebrow:"CONTROLLED DOCUMENTS",intro:"Register governance documents, control access and track authorization status."},
 "Signature Platform":{collection:"signatures",title:"Signature Platform",eyebrow:"E-SIGNATURE CONTROL",intro:"Route documents for authorized electronic signature and preserve the signer record."},
 Decisions:{collection:"decisions",title:"Decision Management",eyebrow:"DECISION REGISTER",intro:"Record decisions, responsible owners, implementation status and evidence."},
 "Risk Register":{collection:"risks",title:"Risk Register",eyebrow:"RISK MANAGEMENT",intro:"Identify, assess, assign and monitor institutional risks and mitigation measures."},
 "Authorization & Approvals":{collection:"authorizationRequests",title:"Authorization & Approvals",eyebrow:"CONTROLLED AUTHORIZATION",intro:"Route operational authorization requests through responsible reviewers and approvers."},
 "Finance Portfolio":{collection:"financeBudgets",title:"Finance Portfolio",eyebrow:"FINANCIAL MANAGEMENT",intro:"Manage approved budgets, allocations, commitments and financial oversight records."},
 Procurement:{collection:"financeCommitments",title:"Procurement Management",eyebrow:"PROCUREMENT CONTROL",intro:"Manage procurement requests, quotations, evaluation, approval and completion."},
 Reports:{collection:"reports",title:"Reports & Management Information",eyebrow:"REPORTING",intro:"Register management, programme and governance reports with reporting periods and approval status."},
 "Audit Trail":{collection:"audit",title:"Audit Trail",eyebrow:"IMMUTABLE EVIDENCE",intro:"Review system-generated audit events. Audit records cannot be edited or deleted from this interface."},
 Settings:{collection:"systemSettings",title:"System Settings",eyebrow:"SYSTEM ADMINISTRATION",intro:"Maintain controlled configuration values for the IRPA Digital Board Governance System."}
};
const STATUS={"Meeting Room":["Scheduled","Live","Paused","Closed"],Actions:["Open","In Progress","Blocked","Completed","Cancelled"],Documents:["Draft","Under Review","Authorized","Superseded","Archived"],"Signature Platform":["Pending Signature","Signed","Declined","Expired"],Decisions:["Draft","Approved","In Implementation","Implemented","Closed"],"Risk Register":["Open","Monitoring","Mitigated","Closed","Accepted"],"Authorization & Approvals":["Draft","Submitted","Under Review","Approved","Rejected","Returned","Completed"],"Finance Portfolio":["Draft","Board Approved","Active","Closed"],Procurement:["Draft","Submitted","Evaluation","Approved","Ordered","Completed","Cancelled"],Reports:["Draft","Under Review","Approved","Published","Archived"],"Audit Trail":[],Settings:["Active","Inactive"]};
function blank(module){const b={title:"",reference:"",description:"",status:(STATUS[module]?.[0]||"Draft"),owner:"",dueDate:"",priority:"Medium",meetingReference:"",documentReference:"",authorizedUids:"",assignedTo:"",reviewer:"",approver:"",approvalDate:"",notes:""};if(module==="Risk Register")return{...b,likelihood:"3",impact:"3",mitigation:"",riskOwner:""};if(module==="Finance Portfolio")return{...b,budgetYear:String(new Date().getFullYear()),budgetAmount:"",fundingSource:"",costCentre:""};if(module==="Procurement")return{...b,procurementMethod:"Request for Quotations",supplier:"",estimatedAmount:"",purchaseOrder:""};if(module==="Reports")return{...b,reportType:"Management Report",reportingPeriod:"",preparedBy:"",approvedBy:""};if(module==="Signature Platform")return{...b,signerUid:"",signerName:"",signerEmail:"",signedAt:"",signatureStatus:"Pending Signature"};if(module==="Authorization & Approvals")return{...b,requestType:"Operational Authorization",requestedBy:"",involvedUids:"",requestedAmount:"",budgetLine:""};if(module==="Documents")return{...b,documentType:"Governance Document",version:"1.0",classification:"Internal",authorizedUids:"",expiryDate:""};return b}
function Field({label,name,value,onChange,children,wide=false,type="text"}){return <div className={wide?"form-field form-field-wide":"form-field"}><label>{label}</label>{children||<input type={type} name={name} value={value??""} onChange={onChange}/>}</div>}
export default function OperationalGateways({module}){
 if(module==="Meeting Room")return <MeetingRoom/>;
 const cfg=CONFIG[module]||CONFIG.Settings;const readOnly=module==="Audit Trail";const[rows,setRows]=useState([]),[form,setForm]=useState(blank(module)),[editing,setEditing]=useState(null),[view,setView]=useState(null),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){try{setRows(await getRecords(COLLECTIONS[cfg.collection]))}catch(e){setErr(e.message||`Unable to load ${cfg.title}.`)}}
 useEffect(()=>{setForm(blank(module));setEditing(null);setView(null);setMsg("");setErr("");load()},[module]);
 const filtered=useMemo(()=>rows.filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[rows,search]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 function add(){setEditing(null);setForm(blank(module));setMsg("");window.scrollTo({top:0,behavior:"smooth"})}
 function edit(r){setEditing(r);setForm({...blank(module),...r});setView(null);window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e){e.preventDefault();setBusy(true);setErr("");setMsg("");try{const payload={...form};if(module==="Documents")payload.authorizedUids=String(form.authorizedUids||"").split(",").map(x=>x.trim()).filter(Boolean);if(module==="Authorization & Approvals"||module==="Actions")payload.involvedUids=String(form.involvedUids||"").split(",").map(x=>x.trim()).filter(Boolean);if(editing)await updateRecord(cfg.collection,editing.id,payload);else await createRecord(cfg.collection,payload);setMsg(editing?`${cfg.title} record updated successfully.`:`${cfg.title} record created successfully.`);setEditing(null);setForm(blank(module));await load()}catch(e){setErr(e.message||`Unable to save ${cfg.title}.`)}finally{setBusy(false)}}
 async function remove(r){if(!window.confirm(`Delete this ${cfg.title} record?`))return;setBusy(true);try{await deleteRecord(cfg.collection,r.id);await load();setMsg("Record deleted successfully.")}catch(e){setErr(e.message||"Unable to delete record.")}finally{setBusy(false)}}
 const statusOptions=STATUS[module]||[];
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">{cfg.eyebrow}</span><h1>{cfg.title}</h1><p>{cfg.intro}</p></div>{!readOnly&&<button onClick={add}>+ New {module==="Procurement"?"Procurement Request":"Record"}</button>}</section>{msg&&<div className="success-message action-feedback">{msg}</div>}{err&&<div className="error-message action-feedback">{err}</div>}
 {!readOnly&&<section className="panel"><div className="panel-header"><div><h2>{editing?"Edit Controlled Record":"Create Controlled Record"}</h2><p className="panel-description">Complete the fields below. Changes are recorded in the institutional audit trail.</p></div></div><form onSubmit={save}><div className="form-grid">
 <Field label="Title / Subject" name="title" value={form.title} onChange={change}/><Field label="Reference" name="reference" value={form.reference} onChange={change}/><Field label="Status" name="status" value={form.status} onChange={change}><select name="status" value={form.status} onChange={change}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></Field>
 {module==="Actions"&&<><Field label="Owner / Responsible Person" name="owner" value={form.owner} onChange={change}/><Field label="Due Date" name="dueDate" type="date" value={form.dueDate} onChange={change}/><Field label="Priority" name="priority" value={form.priority} onChange={change}><select name="priority" value={form.priority} onChange={change}><option>High</option><option>Medium</option><option>Low</option></select></Field><Field label="Meeting Reference" name="meetingReference" value={form.meetingReference} onChange={change}/></>}
 {module==="Meeting Room"&&<><Field label="Meeting Reference" name="meetingReference" value={form.meetingReference} onChange={change}/><Field label="Event / Session" name="eventType" value={form.eventType||""} onChange={change}/><Field label="Participant / Role" name="participant" value={form.participant||""} onChange={change}/></>}
 {module==="Documents"&&<><Field label="Document Type" name="documentType" value={form.documentType} onChange={change}/><Field label="Version" name="version" value={form.version} onChange={change}/><Field label="Classification" name="classification" value={form.classification} onChange={change}><select name="classification" value={form.classification} onChange={change}><option>Public</option><option>Internal</option><option>Confidential</option><option>Restricted</option></select></Field><Field label="Expiry Date" name="expiryDate" type="date" value={form.expiryDate} onChange={change}/><Field label="Authorized User UIDs" name="authorizedUids" value={Array.isArray(form.authorizedUids)?form.authorizedUids.join(","):form.authorizedUids} onChange={change}/></>}
 {module==="Signature Platform"&&<><Field label="Document Reference" name="documentReference" value={form.documentReference} onChange={change}/><Field label="Signer Name" name="signerName" value={form.signerName} onChange={change}/><Field label="Signer Email" name="signerEmail" value={form.signerEmail} onChange={change}/><Field label="Signer UID" name="signerUid" value={form.signerUid} onChange={change}/><Field label="Signature Status" name="signatureStatus" value={form.signatureStatus} onChange={change}><select name="signatureStatus" value={form.signatureStatus} onChange={change}><option>Pending Signature</option><option>Signed</option><option>Declined</option><option>Expired</option></select></Field></>}
 {module==="Decisions"&&<><Field label="Decision Owner" name="owner" value={form.owner} onChange={change}/><Field label="Meeting Reference" name="meetingReference" value={form.meetingReference} onChange={change}/><Field label="Implementation Due Date" name="dueDate" type="date" value={form.dueDate} onChange={change}/></>}
 {module==="Risk Register"&&<><Field label="Risk Owner" name="riskOwner" value={form.riskOwner} onChange={change}/><Field label="Likelihood (1–5)" name="likelihood" value={form.likelihood} onChange={change} type="number"/><Field label="Impact (1–5)" name="impact" value={form.impact} onChange={change} type="number"/><Field label="Mitigation / Treatment" name="mitigation" value={form.mitigation} onChange={change} wide/></>}
 {module==="Authorization & Approvals"&&<><Field label="Request Type" name="requestType" value={form.requestType} onChange={change}/><Field label="Requested By" name="requestedBy" value={form.requestedBy} onChange={change}/><Field label="Reviewer" name="reviewer" value={form.reviewer} onChange={change}/><Field label="Approver" name="approver" value={form.approver} onChange={change}/><Field label="Requested Amount" name="requestedAmount" value={form.requestedAmount} onChange={change}/><Field label="Budget Line" name="budgetLine" value={form.budgetLine} onChange={change}/><Field label="Involved User UIDs (comma separated)" name="involvedUids" value={Array.isArray(form.involvedUids)?form.involvedUids.join(","):form.involvedUids} onChange={change}/></>}
 {module==="Finance Portfolio"&&<><Field label="Budget Year" name="budgetYear" value={form.budgetYear} onChange={change}/><Field label="Budget Amount" name="budgetAmount" value={form.budgetAmount} onChange={change}/><Field label="Funding Source" name="fundingSource" value={form.fundingSource} onChange={change}/><Field label="Cost Centre / Budget Line" name="costCentre" value={form.costCentre} onChange={change}/></>}
 {module==="Procurement"&&<><Field label="Procurement Method" name="procurementMethod" value={form.procurementMethod} onChange={change}><select name="procurementMethod" value={form.procurementMethod} onChange={change}><option>Request for Quotations</option><option>Competitive Tender</option><option>Direct Procurement</option><option>Framework Contract</option></select></Field><Field label="Supplier" name="supplier" value={form.supplier} onChange={change}/><Field label="Estimated Amount" name="estimatedAmount" value={form.estimatedAmount} onChange={change}/><Field label="Purchase Order" name="purchaseOrder" value={form.purchaseOrder} onChange={change}/><Field label="Evaluation / Approval Notes" name="approvalNotes" value={form.approvalNotes||""} onChange={change}/></>}
 {module==="Reports"&&<><Field label="Report Type" name="reportType" value={form.reportType} onChange={change}/><Field label="Reporting Period" name="reportingPeriod" value={form.reportingPeriod} onChange={change}/><Field label="Prepared By" name="preparedBy" value={form.preparedBy} onChange={change}/><Field label="Approved By" name="approvedBy" value={form.approvedBy} onChange={change}/></>}
 <Field label="Description / Details" name="description" value={form.description} onChange={change} wide/><Field label="Notes / Evidence" name="notes" value={form.notes} onChange={change} wide/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving...":editing?"Save Changes":"Create Record"}</button>{editing&&<button type="button" className="secondary-button" onClick={()=>{setEditing(null);setForm(blank(module))}}>Cancel</button>}</div></form></section>}
 <section className="panel"><div className="panel-header"><div><h2>{cfg.title} Register</h2><span>{filtered.length} record(s)</span></div><input className="table-search" placeholder="Search records..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrapper"><table><thead><tr><th>Reference / Subject</th><th>Status</th><th>Owner / Responsible</th><th>Details</th><th>Actions</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="5">No records found.</td></tr>:filtered.map(r=><tr key={r.id}><td><strong>{r.reference||r.title||r.name||r.id}</strong><div className="table-subtext">{r.title||r.documentReference||r.meetingReference||""}</div></td><td><span className="status-badge">{r.status||r.signatureStatus||"—"}</span></td><td>{r.owner||r.riskOwner||r.requestedBy||r.signerName||r.preparedBy||"—"}</td><td>{String(r.description||r.notes||r.mitigation||r.eventType||"").slice(0,120)}</td><td><div className="member-actions"><button type="button" onClick={()=>setView(r)}>View</button>{!readOnly&&<><button type="button" onClick={()=>edit(r)}>Edit</button><button type="button" className="danger-button" onClick={()=>remove(r)}>Delete</button></>}</div></td></tr>)}</tbody></table></div></section>
 {view&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROLLED RECORD</span><h2>Record Details</h2></div><button className="secondary-button" onClick={()=>setView(null)}>Close</button></div><pre className="record-details">{JSON.stringify(view,null,2)}</pre></section>}
 </div>;
}
