import React,{useEffect,useMemo,useState}from"react";
import{auth}from"../firebase/config";
import{COLLECTIONS,getRecords}from"../firebase/data";
import{createProcurementVendor,createProcurementRequest,uploadProcurementQuotation,registerProcurementPR,reviewProcurementRequest,authorizeProcurementRequest,generateProcurementPO,uploadProcurementEvidence,sendProcurementToFinance,PROCUREMENT_STAGES,procurementTeamRole,procurementApproverRole}from"../firebase/procurement";
const APPROVERS=["Executive Director","Director Livestock","Livestock Director","Director Internal Oversight","Internal Oversight Director","Director Finance & Administration","Director Human Resources","Director Outreach","Director Community Development","Director Environment","Director Field","Director Operations","Operations Director","Outreach Director","Community Development Director","Environment Director","Field Director"];
function Field({label,name,value,onChange,type="text",wide=false,required=false,children}){return <label className={wide?"form-field form-field-wide":"form-field"}>{label}{children||<input name={name} value={value??""} type={type} onChange={onChange} required={required}/>}</label>}
export default function ProcurementPortal({profile}){
 const role=profile?.role||"",uid=auth.currentUser?.uid||"",team=procurementTeamRole(role),approver=procurementApproverRole(role);
 const[vendors,setVendors]=useState([]),[requests,setRequests]=useState([]),[directors,setDirectors]=useState([]),[selected,setSelected]=useState(null),[files,setFiles]=useState([null,null,null]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[vf,setVf]=useState({name:"",serviceType:"",contactName:"",phone:"",email:"",address:"",registrationNumber:"",taxNumber:""});
 const[rf,setRf]=useState({title:"",description:"",department:"",estimatedAmount:"",procurementMethod:"Request for Quotations",vendorId:""});
 async function load(){try{const[v,r,e]=await Promise.all([getRecords(COLLECTIONS.procurementVendors),getRecords(COLLECTIONS.procurementRequests),getRecords(COLLECTIONS.employees)]);setVendors(v);setRequests(r);setDirectors(e.filter(x=>APPROVERS.includes(x.role)&&x.status==="Active"&&x.uid))}catch(x){setError(x.message||"Unable to load procurement records.")}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>requests.filter(r=>team||r.requestedByUid===uid),[requests,team,uid]);
 async function run(fn,success){setBusy(true);setError("");setMessage("");try{await fn();setMessage(success);setSelected(null);await load()}catch(x){setError(x.message||"Action failed.")}finally{setBusy(false)}}
 async function submitVendor(e){e.preventDefault();await run(()=>createProcurementVendor(vf),"Vendor/service provider registered. Procurement Team review is now required.");setVf({name:"",serviceType:"",contactName:"",phone:"",email:"",address:"",registrationNumber:"",taxNumber:""})}
 async function submitRequest(e){e.preventDefault();await run(()=>createProcurementRequest(rf),"Procurement request initiated. Step 2 — three quotations — is now open.");setRf({title:"",description:"",department:"",estimatedAmount:"",procurementMethod:"Request for Quotations",vendorId:""})}
 async function quotes(){await run(async()=>{if(files.some(x=>!x))throw new Error("Exactly three quotation PDFs are required.");for(let i=0;i<3;i++)await uploadProcurementQuotation(selected.id,files[i],i+1)},"Three quotations uploaded. PR registration is now open.");setFiles([null,null,null])}
 function printPO(r){const w=window.open("","_blank");if(!w)return;w.document.write("<html><head><title>IRPA Purchase Order</title><style>body{font-family:Arial;padding:40px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #333;padding:8px}</style></head><body><h1>IMPROVEMENT OF RANGELAND IN PASTORAL AREAS</h1><h2>PURCHASE ORDER</h2><p><b>PO Number:</b> "+(r.poNumber||"—")+" &nbsp; <b>PR Number:</b> "+(r.prNumber||"—")+"</p><p><b>Procurement Title:</b> "+r.title+"</p><p><b>Vendor:</b> "+r.vendorName+" ("+(r.vendorRegistrationNumber||"—")+")</p><table><tr><th>Description</th><th>Amount</th></tr><tr><td>"+r.title+"</td><td>"+(r.estimatedAmount||"—")+"</td></tr></table><p><b>Authorised By:</b> "+(r.authorizedByName||"—")+" — "+(r.authorizedByRole||"—")+"</p><p><b>Requester:</b> "+(r.requestedByName||"—")+"</p><script>window.onload=function(){window.print()}</script></body></html>");w.document.close()}
 return <div className="page">
 <section className="welcome-panel"><div><span className="eyebrow">PROCUREMENT CONTROL CENTRE</span><h1>Procurement Portal</h1><p>Locked workflow: initiation → three quotations → PR → Procurement Team review → Accounting Officer authorization → PO → delivery note → invoice → Finance.</p></div><div className="identity-card"><span>Access</span><strong>{team?"PROCUREMENT TEAM":approver?"AUTHORIZING OFFICER":"REQUESTER"}</strong></div></section>
 {message&&<div className="success-message action-feedback" role="status">{message}</div>}{error&&<div className="error-message action-feedback" role="alert">{error}</div>}
 <section className="dashboard-grid">{PROCUREMENT_STAGES.map(s=><div className="stat-card workflow-stage" key={s}><span>{s}</span><strong>{visible.filter(r=>r.status===s).length}</strong><small>Locked until the previous stage is completed.</small></div>)}</section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">STEP 1</span><h2>Vendor / Service Provider Registration</h2><p className="panel-description">All active members may register a vendor. Only the dedicated Procurement Team may approve it.</p></div></div><form onSubmit={submitVendor}><div className="form-grid"><Field label="Vendor / Service Provider Name" name="name" value={vf.name} onChange={e=>setVf({...vf,name:e.target.value})} required/><Field label="Goods / Service Category" name="serviceType" value={vf.serviceType} onChange={e=>setVf({...vf,serviceType:e.target.value})} required/><Field label="Registration Number" name="registrationNumber" value={vf.registrationNumber} onChange={e=>setVf({...vf,registrationNumber:e.target.value})}/><Field label="Tax Identification Number" name="taxNumber" value={vf.taxNumber} onChange={e=>setVf({...vf,taxNumber:e.target.value})}/><Field label="Contact Person" name="contactName" value={vf.contactName} onChange={e=>setVf({...vf,contactName:e.target.value})}/><Field label="Phone" name="phone" value={vf.phone} onChange={e=>setVf({...vf,phone:e.target.value})}/><Field label="Email" name="email" value={vf.email} onChange={e=>setVf({...vf,email:e.target.value})}/><Field label="Address" name="address" value={vf.address} onChange={e=>setVf({...vf,address:e.target.value})}/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving…":"Register Vendor / Service Provider"}</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">STEP 1</span><h2>Procurement Request</h2><p className="panel-description">Every active member can initiate. The vendor is selected from the registered vendor list; no free-text vendor is permitted.</p></div></div><form onSubmit={submitRequest}><div className="form-grid"><Field label="Procurement Title" name="title" value={rf.title} onChange={e=>setRf({...rf,title:e.target.value})} required/><Field label="Department / Unit" name="department" value={rf.department} onChange={e=>setRf({...rf,department:e.target.value})} required/><Field label="Estimated Amount" name="estimatedAmount" value={rf.estimatedAmount} onChange={e=>setRf({...rf,estimatedAmount:e.target.value})} type="number" required/><Field label="Procurement Method" name="procurementMethod" value={rf.procurementMethod} onChange={e=>setRf({...rf,procurementMethod:e.target.value})}><select value={rf.procurementMethod} onChange={e=>setRf({...rf,procurementMethod:e.target.value})}><option>Request for Quotations</option><option>Competitive Tender</option><option>Direct Procurement</option><option>Framework Contract</option></select></Field><Field label="Registered Vendor / Service Provider" name="vendorId" value={rf.vendorId} onChange={e=>setRf({...rf,vendorId:e.target.value})} required><select value={rf.vendorId} onChange={e=>setRf({...rf,vendorId:e.target.value})} required><option value="">Select registered vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name+" — "+(v.vendorRegistrationNumber||v.registrationNumber||"No registration no.")+" — "+v.status}</option>)}</select></Field><Field label="Request Description / Scope" name="description" value={rf.description} onChange={e=>setRf({...rf,description:e.target.value})} wide required/></div><div className="form-actions"><button disabled={busy}>{busy?"Saving…":"Initiate Procurement Request"}</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROLLED REGISTER</span><h2>Procurement Requests</h2><p className="panel-description">Only the requester and Procurement Team can operate the request. Each stage exposes only its permitted action.</p></div></div><div className="table-wrapper"><table><thead><tr><th>Procurement</th><th>Vendor</th><th>PR / PO</th><th>Stage</th><th>Control</th></tr></thead><tbody>{visible.length?visible.slice(0,100).map(r=><tr key={r.id}><td><strong>{r.title}</strong><div className="table-subtext">{r.requestedByName||r.requestedByEmail}</div></td><td>{r.vendorName}<div className="table-subtext">{r.vendorRegistrationNumber||"—"}</div></td><td>{r.prNumber||"—"} / {r.poNumber||"—"}</td><td><span className="status-badge">{r.status}</span></td><td><button type="button" onClick={()=>setSelected(r)}>Open Current Stage</button></td></tr>):<tr><td colSpan="5">No procurement requests.</td></tr>}</tbody></table></div></section>
 {selected&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">WORKFLOW GATE</span><h2>{selected.title}</h2><p className="panel-description">Current stage: <strong>{selected.status}</strong></p></div><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></div>
 <div className="detail-grid"><div><span>Vendor</span><strong>{selected.vendorName}</strong></div><div><span>Vendor Registration No.</span><strong>{selected.vendorRegistrationNumber||"—"}</strong></div><div><span>PR Number</span><strong>{selected.prNumber||"Not issued"}</strong></div><div><span>PO Number</span><strong>{selected.poNumber||"Not generated"}</strong></div><div><span>Quotations</span><strong>{selected.quotationCount||0} / 3</strong></div></div>
 {selected.status==="Quotations Required"&&selected.requestedByUid===uid&&<div className="panel"><h3>Step 2 — Upload exactly three quotations</h3><div className="form-grid">{[0,1,2].map(i=><label className="form-field" key={i}>Quotation {i+1}<input type="file" accept="application/pdf,.pdf" onChange={e=>{const n=[...files];n[i]=e.target.files?.[0]||null;setFiles(n)}} required/></label>)}</div><button type="button" onClick={quotes} disabled={busy}>{busy?"Uploading…":"Upload Three Quotations"}</button></div>}
 {selected.status==="PR Registration"&&team&&<div className="panel"><h3>Step 3 — PR Registration</h3><p>The system will issue the PR Number automatically. Manual PR numbers are not permitted.</p><button type="button" onClick={()=>run(()=>registerProcurementPR(selected.id),"PR Number issued. Procurement Team review is now open.")} disabled={busy}>Register PR & Issue PR Number</button></div>}
 {selected.status==="Procurement Review"&&team&&<div className="panel"><h3>Step 4A — Procurement Team Review</h3><p>Review the three quotations and the registered vendor before forwarding the request for authorization.</p><button type="button" onClick={()=>run(()=>reviewProcurementRequest(selected.id,"Approved"),"Procurement review approved. Accounting Officer authorization is now open.")} disabled={busy}>Approve Procurement Review</button><button type="button" className="secondary-button" onClick={()=>run(()=>reviewProcurementRequest(selected.id,"Rejected"),"Procurement request rejected.")} disabled={busy}>Reject</button></div>}
 {selected.status==="Pending Authorization"&&<div className="panel"><h3>Step 4B — Accounting Officer Authorization</h3><select value={selected.approverUid||""} onChange={e=>setSelected({...selected,approverUid:e.target.value})}><option value="">Select authorised officer</option>{directors.map(d=><option key={d.uid} value={d.uid}>{d.name||d.email} — {d.role}</option>)}</select><p className="panel-description">Eligible options include the Executive Director, Livestock Director, Internal Oversight Director and registered departmental directors.</p><button type="button" onClick={()=>run(()=>authorizeProcurementRequest(selected.id,selected.approverUid),"Procurement authorized. PO generation is now open.")} disabled={busy||!selected.approverUid}>Authorise & Approve Process</button></div>}
 {selected.status==="PO Generation"&&team&&<div className="panel"><h3>Step 4C — Purchase Order Generation</h3><div className="form-grid"><Field label="Procurement Title" name="t" value={selected.title} onChange={()=>{}}/><Field label="Vendor Registration Number" name="v" value={selected.vendorRegistrationNumber} onChange={()=>{}}/><Field label="Vendor / Service Provider Name" name="vn" value={selected.vendorName} onChange={()=>{}}/><Field label="Selected Quotation(s)" name="q" value="Quotation 1, Quotation 2, Quotation 3" onChange={()=>{}}/><Field label="PR Number" name="pr" value={selected.prNumber} onChange={()=>{}}/></div><p className="panel-description">All fields are read-only selections from the registered procurement request. No new title, vendor or PR entry is allowed.</p><button type="button" onClick={()=>run(()=>generateProcurementPO(selected.id),"PO generated. The requester can print it; delivery-note upload is now the next controlled stage.")} disabled={busy}>Generate PO</button></div>}
 {selected.status==="PO Generated"&&<div className="panel"><h3>Purchase Order</h3><p>PO Number: <strong>{selected.poNumber}</strong></p><button type="button" onClick={()=>printPO(selected)}>Print Purchase Order</button></div>}
 {selected.status==="Delivery Note Required"&&selected.requestedByUid===uid&&<div className="panel"><h3>Step 5 — Delivery Note</h3><input type="file" accept="application/pdf,.pdf" onChange={e=>setSelected({...selected,deliveryFile:e.target.files?.[0]})}/><button type="button" onClick={()=>run(()=>uploadProcurementEvidence(selected.id,"deliveryNote",selected.deliveryFile),"Delivery Note uploaded. Invoice upload is now open.")} disabled={busy||!selected.deliveryFile}>Upload Delivery Note</button></div>}
 {selected.status==="Invoice Required"&&selected.requestedByUid===uid&&<div className="panel"><h3>Step 6 — Invoice</h3><input type="file" accept="application/pdf,.pdf" onChange={e=>setSelected({...selected,invoiceFile:e.target.files?.[0]})}/><button type="button" onClick={()=>run(()=>uploadProcurementEvidence(selected.id,"invoice",selected.invoiceFile),"Invoice uploaded. Complete procurement evidence is ready for Finance.")} disabled={busy||!selected.invoiceFile}>Upload Invoice</button></div>}
 {selected.status==="Finance Handoff"&&team&&<div className="panel"><h3>Step 7 — Finance Handoff</h3><p>Request, vendor, three quotations, PR, PO, delivery note and invoice will be linked to the Finance Portfolio payment transaction.</p><button type="button" onClick={()=>run(()=>sendProcurementToFinance(selected.id),"Complete procurement evidence handed to Finance for payment processing.")} disabled={busy}>Send Complete Evidence to Finance</button></div>}
 </section>}
 <section className="panel"><div className="panel-header"><div><span className="eyebrow">VENDOR REVIEW</span><h2>Procurement Team Vendor Control</h2></div></div><div className="table-wrapper"><table><thead><tr><th>Vendor</th><th>Registration</th><th>Category</th><th>Status</th><th>Control</th></tr></thead><tbody>{vendors.map(v=><tr key={v.id}><td>{v.name}</td><td>{v.vendorRegistrationNumber||v.registrationNumber||"—"}</td><td>{v.serviceType||"—"}</td><td><span className="status-badge">{v.status}</span></td><td>{team&&v.status==="Pending Review"?<><button type="button" onClick={()=>run(()=>reviewProcurementRequest(v.id,"Approved","vendor"),"Vendor approved.")}>Approve</button><button type="button" className="secondary-button" onClick={()=>run(()=>reviewProcurementRequest(v.id,"Rejected","vendor"),"Vendor rejected.")}>Reject</button></>:<span className="muted">Controlled</span>}</td></tr>)}</tbody></table></div></section>
 </div>
}