import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,updateRecord,deleteRecord,COLLECTIONS,openVotingIssue}from"../firebase/data";
const STATUSES=["Draft","Submitted","Voting Open","Passed","Rejected","Final"];
const empty={meetingId:"",meetingReference:"",matterPresented:"",proposedResolution:"",mover:"",seconder:"",status:"Draft",votingRequired:false,votingStatus:"Not Required",votingResult:"Pending"};
export default function Resolutions(){
 const[rows,setRows]=useState([]),[meetings,setMeetings]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("All");
 async function load(){try{const[r,m]=await Promise.all([getRecords(COLLECTIONS.resolutions),getRecords(COLLECTIONS.meetings)]);setRows(r);setMeetings(m)}catch(e){setError(e.message||"Unable to load resolutions.")}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>rows.filter(r=>{const q=search.trim().toLowerCase();return(!q||[r.resolutionReference,r.meetingReference,r.matterPresented,r.proposedResolution].join(" ").toLowerCase().includes(q))&&(filter==="All"||r.status===filter)}),[rows,search,filter]);
 function change(e){const{name,value,type,checked}=e.target;setForm(v=>({...v,[name]:type==="checkbox"?checked:value}))}
 function create(){setEditing(null);setForm(empty);setError("");setMessage("")}
 function edit(r){setEditing(r);setForm({...empty,...r});setError("");setMessage("")}
 async function save(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{const m=meetings.find(x=>x.id===form.meetingId);if(!m)throw new Error("An originating meeting is required.");const data={...form,meetingReference:m.title};if(editing){if(editing.votingIssueId&&(form.meetingId!==editing.meetingId))throw new Error("A resolution already linked to voting cannot be moved to another meeting.");await updateRecord(COLLECTIONS.resolutions,editing.id,data)}else{const reference=`IRPA-RES-${new Date().getFullYear()}-${Date.now().toString().slice(-8)}`;await createRecord(COLLECTIONS.resolutions,{...data,resolutionReference:reference})}setMessage(editing?"Resolution updated successfully.":"Resolution created successfully.");setForm(empty);setEditing(null);await load()}catch(e){setError(e.message||"Unable to save resolution.")}finally{setBusy(false)}}
 async function startVote(r){setBusy(true);setError("");setMessage("");try{if(!r.votingRequired)throw new Error("This resolution is not marked as requiring a vote.");const issue=await openVotingIssue({meetingId:r.meetingId,meetingReference:r.meetingReference,resolutionId:r.id,resolutionReference:r.resolutionReference,votingReference:r.matterPresented||r.proposedResolution});if(r.votingIssueId!==issue.id||r.status!=="Voting Open")await updateRecord(COLLECTIONS.resolutions,r.id,{status:"Voting Open",votingStatus:"Open",votingIssueId:issue.id,votingResult:"Pending"});setMessage(issue.alreadyOpen?"Voting is already open for this resolution.":"Anonymous voting has been opened for this resolution.");await load()}catch(e){setError(e.message||"Unable to open voting.")}finally{setBusy(false)}}
 async function remove(r){if(!window.confirm("Delete this draft resolution?"))return;setBusy(true);try{await deleteRecord(COLLECTIONS.resolutions,r.id);await load()}catch(e){setError(e.message||"Unable to delete resolution.")}finally{setBusy(false)}}
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">IRPA GOVERNANCE</span><h1>Resolutions</h1><p>Meeting-originated resolutions form the controlled bridge between proceedings and anonymous voting.</p></div><button onClick={create}>+ New Resolution</button></section>{message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
 <section className="panel"><div className="panel-header"><div><h2>{editing?"Edit Resolution":"Create Resolution"}</h2><p className="panel-description">A resolution must originate from a meeting. Voting cannot cross meeting boundaries.</p></div></div><form onSubmit={save}><div className="form-grid"><div className="form-field"><label>Originating Meeting</label><select name="meetingId" value={form.meetingId} onChange={change} required><option value="">Select meeting...</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.title} — {m.date||""}</option>)}</select></div><div className="form-field"><label>Status</label><select name="status" value={form.status} onChange={change}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div className="form-field form-field-wide"><label>Matter Presented</label><textarea name="matterPresented" value={form.matterPresented} onChange={change} rows="3" required/></div><div className="form-field form-field-wide"><label>Proposed Resolution</label><textarea name="proposedResolution" value={form.proposedResolution} onChange={change} rows="4" required/></div><div className="form-field"><label>Mover</label><input name="mover" value={form.mover} onChange={change}/></div><div className="form-field"><label>Seconder</label><input name="seconder" value={form.seconder} onChange={change}/></div><label><input type="checkbox" name="votingRequired" checked={form.votingRequired} onChange={change}/> Voting Required</label></div><div className="form-actions"><button disabled={busy}>{busy?"Saving...":editing?"Save Resolution":"Create Resolution"}</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><h2>Resolution Register</h2><span>{visible.length} of {rows.length} record(s)</span></div></div><div className="form-grid"><div className="form-field form-field-wide"><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search issue, resolution or meeting..."/></div><div className="form-field"><label>Status</label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="table-wrapper"><table><thead><tr><th>Reference</th><th>Meeting</th><th>Matter / Resolution</th><th>Status</th><th>Voting</th><th>Record</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan="6">No resolutions found.</td></tr>:visible.map(r=><tr key={r.id}><td><strong>{r.resolutionReference||r.id}</strong></td><td>{r.meetingReference||r.meetingId}</td><td>{r.matterPresented||r.proposedResolution}</td><td><span className="status-badge">{r.status}</span>{r.votingRequired&&<div className="table-subtext">{r.votingStatus||"Required"}{r.votingResult&&r.votingResult!=="Pending"?` · ${r.votingResult}`:""}</div>}</td><td>{r.votingRequired&&r.status!=="Passed"&&r.status!=="Rejected"&&r.status!=="Final"?<button disabled={busy} onClick={()=>startVote(r)}>{r.votingIssueId?"Open / Return to Voting":"Open Anonymous Voting"}</button>:r.votingIssueId?`Completed · ${r.votingResult||r.status}`:"Not Required"}</td><td><div className="member-actions"><button onClick={()=>edit(r)}>Edit</button>{r.status==="Draft"&&!r.votingIssueId&&<button onClick={()=>remove(r)}>Delete</button>}</div></td></tr>)}</tbody></table></div></section></div>;
}
