import React,{useEffect,useMemo,useState}from"react";
import{createRecord,deleteRecord,getRecords,updateRecord,COLLECTIONS}from"../firebase/data";
const STATUSES=["Draft","Submitted","Voted","Passed","Rejected","Final"];
const empty={meetingId:"",meetingTitle:"",referenceNo:"",matter:"",proposal:"",mover:"",seconder:"",status:"Draft",notes:""};
function nextRef(rows){const year=new Date().getFullYear();const n=rows.filter(r=>String(r.referenceNo||"").startsWith(`IRPA-RES-${year}-`)).length+1;return`IRPA-RES-${year}-${String(n).padStart(4,"0")}`}
export default function Resolutions(){const[rows,setRows]=useState([]),[meetings,setMeetings]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[view,setView]=useState(null),[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){try{const[r,m]=await Promise.all([getRecords(COLLECTIONS.resolutions),getRecords(COLLECTIONS.meetings)]);setRows(r);setMeetings(m)}catch(e){setErr(e.message||"Unable to load resolutions.")}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>rows.filter(r=>{const q=search.toLowerCase().trim();return(!q||JSON.stringify(r).toLowerCase().includes(q))&&(filter==="All"||r.status===filter)}),[rows,search,filter]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 function selectMeeting(e){const m=meetings.find(x=>x.id===e.target.value);setForm(f=>({...f,meetingId:m?.id||"",meetingTitle:m?.title||""}))}
 function add(){setEdit(null);setView(null);setForm({...empty,referenceNo:nextRef(rows)});setMsg("");setErr("");window.scrollTo({top:0,behavior:"smooth"})}
 function editRow(r){setEdit(r);setView(null);setForm({...empty,...r});setMsg("");setErr("");window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e){e.preventDefault();setBusy(true);setErr("");try{if(edit)await updateRecord(COLLECTIONS.resolutions,edit.id,form);else await createRecord(COLLECTIONS.resolutions,{...form,referenceNo:form.referenceNo||nextRef(rows)});setMsg(edit?"Resolution updated successfully.":"Resolution created and linked to the meeting.");setEdit(null);setForm(empty);await load()}catch(x){setErr(x.message||"Unable to save resolution.")}finally{setBusy(false)}}
 async function remove(r){if(!confirm(`Delete resolution ${r.referenceNo||r.id}?`))return;setBusy(true);try{await deleteRecord(COLLECTIONS.resolutions,r.id);await load();setMsg("Resolution deleted.")}catch(x){setErr(x.message||"Unable to delete resolution.")}finally{setBusy(false)}}
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">IRPA GOVERNANCE ENGINE</span><h1>Resolutions</h1><p>Authoritative resolutions linked to meetings. Each resolution becomes the source record for voting and subsequent decisions.</p></div><button onClick={add}>+ New Resolution</button></section>{msg&&<div className="success-message action-feedback">{msg}</div>}{err&&<div className="error-message action-feedback">{err}</div>}
 <section className="dashboard-grid"><div className="stat-card"><span>Total</span><strong>{rows.length}</strong><small>Resolution register</small></div><div className="stat-card"><span>Draft</span><strong>{rows.filter(r=>r.status==="Draft").length}</strong><small>Awaiting submission</small></div><div className="stat-card"><span>Passed</span><strong>{rows.filter(r=>r.status==="Passed"||r.status==="Final").length}</strong><small>Approved governance outcomes</small></div><div className="stat-card"><span>Rejected</span><strong>{rows.filter(r=>r.status==="Rejected").length}</strong><small>Closed negative outcomes</small></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Resolution Workflow</h2><p className="panel-description">Meeting matter → proposed resolution → mover/seconder → voting → passed/rejected → final decision.</p></div></div><div className="form-actions"><span className="status-badge">Draft</span><span>→</span><span className="status-badge">Submitted</span><span>→</span><span className="status-badge">Voted</span><span>→</span><span className="status-badge">Passed / Rejected</span><span>→</span><span className="status-badge">Final</span></div></section>
 {(edit||form.referenceNo)&&<section className="panel"><div className="panel-header"><div><h2>{edit?`Edit ${edit.referenceNo}`:"Create Resolution"}</h2><p className="panel-description">The meeting link is mandatory because resolutions must originate from an institutional meeting record.</p></div><button className="secondary-button" onClick={()=>{setEdit(null);setForm(empty)}}>Close</button></div><form onSubmit={save}><div className="form-grid"><div className="form-field"><label>Resolution Reference</label><input name="referenceNo" value={form.referenceNo} onChange={change} required/></div><div className="form-field"><label>Source Meeting</label><select value={form.meetingId} onChange={selectMeeting} required><option value="">Select meeting</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.title} — {m.date||"No date"}</option>)}</select></div><div className="form-field form-field-wide"><label>Matter Presented</label><textarea name="matter" value={form.matter} onChange={change} rows="4" required/></div><div className="form-field form-field-wide"><label>Proposed Resolution</label><textarea name="proposal" value={form.proposal} onChange={change} rows="5" required/></div><div className="form-field"><label>Mover</label><input name="mover" value={form.mover} onChange={change} required/></div><div className="form-field"><label>Seconder</label><input name="seconder" value={form.seconder} onChange={change}/></div><div className="form-field"><label>Status</label><select name="status" value={form.status} onChange={change}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field form-field-wide"><label>Notes / Supporting Context</label><textarea name="notes" value={form.notes} onChange={change} rows="4"/></div></div><div className="form-actions"><button disabled={busy}>{busy?"Saving...":edit?"Save Resolution":"Create Resolution"}</button><button type="button" className="secondary-button" onClick={()=>{setEdit(null);setForm(empty)}}>Cancel</button></div></form></section>}
 <section className="panel"><div className="panel-header"><div><h2>Resolution Register</h2><span>{visible.length} of {rows.length} record(s)</span></div><button className="secondary-button" onClick={add}>+ New Resolution</button></div><div className="form-grid"><div className="form-field"><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Reference, meeting, matter, proposal..."/></div><div className="form-field"><label>Status</label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="table-wrapper"><table><thead><tr><th>Reference</th><th>Meeting</th><th>Matter / Proposal</th><th>Mover / Seconder</th><th>Status</th><th>Record</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan="6">No resolutions found.</td></tr>:visible.map(r=><tr key={r.id}><td><strong>{r.referenceNo||r.id}</strong></td><td>{r.meetingTitle||r.meetingId||"—"}</td><td>{String(r.proposal||r.matter||"").slice(0,140)}</td><td>{r.mover||"—"}{r.seconder?` / ${r.seconder}`:""}</td><td><span className="status-badge">{r.status||"Draft"}</span></td><td><div className="member-actions"><button onClick={()=>setView(r)}>View</button><button onClick={()=>editRow(r)}>Edit</button><button className="danger-button" onClick={()=>remove(r)}>Delete</button></div></td></tr>)}</tbody></table></div></section>{view&&<section className="panel"><div className="panel-header"><h2>Resolution Details</h2><button className="secondary-button" onClick={()=>setView(null)}>Close</button></div><div className="form-grid"><div className="form-field"><label>Reference</label><input readOnly value={view.referenceNo||""}/></div><div className="form-field"><label>Meeting</label><input readOnly value={view.meetingTitle||""}/></div><div className="form-field form-field-wide"><label>Proposed Resolution</label><textarea readOnly rows="7" value={view.proposal||""}/></div><div className="form-field form-field-wide"><label>Notes</label><textarea readOnly rows="5" value={view.notes||""}/></div></div></section>}</div>}
