import React,{useEffect,useMemo,useRef,useState}from"react";
import{getRecords}from"../firebase/data";
import{downloadDriveBytes}from"../firebase/signatureStorage";
import{auth}from"../firebase/config";
import{createCompletionCertificate,createSignatureEnvelope,getMySignatureProfile,getSignatureEnvelope,getSignatureEnvelopes,saveMySignatureProfile,signEnvelope}from"../firebase/signaturePlatform";
import*as pdfjsLib from"pdfjs-dist";
import pdfWorker from"pdfjs-dist/build/pdf.worker.min.mjs?url";

pdfjsLib.GlobalWorkerOptions.workerSrc=pdfWorker;

const TYPES=["Signature","Initials","Date","Name","Text","Number","Comment","Remarks","Checkbox"];
const COLORS={Signature:"#6d5dfc",Initials:"#7c3aed",Date:"#0891b2",Name:"#2563eb",Text:"#0f766e",Number:"#db2777",Comment:"#0284c7",Remarks:"#ea580c",Checkbox:"#b45309"};
const DEFAULTS={Signature:{width:28,height:10},Initials:{width:16,height:8},Date:{width:18,height:6},Name:{width:24,height:6},Text:{width:30,height:7},Number:{width:20,height:6},Comment:{width:34,height:10},Remarks:{width:34,height:10},Checkbox:{width:7,height:7}};

function makeField(type,i,uid,page=1){const d=DEFAULTS[type]||DEFAULTS.Text;return{fieldId:`FIELD-${Date.now()}-${i}`,type,page,x:8,y:12,width:d.width,height:d.height,required:type!=="Checkbox",signerUid:uid,responsibility:type==="Signature"?"Signature":type==="Initials"?"Initial":type==="Date"?"Date":type==="Comment"?"Comment":type==="Remarks"?"Remarks":type==="Number"?"Number Entry":type==="Checkbox"?"Approval":"Review",placeholder:type==="Comment"?"Enter comment":type==="Remarks"?"Enter remarks":type==="Number"?"Enter number":""};}

function clamp(v,min,max){return Math.max(min,Math.min(max,v));}

function FieldBox({field,selected,onSelect,onMove,onResize,onDelete,zoom,recipients}){
 const ref=useRef(null);const drag=useRef(null);const resize=useRef(null);
 const startMove=e=>{e.preventDefault();e.stopPropagation();onSelect(field.fieldId);const r=ref.current?.parentElement?.getBoundingClientRect();if(!r)return;drag.current={sx:e.clientX,sy:e.clientY,fx:field.x,fy:field.y,w:r.width,h:r.height};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end,{once:true});};
 const move=e=>{if(!drag.current)return;const d=drag.current;onMove(field.fieldId,clamp(d.fx+((e.clientX-d.sx)/d.w)*100,0,100-field.width),clamp(d.fy+((e.clientY-d.sy)/d.h)*100,0,100-field.height));};
 const end=()=>{drag.current=null;window.removeEventListener("pointermove",move);};
 const startResize=e=>{e.preventDefault();e.stopPropagation();onSelect(field.fieldId);const r=ref.current?.parentElement?.getBoundingClientRect();if(!r)return;resize.current={sx:e.clientX,sy:e.clientY,fw:field.width,fh:field.height,w:r.width,h:r.height};window.addEventListener("pointermove",resizeMove);window.addEventListener("pointerup",resizeEnd,{once:true});};
 const resizeMove=e=>{if(!resize.current)return;const d=resize.current;onResize(field.fieldId,clamp(d.fw+((e.clientX-d.sx)/d.w)*100,3,100-field.x),clamp(d.fh+((e.clientY-d.sy)/d.h)*100,3,100-field.y));};
 const resizeEnd=()=>{resize.current=null;window.removeEventListener("pointermove",resizeMove);};
 const c=COLORS[field.type]||COLORS.Text;
 return <div ref={ref} onPointerDown={startMove} onClick={e=>{e.stopPropagation();onSelect(field.fieldId)}} style={{position:"absolute",left:`${field.x}%`,top:`${field.y}%`,width:`${field.width}%`,height:`${field.height}%`,boxSizing:"border-box",border:`2px ${selected?"solid":"dashed"} ${c}`,background:`${c}18`,borderRadius:5,cursor:"move",zIndex:selected?30:20,userSelect:"none",minWidth:22,minHeight:18}}>
   <div style={{height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",fontSize:Math.max(9,11*zoom),fontWeight:700,color:c,overflow:"hidden",whiteSpace:"nowrap",padding:"2px 18px 2px 5px",boxSizing:"border-box"}}><span>{field.type}{field.required?" *":""}</span><small style={{fontSize:Math.max(7,8*zoom),opacity:.85,overflow:"hidden",textOverflow:"ellipsis",maxWidth:"100%"}}>{recipients.find(r=>r.uid===field.signerUid)?.name||"Unassigned"} · {field.responsibility||"Review"}</small></div>
   {selected&&<><button type="button" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onDelete(field.fieldId)}} style={{position:"absolute",right:2,top:2,width:18,height:18,border:0,borderRadius:4,background:"#111827",color:"#fff",fontSize:11,cursor:"pointer"}}>×</button><span onPointerDown={startResize} style={{position:"absolute",right:-4,bottom:-4,width:10,height:10,borderRadius:2,background:c,cursor:"nwse-resize"}}/></>}
 </div>;
}

function PDFDesigner({url,documentId,fields,setFields,recipients,selectedField,setSelectedField}){
 const canvasRef=useRef(null),pageHostRef=useRef(null);const[pdf,setPdf]=useState(null);const[pageNum,setPageNum]=useState(1);const[pageSize,setPageSize]=useState({width:800,height:1035});const[zoom,setZoom]=useState(1);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{let dead=false;(async()=>{if(!url){setPdf(null);return}setLoading(true);setError("");try{const source=url.startsWith("drive://")?{data:await downloadDriveBytes(url.slice("drive://".length),documentId)}:{url};const task=pdfjsLib.getDocument(source);const p=await task.promise;if(!dead){setPdf(p);setPageNum(1)}}catch(e){if(!dead)setError(e.message||"Unable to render PDF.")}finally{if(!dead)setLoading(false)}})();return()=>{dead=true};},[url]);
 useEffect(()=>{let dead=false;(async()=>{if(!pdf||!canvasRef.current)return;try{const page=await pdf.getPage(pageNum);const base=page.getViewport({scale:1});const scale=Math.max(.55,(760/base.width))*zoom;const viewport=page.getViewport({scale});const canvas=canvasRef.current;const output=window.devicePixelRatio||1;canvas.width=Math.floor(viewport.width*output);canvas.height=Math.floor(viewport.height*output);canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;setPageSize({width:viewport.width,height:viewport.height});const ctx=canvas.getContext("2d");ctx.setTransform(output,0,0,output,0,0);await page.render({canvasContext:ctx,viewport}).promise;if(!dead){} }catch(e){if(!dead)setError(e.message||"Unable to render page.")}})();return()=>{dead=true}},[pdf,pageNum,zoom]);
 const pageFields=fields.filter(f=>Number(f.page)===pageNum);
 const addAt=(type,x,y)=>{if(!recipients.length){setError("Add at least one signer before placing fields.");return}const f=makeField(type,fields.length,recipients[0].uid,pageNum);f.x=clamp(x-f.width/2,0,100-f.width);f.y=clamp(y-f.height/2,0,100-f.height);setFields([...fields,f]);setSelectedField(f.fieldId);};
 const drop=e=>{e.preventDefault();const type=e.dataTransfer.getData("fieldType");if(!type)return;const r=pageHostRef.current.getBoundingClientRect();addAt(type,((e.clientX-r.left)/r.width)*100,((e.clientY-r.top)/r.height)*100);};
 const update=(id,patch)=>setFields(fields.map(f=>f.fieldId===id?{...f,...patch}:f));
 return <div style={{display:"grid",gridTemplateColumns:"180px minmax(500px,1fr) 250px",gap:12,marginTop:18,minHeight:700}}>
  <aside style={{background:"rgba(15,23,42,.7)",border:"1px solid rgba(255,255,255,.09)",borderRadius:12,padding:12}}><strong style={{display:"block",marginBottom:12}}>FIELD PALETTE</strong>{TYPES.map(t=><div key={t} draggable onDragStart={e=>e.dataTransfer.setData("fieldType",t)} onClick={()=>{const r=pageHostRef.current?.getBoundingClientRect();if(r)addAt(t,50,20)}} style={{padding:"10px 9px",marginBottom:8,borderRadius:7,border:`1px solid ${COLORS[t]}80`,background:`${COLORS[t]}18`,color:"#fff",cursor:"grab",fontWeight:700}}>{t}<small style={{display:"block",opacity:.65,fontWeight:400}}>Drag onto page</small></div>)}<div className="panel" style={{marginTop:16,padding:10,background:"rgba(255,255,255,.03)"}}><strong style={{display:"block",marginBottom:8}}>ASSIGN RESPONSIBILITY</strong><p style={{fontSize:11,opacity:.7,margin:"0 0 10px"}}>Every highlighted field is assigned to an addressee. The assigned officer will see only their responsibilities when signing.</p>{fields.length===0?<div style={{fontSize:11,opacity:.6}}>Place a field on the document to assign it.</div>:fields.map((f,i)=><div key={f.fieldId} style={{padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><strong style={{fontSize:11}}>{i+1}. {f.type}</strong><label style={{display:"block",marginTop:5,fontSize:11}}>Addressee<select value={f.signerUid||""} onChange={e=>setFields(fields.map(x=>x.fieldId===f.fieldId?{...x,signerUid:e.target.value}:x))}><option value="">Select addressee</option>{recipients.map(r=><option key={r.uid} value={r.uid}>{r.name||r.email}</option>)}</select></label><label style={{display:"block",marginTop:5,fontSize:11}}>Responsibility<select value={f.responsibility||""} onChange={e=>setFields(fields.map(x=>x.fieldId===f.fieldId?{...x,responsibility:e.target.value}:x))}><option value="">Select responsibility</option><option>Signature</option><option>Initial</option><option>Review</option><option>Comment</option><option>Number Entry</option><option>Remarks</option><option>Date</option><option>Verification</option><option>Recommendation</option><option>Authorization</option><option>Approval</option><option>Final Authorization</option></select></label></div>)}</div><div style={{marginTop:16,fontSize:12,opacity:.7}}>Drag, move and resize fields directly on the rendered PDF page.</div></aside>
  <main style={{background:"#1e293b",borderRadius:12,padding:12,overflow:"auto",minHeight:680}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,marginBottom:12,position:"sticky",top:0,zIndex:50,background:"#1e293b",paddingBottom:8}}><div style={{display:"flex",gap:6}}><button type="button" className="text-button" disabled={!pdf||pageNum<=1} onClick={()=>setPageNum(p=>p-1)}>‹</button><span style={{padding:"8px 10px",fontSize:13}}>Page {pageNum} / {pdf?.numPages||0}</span><button type="button" className="text-button" disabled={!pdf||pageNum>=pdf.numPages} onClick={()=>setPageNum(p=>p+1)}>›</button></div><div style={{display:"flex",gap:6,alignItems:"center"}}><button type="button" className="text-button" onClick={()=>setZoom(z=>clamp(Number((z-.1).toFixed(2)),.6,1.8))}>−</button><span style={{fontSize:12}}>{Math.round(zoom*100)}%</span><button type="button" className="text-button" onClick={()=>setZoom(z=>clamp(Number((z+.1).toFixed(2)),.6,1.8))}>+</button></div></div>{loading&&<div className="muted">Rendering PDF…</div>}{error&&<div className="auth-message" style={{marginBottom:10}}>{error}</div>} {!url?<div className="muted" style={{padding:40,textAlign:"center"}}>Select a controlled PDF to open the visual designer.</div>:<div style={{display:"flex",justifyContent:"center",padding:8}}><div ref={pageHostRef} onDragOver={e=>e.preventDefault()} onDrop={drop} onPointerDown={()=>setSelectedField(null)} style={{position:"relative",width:pageSize.width,height:pageSize.height,background:"#fff",boxShadow:"0 8px 30px rgba(0,0,0,.35)",flex:"0 0 auto"}}><canvas ref={canvasRef} style={{position:"absolute",inset:0,pointerEvents:"none"}}/>{pageFields.map(f=><FieldBox key={f.fieldId} field={f} selected={selectedField===f.fieldId} onSelect={setSelectedField} onMove={(id,x,y)=>update(id,{x,y})} onResize={(id,width,height)=>update(id,{width,height})} onDelete={id=>{setFields(fields.filter(f=>f.fieldId!==id));setSelectedField(null)}} zoom={zoom} recipients={recipients}/>)}</div></div>}</main>
  <aside style={{background:"rgba(15,23,42,.7)",border:"1px solid rgba(255,255,255,.09)",borderRadius:12,padding:12}}><strong>FIELD PROPERTIES</strong>{!selectedField?<p className="muted" style={{fontSize:13,marginTop:16}}>Select a field on the PDF to edit its properties.</p>:(()=>{const f=fields.find(x=>x.fieldId===selectedField);if(!f)return null;return <div style={{marginTop:14}}><label>Type<select value={f.type} onChange={e=>update(f.fieldId,{type:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Assigned addressee<select value={f.signerUid||""} onChange={e=>update(f.fieldId,{signerUid:e.target.value})}><option value="">Assign addressee</option>{recipients.map(r=><option key={r.uid} value={r.uid}>{r.name||r.email} · {r.role||""}</option>)}</select></label><label>Responsibility<select value={f.responsibility||""} onChange={e=>update(f.fieldId,{responsibility:e.target.value})}><option value="">Select responsibility</option><option>Signature</option><option>Initial</option><option>Review</option><option>Comment</option><option>Number Entry</option><option>Remarks</option><option>Date</option><option>Verification</option><option>Recommendation</option><option>Authorization</option><option>Approval</option><option>Final Authorization</option></select></label><label>Page<input type="number" min="1" max={pdf?.numPages||1} value={f.page} onChange={e=>update(f.fieldId,{page:clamp(Number(e.target.value)||1,1,pdf?.numPages||1)})}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><label>X %<input type="number" min="0" max="100" step=".1" value={Number(f.x).toFixed(1)} onChange={e=>update(f.fieldId,{x:clamp(Number(e.target.value)||0,0,100-f.width)})}/></label><label>Y %<input type="number" min="0" max="100" step=".1" value={Number(f.y).toFixed(1)} onChange={e=>update(f.fieldId,{y:clamp(Number(e.target.value)||0,0,100-f.height)})}/></label><label>Width %<input type="number" min="3" max="100" step=".1" value={Number(f.width).toFixed(1)} onChange={e=>update(f.fieldId,{width:clamp(Number(e.target.value)||3,3,100-f.x)})}/></label><label>Height %<input type="number" min="3" max="100" step=".1" value={Number(f.height).toFixed(1)} onChange={e=>update(f.fieldId,{height:clamp(Number(e.target.value)||3,3,100-f.y)})}/></label></div><label style={{display:"flex",gap:8,alignItems:"center",marginTop:12}}><input type="checkbox" checked={!!f.required} onChange={e=>update(f.fieldId,{required:e.target.checked})}/> Required field</label><button type="button" className="text-button" style={{marginTop:14}} onClick={()=>{setFields(fields.filter(x=>x.fieldId!==f.fieldId));setSelectedField(null)}}>Delete field</button></div>})()}</aside>
 </div>;
}

export default function SignaturePlatform({signerOnly=false,signingEnvelopeId=null,initialDocument=null}){
 const[tab,setTab]=useState("Profile"),[profile,setProfile]=useState(null),[docs,setDocs]=useState([]),[envelopes,setEnvelopes]=useState([]),[members,setMembers]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[displayName,setDisplayName]=useState(""),[initials,setInitials]=useState(""),[signatureFile,setSignatureFile]=useState(null),[initialsFile,setInitialsFile]=useState(null);
 const[title,setTitle]=useState(""),[documentId,setDocumentId]=useState(""),[documentUrl,setDocumentUrl]=useState(""),[signingMode,setSigningMode]=useState("Sequential"),[selectedSigner,setSelectedSigner]=useState(""),[signerEmail,setSignerEmail]=useState(""),[signerRole,setSignerRole]=useState("Review"),[recipients,setRecipients]=useState([]),[fields,setFields]=useState([]),[selectedField,setSelectedField]=useState(null),[fieldValues,setFieldValues]=useState({}),[ownerSigningEnabled,setOwnerSigningEnabled]=useState(false);
 useEffect(()=>{(async()=>{
    try{
      if(signerOnly){
        if(!signingEnvelopeId)throw new Error("No signing invitation was supplied.");

        const [envelope, signerProfile] = await Promise.all([
          getSignatureEnvelope(signingEnvelopeId),
          getMySignatureProfile()
        ]);

        setEnvelopes([envelope]);
        setSelected(envelope);
        setProfile(signerProfile);
        setDisplayName(signerProfile?.displayName||"");
        setInitials(signerProfile?.initials||"");
        setTab("Sign Document");
        return;
      }

      const[p,d,e]=await Promise.all([
        getMySignatureProfile(),
        getRecords("documents"),
        getSignatureEnvelopes()
      ]);

      setProfile(p);
      setDocs(d);
      setEnvelopes(e);
      setDisplayName(p?.displayName||"");
      setInitials(p?.initials||"");

      const m=await getRecords("members");
      setMembers(m.filter(x=>x.status==="Active"));
    }catch(x){
      setMessage(x.message||"Unable to load Signature Platform.")
    }
  })()},[signerOnly,signingEnvelopeId]);
 useEffect(()=>{if(initialDocument?.id){setDocs(prev=>[initialDocument,...prev.filter(d=>d.id!==initialDocument.id)]);setDocumentId(initialDocument.id);setTab("Prepare Envelope");setMessage(`Document "${initialDocument.title||initialDocument.fileName||initialDocument.id}" is ready for selection and signing.`)}},[initialDocument]);
 const selectedDoc=useMemo(()=>docs.find(x=>x.id===documentId),[docs,documentId]);
 const documentOwner=useMemo(()=>({uid:auth.currentUser?.uid,name:auth.currentUser?.displayName||auth.currentUser?.email||"Document Owner",email:auth.currentUser?.email||"",role:"Document Owner",routingOrder:1,status:"Owner"}),[auth.currentUser?.uid,auth.currentUser?.displayName,auth.currentUser?.email]);
 const workflowRecipients=useMemo(()=>[documentOwner,...recipients.filter(r=>r.uid!==documentOwner.uid).map((r,i)=>({...r,routingOrder:signingMode==="Sequential"?i+2:r.routingOrder||1}))],[documentOwner,recipients,signingMode]);
 useEffect(()=>{if(selectedDoc){const link=String(selectedDoc.webViewLink||"");const driveId=selectedDoc.fileId||((link.match(/\/d\/([a-zA-Z0-9_-]+)/)||[])[1])||((link.match(/[?&]id=([a-zA-Z0-9_-]+)/)||[])[1])||"";const url=selectedDoc.fileUrl||selectedDoc.documentUrl||selectedDoc.storageUrl||selectedDoc.pdfUrl||(driveId?`drive://${driveId}`:"");setDocumentUrl(url)}else setDocumentUrl("")},[selectedDoc]);
 async function saveProfile(e){e.preventDefault();setBusy(true);setMessage("");try{if(!signatureFile)throw new Error("Choose the real handwritten signature image to save.");const p=await saveMySignatureProfile({signatureFile,initialsFile,displayName,initials});setProfile(p);setSignatureFile(null);setInitialsFile(null);e.target.reset();setMessage("Signature profile saved successfully.")}catch(x){setMessage(x.message||"Unable to save signature profile.")}finally{setBusy(false)}}
 function addSigner(){const email=String(signerEmail||"").trim().toLowerCase();const m=members.find(x=>x.uid===selectedSigner||String(x.email||"").trim().toLowerCase()===email);if(!m){setMessage("Select a registered officer or enter the email address of a registered IRPA officer.");return;}if(recipients.some(x=>x.uid===m.uid)){setMessage("This officer is already in the signer hierarchy.");return;}const role=signerRole||"Review";setRecipients([...recipients,{uid:m.uid,name:m.name||m.email,email:m.email||email,role,routingOrder:signingMode==="Sequential"?recipients.length+2:1,status:"Pending"}]);setSelectedSigner("");setSignerEmail("");setSignerRole("Review");setMessage(`${m.name||m.email} added as ${role}.`)}
 function removeSigner(uid){const removed=recipients.find(r=>r.uid===uid);setRecipients(recipients.filter(r=>r.uid!==uid));setFields(fields.map(f=>f.signerUid===uid?{...f,signerUid:""}:f));setMessage(`${removed?.name||"Officer"} removed. Reassign any fields previously assigned to this officer before saving the draft.`)}
 function moveSigner(uid,direction){const index=recipients.findIndex(r=>r.uid===uid);const next=index+direction;if(index<0||next<0||next>=recipients.length)return;const copy=[...recipients];[copy[index],copy[next]]=[copy[next],copy[index]];setRecipients(copy.map((r,i)=>({...r,routingOrder:signingMode==="Sequential"?i+2:r.routingOrder||1})));}
 async function createEnvelope(e){e.preventDefault();if(busy)return;setMessage("Create Draft Envelope clicked. Validating the assigned document and signer fields…");setBusy(true);try{if(!title.trim())throw new Error("Enter an envelope title before creating the draft.");if(!documentId)throw new Error("Select a controlled document before creating the draft envelope.");if(!documentUrl)throw new Error("The selected controlled document has no PDF file URL. Please select the uploaded PDF again.");const owner={...documentOwner,optionalSigning:!ownerSigningEnabled};const orderedRecipients=[owner,...recipients.filter(r=>r.uid!==owner.uid).map((r,i)=>({...r,routingOrder:signingMode==="Sequential"?i+2:r.routingOrder||1}))];const signerUids=new Set(orderedRecipients.map(r=>r.uid));if(fields.some(f=>!f.signerUid||!signerUids.has(f.signerUid)))throw new Error("Assign every field to the document owner or an assigned signer before creating the envelope.");const env=await createSignatureEnvelope({title,documentId,documentReference:selectedDoc?.reference||selectedDoc?.title||documentId,documentUrl,signingMode,recipients:orderedRecipients,fields});setEnvelopes(prev=>[env,...prev]);setTitle("");setDocumentId("");setDocumentUrl("");setRecipients([]);setFields([]);setSelectedField(null);setTab("Envelopes");setMessage(`${env.envelopeReference} created as Draft.`)}catch(x){console.error("IRPA Signature Platform: Create Draft Envelope failed",x);setMessage(`Create Draft Envelope failed: ${x.message||"Unable to create envelope."}`)}finally{setBusy(false)}}
 async function sign(){setBusy(true);setMessage("");try{if(!selected)throw new Error("Open a signing envelope first.");const uid=auth.currentUser?.uid;if(selected.signingMode==="Sequential"&&selected.currentSignerUid!==uid)throw new Error("This envelope is waiting for another signer.");const mine=(selected.fields||[]).filter(f=>f.signerUid===uid);if(mine.some(f=>f.required&&["Text","Name","Date","Number","Comment","Remarks"].includes(f.type)&&!fieldValues[f.fieldId]))throw new Error("Complete all required fields assigned to you.");const updated=await signEnvelope(selected,profile,fieldValues);setSelected(updated);setEnvelopes(envelopes.map(e=>e.id===updated.id?updated:e));setMessage(updated.status==="Completed"?"Document completed and signed successfully.":"Your signature was applied. The next signer can continue.")}catch(x){setMessage(x.message||"Unable to complete signing.")}finally{setBusy(false)}}
 async function certificate(){setBusy(true);try{const url=await createCompletionCertificate(selected);const updated={...selected,certificateUrl:url};setSelected(updated);setEnvelopes(envelopes.map(e=>e.id===updated.id?updated:e));setMessage("Certificate of Completion generated.")}catch(x){setMessage(x.message||"Unable to generate certificate.")}finally{setBusy(false)}}
 return <div className="page"><section className="welcome-panel"><div><span className="eyebrow">IRPA SIGNATURE PLATFORM</span><h1>{signerOnly?"Signing Invitation":"Electronic Signature Workspace"}</h1><p>{signerOnly?"Review the invited controlled document and complete only the signature fields assigned to you.":"Prepare, route, sign and evidence controlled IRPA documents."}</p></div><div className="identity-card"><span>Signature status</span><strong>{profile?.status||"Not configured"}</strong></div></section>
 {!signerOnly&&<div className="dashboard-grid" style={{marginBottom:18}}>{[["Signature Profile",profile?"Active":"Required"],["Envelopes",envelopes.length],["Controlled Documents",docs.length],["Pending Signing",envelopes.filter(e=>e.status!=="Completed").length]].map(([a,b])=><div className="stat-card" key={a}><span>{a}</span><strong>{b}</strong><small>Signature Platform</small></div>)}</div>}
 {!signerOnly&&<div style={{display:"flex",gap:8,marginBottom:18,flexWrap:"wrap"}}>{["Profile","Prepare Envelope","Envelopes","Sign Document"].map(x=><button key={x} className={tab===x?"secondary-button":"text-button"} onClick={()=>setTab(x)}>{x}</button>)}</div>}{message&&<div className="auth-message" style={{marginBottom:16}}>{message}</div>}
 {!signerOnly&&tab==="Profile"&&<section className="panel"><div className="panel-heading"><div><span className="eyebrow">SIGNATURE IDENTITY</span><h2>My Signature Profile</h2></div></div><p className="muted">Upload the actual handwritten signature and optional initials used during signing.</p><form onSubmit={saveProfile}><div className="form-grid"><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label><label>Initials<input value={initials} onChange={e=>setInitials(e.target.value)} placeholder="e.g. DEM"/></label><label>Signature image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setSignatureFile(e.target.files?.[0]||null)} required/></label><label>Initials image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setInitialsFile(e.target.files?.[0]||null)}/></label></div><div className="dashboard-grid" style={{marginTop:16}}>{profile?.signatureUrl&&<div className="stat-card"><span>Saved signature</span><div style={{background:"#fff",padding:12,borderRadius:8,marginTop:8}}><img src={profile.signatureUrl} alt="Signature" style={{maxWidth:"100%",maxHeight:100}}/></div><small>SHA-256: {profile.signatureSha256}</small></div>}{profile?.initialsUrl&&<div className="stat-card"><span>Saved initials</span><div style={{background:"#fff",padding:12,borderRadius:8,marginTop:8}}><img src={profile.initialsUrl} alt="Initials" style={{maxWidth:"100%",maxHeight:100}}/></div></div>}</div><button style={{marginTop:18}} disabled={busy}>{busy?"Saving...":profile?"Replace Signature":"Save Signature Profile"}</button></form></section>}
 {!signerOnly&&tab==="Prepare Envelope"&&<section className="panel"><div className="panel-heading"><div><span className="eyebrow">ENVELOPE PREPARATION</span><h2>Prepare, Assign & Route Document</h2><p className="muted">Upload/select the controlled PDF, place comments, numbers, remarks, dates and signatures, assign every field to an officer, and route the document in the required sequence.</p></div></div><form onSubmit={createEnvelope}><div className="form-grid"><label>Envelope title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Board Resolution Approval"/></label><label>Controlled document<select value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">Select document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.reference||d.title||d.id}</option>)}</select></label><label>Signing route<select value={signingMode} onChange={e=>setSigningMode(e.target.value)}><option>Sequential</option><option>Parallel</option><option>Mixed</option></select></label></div>
 <div className="panel" style={{marginTop:18,border:"1px solid rgba(109,93,252,.35)"}}><h3>Signer Hierarchy</h3><p className="muted" style={{marginTop:4}}>The document owner controls the workflow. Add each signing officer as a separate level. Define the officer by email and assign the purpose of their action. Add as many levels as required.</p><div className="form-grid"><label>1. Add signer / officer<select value={selectedSigner} onChange={e=>{setSelectedSigner(e.target.value);const m=members.find(x=>x.uid===e.target.value);setSignerEmail(m?.email||"")}}><option value="">Select registered officer</option>{members.filter(m=>m.uid!==documentOwner.uid&&!recipients.some(r=>r.uid===m.uid)).map(m=><option key={m.uid} value={m.uid}>{m.name||m.email}</option>)}</select></label><label>Signer email address<input type="email" value={signerEmail} onChange={e=>setSignerEmail(e.target.value)} placeholder="officer@irpa.or.tz"/></label><label>Role / action<select value={signerRole} onChange={e=>setSignerRole(e.target.value)}><option>Review</option><option>Authorization</option><option>Approval</option><option>Verification</option><option>Recommendation</option><option>Comment</option><option>Signature</option><option>Final Authorization</option><option>Other</option></select></label></div><button type="button" className="secondary-button" onClick={addSigner} disabled={!selectedSigner&&!signerEmail}>Add signer / next level</button><div style={{marginTop:16}}><strong>Workflow ladder</strong>{recipients.length===0?<p className="muted">No officers added yet. Add Level 2, Level 3, Level 4 and as many additional levels as required.</p>:recipients.map((r,i)=><div key={r.uid} style={{display:"grid",gridTemplateColumns:"44px minmax(0,1fr) auto",gap:10,alignItems:"center",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><strong>Level {i+2}</strong><span><strong>{r.name}</strong><small style={{display:"block"}}>{r.email} · {r.role}</small></span><span style={{display:"flex",gap:4}}><button type="button" className="text-button" onClick={()=>moveSigner(r.uid,-1)} disabled={i===0}>↑</button><button type="button" className="text-button" onClick={()=>moveSigner(r.uid,1)} disabled={i===recipients.length-1}>↓</button><button type="button" className="text-button" onClick={()=>removeSigner(r.uid)}>Remove</button></span></div>)}</div></div>
 <div className="panel" style={{marginTop:18}}><h3>Document Workflow & Signer Hierarchy</h3><p className="muted" style={{marginTop:4}}>Assign each field to the document owner or an officer. The owner can be included as an optional signing step; if optional, the workflow proceeds to the first assigned officer without requiring the owner to sign.</p><div style={{padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><strong>1. {documentOwner.name}</strong><small style={{display:"block"}}>{documentOwner.email} · Document Owner</small><label style={{display:"flex",gap:8,alignItems:"center",marginTop:8}}><input type="checkbox" checked={ownerSigningEnabled} onChange={e=>setOwnerSigningEnabled(e.target.checked)}/> Owner signing is optional</label></div>{recipients.length===0?<p className="muted" style={{marginTop:10}}>Add the responsible officers who must sign or complete this document.</p>:recipients.map((r,i)=><div key={r.uid} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"9px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><span><strong>{signingMode==="Sequential"?`${i+2}. `:""}{r.name}</strong><small style={{display:"block"}}>{r.email} · {r.role}</small></span><button type="button" className="text-button" onClick={()=>removeSigner(r.uid)}>Remove officer</button></div>)}</div>
 <div className="panel" style={{marginTop:18,border:"1px solid rgba(109,93,252,.35)"}}><h3>Field Assignment</h3><p className="muted" style={{marginTop:4}}>When you place a Signature, Initials, Date, Number, Comment or Remarks field, select the responsible person in <strong>FIELD PROPERTIES → Signer</strong>. This assignment controls who receives the task and the signing sequence.</p></div>
 <PDFDesigner url={documentUrl} documentId={documentId} fields={fields} setFields={setFields} recipients={workflowRecipients} selectedField={selectedField} setSelectedField={setSelectedField}/>
 <button type="submit" style={{marginTop:18}} disabled={busy} aria-busy={busy?"true":"false"} onClick={()=>{if(!busy)setMessage("Create Draft Envelope clicked. Validating…")}}>{busy?"Creating Draft Envelope…":"Create Draft Envelope"}</button></form></section>}
 {!signerOnly&&tab==="Envelopes"&&<section className="panel"><div className="panel-heading"><div><span className="eyebrow">ENVELOPE REGISTER</span><h2>Signing Transactions</h2></div></div>{envelopes.length===0?<p className="muted">No signing envelopes yet.</p>:envelopes.map(e=><article key={e.id} className="stat-card" style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><span>{e.envelopeReference}</span><h3 style={{margin:"5px 0"}}>{e.title}</h3><small>{e.documentReference} · {e.signingMode} · {e.recipients?.length||0} signer(s)</small></div><div><strong>{e.status}</strong><br/><button className="text-button" onClick={()=>{setSelected(e);setTab("Sign Document")}}>Open</button></div></div></article>)}</section>}
 {tab==="Sign Document"&&<section className="panel">{!selected?<><h2>Signing Ceremony</h2><p className="muted">This signing invitation could not be loaded.</p></>:<><div className="panel-heading"><div><span className="eyebrow">SIGNING CEREMONY</span><h2>{selected.title}</h2><p>{selected.envelopeReference} · {selected.status}</p></div></div>{selected.documentUrl&&<iframe title="Signing document" src={selected.signedDocumentUrl||selected.documentUrl} style={{width:"100%",height:620,border:"1px solid rgba(255,255,255,.12)",borderRadius:10}}/>}<div className="panel" style={{marginTop:18}}><h3>Fields assigned to you</h3>{(selected.fields||[]).filter(f=>f.signerUid===auth.currentUser?.uid).map(f=><label key={f.fieldId} style={{display:"block",marginTop:10}}>{f.type}{f.required?" *":""}{f.type==="Signature"||f.type==="Initials"?<div className="stat-card" style={{marginTop:5}}>{f.type} will use your saved Signature Profile.</div>:<input value={fieldValues[f.fieldId]||""} onChange={e=>setFieldValues({...fieldValues,[f.fieldId]:e.target.value})} placeholder={f.placeholder||`Enter ${f.type.toLowerCase()}`} type={f.type==="Number"?"number":"text"}/>}</label>)}<div style={{marginTop:18,display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={sign} disabled={busy||selected.status==="Completed"}>{busy?"Processing...":selected.status==="Completed"?"Completed":"Adopt Signature & Sign"}</button>{selected.status==="Completed"&&<button className="secondary-button" onClick={certificate} disabled={busy}>Generate Certificate of Completion</button>}{selected.signedDocumentUrl&&<a className="secondary-button" href={selected.signedDocumentUrl} target="_blank" rel="noreferrer">Open Signed PDF</a>}{selected.certificateUrl&&<a className="secondary-button" href={selected.certificateUrl} target="_blank" rel="noreferrer">Open Certificate</a>}</div></div></>}</section>}
 </div>;
}
