import React,{useEffect,useMemo,useState}from"react";
import{getRecords,getRecord,COLLECTIONS,openVotingIssue,castAnonymousVote,hasVotedOnIssue,closeVotingIssue}from"../firebase/data";
import{auth}from"../firebase/config";
const FILTERS={outcome:["All","For","Against","Abstain"],result:["All","Passed","Rejected","Pending"],status:["All","Locked"],};
function formatDate(v){if(!v)return"—";try{const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}catch{return"—"}}
export default function Voting(){
 const[issues,setIssues]=useState([]),[votes,setVotes]=useState([]),[meetings,setMeetings]=useState([]),[search,setSearch]=useState(""),[outcome,setOutcome]=useState("All"),[result,setResult]=useState("All"),[year,setYear]=useState("All"),[view,setView]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[form,setForm]=useState({meetingId:"",votingReference:"",resolutionReference:""}),[voted,setVoted]=useState({});
 async function load(){try{setError("");const[is,vs,ms]=await Promise.all([getRecords(COLLECTIONS.votingIssues),getRecords(COLLECTIONS.votes),getRecords(COLLECTIONS.meetings)]);setIssues(is);setVotes(vs);setMeetings(ms);const state={};for(const i of is.filter(x=>x.status==="Open"))state[i.id]=await hasVotedOnIssue(i.id);setVoted(state)}catch(e){setError(e.message||"Unable to load voting records.")}}
 useEffect(()=>{const run=async()=>{const u=auth.currentUser;if(u){const p=await getRecord(COLLECTIONS.adminProfiles,u.uid);setAdmin(p?.active===true)}await load()};run()},[]);
 const years=useMemo(()=>["All",...new Set(votes.map(r=>{const d=r.votedAt?.toDate?r.votedAt.toDate():new Date(r.votedAt||r.createdAt);return Number.isNaN(d.getTime())?null:d.getFullYear()}).filter(Boolean).sort((a,b)=>b-a))],[votes]);
 const filtered=useMemo(()=>votes.filter(r=>{const q=search.trim().toLowerCase();const blob=[r.votingReference,r.meetingReference,r.resolutionReference,r.result,r.outcome].join(" ").toLowerCase();const d=r.votedAt?.toDate?r.votedAt.toDate():new Date(r.votedAt||r.createdAt);return(!q||blob.includes(q))&&(outcome==="All"||r.outcome===outcome)&&(result==="All"||r.result===result)&&(year==="All"||d.getFullYear()===Number(year))}),[votes,search,outcome,result,year]);
 const metrics=useMemo(()=>({total:votes.length,for:votes.filter(x=>x.outcome==="For").length,against:votes.filter(x=>x.outcome==="Against").length,abstain:votes.filter(x=>x.outcome==="Abstain").length,open:issues.filter(x=>x.status==="Open").length}),[votes,issues]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function openIssue(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{const m=meetings.find(x=>x.id===form.meetingId);if(!m)throw new Error("Select the originating meeting.");const issue=await openVotingIssue({meetingId:m.id,meetingReference:m.title,resolutionReference:form.resolutionReference||null,votingReference:form.votingReference});setForm({meetingId:"",votingReference:"",resolutionReference:""});setMessage(issue.alreadyOpen?"This voting issue is already open. No duplicate voting process was created.":"Voting has been opened for this meeting issue.");await load()}catch(e){setError(e.message||"Unable to open voting.")}finally{setBusy(false)}}
 async function vote(issue,outcomeValue){if(voted[issue.id]){setError("You have already voted on this issue. Duplicate voting is not permitted.");return}if(!window.confirm(`Cast your anonymous vote: ${outcomeValue}? You cannot change or cast another vote on this issue.`))return;setBusy(true);setError("");setMessage("");try{await castAnonymousVote({votingIssueId:issue.id,outcome:outcomeValue});setVoted(v=>({...v,[issue.id]:true}));setMessage("Your anonymous vote has been recorded and locked. You cannot vote again on this issue.");await load()}catch(e){setError(e.message||"Vote could not be recorded.")}finally{setBusy(false)}}
 function tally(issue){const rows=votes.filter(v=>v.votingIssueId===issue.id);const f=rows.filter(v=>v.outcome==="For").length,a=rows.filter(v=>v.outcome==="Against").length,s=rows.filter(v=>v.outcome==="Abstain").length;return{f,a,s,total:rows.length}}
 async function closeIssue(issue){const t=tally(issue);const r=t.f>t.a?"Passed":t.a>t.f?"Rejected":"Pending";if(!window.confirm(`Close voting for "${issue.votingReference}"? Current tally: For ${t.f}, Against ${t.a}, Abstain ${t.s}. Result: ${r}.`))return;setBusy(true);try{await closeVotingIssue(issue.id,r);setMessage(`Voting closed. Result: ${r}.`);await load()}catch(e){setError(e.message||"Unable to close voting.")}finally{setBusy(false)}}
 return <div className="page">
  <section className="welcome-panel"><div><span className="eyebrow">IRPA GOVERNANCE VOTING</span><h1>Voting Process & Records</h1><p>Meeting-linked anonymous voting. Each eligible member may cast exactly one vote against each voting issue. Completed ballots are immutable.</p></div></section>
  {message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}
  <section className="dashboard-grid"><div className="stat-card"><span>Open Voting Issues</span><strong>{metrics.open}</strong><small>Awaiting votes</small></div><div className="stat-card"><span>Total Votes Cast</span><strong>{metrics.total}</strong><small>Immutable register</small></div><div className="stat-card"><span>For</span><strong>{metrics.for}</strong><small>Anonymous ballots</small></div><div className="stat-card"><span>Against</span><strong>{metrics.against}</strong><small>Anonymous ballots</small></div></section>
  {admin&&<section className="panel"><div className="panel-header"><div><h2>Open Voting from Meeting</h2><p className="panel-description">The voting origin must be the actual issue requiring voting action. Opening the same issue again is blocked.</p></div></div><form onSubmit={openIssue}><div className="form-grid"><div className="form-field"><label>Originating Meeting</label><select name="meetingId" value={form.meetingId} onChange={change} required><option value="">Select meeting...</option>{meetings.map(m=><option value={m.id} key={m.id}>{m.title} — {m.date||"No date"}</option>)}</select></div><div className="form-field"><label>Resolution Reference</label><input name="resolutionReference" value={form.resolutionReference} onChange={change} placeholder="Optional resolution reference"/></div><div className="form-field form-field-wide"><label>Voting Origin / Issue Requiring Voting Action</label><textarea name="votingReference" value={form.votingReference} onChange={change} rows="3" placeholder="Enter the exact matter from the meeting proceedings that requires a vote..." required/></div></div><button disabled={busy}>{busy?"Opening...":"Open Anonymous Voting"}</button></form></section>}
  <section className="panel"><div className="panel-header"><div><h2>Active Voting Issues</h2><span>{issues.filter(x=>x.status==="Open").length} open issue(s)</span></div></div>{issues.filter(x=>x.status==="Open").length===0?<p className="panel-description">No voting issue is currently open.</p>:<div className="dashboard-grid">{issues.filter(x=>x.status==="Open").map(issue=>{const t=tally(issue);return <div className="panel" key={issue.id}><span className="eyebrow">ANONYMOUS BALLOT</span><h3>{issue.votingReference}</h3><p><strong>Meeting:</strong> {issue.meetingReference||issue.meetingId}</p>{issue.resolutionReference&&<p><strong>Resolution:</strong> {issue.resolutionReference}</p>}<p><strong>Current ballots:</strong> {t.total} · For {t.f} · Against {t.a} · Abstain {t.s}</p>{voted[issue.id]?<div className="success-message">You have voted on this issue. Your ballot is locked.</div>:<div className="form-actions"><button disabled={busy} onClick={()=>vote(issue,"For")}>For</button><button disabled={busy} className="secondary-button" onClick={()=>vote(issue,"Against")}>Against</button><button disabled={busy} className="secondary-button" onClick={()=>vote(issue,"Abstain")}>Abstain</button></div>}{admin&&<button className="secondary-button" disabled={busy} onClick={()=>closeIssue(issue)}>Close & Calculate Result</button>}</div>})}</div>}</section>
  <section className="panel"><div className="panel-header"><div><h2>Historical Voting Register</h2><span>{filtered.length} of {votes.length} voting record(s)</span></div></div><div className="form-grid"><div className="form-field form-field-wide"><label>Search Voting Origin / Issue</label><input value={search}onChange={e=>setSearch(e.target.value)}placeholder="Search the issue, meeting or resolution..."/></div><div className="form-field"><label>Vote Outcome</label><select value={outcome}onChange={e=>setOutcome(e.target.value)}>{FILTERS.outcome.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Result</label><select value={result}onChange={e=>setResult(e.target.value)}>{FILTERS.result.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Year</label><select value={year}onChange={e=>setYear(e.target.value)}>{years.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="table-wrapper"><table><thead><tr><th>Voting Origin / Issue</th><th>Meeting</th><th>Resolution</th><th>Vote</th><th>Result</th><th>Voted</th><th>Record</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="7">No voting records match the current filters.</td></tr>:filtered.map(r=><tr key={r.id}><td><strong>{r.votingReference||"—"}</strong><div className="table-subtext">Record: {r.voteReference||r.id}</div></td><td>{r.meetingReference||r.meetingId||"—"}</td><td>{r.resolutionReference||r.resolutionId||"—"}</td><td><span className="status-badge">{r.outcome||"—"}</span></td><td>{r.result||"Pending"}</td><td>{formatDate(r.votedAt||r.createdAt)}</td><td><button type="button" onClick={()=>setView(r)}>View</button></td></tr>)}</tbody></table></div></section>
  {view&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">IMMUTABLE VOTING RECORD</span><h2>{view.votingReference||"Voting Record"}</h2><p className="panel-description">Voter identity is not stored in the ballot record.</p></div><button className="secondary-button" onClick={()=>setView(null)}>Close</button></div><div className="form-grid"><div className="form-field"><label>Vote Record</label><input value={view.voteReference||view.id}readOnly/></div><div className="form-field"><label>Meeting</label><input value={view.meetingReference||view.meetingId||"—"}readOnly/></div><div className="form-field"><label>Resolution</label><input value={view.resolutionReference||view.resolutionId||"—"}readOnly/></div><div className="form-field"><label>Vote</label><input value={view.outcome||"—"}readOnly/></div><div className="form-field"><label>Result</label><input value={view.result||"Pending"}readOnly/></div><div className="form-field"><label>Status</label><input value={view.status||"Locked"}readOnly/></div><div className="form-field form-field-wide"><label>Voting Origin — Issue Requiring Voting Action</label><textarea value={view.votingReference||"—"}readOnly rows="4"/></div></div></section>}
 </div>}
