import {VersionConflict} from "./adapters.mjs";import {archivePath,parseArchiveSelection,signerCopyPath} from "./archives.mjs";import {MAX_SIGNERS,buildSignedPdf,validateSignatureInput} from "./pdf.mjs";import {HttpError,ID_RE,canonicalJson,cleanSegment,cleanText,randomHex,safeEqual,sha256Hex,validateEmail,validateName} from "./util.mjs";
export async function chainEvents(events,e){const body={...e,prevHash:events.length?events.at(-1).hash:"GENESIS"};return[...events,{...body,hash:await sha256Hex(canonicalJson(body))}]}
export async function verifyChain(events){let p="GENESIS";for(const e of events){const {hash,...b}=e;if(b.prevHash!==p||await sha256Hex(canonicalJson(b))!==hash)return false;p=hash}return true}
async function mutate(ctx,id,fn){for(let i=0;i<5;i++){const c=await ctx.meta.get("envelopes",id);if(!c)throw new HttpError(404,"Envelope not found.");const {patch,result}=await fn(c);if(!patch)return result;try{await ctx.meta.update("envelopes",id,patch,{ifVersion:c._v});return result}catch(e){if(!(e instanceof VersionConflict))throw e}}throw new HttpError(409,"Please retry.")}
function tokenParts(t){const p=String(t||"").split(".");if(p.length!==3||!ID_RE.test(p[0])||!/^S\d{1,2}$/.test(p[1])||!/^[0-9a-f]{64}$/.test(p[2]))throw new HttpError(401,"Invalid signing link.");return p}
async function load(ctx,t){const[eid,sid,secret]=tokenParts(t),e=await ctx.meta.get("envelopes",eid),s=e?.signers.find(x=>x.id===sid);if(!e||!s)throw new HttpError(401,"Invalid signing link.");if(!safeEqual(await sha256Hex(secret),s.tokenHash))throw new HttpError(403,"This signing link is not valid.");return{env:e,signer:s}}
function active(ctx,e){if(["Voided","Declined"].includes(e.status))throw new HttpError(403,"This envelope is no longer active.");if(ctx.now()>new Date(e.expiresAt))throw new HttpError(403,"This signing link has expired.")}
const can=(e,s)=>s.status==="Pending"&&e.signers.every(x=>x.order>=s.order||x.status==="Signed");
export function canAuthenticatedSignerAccess(signer,user){
  if(!signer?.uid) return true;
  return Boolean(user?.uid)&&user.uid===signer.uid;
}
function assertSignerAuthentication(signer,user){
  if(!canAuthenticatedSignerAccess(signer,user)) throw new HttpError(403,"Sign in as the invited signer to continue.");
}
async function original(ctx,e){const d=await ctx.meta.get("documents",e.documentId),b=d&&await ctx.storage.get(d.primaryStorageId);if(!b||await sha256Hex(b)!==e.documentHash)throw new HttpError(409,"The document failed its integrity check.");return{doc:d,bytes:b}}
export async function createEnvelope(ctx,user,body){if(!ctx.sendInvitation&&!ctx.allowReturnTokens)throw new HttpError(500,"Invitation transport is not configured.");const doc=ID_RE.test(String(body?.documentId||""))&&await ctx.meta.get("documents",body.documentId);if(!doc||doc.status!=="Stored"||(doc.ownerUid!==user.uid&&!user.isAdmin))throw new HttpError(403,"You are not authorized for this document.");const archives=parseArchiveSelection(body.archives),input=body.signers;if(!Array.isArray(input)||input.length<1||input.length>MAX_SIGNERS)throw new HttpError(400,`Provide between 1 and ${MAX_SIGNERS} signers.`);if(!await ctx.storage.get(doc.primaryStorageId))throw new HttpError(409,"The stored document failed its integrity check.");const id=`ENV-${randomHex(8)}`,seen=new Set(),signers=[],secrets=[];for(let i=0;i<input.length;i++){const s=input[i],email=validateEmail(s?.email);if(seen.has(email.toLowerCase()))throw new HttpError(400,"Duplicate signer email.");seen.add(email.toLowerCase());const secret=randomHex(32);secrets.push(secret);signers.push({id:`S${i+1}`,email,name:validateName(s?.name),order:Number.isInteger(s?.order)&&s.order>0?s.order:i+1,uid:s?.uid?cleanSegment(s.uid,128):null,status:"Pending",tokenHash:await sha256Hex(secret),invitation:"Pending"})}const e={id,documentId:doc.id,documentHash:doc.hash,title:doc.title,fileName:doc.fileName,classification:doc.classification,createdBy:user.uid,status:"Sent",signers,archiveTargets:archives,createdAt:ctx.now().toISOString(),expiresAt:new Date(ctx.now().getTime()+ctx.config.ttlDays*86400000).toISOString(),events:[],completion:null};e.events=await chainEvents([],{type:"envelope.created",at:e.createdAt,actor:user.uid,documentHash:doc.hash,signerCount:signers.length});await ctx.meta.create("envelopes",id,e);for(let i=0;i<signers.length;i++){const token=`${id}.${signers[i].id}.${secrets[i]}`;if(ctx.sendInvitation){try{await ctx.sendInvitation({to:signers[i].email,name:signers[i].name,link:`${ctx.config.appUrl}/sign?token=${encodeURIComponent(token)}`})}catch(err){signers[i].invitation="Failed";ctx.logger.error("ENVELOPE_INVITATION_FAILED",{envelopeId:id,signerId:signers[i].id,message:String(err?.message||err).slice(0,200)})}}else signers[i].invitation="Sent"}await mutate(ctx,id,async cur=>({patch:{signers:cur.signers,events:await chainEvents(cur.events,{type:"invitations.updated",at:ctx.now().toISOString()})}}));return{ok:true,envelopeId:id,status:"Sent",invitations:signers.map((s,i)=>({signerId:s.id,email:s.email,status:s.invitation})),...(ctx.allowReturnTokens?{tokens:secrets.map((s,i)=>`${id}.S${i+1}.${s}`)}:{})}}
export async function openSigning(ctx,token,user=null){const{env,signer}=await load(ctx,token);active(ctx,env);assertSignerAuthentication(signer,user);return{ok:true,envelopeId:env.id,documentId:env.documentId,title:env.title,documentHash:env.documentHash,status:env.status,signer:{id:signer.id,name:signer.name,email:signer.email,status:signer.status,authenticated:!!signer.uid},canSign:can(env,signer)}}
export async function getSigningPdf(ctx,token,user=null){const{env,signer}=await load(ctx,token);assertSignerAuthentication(signer,user);if(env.status==="Completed"){const b=await ctx.storage.get(env.completion.primaryStorageId);if(!b||await sha256Hex(b)!==env.completion.finalHash)throw new HttpError(500,"Integrity check failed.");return{bytes:b,fileName:env.completion.fileName,hash:env.completion.finalHash}}active(ctx,env);const x=await original(ctx,env);return{bytes:x.bytes,fileName:env.fileName,hash:env.documentHash}}
export async function sign(ctx,{token,signature,consent,ip,userAgent,user}){if(consent!==true)throw new HttpError(400,"Consent to sign electronically is required.");const sig=await validateSignatureInput(signature),loaded=await load(ctx,token),e0=loaded.env,s0=loaded.signer;if(s0.status==="Signed")return{ok:true,idempotent:true,status:e0.status,completed:e0.status==="Completed"};active(ctx,e0);assertSignerAuthentication(s0,user);if(!can(e0,s0))throw new HttpError(409,"It is not yet your turn to sign.");await original(ctx,e0);const out=await mutate(ctx,e0.id,async cur=>{const s=cur.signers.find(x=>x.id===s0.id);if(s.status==="Signed")return{patch:null,result:{idempotent:true,status:cur.status}};if(!can(cur,s))throw new HttpError(409,"It is not yet your turn to sign.");const at=ctx.now().toISOString();s.status="Signed";s.signedAt=at;s.signatureType=sig.type;s.signatureValue=sig.value;s.ip=ip||null;s.userAgent=cleanText(userAgent||"",200)||null;const last=cur.signers.every(x=>x.status==="Signed");return{patch:{signers:cur.signers,status:last?"Completing":"InProgress",events:await chainEvents(cur.events,{type:"signer.signed",signerId:s.id,at,ip:ip||null,signatureType:sig.type,signatureHash:await sha256Hex(sig.value)})},result:{idempotent:false,winner:last,status:last?"Completing":"InProgress"}}});if(out.idempotent)return{ok:true,idempotent:true,status:out.status,completed:out.status==="Completed"};if(!out.winner)return{ok:true,status:"InProgress",completed:false};const done=await finalizeEnvelope(ctx,e0.id);return done.completed?{ok:true,status:"Completed",completed:true}:{ok:true,status:"CompletionFailed",completed:false}}
export async function declineSigning(ctx,{token,reason,ip,user}){const{env,signer}=await load(ctx,token);active(ctx,env);assertSignerAuthentication(signer,user);await mutate(ctx,env.id,async cur=>{const s=cur.signers.find(x=>x.id===signer.id);if(s.status!=="Pending")throw new HttpError(409,"This envelope can no longer be declined.");s.status="Declined";return{patch:{signers:cur.signers,status:"Declined",events:await chainEvents(cur.events,{type:"signer.declined",signerId:s.id,at:ctx.now().toISOString(),ip:ip||null,reason:cleanText(reason||"",300)})}}});return{ok:true,status:"Declined"}}
export async function finalizeEnvelope(ctx,id){const e=await ctx.meta.get("envelopes",id);if(!e)throw new HttpError(404,"Envelope not found.");if(e.status==="Completed")return{ok:true,completed:true,completion:e.completion};if(!["Completing","CompletionFailed"].includes(e.status))return{ok:false,completed:false};await ctx.meta.update("envelopes",id,{status:"Finalizing"},{ifVersion:e._v});const cur=await ctx.meta.get("envelopes",id),stored=[];try{const{bytes:orig}=await original(ctx,cur),completedAt=ctx.now().toISOString(),finalBytes=await buildSignedPdf(orig,{envelopeId:cur.id,documentId:cur.documentId,title:cur.title,originalHash:cur.documentHash,chainHead:cur.events.at(-1).hash,completedAt,signers:cur.signers.map(s=>({name:s.name,email:s.email,signedAt:s.signedAt,ip:s.ip,signatureType:s.signatureType,signatureValue:s.signatureValue}))}),finalHash=await sha256Hex(finalBytes),fileName=`${cleanSegment(cur.fileName.replace(/\.pdf$/i,""),80)}-signed-${finalHash.slice(0,12)}.pdf`;for(const k of cur.archiveTargets){const path=archivePath({archiveKey:k,classification:cur.classification,documentId:cur.documentId,fileName});const r=await ctx.storage.put({path,bytes:finalBytes,contentType:"application/pdf",metadata:{envelopeId:cur.id,documentId:cur.documentId,finalHash,state:"Final Completed Document",archive:k}});stored.push({kind:"archive",archiveKey:k,id:r.id,path})}for(const c of[{kind:"owner-copy",ownerKey:cur.createdBy},...cur.signers.map(s=>({kind:"signer-copy",ownerKey:s.uid||`${cur.id}-${s.id}`,signerId:s.id}))]){const path=signerCopyPath({ownerKey:c.ownerKey,fileName});const r=await ctx.storage.put({path,bytes:finalBytes,contentType:"application/pdf",metadata:{finalHash,state:"Final Completed Document",archive:"my-documents"}});stored.push({kind:c.kind,signerId:c.signerId,id:r.id,path})}const completion={finalHash,fileName,completedAt,primaryStorageId:stored[0].id,files:stored};await ctx.meta.update("envelopes",id,{status:"Completed",completion,events:await chainEvents(cur.events,{type:"envelope.completed",at:completedAt,finalHash,fileCount:stored.length})},{ifVersion:cur._v});return{ok:true,completed:true,completion}}catch(err){for(const f of stored){try{await ctx.storage.delete(f.id)}catch{}}await ctx.meta.update("envelopes",id,{status:"CompletionFailed"},{ifVersion:(await ctx.meta.get("envelopes",id))._v});return{ok:false,completed:false,error:"COMPLETION_FAILED"}}}
const owner=(e,u)=>e.createdBy===u.uid||u.isAdmin===true;
export async function retryCompletion(ctx,user,id){const e=await ctx.meta.get("envelopes",id);if(!e||!owner(e,user))throw new HttpError(403,"Not authorized.");return finalizeEnvelope(ctx,id)}
export async function voidEnvelope(ctx,user,id,reason){const e=await ctx.meta.get("envelopes",id);if(!e||!owner(e,user))throw new HttpError(403,"Not authorized.");await mutate(ctx,id,async c=>({patch:{status:"Voided",events:await chainEvents(c.events,{type:"envelope.voided",at:ctx.now().toISOString(),actor:user.uid,reason:cleanText(reason||"",300)})}}));return{ok:true,status:"Voided"}}
export async function getEnvelopeStatus(ctx,user,id){const e=await ctx.meta.get("envelopes",id);if(!e||!owner(e,user))throw new HttpError(403,"Not authorized.");return{ok:true,envelopeId:id,documentId:e.documentId,status:e.status,signers:e.signers.map(s=>({id:s.id,name:s.name,email:s.email,order:s.order,status:s.status,signedAt:s.signedAt||null,invitation:s.invitation})),completion:e.completion?{finalHash:e.completion.finalHash,completedAt:e.completion.completedAt,files:e.completion.files}:null,eventCount:e.events.length,auditChainValid:await verifyChain(e.events)}}
