import React,{useState}from"react";
import{ref,uploadBytes,getDownloadURL}from"firebase/storage";
import{storage,auth}from"../firebase/config";
import{createRecord,COLLECTIONS}from"../firebase/data";

export default function ControlledDocumentUpload({purpose="Controlled Document",onUploaded}){
 const[file,setFile]=useState(null),[title,setTitle]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function submit(e){e.preventDefault();setBusy(true);setMessage("");setError("");try{if(!auth.currentUser)throw new Error("You must be signed in.");if(!file)throw new Error("Select a PDF document to upload.");if(file.type!=="application/pdf")throw new Error("Only PDF documents are accepted.");if(file.size>10*1024*1024)throw new Error("PDF must not exceed 10 MB.");const name=(title.trim()||file.name.replace(/\.pdf$/i,"")).slice(0,160);const path=`documents/${auth.currentUser.uid}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const snap=await uploadBytes(ref(storage,path),file,{contentType:"application/pdf",customMetadata:{uploadedByUid:auth.currentUser.uid,purpose}});const url=await getDownloadURL(snap.ref);const id=await createRecord(COLLECTIONS.documents,{title:name,documentType:"PDF",purpose,fileName:file.name,fileUrl:url,storagePath:path,fileSize:file.size,contentType:file.type,status:"Draft",classification:"Internal",authorizedUids:[auth.currentUser.uid],createdByUid:auth.currentUser.uid,createdByEmail:auth.currentUser.email||"",workflowStage:"Draft",controlledUpload:true});const doc={id,title:name,documentType:"PDF",purpose,fileName:file.name,fileUrl:url,storagePath:path,fileSize:file.size,contentType:file.type,status:"Draft",classification:"Internal",authorizedUids:[auth.currentUser.uid],createdByUid:auth.currentUser.uid,createdByEmail:auth.currentUser.email||"",workflowStage:"Draft",controlledUpload:true};setMessage(`Document uploaded successfully: ${name}.`);setFile(null);setTitle("");e.target.reset();onUploaded?.(doc)}catch(x){setError(x.message||"Unable to upload document.")}finally{setBusy(false)}}
 return <section className="panel"><div className="panel-header"><div><span className="eyebrow">CONTROLLED DOCUMENT UPLOAD</span><h2>{purpose}</h2><p className="panel-description">Upload the source PDF into the controlled IRPA document register. Maximum 10 MB. The uploader is recorded as the document owner.</p></div></div>{message&&<div className="success-message action-feedback">{message}</div>}{error&&<div className="error-message action-feedback">{error}</div>}<form onSubmit={submit}><div className="form-grid"><div className="form-field"><label>Document Title</label><input value={title}onChange={e=>setTitle(e.target.value)}placeholder="Enter document title"/></div><div className="form-field"><label>PDF File</label><input type="file"accept="application/pdf,.pdf"onChange={e=>setFile(e.target.files?.[0]||null)}required/></div></div><div className="form-actions"><button disabled={busy}>{busy?"Uploading…":"Upload Controlled PDF"}</button></div></form></section>;
}
