import React,{useEffect,useMemo,useState}from"react";
import{COLLECTIONS,createRecord,getRecords,updateRecord}from"../firebase/data";

const todayKey=()=>new Date().toISOString().slice(0,10);
const money=v=>{const n=Number(v||0);return Number.isFinite(n)?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"—"};
const clean=v=>String(v??"").trim();

function Field({label,name,form,setForm,type="text",wide=false,required=false}){return <label className={wide?"form-field form-field-wide":"form-field"}>{label}<input name={name} type={type} value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})} required={required}/></label>}

function daysUntil(date){if(!date)return null;const d=new Date(date+"T00:00:00");const t=new Date(todayKey()+"T00:00:00");return Math.round((d-t)/86400000)}
function obligationState(r){if(String(r.status||"").toLowerCase()==="submitted"||String(r.status||"").toLowerCase()==="closed")return"Completed";const d=daysUntil(r.dueDate);if(d===null)return"Date not set";if(d<0)return"Overdue";if(d<=30)return"Due within 30 days";return"Scheduled"}

export default function DonorFunderRelations(){
 const[donors,setDonors]=useState([]),[obligations,setObligations]=useState([]),[grants,setGrants]=useState([]),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("registry"),[selectedDonor,setSelectedDonor]=useState(""),[donorForm,setDonorForm]=useState({name:"",type:"Foundation",contactPerson:"",email:"",phone:"",website:"",relationshipOwner:"",status:"Prospect",thematicInterests:"",notes:""}),[obligationForm,setObligationForm]=useState({donorId:"",grantId:"",reportType:"Narrative & Financial Report",reportingPeriod:"",dueDate:"",responsibleOwner:"",status:"Open",submissionDate:"",notes:""});
 async function load(){
  setBusy(true);setError("");
  try{
   const[ds,os,gs]=await Promise.all([getRecords(COLLECTIONS.donorFunders),getRecords(COLLECTIONS.grantReportingObligations),getRecords(COLLECTIONS.financeGrants)]);
   setDonors(ds);setObligations(os);setGrants(gs);
  }catch(e){setError(e.message||"Unable to load donor/funder relations.");}
  finally{setBusy(false)}
 }
 useEffect(()=>{load()},[]);
 const grantById=useMemo(()=>Object.fromEntries(grants.map(g=>[g.id,g])),[grants]);
 const selected=donors.find(d=>d.id===selectedDonor)||null;
 const donorGrants=useMemo(()=>selected?grants.filter(g=>clean(g.donor||g.donorName).toLowerCase()===clean(selected.name).toLowerCase()):[],[grants,selected]);
 const donorObligations=useMemo(()=>selected?obligations.filter(o=>o.donorId===selected.id),[obligations,selected]);
 const alerts=useMemo(()=>obligations.map(o=>({...o,_state:obligationState(o)})).filter(o=>o._state==="Overdue"||o._state==="Due within 30 days").sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))),[obligations]);
 const totals=useMemo(()=>({donors:donors.length,active:donors.filter(d=>["Active","Prospect","Engaged"].includes(d.status)).length,grants:grants.length,awarded:grants.reduce((s,g)=>s+Number(g.amount||g.awardAmount||0),0),overdue:alerts.filter(x=>x._state==="Overdue").length,dueSoon:alerts.filter(x=>x._state==="Due within 30 days").length}),[donors,grants,alerts]);
 async function addDonor(e){e.preventDefault();setSaving(true);setError("");setMessage("");try{if(!clean(donorForm.name))throw new Error("Funder / donor name is required.");const id=await createRecord(COLLECTIONS.donorFunders,{...donorForm,name:clean(donorForm.name),recordType:"DONOR_FUNDER_REGISTRY",status:donorForm.status||"Prospect"});setSelectedDonor(id);setDonorForm({name:"",type:"Foundation",contactPerson:"",email:"",phone:"",website:"",relationshipOwner:"",status:"Prospect",thematicInterests:"",notes:""});setMessage("Donor/funder registered in the dedicated relationship registry.");await load()}catch(e){setError(e.message||"Unable to create donor/funder record.")}finally{setSaving(false)}}
 async function addObligation(e){e.preventDefault();setSaving(true);setError("");setMessage("");try{if(!obligationForm.donorId)throw new Error("Select a donor/funder.");if(!obligationForm.dueDate)throw new Error("A reporting deadline is required.");const id=await createRecord(COLLECTIONS.grantReportingObligations,{...obligationForm,recordType:"GRANT_REPORTING_OBLIGATION"});setMessage("Grant reporting obligation registered.");setObligationForm({...obligationForm,grantId:"",reportingPeriod:"",dueDate:"",submissionDate:"",notes:""});await load();setTab("deadlines");}catch(e){setError(e.message||"Unable to create reporting obligation.")}finally{setSaving(false)}}
 async function markSubmitted(o){setSaving(true);setError("");try{await updateRecord(COLLECTIONS.grantReportingObligations,o.id,{status:"Submitted",submissionDate:todayKey()});setMessage("Reporting obligation marked Submitted.");await load()}catch(e){setError(e.message||"Unable to update reporting obligation.")}finally{setSaving(false)}}
 function printDonorReport(d=selected){
  if(!d)return;
  const relatedGrants=grants.filter(g=>clean(g.donor||g.donorName).toLowerCase()===clean(d.name).toLowerCase());
  const relatedObligations=obligations.filter(o=>o.donorId===d.id);
  const w=window.open("","_blank","noopener,noreferrer");if(!w)return;
  const rows=(items,cols)=>items.length?items.map(x=>"<tr>"+cols.map(c=>"<td>"+String(c(x)??"—").replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))+"</td>").join("")+"</tr>").join(""):"<tr><td colspan='"+cols.length+"'>No records</td></tr>";
  w.document.write("<html><head><title>IRPA Donor/Funder Report</title><style>body{font-family:Arial,sans-serif;padding:34px;color:#111}h1{margin:0 0 4px}h2{margin-top:28px}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #aaa;padding:7px;text-align:left;font-size:12px}.muted{color:#555}.header{border-bottom:3px solid #222;padding-bottom:14px}</style></head><body>");
  w.document.write("<div class='header'><h1>IMPROVEMENT OF RANGELAND IN PASTORAL AREAS</h1><div class='muted'>Donor / Funder Relationship & Reporting Profile</div><div class='muted'>Generated "+new Date().toLocaleString()+"</div></div>");
  w.document.write("<h2>"+d.name+"</h2><p>Type: "+(d.type||"—")+" · Status: "+(d.status||"—")+" · Relationship owner: "+(d.relationshipOwner||"—")+"</p><p>Contact: "+(d.contactPerson||"—")+" · "+(d.email||"—")+" · "+(d.phone||"—")+"</p>");
  w.document.write("<h2>Funding History</h2><table><tr><th>Grant</th><th>Status</th><th>Period</th><th>Award</th></tr>"+rows(relatedGrants,[x=>x.title||x.reference||x.id,x=>x.status,x=>x.grantPeriod||x.reportingPeriod,x=>money(x.amount||x.awardAmount)])+"</table>");
  w.document.write("<h2>Reporting Obligations</h2><table><tr><th>Report</th><th>Period</th><th>Due</th><th>Status</th></tr>"+rows(relatedObligations,[x=>x.reportType,x=>x.reportingPeriod,x=>x.dueDate,x=>obligationState(x)])+"</table>");
  w.document.write("<p class='muted'>This is a donor-ready management export derived from IRPA's internal grant and relationship registers. It is not a statutory financial statement or external audit opinion.</p></body></html>");
  w.document.close();w.focus();w.print();
 }
 return <div className="panel" id="donor-funder-relations">
  <div className="panel-header"><div><span className="eyebrow">FUNDRAISING ENABLEMENT — CONTROLLED MODULE</span><h2>Donor & Funder Relations</h2><p className="panel-description">A dedicated relationship registry and grant-reporting tracker alongside the governance and finance core. It does not alter approvals, payment controls, procurement, voting or financial reference issuance.</p></div><button type="button" className="secondary-button" onClick={load} disabled={busy}>{busy?"Refreshing…":"Refresh"}</button></div>
  <div className="dashboard-grid"><div className="stat-card"><span>Donor / Funders</span><strong>{totals.donors}</strong><small>Dedicated relationship records</small></div><div className="stat-card"><span>Active Relationships</span><strong>{totals.active}</strong><small>Prospect, engaged or active</small></div><div className="stat-card"><span>Grant Records</span><strong>{totals.grants}</strong><small>Authoritative Finance grant register</small></div><div className="stat-card"><span>Awarded Value</span><strong>{money(totals.awarded)}</strong><small>Derived from Finance grants</small></div><div className="stat-card"><span>Overdue Reports</span><strong>{totals.overdue}</strong><small>Requires attention</small></div><div className="stat-card"><span>Due ≤ 30 Days</span><strong>{totals.dueSoon}</strong><small>Reporting deadline watch</small></div></div>
  <div className="member-actions unified-control-tabs" role="tablist"><button type="button" className={tab==="registry"?"unified-control-tab active":"unified-control-tab"} onClick={()=>setTab("registry")}>Funder Registry</button><button type="button" className={tab==="deadlines"?"unified-control-tab active":"unified-control-tab"} onClick={()=>setTab("deadlines")}>Reporting Deadlines</button><button type="button" className={tab==="exports"?"unified-control-tab active":"unified-control-tab"} onClick={()=>setTab("exports")}>Donor-Ready Exports</button></div>
  {error&&<div className="error-message action-feedback">{error}</div>}{message&&<div className="success-message action-feedback">{message}</div>}
  {tab==="registry"&&<><section className="panel"><div className="panel-header"><div><span className="eyebrow">RELATIONSHIP REGISTER</span><h3>Donor / Funder Registry</h3><p className="panel-description">Contact, relationship ownership, status and thematic interests are stored separately from financeGrants.</p></div></div><form onSubmit={addDonor}><div className="form-grid"><Field label="Funder / Donor Name" name="name" form={donorForm} setForm={setDonorForm} required/><Field label="Type" name="type" form={donorForm} setForm={setDonorForm}/><Field label="Contact Person" name="contactPerson" form={donorForm} setForm={setDonorForm}/><Field label="Email" name="email" type="email" form={donorForm} setForm={setDonorForm}/><Field label="Phone" name="phone" form={donorForm} setForm={setDonorForm}/><Field label="Website" name="website" form={donorForm} setForm={setDonorForm}/><Field label="Relationship Owner" name="relationshipOwner" form={donorForm} setForm={setDonorForm}/><Field label="Status" name="status" form={donorForm} setForm={setDonorForm}/><Field label="Thematic Interests" name="thematicInterests" form={donorForm} setForm={setDonorForm} wide/><Field label="Notes" name="notes" form={donorForm} setForm={setDonorForm} wide/></div><div className="form-actions"><button disabled={saving}>{saving?"Saving…":"Register Donor / Funder"}</button></div></form></section>
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">RELATIONSHIP PORTFOLIO</span><h3>Registered Funders</h3></div></div><div className="table-wrapper"><table><thead><tr><th>Funder</th><th>Type</th><th>Owner</th><th>Status</th><th>Funding History</th><th>Reporting</th><th>Control</th></tr></thead><tbody>{donors.length?donors.map(d=>{const gs=grants.filter(g=>clean(g.donor||g.donorName).toLowerCase()===clean(d.name).toLowerCase());const os=obligations.filter(o=>o.donorId===d.id);return <tr key={d.id}><td><strong>{d.name}</strong><div className="table-subtext">{d.contactPerson||d.email||"—"}</div></td><td>{d.type||"—"}</td><td>{d.relationshipOwner||"—"}</td><td><span className="status-badge">{d.status||"Prospect"}</span></td><td>{gs.length} grant(s) · {money(gs.reduce((s,g)=>s+Number(g.amount||g.awardAmount||0),0))}</td><td>{os.filter(x=>obligationState(x)==="Overdue").length} overdue · {os.filter(x=>obligationState(x)==="Due within 30 days").length} soon</td><td><button type="button" className="secondary-button" onClick={()=>{setSelectedDonor(d.id);setTab("exports")}}>Open Profile</button></td></tr>}) : <tr><td colSpan="7">No donor/funder relationships are registered yet.</td></tr>}</tbody></table></div></section></>}
  {tab==="deadlines"&&<><section className="panel"><div className="panel-header"><div><span className="eyebrow">GRANT COMPLIANCE / REPORTING</span><h3>Reporting Deadline Tracker</h3><p className="panel-description">Each grant obligation has an owner, due date and status. The dashboard flags overdue and near-term deadlines so Finance/management can act before a reporting date is missed.</p></div></div><form onSubmit={addObligation}><div className="form-grid"><label className="form-field">Donor / Funder<select value={obligationForm.donorId} onChange={e=>setObligationForm({...obligationForm,donorId:e.target.value})} required><option value="">Select donor / funder</option>{donors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="form-field">Grant Record<select value={obligationForm.grantId} onChange={e=>setObligationForm({...obligationForm,grantId:e.target.value})}><option value="">Select linked grant (optional)</option>{grants.map(g=><option key={g.id} value={g.id}>{g.title||g.reference||g.id}</option>)}</select></label><Field label="Report Type" name="reportType" form={obligationForm} setForm={setObligationForm}/><Field label="Reporting Period" name="reportingPeriod" form={obligationForm} setForm={setObligationForm}/><Field label="Due Date" name="dueDate" type="date" form={obligationForm} setForm={setObligationForm} required/><Field label="Responsible Owner" name="responsibleOwner" form={obligationForm} setForm={setObligationForm}/><Field label="Status" name="status" form={obligationForm} setForm={setObligationForm}/><Field label="Notes" name="notes" form={obligationForm} setForm={setObligationForm} wide/></div><div className="form-actions"><button disabled={saving}>{saving?"Saving…":"Add Reporting Obligation"}</button></div></form></section>
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">DEADLINE WATCH</span><h3>Upcoming & Overdue Obligations</h3></div></div><div className="table-wrapper"><table><thead><tr><th>Funder</th><th>Report</th><th>Grant</th><th>Due</th><th>State</th><th>Owner</th><th>Action</th></tr></thead><tbody>{obligations.length?[...obligations].sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).map(o=>{const d=donors.find(x=>x.id===o.donorId);const g=grantById[o.grantId];return <tr key={o.id}><td>{d?.name||"—"}</td><td>{o.reportType||"—"}<div className="table-subtext">{o.reportingPeriod||"—"}</div></td><td>{g?.title||g?.reference||"—"}</td><td>{o.dueDate||"—"}</td><td><span className="status-badge">{obligationState(o)}</span></td><td>{o.responsibleOwner||"—"}</td><td>{obligationState(o)==="Completed"?<span className="muted">Completed</span>:<button type="button" className="secondary-button" disabled={saving} onClick={()=>markSubmitted(o)}>Mark Submitted</button>}</td></tr>}) : <tr><td colSpan="7">No grant reporting obligations are registered.</td></tr>}</tbody></table></div></section></>}
  {tab==="exports"&&<section className="panel"><div className="panel-header"><div><span className="eyebrow">DONOR-READY EVIDENCE</span><h3>Branded Relationship & Reporting Export</h3><p className="panel-description">Select a funder to generate a print/PDF-ready profile using the relationship registry, Finance grant history and reporting obligations.</p></div></div><div className="form-grid"><label className="form-field">Funder / Donor<select value={selectedDonor} onChange={e=>setSelectedDonor(e.target.value)}><option value="">Select donor / funder</option>{donors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>{selected?<><div className="dashboard-grid"><div className="stat-card"><span>Funder</span><strong>{selected.name}</strong><small>{selected.type||"—"} · {selected.status||"—"}</small></div><div className="stat-card"><span>Grant Portfolio</span><strong>{donorGrants.length}</strong><small>{money(donorGrants.reduce((s,g)=>s+Number(g.amount||g.awardAmount||0),0))} recorded value</small></div><div className="stat-card"><span>Reporting Obligations</span><strong>{donorObligations.length}</strong><small>{donorObligations.filter(x=>obligationState(x)==="Overdue").length} overdue</small></div></div><div className="form-actions"><button type="button" onClick={()=>printDonorReport(selected)}>Generate Donor-Ready Report / Print to PDF</button></div></>:<div className="action-feedback">Select a donor/funder to prepare an export.</div>}</section>}
  <div className="action-feedback"><strong>Control boundary:</strong> this module records relationship and reporting-management information separately from the locked governance/finance control core. Finance grant records remain authoritative for grant values and financial references.</div>
 </div>
}
