import React,{useEffect,useMemo,useState}from"react";
import{createRecord,getRecords,COLLECTIONS}from"../firebase/data";

const TYPES=["text","number","integer","decimal","select_one","select_many","date","datetime","gps","boolean","likert","long_text"];
const DOMAINS=["Household / Socioeconomic","Pastoral Livelihoods","Livestock","Rangeland / Ecology","Climate / Environment","Market / Value Chain","Gender / Social Inclusion","Youth","Governance","Programme Monitoring","Health / Nutrition","Other"];
const emptyField=()=>({id:"field-"+Date.now()+"-"+Math.random().toString(36).slice(2,7),label:"",name:"",type:"text",required:false,options:"",min:"",max:"",domain:"Other"});

function clean(v){return String(v??"").trim()}
function makeName(v){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,50)}

export default function ResearchDataCollectionStudio({setMessage,setError}){
 const[mode,setMode]=useState("instruments"),[busy,setBusy]=useState(false),[instruments,setInstruments]=useState([]),[instrument,setInstrument]=useState({title:"",description:"",domain:"Pastoral Livelihoods",version:"1.0",language:"English",offlineEnabled:true,gpsEnabled:true,consentRequired:true,fields:[emptyField()]}),[selected,setSelected]=useState(null),[responses,setResponses]=useState({}),[pending,setPending]=useState(()=>{try{return JSON.parse(localStorage.getItem("irpaResearchOfflineQueue")||"[]")}catch{return[]}});

 async function load(){setBusy(true);try{setInstruments(await getRecords(COLLECTIONS.researchInstruments));}catch(e){setError?.(e.message||"Unable to load research instruments.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const sync=async()=>{if(!navigator.onLine||!pending.length)return;const queue=[...pending];const remaining=[];for(const item of queue){try{await createRecord(COLLECTIONS.researchSubmissions,item)}catch{remaining.push(item)}}setPending(remaining);try{localStorage.setItem("irpaResearchOfflineQueue",JSON.stringify(remaining))}catch{}};window.addEventListener("online",sync);sync();return()=>window.removeEventListener("online",sync)},[pending.length]);

 const updateField=(id,key,value)=>setInstrument(s=>({...s,fields:s.fields.map(f=>f.id===id?{...f,[key]:value}:f)}));
 const saveInstrument=async e=>{e.preventDefault();const fields=instrument.fields.map(f=>({...f,name:f.name||makeName(f.label),options:clean(f.options).split(",").map(clean).filter(Boolean)}));if(!instrument.title.trim())return setError?.("Give the data collection instrument a title.");if(fields.some(f=>!f.label.trim()||!f.name.trim()))return setError?.("Every collection field requires a label and variable name.");setBusy(true);try{const id=await createRecord(COLLECTIONS.researchInstruments,{...instrument,fields,recordType:"Research Data Collection Instrument",recordOrigin:"PRODUCTION",status:"Draft",standard:"IRPA Research Data Collection Standard V1",createdForDomains:[...new Set(fields.map(f=>f.domain))]});setMessage?.("Data collection instrument created: "+id);setInstrument({title:"",description:"",domain:"Pastoral Livelihoods",version:"1.0",language:"English",offlineEnabled:true,gpsEnabled:true,consentRequired:true,fields:[emptyField()]});await load()}catch(e){setError?.(e.message||"Unable to save collection instrument.")}finally{setBusy(false)}};

 const openInstrument=i=>{setSelected(i);setResponses({});setMode("collect")};
 const submit=async e=>{e.preventDefault();if(!selected)return;const missing=selected.fields.filter(f=>f.required&&!clean(responses[f.name])).map(f=>f.label);if(missing.length)return setError?.("Required fields missing: "+missing.join(", "));const payload={instrumentId:selected.id,instrumentTitle:selected.title,instrumentVersion:selected.version,values:responses,consentCaptured:selected.consentRequired?responses.__consent===true:true,collectionMode:navigator.onLine?"ONLINE":"OFFLINE",collectedAt:new Date().toISOString(),gpsCaptured:Boolean(responses.__gps),recordType:"Research Data Collection Submission",recordOrigin:"PRODUCTION"};setBusy(true);try{if(!navigator.onLine){const q=[...pending,payload];setPending(q);localStorage.setItem("irpaResearchOfflineQueue",JSON.stringify(q));setMessage?.("Submission saved securely to the device queue and will synchronize when connectivity returns.");}else{await createRecord(COLLECTIONS.researchSubmissions,payload);setMessage?.("Research submission recorded and synchronized.");}setResponses({});}catch(e){const q=[...pending,payload];setPending(q);try{localStorage.setItem("irpaResearchOfflineQueue",JSON.stringify(q))}catch{}setMessage?.("Submission queued for synchronization after connectivity returns.")}finally{setBusy(false)}};

 const previewFields=useMemo(()=>instrument.fields,[instrument.fields]);
 return <section className="panel">
   <div className="panel-header"><div><span className="eyebrow">FIELD RESEARCH · DATA COLLECTION</span><h2>Professional Data Collection Studio</h2><p className="panel-description">Build controlled research instruments with validation, required fields, structured response types, GPS capture, consent, domain classification and offline-capable submission.</p></div><div className="form-actions"><button type="button" onClick={()=>setMode("instruments")}>Instrument Builder</button><button type="button" className="secondary-button" onClick={()=>setMode("collect")}>Collect Data</button></div></div>
   {mode==="instruments"&&<form onSubmit={saveInstrument}>
    <div className="form-grid"><label>Instrument title<input value={instrument.title} onChange={e=>setInstrument({...instrument,title:e.target.value})} placeholder="e.g. Longido Rangeland Condition Survey"/></label><label>Research domain<select value={instrument.domain} onChange={e=>setInstrument({...instrument,domain:e.target.value})}>{DOMAINS.map(x=><option key={x}>{x}</option>)}</select></label><label>Version<input value={instrument.version} onChange={e=>setInstrument({...instrument,version:e.target.value})}/></label><label>Language<input value={instrument.language} onChange={e=>setInstrument({...instrument,language:e.target.value})}/></label></div>
    <label>Description<textarea value={instrument.description} onChange={e=>setInstrument({...instrument,description:e.target.value})} placeholder="Purpose, population, sampling frame and collection protocol"/></label>
    <div className="dashboard-grid" style={{marginTop:12}}><label className="stat-card"><input type="checkbox" checked={instrument.offlineEnabled} onChange={e=>setInstrument({...instrument,offlineEnabled:e.target.checked})}/> Offline-capable collection</label><label className="stat-card"><input type="checkbox" checked={instrument.gpsEnabled} onChange={e=>setInstrument({...instrument,gpsEnabled:e.target.checked})}/> GPS / geospatial capture</label><label className="stat-card"><input type="checkbox" checked={instrument.consentRequired} onChange={e=>setInstrument({...instrument,consentRequired:e.target.checked})}/> Consent acknowledgement</label></div>
    <div className="panel" style={{marginTop:16,boxShadow:"none"}}><div className="panel-header"><div><span className="eyebrow">QUESTION / VARIABLE DESIGNER</span><h3>Structured Collection Fields</h3></div><button type="button" className="secondary-button" onClick={()=>setInstrument(s=>({...s,fields:[...s.fields,emptyField()]}))}>Add Field</button></div>
    <div style={{display:"grid",gap:10}}>{previewFields.map((f,i)=><div key={f.id} className="record-details"><div className="form-grid"><label>Label<input value={f.label} onChange={e=>updateField(f.id,"label",e.target.value)} placeholder="Question / measurement"/></label><label>Variable name<input value={f.name} onChange={e=>updateField(f.id,"name",makeName(e.target.value))} placeholder="variable_name"/></label><label>Type<select value={f.type} onChange={e=>updateField(f.id,"type",e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Domain<select value={f.domain} onChange={e=>updateField(f.id,"domain",e.target.value)}>{DOMAINS.map(t=><option key={t}>{t}</option>)}</select></label></div><div className="form-grid"><label>Options / choices<input value={f.options} onChange={e=>updateField(f.id,"options",e.target.value)} placeholder="Male,Female,Other"/></label><label>Minimum<input value={f.min} onChange={e=>updateField(f.id,"min",e.target.value)}/></label><label>Maximum<input value={f.max} onChange={e=>updateField(f.id,"max",e.target.value)}/></label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={f.required} onChange={e=>updateField(f.id,"required",e.target.checked)}/> Required</label></div><button type="button" className="secondary-button" onClick={()=>setInstrument(s=>({...s,fields:s.fields.filter(x=>x.id!==f.id)}))} disabled={instrument.fields.length===1}>Remove field {i+1}</button></div>)}</div></div>
    <button type="submit" disabled={busy}>{busy?"Saving…":"Save Research Instrument"}</button>
   </form>}
   {mode==="instruments"&&<section className="panel" style={{marginTop:16,boxShadow:"none"}}><div className="panel-header"><div><span className="eyebrow">DEPLOYED INSTRUMENTS</span><h3>Collection Instruments</h3></div></div>{!instruments.length?<p className="panel-description">No research instruments have been created yet.</p>:<div className="table-wrapper"><table><thead><tr><th>Instrument</th><th>Domain</th><th>Version</th><th>Fields</th><th>Mode</th><th>Action</th></tr></thead><tbody>{instruments.map(i=><tr key={i.id}><td><strong>{i.title}</strong><div className="table-subtext">{i.description||"—"}</div></td><td>{i.domain}</td><td>{i.version}</td><td>{i.fields?.length||0}</td><td>{i.offlineEnabled?"Offline capable":"Online"}</td><td><button type="button" onClick={()=>openInstrument(i)}>Collect</button></td></tr>)}</tbody></table></div>}</section>}
   {mode==="collect"&&<section className="panel" style={{marginTop:16,boxShadow:"none"}}><div className="panel-header"><div><span className="eyebrow">ENUMERATOR WORKSPACE</span><h3>{selected?selected.title:"Select an instrument"}</h3></div>{selected&&<button type="button" className="secondary-button" onClick={()=>setMode("instruments")}>Back to Instruments</button>}</div>{!selected?<div className="table-wrapper"><table><thead><tr><th>Instrument</th><th>Domain</th><th>Version</th><th>Action</th></tr></thead><tbody>{instruments.map(i=><tr key={i.id}><td>{i.title}</td><td>{i.domain}</td><td>{i.version}</td><td><button type="button" onClick={()=>openInstrument(i)}>Start Collection</button></td></tr>)}</tbody></table></div>:<form onSubmit={submit}><div className="record-details"><strong>Collection controls</strong><div className="table-subtext">Connectivity: {navigator.onLine?"ONLINE":"OFFLINE"} · Pending device queue: {pending.length} · GPS and consent are controlled by the instrument.</div></div>{selected.fields.map(f=><label key={f.id}>{f.label}{f.required?" *":""}{f.type==="long_text"?<textarea value={responses[f.name]||""} onChange={e=>setResponses({...responses,[f.name]:e.target.value})}/>:f.type==="select_one"?<select value={responses[f.name]||""} onChange={e=>setResponses({...responses,[f.name]:e.target.value})}><option value="">Select</option>{(Array.isArray(f.options)?f.options:[]).map(o=><option key={o}>{o}</option>)}</select>:f.type==="select_many"?<input value={responses[f.name]||""} onChange={e=>setResponses({...responses,[f.name]:e.target.value})} placeholder="Enter selected options separated by commas"/>:<input type={["number","integer","decimal"].includes(f.type)?"number":f.type==="date"?"date":f.type==="datetime"?"datetime-local":"text"} value={responses[f.name]||""} onChange={e=>setResponses({...responses,[f.name]:e.target.value})}/>}</label>)}{selected.gpsEnabled&&<label>GPS location<input value={responses.__gps||""} onChange={e=>setResponses({...responses,__gps:e.target.value})} placeholder="Latitude, longitude (device GPS integration point)"/></label>}{selected.consentRequired&&<label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={responses.__consent===true} onChange={e=>setResponses({...responses,__consent:e.target.checked})}/> Participant consent captured</label>}<button type="submit" disabled={busy}>{busy?"Saving…":navigator.onLine?"Submit Research Data":"Save Offline Submission"}</button></form>}</section>}
 </section>
}
