import React,{useMemo,useState}from"react";
import jStat from"jstat";
import{centroid,distance,point}from"@turf/turf";

const clean=v=>String(v??"").trim();
const nums=a=>a.map(Number).filter(Number.isFinite);
const mean=a=>{const x=nums(a);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null};
const variance=(a,sample=true)=>{const x=nums(a),m=mean(x);return x.length>(sample?1:0)?x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-(sample?1:0)):null};
const sd=a=>{const v=variance(a);return v==null?null:Math.sqrt(v)};
const quantile=(a,q)=>{const x=nums(a).sort((u,v)=>u-v);if(!x.length)return null;const p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i+1]===undefined?x[i]:x[i]+f*(x[i+1]-x[i])};
const tP=(t,df)=>2*(1-jStat.studentt.cdf(Math.abs(t),df));
const invT=(p,df)=>jStat.studentt.inv(p,df);
function pearson(x,y){const a=[],b=[];x.forEach((v,i)=>{const xx=Number(v),yy=Number(y[i]);if(Number.isFinite(xx)&&Number.isFinite(yy)){a.push(xx);b.push(yy)}});if(a.length<3)return null;const mx=mean(a),my=mean(b),den=Math.sqrt(a.reduce((s,v)=>s+(v-mx)**2,0)*b.reduce((s,v)=>s+(v-my)**2,0));return den?a.reduce((s,v,i)=>s+(v-mx)*(b[i]-my),0)/den:null}
function rank(a){return a.map((v,i)=>({v:Number(v),i})).sort((x,y)=>x.v-y.v).reduce((r,x,i,arr)=>{let j=i;while(j+1<arr.length&&arr[j+1].v===x.v)j++;const rr=(i+j)/2+1;for(let k=i;k<=j;k++)r[arr[k].i]=rr;return r},[])}
function spearman(x,y){const a=[],b=[];x.forEach((v,i)=>{if(Number.isFinite(Number(v))&&Number.isFinite(Number(y[i]))){a.push(Number(v));b.push(Number(y[i]))}});return pearson(rank(a),rank(b))}
function simpleRegression(x,y){const a=[],b=[];x.forEach((v,i)=>{if(Number.isFinite(Number(v))&&Number.isFinite(Number(y[i]))){a.push(Number(v));b.push(Number(y[i]))}});if(a.length<3)return null;const mx=mean(a),my=mean(b),ssx=a.reduce((s,v)=>s+(v-mx)**2,0),sxy=a.reduce((s,v,i)=>s+(v-mx)*(b[i]-my),0),slope=sxy/ssx,intercept=my-slope*mx,r=pearson(a,b);return{slope,intercept,r,r2:r*r,n:a.length}}
function welchT(a,b){const x=nums(a),y=nums(b);if(x.length<2||y.length<2)return null;const mx=mean(x),my=mean(y),vx=variance(x),vy=variance(y),se=Math.sqrt(vx/x.length+vy/y.length),t=(mx-my)/se,df=(vx/x.length+vy/y.length)**2/((vx/x.length)**2/(x.length-1)+(vy/y.length)**2/(y.length-1));return{mean1:mx,mean2:my,difference:mx-my,t,df,p:tP(t,df)}}
function oneSampleT(a,mu){const x=nums(a),m=mean(x),s=sd(x);if(x.length<2||!s)return null;const se=s/Math.sqrt(x.length),t=(m-mu)/se,df=x.length-1;return{n:x.length,mean:m,mu,t,df,p:tP(t,df),ciLow:m-invT(.975,df)*se,ciHigh:m+invT(.975,df)*se}}
function anova(groups){const g=groups.map(nums).filter(x=>x.length),n=g.reduce((s,x)=>s+x.length,0);if(g.length<2||n<=g.length)return null;const grand=g.flat().reduce((s,v)=>s+v,0)/n,between=g.reduce((s,x)=>s+x.length*(mean(x)-grand)**2,0),within=g.reduce((s,x)=>s+x.reduce((q,v)=>q+(v-mean(x))**2,0),0),df1=g.length-1,df2=n-g.length,F=(between/df1)/(within/df2),p=1-jStat.centralF.cdf(F,df1,df2);return{groups:g.length,n,ssBetween:between,ssWithin:within,df1,df2,F,p,etaSquared:between/(between+within)}}
function chiSquareIndependence(rows){const r=rows.length,c=Math.max(...rows.map(x=>x.length));if(r<2||c<2)return null;const totals=Array(c).fill(0),rt=rows.map(x=>x.reduce((s,v)=>s+Number(v||0),0));rows.forEach(x=>x.forEach((v,j)=>totals[j]+=Number(v||0)));const total=rt.reduce((s,v)=>s+v,0);let chi=0;rows.forEach((x,i)=>{for(let j=0;j<c;j++){const e=rt[i]*totals[j]/total;if(e>0)chi+=(Number(x[j]||0)-e)**2/e}});const df=(r-1)*(c-1),p=1-jStat.chisquare.cdf(chi,df);return{chiSquare:chi,df,p,cramersV:Math.sqrt(chi/(total*Math.min(r-1,c-1)))}}
function cronbach(matrix){const rows=matrix.filter(r=>r.length>=2);if(rows.length<2)return null;const k=rows[0].length,vars=Array.from({length:k},(_,j)=>variance(rows.map(r=>Number(r[j])))).filter(Number.isFinite),totals=rows.map(r=>r.reduce((s,v)=>s+Number(v),0)),vt=variance(totals);return k>1&&vt?{items:k,respondents:rows.length,alpha:k/(k-1)*(1-vars.reduce((s,v)=>s+v,0)/vt)}:null}
function cochran(N,z,e,p=.5){const n0=z*z*p*(1-p)/(e*e);return N?Math.ceil(n0/(1+(n0-1)/N)):Math.ceil(n0)}
function multipleRegression(X,y){const n=y.length,p=X[0]?.length||0;if(n<=p)return null;const A=X.map(row=>[1,...row.map(Number)]),b=y.map(Number),m=A[0].length,M=Array.from({length:m},(_,i)=>Array.from({length:m},(_,j)=>A.reduce((s,row,k)=>s+row[i]*row[j],0))),v=Array.from({length:m},(_,i)=>A.reduce((s,row,k)=>s+row[i]*b[k],0));for(let i=0;i<m;i++){let pivot=i;for(let r=i+1;r<m;r++)if(Math.abs(M[r][i])>Math.abs(M[pivot][i]))pivot=r;if(Math.abs(M[pivot][i])<1e-12)return null;[M[i],M[pivot]]=[M[pivot],M[i]];[v[i],v[pivot]]=[v[pivot],v[i]];const d=M[i][i];for(let j=i;j<m;j++)M[i][j]/=d;v[i]/=d;for(let r=0;r<m;r++){if(r===i)continue;const q=M[r][i];for(let j=i;j<m;j++)M[r][j]-=q*M[i][j];v[r]-=q*v[i]}}const beta=v,pred=A.map(row=>row.reduce((s,z,i)=>s+z*beta[i],0)),ym=mean(b),sst=b.reduce((s,z)=>s+(z-ym)**2,0),sse=b.reduce((s,z,i)=>s+(z-pred[i])**2,0);return{coefficients:beta,r2:1-sse/sst,n,p}}
function dataProfile(rows,variables){return variables.map(v=>{const raw=rows.map(r=>r.values?.[v]),x=nums(raw),missing=raw.filter(z=>clean(z)==="").length,q1=quantile(x,.25),q3=quantile(x,.75),iqr=q3!=null?q3-q1:null,outliers=iqr==null?0:x.filter(z=>z<q1-1.5*iqr||z>q3+1.5*iqr).length;return{variable:v,n:x.length,missing,missingPct:rows.length?missing/rows.length:0,unique:new Set(raw.map(clean).filter(Boolean)).size,mean:mean(x),sd:sd(x),min:x.length?Math.min(...x):null,max:x.length?Math.max(...x):null,outliers}})}
function exportFile(name,text,type="application/json"){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
const TOOLSETS=[
 ["Data Quality","Missingness, duplicates, completeness, ranges and IQR outlier diagnostics."],
 ["Descriptive Statistics","Mean, median, mode, variance, SD, SE, CV, quantiles and confidence intervals."],
 ["Inferential Statistics","One-sample and Welch t-tests, one-way ANOVA, chi-square independence and effect sizes."],
 ["Non-parametric","Spearman rank association and distribution-free analytical preparation."],
 ["Regression","Simple linear and multiple linear regression with R² diagnostics."],
 ["Survey & Social Science","Frequencies, weighted summaries, cross-tabulation, reliability and survey design."],
 ["Time Series","Growth rates, moving averages and period-to-period change calculations."],
 ["Spatial / GIS","Coordinate validation, centroid and geodesic distance using Turf.js."],
 ["Remote Sensing","NDVI/EVI summaries and spatially referenced observation diagnostics."],
 ["Multivariate","Correlation matrices and multivariate covariance diagnostics."],
 ["Power / Sample Size","Cochran sample-size calculation with finite-population correction."],
 ["Reproducibility","Software, variables, parameters, timestamp and result archive for every run."]
];
export default function StatisticalAnalysisWorkbench({datasets,selectedDataset,setSelectedDataset,selectedObs,variables,numericColumns,createAnalysisRecord,setMessage,setError,busy}){
 const[tool,setTool]=useState("Data Quality"),[x,setX]=useState(""),[y,setY]=useState(""),[mu,setMu]=useState("0"),[groups,setGroups]=useState("12,14,13|20,18,21|30,29,31"),[contingency,setContingency]=useState("10,20\n20,30"),[weightVar,setWeightVar]=useState(""),[population,setPopulation]=useState(""),[margin,setMargin]=useState("0.05"),[z,setZ]=useState("1.96"),[timeVar,setTimeVar]=useState(""),[lat,setLat]=useState(""),[lon,setLon]=useState("");
 const rows=selectedObs||[],profile=useMemo(()=>dataProfile(rows,variables),[rows,variables]),xv=useMemo(()=>rows.map(r=>r.values?.[x]),[rows,x]),yv=useMemo(()=>rows.map(r=>r.values?.[y]),[rows,y]);
 const result=useMemo(()=>{try{
  if(tool==="Data Quality")return{profile,totalRows:rows.length,completeCases:rows.filter(r=>variables.every(v=>clean(r.values?.[v])!=="")).length};
  if(tool==="Descriptive Statistics")return{statistics:profile};
  if(tool==="Inferential Statistics")return{xOneSample:x?oneSampleT(xv,Number(mu)):null,welch:x&&y?welchT(xv,yv):null,anova:anova(groups.split("|").map(g=>g.split(",").map(Number))),chiSquare:chiSquareIndependence(contingency.split("\n").map(r=>r.split(",").map(Number)))};
  if(tool==="Non-parametric")return{spearman:x&&y?spearman(xv,yv):null};
  if(tool==="Regression"){const predictors=clean(x).split(",").map(clean).filter(Boolean),simple=x&&y?simpleRegression(xv,yv):null,usable=rows.map(r=>({x:predictors.map(v=>Number(r.values?.[v])),y:Number(r.values?.[y])})).filter(q=>q.x.every(Number.isFinite)&&Number.isFinite(q.y));return{simple,multiple:predictors.length>1?multipleRegression(usable.map(q=>q.x),usable.map(q=>q.y)):null}};
  if(tool==="Survey & Social Science"){const matrix=rows.map(r=>clean(r.values?.[x]).split(",").map(Number)).filter(r=>r.length>1);return{profile:profile.find(p=>p.variable===x)||null,cronbach:cronbach(matrix)}};
  if(tool==="Time Series"){const a=nums(rows.map(r=>r.values?.[timeVar]));return{n:a.length,growthRate:a.length>1?(a[a.length-1]-a[0])/Math.abs(a[0]||1):null,movingAverage:a.length?mean(a.slice(-3)):null}};
  if(tool==="Spatial / GIS"){const la=Number(lat),lo=Number(lon),features=rows.map(r=>{const a=Number(r.values?.lon),b=Number(r.values?.lat);return Number.isFinite(a)&&Number.isFinite(b)?point([a,b]):null}).filter(Boolean);return{validLatitude:la>=-90&&la<=90,validLongitude:lo>=-180&&lo<=180,centroid:features.length?centroid({type:"FeatureCollection",features:features.map(geometry=>({type:"Feature",geometry:geometry.geometry,properties:{}}))}).geometry.coordinates:null,distanceKm:features.map(f=>Number.isFinite(la)&&Number.isFinite(lo)?distance(point([lo,la]),f,{units:"kilometers"}):null).filter(Number.isFinite).slice(0,20)}};
  if(tool==="Remote Sensing")return{ndvi:profile.filter(p=>/ndvi/i.test(p.variable)),evi:profile.filter(p=>/evi/i.test(p.variable)),spatialObservationCount:rows.filter(r=>Number.isFinite(Number(r.values?.lat))&&Number.isFinite(Number(r.values?.lon))).length};
  if(tool==="Multivariate"){const cols=numericColumns.slice(0,12);return{variables:cols,correlationMatrix:cols.map(a=>cols.map(b=>pearson(rows.map(r=>r.values?.[a]),rows.map(r=>r.values?.[b]))))}};
  if(tool==="Power / Sample Size"){const n0=(Number(z)||1.96)**2*.25/(Number(margin)||.05)**2;return{sampleSize:population?Math.ceil(n0/(1+(n0-1)/Number(population))):Math.ceil(n0)}};
  return{};
 }catch(e){return{error:e.message}}},[tool,profile,rows,variables,x,y,xv,yv,mu,groups,contingency,numericColumns,timeVar,lat,lon,population,margin,z]);
 async function archive(){if(!selectedDataset){setError("Select a dataset before archiving an analysis.");return}try{await createAnalysisRecord({recordType:"Statistical Analysis",datasetId:selectedDataset.id,datasetName:selectedDataset.name,software:["IRPA Research Statistics Engine","jStat","Turf.js"],tool,variables:{x,y},parameters:{mu,groups,contingency,weightVar,population,margin,z,timeVar,lat,lon},result,generatedAt:new Date().toISOString(),recordOrigin:"PRODUCTION"});setMessage(tool+" analysis calculated and archived with reproducibility metadata.");}catch(e){setError(e.message||"Unable to archive analysis.")}}
 return <section className="panel"><div className="panel-header"><div><span className="eyebrow">SCIENTIFIC + SOCIAL SCIENCE ANALYTICS SUITE</span><h2>Integrated Analysis Workbench</h2><p className="panel-description">Browser-based quantitative research software for social science, environmental science, livestock, rangeland, climate, GIS, remote sensing and programme evidence.</p></div></div>
 <div className="dashboard-grid">{TOOLSETS.map(([n,d])=><button key={n} type="button" className={tool===n?"stat-card active-stage":"stat-card"} onClick={()=>setTool(n)}><span>{n}</span><small>{d}</small></button>)}</div>
 <div className="form-grid" style={{marginTop:16}}><label>Dataset<select value={selectedDataset?.id||""} onChange={e=>setSelectedDataset(datasets.find(d=>d.id===e.target.value)||null)}><option value="">Select dataset</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.name||d.id}</option>)}</select></label><label>Variable X / Outcome<select value={x} onChange={e=>setX(e.target.value)}><option value="">Select variable</option>{variables.map(v=><option key={v}>{v}</option>)}</select></label><label>Variable Y / Predictor<select value={y} onChange={e=>setY(e.target.value)}><option value="">Select variable</option>{variables.map(v=><option key={v}>{v}</option>)}</select></label></div>
 {tool==="Inferential Statistics"&&<div className="form-grid"><label>Null mean<input value={mu} onChange={e=>setMu(e.target.value)}/></label><label>ANOVA groups<textarea value={groups} onChange={e=>setGroups(e.target.value)} placeholder="12,14,13|20,18,21|30,29,31"/></label><label>Contingency table<textarea value={contingency} onChange={e=>setContingency(e.target.value)} placeholder="10,20\n20,30"/></label></div>}
 {tool==="Survey & Social Science"&&<div className="form-grid"><label>Survey item matrix variable<input value={x} onChange={e=>setX(e.target.value)} placeholder="e.g. item1,item2,item3 or encoded item matrix"/></label></div>}
 {tool==="Regression"&&<div className="panel" style={{marginTop:12,boxShadow:"none"}}><p className="panel-description">For multiple regression, enter comma-separated predictor names in Variable X and select the outcome in Variable Y.</p></div>}
 {tool==="Time Series"&&<div className="form-grid"><label>Time-series value variable<select value={timeVar} onChange={e=>setTimeVar(e.target.value)}><option value="">Select variable</option>{numericColumns.map(v=><option key={v}>{v}</option>)}</select></label></div>}
 {tool==="Spatial / GIS"&&<div className="form-grid"><label>Reference latitude<input value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Reference longitude<input value={lon} onChange={e=>setLon(e.target.value)}/></label></div>}
 {tool==="Power / Sample Size"&&<div className="form-grid"><label>Population N (optional)<input value={population} onChange={e=>setPopulation(e.target.value)} placeholder="Leave blank for large/unknown population"/></label><label>Margin of error<input value={margin} onChange={e=>setMargin(e.target.value)}/></label><label>Z / confidence multiplier<input value={z} onChange={e=>setZ(e.target.value)}/></label></div>}
 <div className="form-actions" style={{marginTop:12}}><button type="button" onClick={archive} disabled={busy||!selectedDataset}>Calculate & Archive Analysis</button><button type="button" className="secondary-button" onClick={()=>exportFile("irpa-"+tool.toLowerCase().replaceAll(" ","-")+".json",JSON.stringify(result,null,2))}>Export Result JSON</button></div>
 <div className="record-details" style={{marginTop:16}}><strong>Computed Result</strong><pre style={{whiteSpace:"pre-wrap",overflowX:"auto",maxHeight:420}}>{JSON.stringify(result,null,2)}</pre></div>
 <div className="dashboard-grid" style={{marginTop:16}}>{TOOLSETS.map(([n])=><div key={n} className="stat-card"><span>{n}</span><small>Installed and available in this workbench</small></div>)}</div>
 </section>
}
