import React,{useEffect,useMemo,useState}from"react";
import{cancelDataReset,executeDataReset,getDataResetStatus,requestDataReset}from"../firebase/systemControl";

const GROUPS=[
  ["Governance",["members","employees","meetings","meetingSubscriptions","meetingRoomEvents","transcriptions","resolutions","votes","voteCorrections","votingIssues","actions","documents","signatures","decisions","risks","reports","authorizationRequests","workflowActions","participants"]],
  ["Finance",["staffPaymentRequests","financeBudgets","financeTransactions","financeFunding","financeApprovals","financeCommitments","financeGrants","financeBankAccounts","financeReconciliations","financeAssets","financeRisks","financeReports","financeChartOfAccounts","financeJournalBatches","financePeriods","financeLedgerJournals","financeLedgerEntries","financePaymentMatches","financePaymentTrace","financeReferenceRegistry"]],
  ["Procurement",["procurementVendors","procurementRequests","procurementVendorScores","procurementVendorBlacklist","procurementVendorProbation"]],
  ["Donor & Grant Reporting",["donorFunders","grantReportingObligations"]]
];
const labels={staffPaymentRequests:"Staff Payment Requests",financeBudgets:"Finance Budgets",financeTransactions:"Finance Transactions",financeFunding:"Finance Funding",financeApprovals:"Finance Approvals",financeCommitments:"Finance Commitments",financeGrants:"Finance Grants",financeBankAccounts:"Bank Accounts",financeReconciliations:"Reconciliations",financeAssets:"Assets",financeRisks:"Finance Risks",financeReports:"Finance Reports",financeChartOfAccounts:"Chart of Accounts",financeJournalBatches:"Journal Batches",financePeriods:"Finance Periods",financeLedgerJournals:"Ledger Journals",financeLedgerEntries:"Ledger Entries",financePaymentMatches:"Payment Matches",financePaymentTrace:"Payment Trace",financeReferenceRegistry:"Financial Reference Registry",procurementVendors:"Procurement Vendors",procurementRequests:"Procurement Requests",procurementVendorScores:"Vendor Scores",procurementVendorBlacklist:"Vendor Blacklist",procurementVendorProbation:"Vendor Probation",donorFunders:"Donor / Funder Registry",grantReportingObligations:"Grant Reporting Obligations",meetingSubscriptions:"Meeting Subscriptions",meetingRoomEvents:"Meeting Room Events",voteCorrections:"Vote Corrections",votingIssues:"Voting Issues",authorizationRequests:"Authorization Requests",workflowActions:"Workflow Actions",staffPaymentRequests:"Staff Payment Requests",members:"Members",employees:"Employees",meetings:"Meetings",transcriptions:"Transcriptions",resolutions:"Resolutions",votes:"Votes",actions:"Actions",documents:"Documents",signatures:"Signatures",decisions:"Decisions",risks:"Risks",reports:"Reports",participants:"Participants"};

export default function SystemResetControl(){
 const[selected,setSelected]=useState([]),[scope,setScope]=useState("TRIAL_ONLY"),[graceMinutes,setGraceMinutes]=useState(30),[reason,setReason]=useState(""),[secret,setSecret]=useState(""),[plans,setPlans]=useState([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const selectedSet=useMemo(()=>new Set(selected),[selected]);
 async function refresh(){if(!secret)return;try{const data=await getDataResetStatus({developerSecret:secret});setPlans(data?.plans||[]);}catch(e){setError(e?.message||"Unable to read reset status.");}}
 useEffect(()=>{if(!secret)return;refresh();const id=window.setInterval(refresh,15000);return()=>window.clearInterval(id)},[secret]);
 const toggle=name=>setSelected(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name]);
 const selectGroup=items=>setSelected(v=>[...new Set([...v,...items])]);
 const clearGroup=items=>setSelected(v=>v.filter(x=>!items.includes(x)));
 async function schedule(){setBusy("schedule");setMessage("");setError("");try{if(!selected.length)throw new Error("Select at least one data area.");if(!reason.trim())throw new Error("Enter the reason for the reset.");if(!secret)throw new Error("Enter the developer-provided reset authorization.");const data=await requestDataReset({collections:selected,scope,graceMinutes:Number(graceMinutes),reason:reason.trim(),developerSecret:secret});setMessage(`Reset plan ${data.planId} scheduled. It cannot execute until the ${data.graceMinutes}-minute grace period expires.`);await refresh();}catch(e){setError(e?.message||"Unable to schedule the reset.");}finally{setBusy("")}}
 async function cancel(planId){setBusy("cancel:"+planId);setMessage("");setError("");try{await cancelDataReset({planId,developerSecret:secret});setMessage(`Reset plan ${planId} cancelled. No selected data was deleted.`);await refresh();}catch(e){setError(e?.message||"Unable to cancel the reset.");}finally{setBusy("")}}
 async function execute(planId){if(!window.confirm("The grace period has expired. This operation is destructive within the selected scope. Execute the scheduled reset now?"))return;setBusy("execute:"+planId);setMessage("");setError("");try{const data=await executeDataReset({planId,developerSecret:secret});setMessage(`Reset ${planId} completed. Deleted records: ${JSON.stringify(data.results||{})}`);await refresh();}catch(e){setError(e?.message||"Unable to execute the reset.");}finally{setBusy("")}}
 return <section className="panel" style={{marginTop:20}}>
  <div className="panel-header"><div><span className="eyebrow">SYSTEM RECOVERY CONTROL</span><h2>Controlled Data Reset</h2><p className="panel-description">Schedule a scoped reset with a mandatory grace period. The developer-provided authorization is never stored in the browser or written to the audit record.</p></div></div>
  <div className="stat-card" style={{marginBottom:16}}><span>Protected automatically</span><strong>Audit · Administrators · Reset Plans · Security Configuration</strong><small>These collections cannot be selected by this reset service. Existing administrator access is not revoked by a reset.</small></div>
  <div className="form-grid">
   <label className="field"><span>Reset scope</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="TRIAL_ONLY">Trial data only — safer reset</option><option value="SELECTED_DATA">Selected data — destructive</option></select></label>
   <label className="field"><span>Grace period</span><select value={graceMinutes} onChange={e=>setGraceMinutes(e.target.value)}><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option><option value="1440">24 hours</option></select></label>
   <label className="field form-field-wide"><span>Developer reset authorization</span><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="off" placeholder="Enter the authorization shared by the reset developer" /></label>
   <label className="field form-field-wide"><span>Reset reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows="3" placeholder="Why is this reset required?" /></label>
  </div>
  <div style={{marginTop:18}}><strong>Select data areas</strong><div className="table-subtext">Use the selectors below. Selecting a group does not execute anything.</div></div>
  {GROUPS.map(([group,items])=><div key={group} className="panel" style={{marginTop:12,boxShadow:"none",border:"1px solid rgba(31,90,65,.12)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><strong>{group}</strong><div className="member-actions"><button type="button" className="secondary-button" onClick={()=>selectGroup(items)}>Select group</button><button type="button" className="secondary-button" onClick={()=>clearGroup(items)}>Clear group</button></div></div><div className="form-grid" style={{marginTop:12}}>{items.map(name=><label key={name} className="field" style={{display:"flex",alignItems:"center",gap:9}}><input type="checkbox" checked={selectedSet.has(name)} onChange={()=>toggle(name)} /><span>{labels[name]||name}</span></label>)}</div></div>)}
  <div className="stat-card" style={{marginTop:16}}><span>Selected collections</span><strong>{selected.length}</strong><small>{selected.length?selected.map(x=>labels[x]||x).join(" · "):"None selected"}</small></div>
  <div className="form-actions" style={{marginTop:16}}><button type="button" disabled={busy==="schedule"||!selected.length} onClick={schedule}>{busy==="schedule"?"Scheduling…":"Schedule Reset (Grace Period)"}</button></div>
  {message&&<div className="success-message" style={{marginTop:16}}>{message}</div>}{error&&<div className="error-message" style={{marginTop:16}}>{error}</div>}
  {plans.length>0&&<div className="panel" style={{marginTop:18,boxShadow:"none"}}><div className="panel-header"><div><span className="eyebrow">PENDING RESET PLANS</span><h3>Grace-period queue</h3></div></div>{plans.map(plan=><div key={plan.id} className="stat-card" style={{marginBottom:12}}><span>{plan.scope} · {plan.id}</span><strong>{plan.collections?.length||0} collections selected</strong><small>Scheduled by {plan.requestedByEmail||plan.requestedByUid||"Administrator"} · executes after {plan.executeAfter||"pending timestamp"}</small><div className="member-actions" style={{marginTop:10}}><button type="button" className="secondary-button" disabled={!!busy} onClick={()=>cancel(plan.id)}>Cancel Reset</button><button type="button" disabled={!!busy} onClick={()=>execute(plan.id)}>Execute After Grace Period</button></div></div>)}</div>}
 </section>
}
