export const SIGNATURE_STATES = Object.freeze({
  DRAFT:"DRAFT", PREPARED:"PREPARED", AUTHORITY_VERIFIED:"AUTHORITY_VERIFIED",
  SIGNATURE_REQUESTED:"SIGNATURE_REQUESTED", DELIVERED:"DELIVERED", VIEWED:"VIEWED",
  CONSENTED:"CONSENTED", PARTIALLY_SIGNED:"PARTIALLY_SIGNED", FULLY_SIGNED:"FULLY_SIGNED",
  CRYPTOGRAPHICALLY_SEALED:"CRYPTOGRAPHICALLY_SEALED", TIMESTAMPED:"TIMESTAMPED",
  CERTIFIED:"CERTIFIED", POST_SIGNATURE:"POST_SIGNATURE", FINAL_ARCHIVE:"FINAL_ARCHIVE",
  DECLINED:"DECLINED", VOIDED:"VOIDED", EXPIRED:"EXPIRED", REVOKED:"REVOKED",
  COMPLETION_FAILED:"COMPLETION_FAILED", INTEGRITY_FAILED:"INTEGRITY_FAILED",
  AUTHORITY_FAILED:"AUTHORITY_FAILED", IDENTITY_FAILED:"IDENTITY_FAILED"
});

const TERMINAL=new Set([
  SIGNATURE_STATES.FINAL_ARCHIVE,SIGNATURE_STATES.DECLINED,SIGNATURE_STATES.VOIDED,
  SIGNATURE_STATES.EXPIRED,SIGNATURE_STATES.REVOKED,SIGNATURE_STATES.INTEGRITY_FAILED,
  SIGNATURE_STATES.AUTHORITY_FAILED,SIGNATURE_STATES.IDENTITY_FAILED
]);

const TRANSITIONS=new Map([
  [SIGNATURE_STATES.DRAFT,new Set([SIGNATURE_STATES.PREPARED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.PREPARED,new Set([SIGNATURE_STATES.AUTHORITY_VERIFIED,SIGNATURE_STATES.AUTHORITY_FAILED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.AUTHORITY_VERIFIED,new Set([SIGNATURE_STATES.SIGNATURE_REQUESTED,SIGNATURE_STATES.AUTHORITY_FAILED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.SIGNATURE_REQUESTED,new Set([SIGNATURE_STATES.DELIVERED,SIGNATURE_STATES.EXPIRED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.DELIVERED,new Set([SIGNATURE_STATES.VIEWED,SIGNATURE_STATES.EXPIRED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.VIEWED,new Set([SIGNATURE_STATES.CONSENTED,SIGNATURE_STATES.DECLINED,SIGNATURE_STATES.EXPIRED,SIGNATURE_STATES.VOIDED])],
  [SIGNATURE_STATES.CONSENTED,new Set([SIGNATURE_STATES.PARTIALLY_SIGNED,SIGNATURE_STATES.FULLY_SIGNED,SIGNATURE_STATES.DECLINED,SIGNATURE_STATES.EXPIRED])],
  [SIGNATURE_STATES.PARTIALLY_SIGNED,new Set([SIGNATURE_STATES.PARTIALLY_SIGNED,SIGNATURE_STATES.FULLY_SIGNED,SIGNATURE_STATES.DECLINED,SIGNATURE_STATES.EXPIRED])],
  [SIGNATURE_STATES.FULLY_SIGNED,new Set([SIGNATURE_STATES.CRYPTOGRAPHICALLY_SEALED,SIGNATURE_STATES.COMPLETION_FAILED])],
  [SIGNATURE_STATES.CRYPTOGRAPHICALLY_SEALED,new Set([SIGNATURE_STATES.TIMESTAMPED,SIGNATURE_STATES.COMPLETION_FAILED])],
  [SIGNATURE_STATES.TIMESTAMPED,new Set([SIGNATURE_STATES.CERTIFIED,SIGNATURE_STATES.COMPLETION_FAILED])],
  [SIGNATURE_STATES.CERTIFIED,new Set([SIGNATURE_STATES.POST_SIGNATURE,SIGNATURE_STATES.COMPLETION_FAILED])],
  [SIGNATURE_STATES.POST_SIGNATURE,new Set([SIGNATURE_STATES.FINAL_ARCHIVE,SIGNATURE_STATES.COMPLETION_FAILED])],
  [SIGNATURE_STATES.COMPLETION_FAILED,new Set([SIGNATURE_STATES.FULLY_SIGNED,SIGNATURE_STATES.CRYPTOGRAPHICALLY_SEALED,SIGNATURE_STATES.TIMESTAMPED,SIGNATURE_STATES.CERTIFIED,SIGNATURE_STATES.POST_SIGNATURE])]
]);

export function canTransition(from,to){return TRANSITIONS.get(from)?.has(to)===true;}
export function assertTransition(from,to){
  if(TERMINAL.has(from)) throw new Error("Terminal signature state cannot transition: "+from);
  if(!canTransition(from,to)) throw new Error("Invalid signature transition: "+from+" -> "+to);
  return true;
}
